import type { Metadata } from 'next';

// /support — the App Store listing's Support URL.
//
// WHY THIS EXISTS: the listing pointed at support.sportswise.app, which had DNS but no site behind it
// (Carrd only provisions a certificate for hostnames attached to a site, and nothing claimed that
// one), so tapping "App Support" on the store page produced a TLS handshake failure. Serving the
// page from the same Vercel deployment as the backend removes the dependency: it can't drift out of
// sync with the app, and it can't lapse with a separate subscription.
//
// The FAQ answers are the ones people actually ask; the accurate answer for most is "here's what
// the app does about it already," which is why several point back into the app rather than out.

export const metadata: Metadata = {
  title: 'SportsWise Support',
  description: 'Help, feedback, and answers for SportsWise — the live sports explainer.',
};

const EMAIL = 'feedback@sportswise.app';

export default function Support() {
  return (
    <main style={{ maxWidth: '720px', margin: '0 auto', padding: '40px 20px', fontFamily: 'system-ui, sans-serif', lineHeight: 1.55 }}>
      <h1>SportsWise Support</h1>
      <p><em>Watch and ask why.</em></p>

      <p>
        Need help, have a question, or want to share feedback? Email{' '}
        <a href={`mailto:${EMAIL}`}>{EMAIL}</a> and we&apos;ll get back to you as soon as we can.
        Whether it&apos;s a bug, a feature idea, a sport you&apos;d like us to add, or just a question
        about how something works — your input makes SportsWise better.
      </p>

      <h2>Common questions</h2>

      <h3>The app says &ldquo;no games right now&rdquo; for my sport.</h3>
      <p>
        That means nothing is scheduled inside the next couple of weeks — usually the off-season.
        Tap <strong>Find the next game</strong> to see the upcoming schedule, and star any game to
        get a notification the moment it starts. In the meantime the Coach&apos;s Corner and Academy
        tabs work year-round.
      </p>

      <h3>How do I get notified when a game starts?</h3>
      <p>
        Star it. Either on the game card itself, or from <strong>Find the next game</strong>. You can
        also follow a whole team from the same screen, and we&apos;ll notify you for each of their
        upcoming fixtures. Notifications need to be allowed for SportsWise in iOS Settings.
      </p>

      <h3>The explanation seems wrong.</h3>
      <p>
        Explanations are generated by AI from live game data, and they can occasionally be
        inaccurate — especially in the first seconds after a play, before the data feed has caught
        up. If something looks off, tap the feedback control on the card, or email us with the game
        and roughly when it happened. That&apos;s exactly the kind of report that helps most.
      </p>

      <h3>What does Pro include, and how do I restore it?</h3>
      <p>
        SportsWise Pro unlocks the Coach&apos;s Read, unlimited explanations and questions, and the
        full Coach&apos;s Corner. It&apos;s $6.99 a month or $39.99 a year, managed through your Apple
        ID. If you&apos;ve subscribed on another device or reinstalled, open{' '}
        <strong>Settings → Restore Purchases</strong>. If Pro still doesn&apos;t appear, email us
        with the Apple ID email you purchased under (never your password).
      </p>

      <h3>How do I cancel?</h3>
      <p>
        Subscriptions are managed by Apple, not by us: open the iOS <strong>Settings</strong> app →
        your name → <strong>Subscriptions</strong> → SportsWise. Cancelling there stops renewal;
        you keep Pro until the end of the period you&apos;ve paid for.
      </p>

      <h3>Which sports do you cover?</h3>
      <p>
        MLB, NFL, NBA, WNBA, NHL, college football and men&apos;s college basketball, soccer (MLS,
        Premier League, La Liga, Serie A, Bundesliga), rugby (URC, MLR, Six Nations, Super Rugby,
        the Nations Cup, and the European Champions and Challenge Cups), tennis, golf, and cricket.
        Want another one? Tell us — that&apos;s how several of these got added.
      </p>

      <h3>What data does the app collect?</h3>
      <p>
        Very little, and it&apos;s all spelled out in the{' '}
        <a href="https://privacy.sportswise.app">Privacy Policy</a>. In short: the sport and game
        you select, your explanation level and language, and any question you type — that&apos;s
        what&apos;s needed to answer you. No account is required to use the app.
      </p>

      <h2>Contact</h2>
      <p>
        <a href={`mailto:${EMAIL}`}>{EMAIL}</a>
        <br />
        We read everything. Response time is usually within a couple of days.
      </p>

      <p style={{ marginTop: '40px', fontSize: '0.9em', color: '#666' }}>
        <a href="https://privacy.sportswise.app">Privacy Policy</a> ·{' '}
        <a href="https://termsandconditions.sportswise.app">Terms &amp; Conditions</a>
        <br />
        SportsWise is not affiliated with ESPN or any professional league. Explanations are
        AI-generated and for education and entertainment.
      </p>
    </main>
  );
}
