// Signal Decoder — Cricket bank. Umpire signals only (evergreen, rule-based; verified
// against MCC Laws of Cricket, Law 2.13 — the most codified signal set in sport).
// 6 scenarios per tier × 4 tiers. Pure data, zero RN imports.
import type { SignalScenario } from '../signalDecoder';

export const CRICKET_SIGNAL_SCENARIOS: SignalScenario[] = [
  // ── kid ────────────────────────────────────────────────────────────────────
  {
    id: 'crk-sig-kid-1', level: 'kid', signal: 'crk-out',
    prompt: 'The umpire slowly raises one index finger. What is he telling the batter?',
    options: ['Out — your innings is over', 'One more run', 'Great shot!'],
    answer: 0,
    title: 'The raised finger: out',
    exp: {
      kid: 'The single finger means OUT. The batter must walk off, and the next batter comes in. It\'s the most feared finger in sports!',
      beginner: 'The finger answers an APPEAL: fielders shout "Howzat?!" and the umpire raises the finger (out) or shakes his head (not out). Bowled, caught, LBW, run out — one signal covers all dismissals.',
      intermediate: 'Crucial rule: without an appeal, the umpire says nothing — even if the batter is plainly out. The finger is a verdict, and verdicts require the question to be asked.',
      expert: 'Note the theater codified into law: the finger is raised toward the batter, unhurried, often after a deliberate pause. Contrast reviews: after a DRS overturn, the umpire reverses by crossing hands or re-signaling. One raised digit carries the same legal weight as a red card — and cricket etiquette demands the batter walk without protest.',
    },
  },
  {
    id: 'crk-sig-kid-2', level: 'kid', signal: 'crk-six',
    prompt: 'The ball sails over the boundary rope without bouncing, and the umpire raises BOTH arms above his head. How many runs?',
    options: ['Six!', 'Four', 'One'],
    answer: 0,
    title: 'Both arms up: six!',
    exp: {
      kid: 'Both arms high means SIX — the biggest hit in cricket! The ball flew all the way over the rope without touching the ground. Six runs, no running needed!',
      beginner: 'Clearing the boundary on the full = 6 runs, automatically. The batters don\'t run; the umpire\'s raised arms tell the scorers to add six.',
      intermediate: 'The full-flight test is strict: a ball that bounces even once before the rope is four (the side-to-side wave instead). Fielders leaping at the rope create the borderline cases — touch the rope or ground beyond it while touching the ball, and it\'s six.',
      expert: 'The boundary-catch law is the modern drama: a fielder may parry the ball INSIDE the boundary while airborne, but his last contact with the ground before first touching the ball must be inside the rope. TV umpires re-run those frames constantly. The two-arm signal often waits on that exact geometry.',
    },
  },
  {
    id: 'crk-sig-kid-3', level: 'kid', signal: 'crk-four',
    prompt: 'The umpire sweeps an arm back and forth across his chest. What boundary is he signaling?',
    options: ['Four runs — the ball reached the rope after bouncing', 'Six runs', 'No runs'],
    answer: 0,
    title: 'The chest wave: four',
    exp: {
      kid: 'The arm waving across the body means FOUR — the ball rolled or bounced its way past the boundary rope. Four free runs!',
      beginner: 'A ball reaching the boundary along the ground (or after bouncing) scores 4 automatically. The wave finishes with the arm folded across the chest, per the law\'s exact wording.',
      intermediate: 'Four vs six is purely about the bounce: any ground contact before the rope caps it at 4. Watch umpires track the bounce right at the rope\'s edge — that\'s the entire judgment.',
      expert: 'Boundary fours dominate scoring in every format — reading this signal\'s frequency tells you the pitch\'s pace and the outfield\'s speed. Law nuance: overthrows that reach the rope also earn 4, ADDED to runs already completed, which produces cricket\'s odd totals like 7 runs off one delivery.',
    },
  },
  {
    id: 'crk-sig-kid-4', level: 'kid', signal: 'crk-wide',
    prompt: 'The bowler sprays the ball far outside the batter\'s reach, and the umpire stretches BOTH arms out level like a T. What\'s the call?',
    options: ['Wide — 1 penalty run, ball bowled again', 'Out', 'Six'],
    answer: 0,
    title: 'Arms out level: wide',
    exp: {
      kid: 'Arms out flat means WIDE — the ball was too far away for the batter to hit it fairly. The batting team gets 1 free run, and the bowler must bowl that ball AGAIN.',
      beginner: 'A wide adds 1 extra to the batting side and does NOT count as one of the over\'s 6 balls. Wides punish bowlers for taking the contest away from the batter.',
      intermediate: 'The width standard is format-dependent in practice: limited-overs cricket calls wides tightly (especially down the leg side), while Test cricket tolerates more. Same signal, different tolerance — context is part of the decode.',
      expert: 'Strategy layer: with fields spread in T20 death overs, bowlers aim inches outside off stump — the wide line polices exactly that margin. A called wide costs 1 run PLUS an extra ball at the death, often worth far more. Umpires\' wide judgments swing tight run-chases as much as any boundary.',
    },
  },
  {
    id: 'crk-sig-kid-5', level: 'kid', signal: 'crk-noball',
    prompt: 'Now the umpire flings just ONE arm out horizontally. What is this call?',
    options: ['No-ball — an illegal delivery', 'Wide', 'Four'],
    answer: 0,
    title: 'One arm out: no-ball',
    exp: {
      kid: 'One arm out means NO-BALL — the bowler broke a bowling rule, most often stepping past the front line. One free run, and the ball is bowled again!',
      beginner: 'Common causes: front foot fully beyond the popping crease, a full toss above the waist, throwing (elbow straightening). 1 run to the batting side, re-bowled, and the batter can\'t be out bowled/caught/LBW off it.',
      intermediate: 'ONE arm = no-ball, BOTH arms = wide — cricket\'s classic confusable pair, and the exact kind of distinction this game exists to teach. Remember: one rule broken by the bowler\'s BODY (no-ball) vs the ball\'s LINE (wide).',
      expert: 'The no-ball\'s real price in white-ball cricket is the FREE HIT that follows (see that signal): the next delivery can\'t dismiss the batter by most modes, so batters swing without fear. TV umpires now check front-foot landings on every ball — the one-armed signal increasingly arrives via earpiece.',
    },
  },
  {
    id: 'crk-sig-kid-6', level: 'kid', signal: 'crk-bye',
    prompt: 'The ball whizzes past everyone — bat, pads, keeper — and the batters run anyway. The umpire raises an OPEN hand above his head. What are these runs called?',
    options: ['Byes — runs without bat or body touching the ball', 'Sixes', 'Wickets'],
    answer: 0,
    title: 'Open palm up: byes',
    exp: {
      kid: 'The open hand means BYES — sneaky runs taken when the ball touched NOTHING! Nobody hit it, the keeper missed it, so the batters just ran.',
      beginner: 'Byes are extras: they count for the team\'s total but not the batter\'s personal score. The wicketkeeper is usually "charged" for them — clean keepers concede almost none.',
      intermediate: 'The signal family matters: open palm up = bye; touching a raised knee = LEG bye (ball hit the batter\'s body first). Bat involved = ordinary runs, no signal at all.',
      expert: 'Byes off fast bowling on bouncy pitches test keepers standing back; byes standing up to spin are rarer and more embarrassing. Scorecard literacy: a high "extras" line with many byes tells you about keeping quality and pitch behavior without watching a single delivery.',
    },
  },

  // ── beginner ──────────────────────────────────────────────────────────────
  {
    id: 'crk-sig-beg-1', level: 'beginner', signal: 'crk-legbye',
    prompt: 'The ball thuds into the batter\'s pad and dribbles away; the batters run one. The umpire touches a RAISED KNEE. What run is this?',
    options: ['A leg bye — the ball came off the body, not the bat', 'A bye', 'A no-ball'],
    answer: 0,
    title: 'Touching the knee: leg bye',
    exp: {
      kid: 'Tapping the raised knee means LEG BYE — the ball bounced off the batter\'s leg (not the bat!) and they ran. The run counts for the team, not the batter.',
      beginner: 'Leg byes are extras credited to the team when the ball deflects off the batter\'s body. Condition: the batter must have TRIED to hit it (or dodged it) — pure pad-kicking for runs isn\'t allowed.',
      intermediate: 'Knee-tap vs open-palm-up is the classic pairing: body deflection (leg bye) vs clean miss past everything (bye). If the umpire judges NO shot was attempted, leg byes are disallowed — dead ball, runs canceled.',
      expert: 'Interlock with LBW: pad first + no shot offered widens LBW\'s scope (impact outside off matters less), so the same pad-strike can produce a knee-tap (runs), a disallowed dead ball, or a raised finger — three outcomes from one thud, decided by shot-attempt judgment and ball trajectory. That decision tree is peak umpire-craft.',
    },
  },
  {
    id: 'crk-sig-beg-2', level: 'beginner', signal: 'crk-dead',
    prompt: 'The umpire crosses and uncrosses his wrists low in front of his waist. What state is the ball now in?',
    options: ['Dead — nothing can happen until the next delivery', 'On fire — free hit', 'Lost'],
    answer: 0,
    title: 'Crossed wrists low: dead ball',
    exp: {
      kid: 'The crossing wrists mean DEAD BALL — the game freezes! No runs, no outs, nothing counts until the bowler starts again.',
      beginner: 'Umpires kill the ball for distractions, injuries, the ball lodging in equipment, or a batter not ready. Anything mid-play is voided — runs in progress don\'t count.',
      intermediate: 'Dead ball is also the correction tool: bowler stops mid-run-up, sightscreen movement, a pigeon on the pitch. Cricket\'s default state between deliveries IS dead — this signal marks the unusual cases where it dies mid-action.',
      expert: 'Sharp edge cases: a batter pulling away as the bowler delivers (dead ball, re-bowled), the ball striking a helmet lying on the field (dead + 5 penalty runs to batters), and the modern "double bounce" delivery. Umpires call it aloud AND sign it — the only signal defined to be both shouted and shown, because a live/dead mistake corrupts everything downstream.',
    },
  },
  {
    id: 'crk-sig-beg-3', level: 'beginner', signal: 'crk-free-hit',
    prompt: 'After a front-foot no-ball in a T20, the umpire circles one arm above his head. What does the NEXT delivery become?',
    options: ['A free hit — the batter can\'t be out by most dismissals', 'A wide', 'The last ball of the over'],
    answer: 0,
    title: 'The overhead circle: free hit',
    exp: {
      kid: 'The circling arm means FREE HIT — the batter gets one delivery where he can swing as hard as he likes and (almost) can\'t be out! It\'s the punishment for the bowler\'s no-ball.',
      beginner: 'On a free hit the batter can\'t be bowled, caught, LBW, or stumped — only run out (and rare oddities). White-ball cricket only. Expect a giant swing.',
      intermediate: 'Field restrictions apply too: for the same batter, the field can\'t change from the no-ball delivery. Bowlers aim yorkers; batters premeditate. A free hit swings T20 win probability more than most boundaries.',
      expert: 'Delicious rule detail: bowled off a free hit = ball stays LIVE — batters can run "bowled byes" as the ball ricochets off the stumps, a sight that breaks new fans\' brains. And if the free-hit delivery is ITSELF a no-ball or wide, the free hit carries over. The circle signal is a one-ball constitutional amendment.',
    },
  },
  {
    id: 'crk-sig-beg-4', level: 'beginner', signal: 'crk-tv',
    prompt: 'A run-out is too close to call. The umpire mimes a rectangle — a TV screen — in the air. What happens now?',
    options: ['The third umpire reviews video and decides', 'The batter chooses', 'The match is paused for tea'],
    answer: 0,
    title: 'The TV box: sent upstairs',
    exp: {
      kid: 'The rectangle means "ask the TV umpire!" A third umpire watching replays makes the call, and the big screen shows OUT or NOT OUT. The crowd holds its breath!',
      beginner: 'For line decisions (run outs, stumpings, boundary calls), the on-field umpire can refer straight to the third umpire. The drawn box is the formal referral.',
      intermediate: 'Distinguish this from DRS: the TV box is the UMPIRE choosing help; a player review (the "T" made with forearms by batter or captain) challenges a decision already made. Two review roads, two different gestures.',
      expert: 'The run-out replay grammar is precise: frame where bails are fully removed vs the batter\'s grounded bat/body behind the crease line — and "benefit of the doubt" formally belongs to the batter. Note DRS\'s "umpire\'s call" only exists for ball-tracking judgments (LBW), not line decisions; line calls are binary. Knowing which review regime you\'re watching tells you what the screen can even say.',
    },
  },
  {
    id: 'crk-sig-beg-5', level: 'beginner', signal: 'crk-noball',
    prompt: 'Same one-arm-out signal — but this time for a chest-high FULL TOSS at the batter. Why is that a no-ball?',
    options: ['High full tosses are dangerous — above the waist on the full is illegal', 'The bowler bowled too slow', 'The ball was too shiny'],
    answer: 0,
    title: 'The beamer: dangerous, therefore illegal',
    exp: {
      kid: 'A ball that flies at the batter\'s body WITHOUT bouncing is scary and dangerous — so it\'s automatically a no-ball, no matter where his feet were.',
      beginner: 'Any full toss above the batter\'s waist (the "beamer") is a no-ball for dangerous bowling. Repeated offences can get the bowler banned from bowling for the innings.',
      intermediate: 'The one-armed signal covers a whole family: foot faults, throwing, dangerous deliveries, breaking the return crease, even the keeper collecting in front of the stumps. The arm says "illegal delivery"; the cause varies.',
      expert: 'Note the escalation regime unique to dangerous bowling: warnings are tracked per bowler, and a second beamer (deliberate or not, in many playing conditions) removes the bowler from the attack — a sanction structure no other no-ball type carries. Umpire safety judgments literally subtract a team\'s best weapon.',
    },
  },
  {
    id: 'crk-sig-beg-6', level: 'beginner', signal: 'crk-new-ball',
    prompt: 'In a Test match, the umpire holds the ball high above his head toward the scorers. What is he announcing?',
    options: ['The fielding team has taken the NEW ball', 'The ball is lost', 'Six runs'],
    answer: 0,
    title: 'Ball aloft: the new ball',
    exp: {
      kid: 'Holding the ball up high means a brand-NEW ball is coming into play! In long matches the ball gets old and soft — a new one is shiny, hard, and fast.',
      beginner: 'In Tests, the fielding captain may take a new ball after 80 overs. New ball = more pace, bounce and swing — a fresh attack spell from the fast bowlers usually follows.',
      intermediate: 'The signal tells scorers to log the change (ball age is tracked in overs). Captains time it tactically: take it immediately at 80, or delay if spinners are strangling with the old one.',
      expert: 'Ball-state is Test cricket\'s hidden engine: new ball (swing/seam) → 30–80 overs (reverse swing potential, spin grip) → renewal. The aloft signal marks a phase transition that reshapes field settings, batting risk, and bowling rotations for the next 20 overs. Reading it is reading the match\'s tides.',
    },
  },

  // ── intermediate ──────────────────────────────────────────────────────────
  {
    id: 'crk-sig-int-1', level: 'intermediate', signal: 'crk-short-run',
    prompt: 'The batters scamper two, but the umpire bends one arm up and taps the fingers on that SAME shoulder. What is being disallowed?',
    options: ['A short run — one batter didn\'t ground his bat behind the crease when turning', 'The second wicket', 'The bowler\'s hat-trick'],
    answer: 0,
    title: 'Same-shoulder tap: short run',
    exp: {
      kid: 'Tapping his own shoulder means SHORT RUN — a batter turned around WITHOUT touching his bat down behind the line. That run doesn\'t count! Cheating the turn costs you.',
      beginner: 'Each run requires bat or body grounded beyond the popping crease before turning back. Fail, and the umpire signals short: that run is deducted from what was run.',
      intermediate: 'Precisely: "the run in which the short running occurred" doesn\'t count — run 2 but turn short after run 1, and only 1 counts. Deliberate short running is a 5-penalty-run offence — a different, harsher regime.',
      expert: 'MCC drafting detail worth savoring: the signal is fingertips to the SAME-side shoulder — while 5-penalty-run signals use the OPPOSITE shoulder (tap = to batting side, placed hand = to fielding side). Three shoulder-touch signals, distinguished by same/opposite and tap/rest. Law 2.13 is a masterclass in gesture design economy.',
    },
  },
  {
    id: 'crk-sig-int-2', level: 'intermediate', signal: 'crk-revoke',
    prompt: 'The umpire touches BOTH shoulders, each with the opposite hand — arms crossed over his chest. What is he undoing?',
    options: ['Revoking his last signal — the previous call is canceled', 'Calling for a jacket', 'Ending the over'],
    answer: 0,
    title: 'Both shoulders crossed: revoke',
    exp: {
      kid: 'Crossing arms to touch both shoulders means "CANCEL THAT!" — the umpire is taking back his last signal, like pressing undo. Even umpires fix mistakes!',
      beginner: 'The revoke signal formally withdraws the previous signal to the scorers — perhaps a four signaled before realizing the fielder saved it, or a wide canceled after seeing an edge. It\'s then followed by the corrected signal.',
      intermediate: 'It exists because scorers act on signals immediately and must be told to reverse the entry — the signal system is a real-time data protocol between field and scorebook, complete with an error-correction code.',
      expert: 'Modern usage spike: DRS overturns. When a review reverses OUT to NOT OUT, the umpire revokes and re-signals the correct outcome (including any runs that now count). Cricket formalized "undo" a century before software did — and it remains the only major sport with a dedicated retraction gesture in its laws.',
    },
  },
  {
    id: 'crk-sig-int-3', level: 'intermediate', signal: 'crk-wide',
    prompt: 'The T-arms wide signal — with the keeper standing way over toward leg side and the batter having moved across his stumps before the ball. What does the umpire judge the width AGAINST?',
    options: ['The batter\'s position and reasonable reach — not just fixed lines on the pitch', 'The painted guide lines only', 'The keeper\'s gloves'],
    answer: 0,
    title: 'Wide is relative to the batter',
    exp: {
      kid: 'A wide isn\'t just about lines on the ground — it\'s about whether THAT batter, standing where he was, could reach the ball with a normal swing.',
      beginner: 'The law defines wide as out of reach for a normal cricket shot, judged from the batter\'s position (and where he\'s moved to). The crease guide-lines are aids, not the law.',
      intermediate: 'Batters moving around the crease complicate it: step to off and a leg-side ball you vacated may NOT be wide (you made it unreachable). Umpires re-anchor the judgment to the batter\'s actual and original stance.',
      expert: 'T20 arms race: batters shuffle to manufacture reach, bowlers follow them with wide-line precision, and playing conditions have added protected-line rules (a leg-side wide behind original leg stump stays wide in some competitions even if the batter moved). The two flat arms encode a genuinely moving target — the most context-dependent boundary judgment in cricket.',
    },
  },
  {
    id: 'crk-sig-int-4', level: 'intermediate', signal: 'crk-out',
    prompt: 'Huge LBW appeal, finger goes up — the batter immediately makes a "T" with his forearms. Walk through what he just invoked.',
    options: ['A DRS review — ball-tracking and edge-detection will test the decision', 'A tantrum penalty', 'A request for tea'],
    answer: 0,
    title: 'The finger vs the T',
    exp: {
      kid: 'The batter is challenging the decision with TV technology! Cameras check if the ball really would have hit the stumps. If the umpire was wrong, the out is canceled.',
      beginner: 'Teams get limited reviews (typically 2–3 per innings, kept if successful). DRS checks: legal delivery? edge (UltraEdge)? pitching/impact/hitting zones (ball-tracking)? The third umpire relays; the on-field umpire re-signals.',
      intermediate: '"Umpire\'s call" is the pivot: if ball-tracking is marginal (clipping the stumps), the ORIGINAL decision stands and the review isn\'t lost (retained in most conditions). The raised finger thus carries weight even into the machine age.',
      expert: 'Umpire\'s call is sport\'s most explicit epistemology: technology has error bars, so marginal predictions defer to the human ruling — the same anchoring principle as rugby\'s "any reason I cannot award" and hockey\'s on-ice call. Cricket just quantified the deference zone in millimetres. The finger→T→finger-or-revoke choreography is a complete judicial appeal, performed in 90 seconds.',
    },
  },
  {
    id: 'crk-sig-int-5', level: 'intermediate', signal: 'crk-bye',
    prompt: 'Open palm raised — byes — but this time the ball had beaten everyone AND raced to the rope. How is it scored?',
    options: ['4 byes — extras for the team; neither the batter nor the bowler is credited/charged', '4 runs to the batter', 'A dot ball'],
    answer: 0,
    title: 'Four byes: the anonymous boundary',
    exp: {
      kid: 'The ball ran all the way to the rope without touching anyone — so the team gets 4 runs, but no player gets credit. Free team runs!',
      beginner: 'Byes reaching the boundary = 4 byes: the umpire signals bye THEN four. They appear in extras; the batter\'s score and the bowler\'s runs-conceded column are both untouched.',
      intermediate: 'That bookkeeping is meaningful: a bowler\'s economy rate survives byes (blamed on the keeper, informally), while wides and no-balls DO count against the bowler. The signal sequence tells scorers which column bleeds.',
      expert: 'Signal-sequencing is a real protocol: bye + four = two signals in order; leg bye + four likewise. Scorers acknowledge each (umpires wait for the wave back). Extras taxonomy — byes (keeper), leg byes (neutral), wides/no-balls (bowler) — is the accounting system that makes bowling analyses comparable across a century of scorebooks.',
    },
  },
  {
    id: 'crk-sig-int-6', level: 'intermediate', signal: 'crk-dead',
    prompt: 'Mid-delivery, a streaker\'s beach ball rolls onto the pitch; the batter smashes the ball to the rope anyway. Crossed wrists follow. What happens to the four?',
    options: ['Canceled — the ball was dead the moment the umpire ruled the distraction', 'It counts double', 'It counts if the batter appeals'],
    answer: 0,
    title: 'Dead means the four never happened',
    exp: {
      kid: 'When something silly interrupts the game — like a beach ball! — the umpire freezes everything. The big hit doesn\'t count, and the bowler bowls that ball again.',
      beginner: 'A dead ball voids the delivery\'s outcomes: no runs, no dismissals, delivery re-bowled (it doesn\'t count in the over). Fairness demands neither side profits from a disrupted ball.',
      intermediate: 'Timing subtleties: umpires judge WHEN the distraction occurred — before the shot (dead, re-bowl) vs after the outcome was settled. A boundary already completed before the interruption stands.',
      expert: 'The deep principle: cricket\'s laws treat each delivery as an atomic transaction — dead ball is the ROLLBACK. Compare baseball\'s dead-ball awards (placements by rule): cricket voids and replays; baseball freezes and compensates. Two dead-ball philosophies, visible entirely through their signals.',
    },
  },

  // ── expert ────────────────────────────────────────────────────────────────
  {
    id: 'crk-sig-exp-1', level: 'expert', signal: 'crk-penalty-bat',
    prompt: 'The umpire repeatedly TAPS one shoulder with his opposite hand. Five runs change hands. Who gets them, and what typically caused it?',
    options: ['5 penalty runs to the BATTING side — e.g. the ball struck a fielder\'s discarded helmet', '5 to the fielding side', 'A short run'],
    answer: 0,
    title: 'The repeated tap: 5 penalty runs to the batting side',
    exp: {
      kid: 'Tap-tap-tap on the shoulder means 5 FREE RUNS for the batting team! It happens when the fielding side breaks a rule — like the ball hitting a helmet they left lying on the grass.',
      beginner: 'Penalty runs punish conduct/equipment offences: ball hitting a fielder\'s parked helmet, deliberate fielding with clothing, illegal ball-tampering. Five runs, signaled by repeatedly tapping the opposite shoulder.',
      intermediate: 'The REPEATED TAPPING = batting side benefits; a hand simply PLACED on the opposite shoulder = fielding side benefits (e.g. batters deliberately running short or damaging the pitch). Motion vs stillness is the entire difference.',
      expert: 'This tap/place pair is the hardest discrimination in Law 2.13 — and this game\'s art shows the motion arcs for exactly that reason. Full context: penalty runs also attach to time-wasting and mock fielding under modern laws, and they\'re added as extras immediately, even mid-over. Five runs without a ball bowled is the laws\' bluntest behavioural lever.',
    },
  },
  {
    id: 'crk-sig-exp-2', level: 'expert', signal: 'crk-penalty-field',
    prompt: 'Now the umpire PLACES a hand on the opposite shoulder and holds it there — no tapping. Decode it against its twin.',
    options: ['5 penalty runs to the FIELDING side — the batting side transgressed', '5 to the batting side', 'Revoke last signal'],
    answer: 0,
    title: 'The placed hand: 5 penalty runs to the fielding side',
    exp: {
      kid: 'A hand RESTING quietly on the shoulder means the 5 free runs go the other way — to the fielding team — because the BATTERS broke a rule this time.',
      beginner: 'Batting-side offences: deliberately running short, damaging the protected pitch area after warnings, deliberate distraction. The 5 runs are added to the fielding side\'s total (or deducted appropriately).',
      intermediate: 'The mnemonic: TAPPING is "applause" for the batters (runs to them); a STILL hand is a stop sign against them. And note the third shoulder signal — same-side fingertip tap = short run — completing the shoulder trilogy.',
      expert: 'Design analysis: Law 2.13 packs three distinct meanings onto shoulder contact using two axes (same/opposite side, moving/static) — a two-bit encoding on one body part. When scorers 70 metres away must never mis-book a 5-run swing, gesture orthogonality is a legal requirement. This pair is the expert exam of cricket signal literacy, and now you pass it.',
    },
  },
  {
    id: 'crk-sig-exp-3', level: 'expert', signal: 'crk-last-hour',
    prompt: 'Late on day five of a Test, the umpire points to his raised wrist — tapping an imaginary watch. What phase has just begun?',
    options: ['The last hour: minimum 15 more overs must be bowled', 'Lunch', 'A drinks break'],
    answer: 0,
    title: 'The watch tap: the last hour',
    exp: {
      kid: 'Pointing at his wrist means the FINAL HOUR of the whole match has started — and the bowling team must bowl at least 15 more overs, no time-wasting allowed!',
      beginner: 'In timed cricket (Tests), the last hour begins at a set time on the final day: a minimum of 15 overs must be bowled regardless of the clock. The signal notifies scorers and both teams.',
      intermediate: 'It exists to kill the stall: a team clinging to a draw would otherwise bowl three overs an hour. The minimum-overs floor makes the endgame honest — survival must be EARNED with the bat.',
      expert: 'Draw-hunting is cricket\'s unique endgame (a five-day match can end with no winner), and the last hour is its regulated climax: field changes slow, light meters appear, and every over of the 15 is a discrete siege event. The little watch-tap is the starting gun for the most particular hour in sport — meaningless in T20, everything in a live Test.',
    },
  },
  {
    id: 'crk-sig-exp-4', level: 'expert', signal: 'crk-free-hit',
    prompt: 'Free hit signaled. The batter is BOWLED middle stump on the free-hit ball, and the batters sprint two runs while fielders stand confused. Valid?',
    options: ['Yes — bowled doesn\'t count on a free hit and the ball stays live: 2 runs', 'No — bowled always ends the innings', 'No — the ball is dead on hitting the stumps'],
    answer: 0,
    title: 'Running byes off your own broken stumps',
    exp: {
      kid: 'On a free hit, hitting the stumps doesn\'t get you out — AND the ball keeps rolling, still in play! So the batters can run runs while everyone else stands frozen. Wild but true!',
      beginner: 'Free hit protections: not out bowled, caught, LBW, stumped. Since the dismissal doesn\'t stand, the ball remains live off the stumps — runs completed count (as byes, if no bat was involved).',
      intermediate: 'Fielding sides genuinely rehearse this: keeper retrieves off the ricochet FAST, because a run out is still possible (the one live dismissal). The frozen-fielder blunder happens at every level, including internationals.',
      expert: 'Why it works legally: the ball only becomes dead by Law 20\'s events (settled with keeper, boundary, dismissal…). The "dismissal" here is void, so no dead-ball trigger fired — the transaction continues. It\'s the perfect case study of cricket-as-state-machine: signals set flags (free hit), and the laws execute deterministically, however absurd the resulting play looks.',
    },
  },
  {
    id: 'crk-sig-exp-5', level: 'expert', signal: 'crk-noball',
    prompt: 'One arm out — but held there noticeably LONG while the umpire watches the batters complete three runs off the no-ball. Total added to the board?',
    options: ['4 — the no-ball penalty PLUS the three runs actually run', '1 — no-balls cap the scoring', '3 — the penalty replaces a run'],
    answer: 0,
    title: 'No-ball arithmetic: penalty stacks with runs',
    exp: {
      kid: 'A no-ball gives 1 free run AND everything the batters score still counts on top! Three runs run + 1 penalty = 4 total. Bad balls are expensive.',
      beginner: 'The no-ball extra (1) stacks with runs off the bat (credited to the batter) or byes/leg-byes run. Plus the delivery is re-bowled — the over gets longer and the batter can\'t be out by most modes.',
      intermediate: 'Scoring taxonomy: penalty run → extras (against the bowler); runs off the bat on a no-ball → batter\'s score. A boundary off a no-ball = 5 total. Scorers need the umpire\'s held signal to allocate columns correctly.',
      expert: 'The held arm is deliberate protocol: umpires maintain the no-ball signal until sure scorers registered it, because mis-booking cascades (bowler analysis, extras, free-hit flag next ball). Add DRS: a dismissal reviewed and found to be off a front-foot no-ball converts OUT into NOT OUT + 1 run + free hit. One horizontal arm reprices an entire delivery three different ways.',
    },
  },
  {
    id: 'crk-sig-exp-6', level: 'expert', signal: 'crk-six',
    prompt: 'Both arms up — but only after a long TV check of a fielder juggling the ball at the rope, stepping beyond it between touches. What geometry made this six rather than a catch?',
    options: ['He touched ball then ground beyond the rope (or was airborne from beyond it) — boundary rules beat the catch', 'The crowd\'s verdict', 'Jugglers are always out'],
    answer: 0,
    title: 'The boundary-rider\'s tightrope',
    exp: {
      kid: 'The fielder caught the ball but stepped on the wrong side of the rope while touching it — so instead of OUT, it\'s SIX! The rope wins against the catch.',
      beginner: 'A catch is only fair if the fielder never touches the ground beyond the boundary while in contact with the ball. Parry it up, step out, jump BACK in… the rules track every touch.',
      intermediate: 'The modern rule: a fielder who is airborne beyond the rope may only touch the ball if his final ground contact BEFORE first touching the ball was inside. Relay catches (throw to a partner inside) live on exactly this clause.',
      expert: 'Recent law tightening: after acrobatic "bunny-hop" saves strained credulity, conditions now require the fielder, after first touching the ball while airborne beyond the boundary, to land fully inside — repeated outside-the-rope juggles are out… of bounds: six. The two raised arms at the end of a three-minute review are the umpire compressing a multi-clause geometry proof into one pictogram.',
    },
  },
];
