// Signal Decoder — MLB bank. Umpire signals only (evergreen, rule-based; verified
// against standard umpire mechanics manuals). 6 scenarios per tier × 4 tiers. Pure data.
import type { SignalScenario } from '../signalDecoder';

export const MLB_SIGNAL_SCENARIOS: SignalScenario[] = [
  // ── kid ────────────────────────────────────────────────────────────────────
  {
    id: 'mlb-sig-kid-1', level: 'kid', signal: 'mlb-out',
    prompt: 'The umpire punches a clenched fist — the "hammer." What is he calling?',
    options: ['Out!', 'Home run', 'Time for snacks'],
    answer: 0,
    title: 'The hammer: out',
    exp: {
      kid: 'The fist punch means OUT — the batter or runner is done for this inning. Three outs and the whole team switches to the field!',
      beginner: 'Outs come many ways: caught fly ball, tag, force at a base, strikeout. However it happens, the fist is the confirmation — and three of them end the half-inning.',
      intermediate: 'On close plays, watch the TIMING of the hammer: umpires deliberately pause a beat ("see it, then call it") to ensure the ball was held securely through the tag before committing.',
      expert: 'Mechanics detail: the out is a right-hand signal — the "action hand" umpires reserve for strikes, outs, and fair calls. A strong sell (a bigger, faster hammer) on bang-bang plays isn\'t theater only; it communicates certainty to dugouts weighing a replay challenge.',
    },
  },
  {
    id: 'mlb-sig-kid-2', level: 'kid', signal: 'mlb-safe',
    prompt: 'The runner slides into the base and the umpire sweeps both arms out flat. The call is…',
    options: ['Safe — the runner stays', 'Out', 'Rain delay'],
    answer: 0,
    title: 'Arms swept wide: safe',
    exp: {
      kid: 'Wide-open arms mean SAFE! The runner beat the ball to the base and gets to stay there.',
      beginner: 'A runner is safe when he touches the base before being tagged (or before the base is touched on a force). The flat outward sweep says: no out, play on.',
      intermediate: 'Safe/out at a base is a race you can watch in the umpire\'s eyes: they take an angle to see BOTH the fielder\'s glove and the runner\'s foot — the sweep comes only after both are resolved.',
      expert: 'A precise variant to know: safe sweep followed by pointing at the ball on the ground = "safe — the fielder DROPPED it." The add-on gesture pre-answers the dugout\'s protest before it starts. Umpire mechanics are built to justify, not just declare.',
    },
  },
  {
    id: 'mlb-sig-kid-3', level: 'kid', signal: 'mlb-strike',
    prompt: 'The pitch zips past the batter and the umpire points sharply to the side. What was the pitch?',
    options: ['A strike', 'A ball', 'A home run'],
    answer: 0,
    title: 'The point: strike',
    exp: {
      kid: 'The sideways point means STRIKE — the pitch was good and the batter should have swung (or swung and missed). Three strikes and you\'re out!',
      beginner: 'A strike is a pitch in the strike zone taken, any swing-and-miss, or a foul with fewer than two strikes. Umpires signal strikes with the right hand — a point or a hammer, their style.',
      intermediate: 'Notice: called BALLS get no signal at all — the umpire just stays set. Only strikes are physically signaled. Silence + no motion is itself information: ball.',
      expert: 'Umpires personalize the strike mechanic (point, hammer, chainsaw) but the grammar is fixed: verbal "strike" + right-hand signal, and on strike three a more emphatic sell. A called third strike often gets a signature punch-out distinct from the swinging version — decoding a punch-out from center field is pure signal literacy.',
    },
  },
  {
    id: 'mlb-sig-kid-4', level: 'kid', signal: 'mlb-time',
    prompt: 'Both of the umpire\'s arms go straight up in the air. What does it mean?',
    options: ['Time! The ball is dead — everything stops', 'Touchdown', 'The batter is out'],
    answer: 0,
    title: 'Both arms up: time / dead ball',
    exp: {
      kid: 'Both arms up means STOP! The ball is "dead" — no running, no tagging, nothing counts until the umpire says play again.',
      beginner: 'Umpires kill the play for injuries, batters stepping out, balls out of play. While the ball is dead, runners can\'t advance and no outs can be made.',
      intermediate: 'The same two-arms-up mechanic announces a FOUL ball (with the verbal call and a point to foul ground). That\'s why you\'ll see it dozens of times a game — dead ball is baseball\'s most common state change.',
      expert: 'The deep rule: baseball is a dead-ball/live-ball state machine. "Time" flips the switch, and NOTHING (steals, runs, appeals) happens while it\'s off; play resumes only when the umpire points at the pitcher and calls "Play." Reading this pair tells you exactly when the game is actually ON.',
    },
  },
  {
    id: 'mlb-sig-kid-5', level: 'kid', signal: 'mlb-homerun',
    prompt: 'The ball sails over the wall and the umpire circles a raised finger overhead. That circle means…',
    options: ['Home run — run all the bases!', 'Foul ball', 'The game is tied'],
    answer: 0,
    title: 'The finger twirl: home run',
    exp: {
      kid: 'The circling finger means HOME RUN! The batter gets to jog around all four bases and score. The circle copies the trip around the bases!',
      beginner: 'A ball over the outfield fence in fair territory is a home run — the batter and every runner on base score. The circular signal mimics the base tour.',
      intermediate: 'The umpire\'s judgment moment is the fence: over in FAIR territory = home run; bouncing over = a "ground-rule" style double (two bases). Watch which signal follows a wall-scraper — twirl vs two fingers tells the story instantly.',
      expert: 'Boundary calls are the classic replay case: fan interference, ball hitting the top of the wall, fair/foul at the pole. The pole itself is IN fair territory — hit it and the twirl comes out. When umpires huddle before twirling, they\'re reconstructing exactly which side of these lines the ball crossed.',
    },
  },
  {
    id: 'mlb-sig-kid-6', level: 'kid', signal: 'mlb-fair',
    prompt: 'A ball lands near the line and the umpire silently points toward the field. What is the call?',
    options: ['Fair ball — keep playing!', 'Foul ball', 'Time out'],
    answer: 0,
    title: 'The silent point: fair ball',
    exp: {
      kid: 'Pointing into the field means the ball is FAIR — it counts! Batters run, fielders throw. And here\'s a secret: the umpire says nothing out loud for fair balls.',
      beginner: 'Fair calls are signal-only — no verbal call, ever. Why? Yelling "FAIR!" could be misheard as "FOUL!" With foul balls it\'s the reverse: loud verbal plus arms up.',
      intermediate: 'The rule of thumb umpires teach: on anything close to the line, watch the hands, not the mouth. Point = fair, play live. Arms up + voice = foul, everything stops.',
      expert: 'Fair/foul is decided by WHERE the ball is when it\'s touched or settles relative to the line (before the base) or where it lands/passes the base (beyond it) — the fielder\'s feet are irrelevant. The silent point exists because a mistaken shout on a live ball is uncorrectable chaos; a point never is.',
    },
  },

  // ── beginner ──────────────────────────────────────────────────────────────
  {
    id: 'mlb-sig-beg-1', level: 'beginner', signal: 'mlb-count',
    prompt: 'The umpire holds up fingers on both hands — three on the left, two on the right. What is being shown?',
    options: ['The count: 3 balls, 2 strikes', 'The score: 3–2', 'Three outs coming'],
    answer: 0,
    title: 'Fingers up: the count',
    exp: {
      kid: 'The umpire is showing the COUNT — how the batter is doing. Left hand = balls (3), right hand = strikes (2). That\'s a "full count" — the next good pitch decides!',
      beginner: 'Convention: balls on the left hand, strikes on the right, spoken "three and two." 4 balls = walk to first; 3 strikes = out. A 3–2 count means every pitch is live drama.',
      intermediate: 'The count IS the tactical state: 3–0 the batter can sit on a perfect pitch; 0–2 the pitcher can waste one in the dirt. Umpires re-show the count precisely because both teams\' strategies branch on it.',
      expert: 'Count-keeping errors are protestable, which is why the mechanic is formalized (show it after foul balls, delays, and on request). Note the order is always balls-then-strikes worldwide — "2 and 1" is 2 balls. Softball/other codes may flip hands, but the spoken order never flips.',
    },
  },
  {
    id: 'mlb-sig-beg-2', level: 'beginner', signal: 'mlb-strike',
    prompt: 'The umpire points to the side but the batter never swung. What kind of strike is this?',
    options: ['A called strike — the pitch caught the zone', 'A foul ball', 'A balk'],
    answer: 0,
    title: 'The called strike',
    exp: {
      kid: 'The batter let a good pitch go by, so the umpire calls the strike FOR him. Watching a perfect pitch counts the same as missing it!',
      beginner: 'The strike zone is roughly over the plate, from the knees to the mid-torso. Take a pitch inside it and the umpire\'s point says: that one counted.',
      intermediate: 'The zone is defined by the BATTER\'S stance, so it moves player to player — one reason framing (catchers subtly holding borderline pitches) is a real skill aimed directly at this signal.',
      expert: 'The called strike is the most-judged event in sports — roughly 150 taken pitches a game, each a zone decision. Umpire "consistency" matters more to players than exact geometry: a zone that\'s identical for both teams all night is considered well-umpired even if slightly wide.',
    },
  },
  {
    id: 'mlb-sig-beg-3', level: 'beginner', signal: 'mlb-time',
    prompt: 'A batted ball lands outside the line. The umpire throws both arms up and shouts. What\'s the ruling?',
    options: ['Foul ball — dead, runners return', 'Home run', 'The batter walks'],
    answer: 0,
    title: 'Arms up + a shout: foul ball',
    exp: {
      kid: 'That\'s a FOUL BALL — it landed outside the lines. Everybody stops, runners go back, and the batter tries again.',
      beginner: 'Foul balls kill the play: runners return, and the batter gets a strike (unless he already has two — a foul can\'t be strike three, except a bunt or caught foul tip).',
      intermediate: 'Same arms as "Time" — the shared mechanic is DEAD BALL. The verbal ("Foul!") plus a point to foul territory is what specifies the cause. Loud voice on fouls, silence on fairs: mishearing must always fail safe.',
      expert: 'The two-strike foul rule creates baseball\'s war of attrition: a batter can foul off pitch after pitch to survive, driving up pitch counts. Exception worth knowing: a two-strike BUNT fouled = strikeout, and a caught foul TIP (sharp, direct to the glove) is a live strike three — different signal entirely.',
    },
  },
  {
    id: 'mlb-sig-beg-4', level: 'beginner', signal: 'mlb-infield-fly',
    prompt: 'With runners on first and second, a high pop-up goes to the shortstop — and the umpire points straight up. What did he just declare?',
    options: ['Infield fly — the batter is automatically out', 'Home run', 'Time out'],
    answer: 0,
    title: 'The skyward point: infield fly',
    exp: {
      kid: 'Pointing straight up means the batter is OUT automatically on this easy pop-up — even before it\'s caught! It\'s a special rule that protects the runners.',
      beginner: 'Infield fly rule: with runners on 1st+2nd (or bases loaded) and fewer than two outs, an easy infield pop makes the batter out immediately, catch or no catch.',
      intermediate: 'The rule exists to kill a cheat: without it, an infielder could drop the pop ON PURPOSE and turn an easy double play on the frozen runners. Declaring the batter out removes the force and the trick.',
      expert: 'Fine print: the umpire calls it at the ball\'s apex ("Infield fly, batter\'s out — if fair"), it never applies to line drives or bunts, and the ball stays LIVE — runners may advance at their own risk after a catch. It\'s a judgment of ordinary effort, not a location: an outfielder camped under it can still trigger the call.',
    },
  },
  {
    id: 'mlb-sig-beg-5', level: 'beginner', signal: 'mlb-safe',
    prompt: 'A pickoff throw to first. The runner dives back, and the umpire gives this flat outward sweep. What happens next?',
    options: ['Nothing — the runner stays and play continues', 'The runner must leave the field', 'The batter gets a strike'],
    answer: 0,
    title: 'Safe on the pickoff',
    exp: {
      kid: 'The runner got back to the base before the tag — SAFE! He stays right there, and the pitcher tries again.',
      beginner: 'Pickoffs test the runner\'s lead. Beat the tag back to the bag and the sweep says: no out, ball still live, same situation.',
      intermediate: 'Watch the first-base umpire\'s positioning: he squares to the tag attempt, reads glove-versus-hand, and sells the call. A pickoff safe/out is the classic replay-review play — the sweep can be challenged.',
      expert: 'Signal-reading nuance: SAFE is signaled; a no-tag ("he never touched him") gets safe PLUS a separate wiping gesture umpires add to explain why. As with fair balls, the mechanics are engineered to answer the manager\'s argument in advance.',
    },
  },
  {
    id: 'mlb-sig-beg-6', level: 'beginner', signal: 'mlb-homerun',
    prompt: 'A fly ball bounces on the warning track and hops over the fence. Does the umpire give the circling-finger signal?',
    options: ['No — that\'s two bases, not a home run', 'Yes — anything over the fence is a homer', 'Only if the outfielder touched it'],
    answer: 0,
    title: 'Over on a bounce ≠ home run',
    exp: {
      kid: 'If the ball BOUNCES before hopping the fence, it\'s not a home run. The batter only gets to second base. The finger circle stays in the pocket!',
      beginner: 'A ball must clear the fence on the fly, in fair territory, for the home-run twirl. On a bounce it\'s a book-rule double: batter to second, runners two bases.',
      intermediate: 'You\'ll see the umpire signal TWO (fingers) or point to second instead — the anti-home-run. Runners already past their two-base award must return, which can wipe an apparent run off the board.',
      expert: 'Common confusion: people call this a "ground-rule double," but it\'s a universal RULE-book double — ground rules are park-specific quirks (catwalks, ivy). Either way, the umpire\'s job is placement: kill the ball, award exactly two bases from the time of pitch, and the twirl never appears.',
    },
  },

  // ── intermediate ──────────────────────────────────────────────────────────
  {
    id: 'mlb-sig-int-1', level: 'intermediate', signal: 'mlb-foul-tip',
    prompt: 'The umpire brushes one hand over the other at shoulder height, then signals a strike. What just happened?',
    options: ['A foul tip — caught, so it\'s a live strike', 'A foul ball into the stands', 'A checked swing'],
    answer: 0,
    title: 'The brush: foul tip',
    exp: {
      kid: 'The batter barely nicked the ball and the catcher caught it anyway. That tiny touch is a FOUL TIP — it counts as a strike, and the game keeps going!',
      beginner: 'A foul tip is a ball that grazes the bat and goes SHARP and DIRECT into the catcher\'s glove. Unlike a foul ball, it\'s a live strike — and with two strikes it\'s a strikeout.',
      intermediate: 'That live/dead difference is everything: runners can steal on a foul tip (the ball never went dead), while a foul ball sends them back. The brush signal exists precisely to announce "this stays live."',
      expert: 'Definition matters: if the nicked ball pops UP even slightly before the catcher gloves it, it\'s a foul BALL, not a tip — dead, and can\'t be strike three. That arc-vs-direct judgment, signaled by brush versus raised arms, decides strikeouts and stolen bases in the same instant.',
    },
  },
  {
    id: 'mlb-sig-int-2', level: 'intermediate', signal: 'mlb-delayed-dead',
    prompt: 'The umpire silently extends his LEFT arm straight out, fist clenched, while play continues. What is he holding?',
    options: ['A delayed dead ball — e.g. catcher\'s interference, sorted after the play', 'A strike call', 'An immediate ejection'],
    answer: 0,
    title: 'The left-arm fist: delayed dead ball',
    exp: {
      kid: 'The umpire saw something wrong — like the bat clipping the catcher\'s glove — but he lets the play finish first. The stretched-out fist means "I saw it, we\'ll fix it in a moment."',
      beginner: 'On catcher\'s interference and similar violations, the umpire signals with the left fist and lets the play run. Afterward, the offense gets the penalty — or keeps the play if it turned out better.',
      intermediate: 'It\'s baseball\'s advantage rule: batter hits interference and singles anyway? The single stands. Grounds out? Take the interference: batter to first. The delayed mechanic preserves the CHOICE.',
      expert: 'Same philosophy as a football flag on a live play or rugby\'s advantage arm — penalize without stealing a better outcome. Note the hand: LEFT arm, because the right is reserved for strikes/outs. An umpire\'s two hands literally carry two channels of information.',
    },
  },
  {
    id: 'mlb-sig-int-3', level: 'intermediate', signal: 'mlb-infield-fly',
    prompt: 'Infield fly is declared… and the shortstop drops the ball. A runner takes off for third. What\'s the ruling on that runner?',
    options: ['Legal — the ball is live; he advances at his own risk', 'Automatically out', 'He must return to second'],
    answer: 0,
    title: 'Infield fly ≠ dead ball',
    exp: {
      kid: 'Even though the batter is out, the ball is still IN PLAY! The runner is allowed to run — it\'s just risky.',
      beginner: 'Infield fly makes the BATTER out; nothing else stops. Dropped ball: runners may advance (no force — they can\'t be forced because the batter is already out). Caught: normal tag-up rules.',
      intermediate: 'This is the most misunderstood signal in baseball: fans think "automatic out = play over." Smart runners exploit the fielder\'s confusion on a drop; smart fielders remember the force is OFF, so they must tag, not step.',
      expert: 'Chess depth: with the force removed, a dropped infield fly creates a tag-only situation the defense rarely rehearses. Meanwhile the runner reads the umpire\'s raised arm as the signal that changed the rules mid-play. One skyward point rewrites the entire baserunning logic for everyone on the field.',
    },
  },
  {
    id: 'mlb-sig-int-4', level: 'intermediate', signal: 'mlb-out',
    prompt: 'Fly ball to the wall, the umpire watches the catch, pauses… then hammers the fist. Why the deliberate delay before this signal?',
    options: ['He must see the ball held securely through the play first', 'He forgot the signal', 'TV asked for suspense'],
    answer: 0,
    title: 'Timing: see it, then call it',
    exp: {
      kid: 'The umpire waits to make sure the fielder REALLY caught it and didn\'t drop it while falling. Then — hammer! Out.',
      beginner: 'A catch requires secure possession and a voluntary release. Umpires are trained to let the play finish — a ball popping loose on the wall collision means no catch at all.',
      intermediate: 'The pause is a core mechanic ("proper timing"): call the play\'s END, not its middle. Fast calls get overturned; a beat of patience produces the right hammer or the right safe sweep.',
      expert: 'Transfer rule nuance: dropping the ball while REACHING to throw is still a catch; dropping during the catching act is not. The umpire\'s eyes track glove-to-hand transfer before the fist moves. When you see a delayed hammer at the wall, you watched that entire legal analysis happen in silence.',
    },
  },
  {
    id: 'mlb-sig-int-5', level: 'intermediate', signal: 'mlb-fair',
    prompt: 'A slow roller dribbles up the third-base line. The umpire hovers, watching it, hands quiet. What is he waiting for?',
    options: ['Where the ball is when touched or stops — that decides fair/foul', 'The crowd\'s opinion', 'The batter to reach first'],
    answer: 0,
    title: 'The hover: fair/foul is about the ball, not the fielder',
    exp: {
      kid: 'The umpire watches the BALL, not the players. If it\'s on or inside the line when someone touches it (or when it stops), the point says FAIR.',
      beginner: 'Before the base, fair/foul is judged where the ball is when touched or when it settles — a ball can wobble in foul ground and roll back fair. Fielders often let rollers drift, hoping they cross foul.',
      intermediate: 'That\'s why third basemen theatrically crouch over a crawling ball doing nothing: touching it in fair territory MAKES it fair. Position of the fielder\'s feet is irrelevant — only the ball versus the line matters.',
      expert: 'Beyond first/third base the test changes: it\'s where the ball lands or passes the BAG (the bag itself is fair — a ball nicking the corner is fair). The umpire\'s silent hover, then a sudden point or arms-up, is a two-zone geometry decision most spectators never realize is being computed.',
    },
  },
  {
    id: 'mlb-sig-int-6', level: 'intermediate', signal: 'mlb-count',
    prompt: 'After a long foul-ball battle, the umpire re-shows fingers: left hand 1, right hand 2. The NEXT pitch is fouled into the stands. What\'s the new count?',
    options: ['Still 1–2 — fouls don\'t add a third strike', '1–3 — strikeout', '2–2'],
    answer: 0,
    title: 'The two-strike foul freeze',
    exp: {
      kid: 'With two strikes, foul balls don\'t count against you! The count stays 1 ball, 2 strikes — the batter survives to try again.',
      beginner: 'Fouls are strikes only up to strike two. After that, a foul changes nothing (except a bunt — a two-strike foul bunt IS strike three). The count freezes at x–2 through any number of fouls.',
      intermediate: 'This creates the "spoiling" battle: two-strike hitters shorten their swing purely to foul off tough pitches, waiting for a mistake. Ten-pitch at-bats are won by this rule.',
      expert: 'Strategic economics: every spoiled pitch raises the starter\'s pitch count (~100 is a typical leash), so spoiling has value even when the at-bat ends in an out. The umpire\'s re-shown 1–2 after each foul is the scoreboard of a war of attrition the casual eye reads as "nothing happening."',
    },
  },

  // ── expert ────────────────────────────────────────────────────────────────
  {
    id: 'mlb-sig-exp-1', level: 'expert', signal: 'mlb-time',
    prompt: 'Arms up — dead ball — while a runner is halfway between second and third. Where does he end up?',
    options: ['Depends on the cause: he returns or is placed by rule, not by his position', 'Always back to second', 'Always awarded third'],
    answer: 0,
    title: 'Dead-ball placement is by rule, not by feet',
    exp: {
      kid: 'When everything stops, the umpire decides where runners belong using the rules — not where they happened to be standing when he yelled stop.',
      beginner: 'Each dead-ball cause carries its own award: foul ball = return to the time-of-pitch base; ball thrown into the stands = two bases; hit-by-pitch = batter to first, runners move only if forced.',
      intermediate: 'The key concept is the award BASELINE: awards count "from the time of pitch" or "time of throw" depending on the violation. Overthrow into the dugout from an infielder\'s first play = two bases from time of PITCH — even if the runner had already rounded second.',
      expert: 'This is where arguments actually live: nobody disputes the arms-up, they dispute the placement math after it. Master the awards table (foul: return; overthrow: 2 from the relevant baseline; balk: 1; HBP: force only) and you can predict every runner\'s final base before the umpire points them there.',
    },
  },
  {
    id: 'mlb-sig-exp-2', level: 'expert', signal: 'mlb-delayed-dead',
    prompt: 'Left-arm fist out. The batter grounds into a double play anyway. The offense\'s manager comes out. What is he asking for?',
    options: ['To take the catcher\'s-interference award instead of the play', 'A replay of the pitch', 'An ejection'],
    answer: 0,
    title: 'The interference option',
    exp: {
      kid: 'Because the catcher bumped the bat, the hitting team gets a CHOICE: keep what happened, or take the free base. A double play is bad — so they\'ll take the free base!',
      beginner: 'Catcher\'s interference: batter awarded first base, runners advance if forced. But if the play\'s outcome was BETTER for the offense, the manager can elect to keep it instead.',
      intermediate: 'The election rule turns the left-arm fist into a free insurance policy for the offense: bad result → take the award; great result (say, a two-run double) → wave the award off and keep the hit.',
      expert: 'Precise mechanics: interference is enforced automatically UNLESS the manager elects the play — and if the batter reaches first AND all runners advance a base, the play stands with no option. Also scoring nuance: catcher\'s interference doesn\'t count as an at-bat and the catcher is charged an error. One quiet fist, an entire decision tree.',
    },
  },
  {
    id: 'mlb-sig-exp-3', level: 'expert', signal: 'mlb-foul-tip',
    prompt: 'Runner stealing on the pitch; batter nicks it sharp into the mitt (this brush signal follows); the catcher throws to second anyway — late. Result?',
    options: ['Strike on the batter AND a stolen base — everything stays live', 'Foul, runner returns', 'Batter out for interference'],
    answer: 0,
    title: 'Foul tip: the play within the play',
    exp: {
      kid: 'A foul tip doesn\'t stop anything! The batter gets a strike, and because the runner kept going, he steals the base fair and square.',
      beginner: 'Foul tip = live ball. The steal attempt proceeds exactly as if the batter had missed cleanly: safe at second means a stolen base plus a strike on the batter.',
      intermediate: 'Compare the near-miss: if that nick had popped up before hitting leather, it\'s a foul BALL — dead, runner marched back. Millimeters of ball flight, opposite baserunning universes, and the umpire\'s brush-vs-arms-up broadcasts which one occurred.',
      expert: 'Catchers know this rule better than anyone: with two strikes and a runner going, a caught tip is simultaneously a strikeout AND still a live steal — the rare "strike \'em out, throw \'em out" where the strikeout came off the BAT. Decode the brush signal and you\'re never confused about why nobody stopped playing.',
    },
  },
  {
    id: 'mlb-sig-exp-4', level: 'expert', signal: 'mlb-strike',
    prompt: 'A checked-swing appeal: the plate umpire asks the base umpire, who gives THIS signal. What was decided?',
    options: ['The batter DID swing — strike', 'The batter held up — ball', 'The pitch was a balk'],
    answer: 0,
    title: 'The appealed check swing',
    exp: {
      kid: 'The far-away umpire had the best side view. His strike signal means the bat DID come around — so the swing counts as a strike.',
      beginner: 'On a checked swing, the catcher or plate umpire may appeal to the first- or third-base umpire, who saw the bat edge-on. Fist/point = swing (strike); a safe-style sweep = no swing.',
      intermediate: 'There\'s no precise rulebook definition of a swing ("did he offer at the pitch?") — it\'s pure judgment, which is why the side angle matters and why the appeal exists at all.',
      expert: 'Procedural teeth: if the plate umpire called it a BALL, the defense can force the appeal; a check-swing appeal can\'t be refused. The reversed call is common on strike three with a runner stealing — a whole cascade (strikeout + throw-down) hangs on a base umpire\'s little punch from 90 feet away.',
    },
  },
  {
    id: 'mlb-sig-exp-5', level: 'expert', signal: 'mlb-safe',
    prompt: 'The sweep is given at the plate, then the defense\'s catcher steps on home and appeals — and the SAME umpire hammers an out. What kind of play allows this reversal?',
    options: ['A missed-plate appeal: the runner never touched home', 'Umpires may flip any call once', 'A replay from the dugout'],
    answer: 0,
    title: 'Safe… until the appeal',
    exp: {
      kid: 'The runner slid past the plate without touching it! He looked safe, but when the catcher tagged the plate and asked, the umpire changed to OUT — you must touch every base.',
      beginner: 'Missing a base isn\'t called automatically. The umpire signals the apparent result (safe on the tag attempt) and waits: only if the defense APPEALS the missed touch does the out appear.',
      intermediate: 'That\'s why you\'ll see catchers casually tag the plate after a wild slide — it\'s a formal appeal. If the runner scrambles back and touches home before the appeal tag, the run counts after all.',
      expert: 'The two signals aren\'t contradictory: the sweep answered "did the tag beat him?" (no); the hammer answered a NEW question, "did he touch the plate?" (also no). Appeals are separate plays with separate calls. Umpiring is question-answering, and knowing WHICH question a signal answers is expert-level decoding.',
    },
  },
  {
    id: 'mlb-sig-exp-6', level: 'expert', signal: 'mlb-infield-fly',
    prompt: 'Umpire points skyward on a pop-up drifting near the line, calling "Infield fly IF FAIR." It lands untouched in foul ground and spins foul. Final ruling?',
    options: ['Just a foul ball — the infield-fly call evaporates', 'Batter out anyway', 'Batter out AND a dead ball'],
    answer: 0,
    title: '"If fair" — the conditional out',
    exp: {
      kid: 'The umpire\'s call had a secret word: IF FAIR. The ball landed foul, so there\'s no automatic out — it\'s just a normal foul ball and the batter bats again.',
      beginner: 'Near the lines, the declaration is conditional: fair = batter out (infield fly); foul = ordinary foul ball, call canceled. The verbal "if fair" is a built-in escape hatch.',
      intermediate: 'Everything from the earlier rule still applies on the fair branch (live ball, force removed) — but the foul branch rewinds completely: strike on the batter (if fewer than two), runners back, nothing happened.',
      expert: 'This is the most conditional call in baseball: an out that exists in superposition until the ball resolves fair or foul, with fair/foul itself judged by the touched-or-settles rules. The pointing arm plus three spoken words encode a full branching ruling — signal literacy at its densest.',
    },
  },
];
