// Signal Decoder — NBA bank. Referee signals only (evergreen, rule-based; verified
// against the shared NBA/FIBA/NFHS officiating signal grammar — differences noted
// in the explanations where relevant). 6 scenarios per tier × 4 tiers. Pure data.
import type { SignalScenario } from '../signalDecoder';

export const NBA_SIGNAL_SCENARIOS: SignalScenario[] = [
  // ── kid ────────────────────────────────────────────────────────────────────
  {
    id: 'nba-sig-kid-1', level: 'kid', signal: 'nba-travel',
    prompt: 'The referee rolls both fists around each other in front of the chest. What is the call?',
    options: ['Traveling — too many steps', 'A three-pointer', 'Halftime'],
    answer: 0,
    title: 'Rolling fists: traveling',
    exp: {
      kid: 'The rolling fists mean TRAVELING — the player took too many steps without bouncing (dribbling) the ball. The other team gets it.',
      beginner: 'You must dribble while moving. Stop your dribble and you get a pivot foot plus limited steps; move that pivot foot or run without dribbling and the rolling fists come out. Turnover.',
      intermediate: 'The modern rule allows the "gather" plus two steps on a drive — that\'s why some moves look like three steps but are legal. The referee is judging when the gather happened, not just counting footfalls.',
      expert: 'Cross-sport trap: this exact rolling-fists motion means FALSE START in football and CHARGING in hockey. Same pictogram, three sports, three meanings — signal vocabularies are per-sport languages, and traveling is basketball\'s most argued judgment call because the gather is invisible to casual eyes.',
    },
  },
  {
    id: 'nba-sig-kid-2', level: 'kid', signal: 'nba-three-good',
    prompt: 'A long shot splashes in and the referee throws BOTH arms straight up. What does it mean?',
    options: ['The three-pointer counts!', 'The player is out of the game', 'Timeout'],
    answer: 0,
    title: 'Both arms up: three points!',
    exp: {
      kid: 'Both arms in the air means the long shot counts for THREE points — one more than a normal basket, because it came from behind the big curved line.',
      beginner: 'Shots from behind the three-point arc are worth 3; inside it, 2. One arm up = attempt from three-land; both arms up when it drops = confirmed three.',
      intermediate: 'The two-stage mechanic exists for the scorer\'s table: the ATTEMPT signal (one arm, before the shot lands) tells the scorers what\'s at stake; the both-arms confirmation locks in 3 instead of 2.',
      expert: 'The referee is ruling on FEET, not the ball\'s flight: both feet must be completely behind the line at launch — a heel on the line makes it a 2. Toe-on-the-line reviews exist precisely because this signal commits a point of value either way.',
    },
  },
  {
    id: 'nba-sig-kid-3', level: 'kid', signal: 'nba-foul',
    prompt: 'The whistle blows and the referee shoots one arm straight up with a closed FIST. What happened?',
    options: ['A foul — someone hit or grabbed an opponent', 'A goal', 'The game is over'],
    answer: 0,
    title: 'Fist up: foul',
    exp: {
      kid: 'The raised fist means FOUL — a player pushed, hit, or grabbed someone. Basketball is a no-grabbing game!',
      beginner: 'A closed fist stops the clock for a personal foul. What follows tells you the price: free throws if the victim was shooting (or the team is in the bonus), otherwise a sideline inbound.',
      intermediate: 'Players collect fouls: 6 in the NBA (5 in FIBA/college) and you\'re done for the night. Watching the fist plus the number the referee then shows the table tells you who\'s in foul trouble.',
      expert: 'Decoder key: FIST up = foul (clock stops, someone is charged); OPEN HAND up = violation (clock stops, just a turnover, nobody charged). That one-hand-shape difference is the fastest way to read a whistle from the cheap seats — and the distractor pair this game will test you on later.',
    },
  },
  {
    id: 'nba-sig-kid-4', level: 'kid', signal: 'nba-technical',
    prompt: 'The referee makes a "T" with two hands. What is being called?',
    options: ['A technical foul — bad behavior', 'A timeout for TV', 'A three-pointer'],
    answer: 0,
    title: 'The T: technical foul',
    exp: {
      kid: 'The T means TECHNICAL FOUL — someone was rude, argued too much, or broke a non-playing rule. The other team gets a free shot!',
      beginner: 'Technicals punish conduct, not contact: yelling at officials, taunting, hanging on the rim, delay tricks. Penalty: a free throw for the opponent plus possession-related consequences by level.',
      intermediate: 'Two technicals = automatic ejection. Coaches can get them too — and a technical\'s free throw can be taken by anyone on the floor, making late-game techs pure gifted points.',
      expert: 'Technicals also cover ILLEGAL DEFENSE (NBA defensive three-seconds) and too-many-players — administrative infractions where the T is bookkeeping, not anger. Reading whether a T followed a shouting match or a quiet defensive reset tells you which species you just saw.',
    },
  },
  {
    id: 'nba-sig-kid-5', level: 'kid', signal: 'nba-jump-ball',
    prompt: 'Two players wrestle for the ball, whistle blows, and the referee raises BOTH thumbs up. What\'s the ruling?',
    options: ['Held ball — a jump ball decides who gets it', 'Both players did great', 'Two free throws'],
    answer: 0,
    title: 'Thumbs up: held ball',
    exp: {
      kid: 'Two thumbs up means both players grabbed the ball at the same time and neither would let go. It\'s nobody\'s ball — so the referee makes it fair!',
      beginner: 'A held ball (two opponents with firm grips) triggers the jump-ball signal. In the NBA the two players actually jump; in college/FIBA the possession arrow at the scorer\'s table decides instead.',
      intermediate: 'Defenders hunt this call on purpose: tying up a rebounder is far better than fouling. The thumbs are a small win for whichever team is more athletic (NBA jump) or holds the arrow (other levels).',
      expert: 'The NBA is the last major level with a live re-jump — everywhere else the alternating-possession arrow made the thumbs a bookkeeping signal. Watch late NBA games: a tie-up with a superior leaper is a designed defensive play, and this signal is its payoff.',
    },
  },
  {
    id: 'nba-sig-kid-6', level: 'kid', signal: 'nba-blocking',
    prompt: 'Whistle! The referee puts both hands on his hips. Which foul is this?',
    options: ['Blocking — the defender got in the way illegally', 'Traveling', 'A slam dunk'],
    answer: 0,
    title: 'Hands on hips: blocking',
    exp: {
      kid: 'Hands on hips means BLOCKING — the defender jumped in front of a moving player too late and caused the crash. Foul on the defense!',
      beginner: 'A defender must establish position BEFORE the ball carrier commits. Arrive late and cause contact: blocking foul on the defense — the offense keeps the ball or shoots free throws.',
      intermediate: 'The eternal pairing: blocking (hands on hips, defense\'s fault) versus charging (fist into palm, offense\'s fault). Same crash, opposite verdicts, decided by whether the defender\'s feet were set in time.',
      expert: 'The NBA adds geography: the restricted-area arc under the rim, inside which a secondary defender can NEVER draw a charge. So this signal near the rim often means "legal guarding position, wrong postcode." Block/charge is the fastest whistle in the sport — and the most replay-reviewed.',
    },
  },

  // ── beginner ──────────────────────────────────────────────────────────────
  {
    id: 'nba-sig-beg-1', level: 'beginner', signal: 'nba-violation',
    prompt: 'The whistle blows and one arm goes straight up — but with an OPEN hand, not a fist. What kind of call is this?',
    options: ['A violation — turnover, but no foul on anyone', 'A personal foul', 'A made basket'],
    answer: 0,
    title: 'Open hand up: violation',
    exp: {
      kid: 'An open hand means a RULE was broken — like stepping out of bounds — but nobody gets in trouble. The other team just gets the ball.',
      beginner: 'Violations (travel, double dribble, out of bounds, 3-in-the-key) cost possession only. No player is charged, no free throws — the open palm stops the clock, then a second signal names the offense.',
      intermediate: 'The open hand is the header of a two-part message: palm = "violation, clock stopped," then rolling fists (travel) or patting motion (illegal dribble) etc. Learn to wait for the second gesture.',
      expert: 'Fist vs palm is the referee\'s most information-dense binary: it instantly divides the rulebook in half (fouls: charged, may bring free throws, count toward limits — versus violations: uncharged, possession only). Every other signal is a footnote to which hand shape started the sentence.',
    },
  },
  {
    id: 'nba-sig-beg-2', level: 'beginner', signal: 'nba-three-attempt',
    prompt: 'As a player rises from deep, one referee raises a single arm with three fingers — BEFORE the ball lands. Why signal now?',
    options: ['Marking a 3-point attempt so scorers award it right if it drops', 'The shot already counts', 'Three seconds left'],
    answer: 0,
    title: 'One arm up: three-point attempt',
    exp: {
      kid: 'The referee is saying "this shot is from three-land!" while the ball is still flying. If it goes in, everyone already knows it\'s worth 3.',
      beginner: 'The nearest official checks the shooter\'s feet at launch and holds the attempt signal. Make: both arms go up (3 confirmed). Miss: the arm simply drops. The value was decided at takeoff.',
      intermediate: 'Officials divide the floor; the referee "on the line" owns this call. Watching for the raised arm during a scramble tells you a corner three was launched even when you couldn\'t see the feet.',
      expert: 'Why pre-signal? Because value disputes after the fact are messy: the scorer needs a contemporaneous ruling. Replay can fix 2-vs-3 at limited stoppages, but the attempt arm is the primary record — an on-court paper trail written in the air.',
    },
  },
  {
    id: 'nba-sig-beg-3', level: 'beginner', signal: 'nba-charge',
    prompt: 'A driving player flattens a set defender. The referee punches a fist into his open palm. Who\'s in trouble?',
    options: ['The OFFENSIVE player — charging', 'The defender — blocking', 'Both players'],
    answer: 0,
    title: 'Fist into palm: charging',
    exp: {
      kid: 'That punch-into-the-hand means CHARGING — the player WITH the ball ran over a defender who was standing still first. Foul on the ball carrier!',
      beginner: 'If the defender establishes legal position before contact, the collision is the ball carrier\'s fault: an offensive foul. Turnover — and the basket doesn\'t count if the shot went in.',
      intermediate: 'The charge/block decision hangs on split-second geometry: torso-to-torso contact with the defender set = charge (this signal); defender still sliding = blocking (hands on hips). Defenders "take charges" deliberately — sacrificing the body to win possession.',
      expert: 'Charging counts as a personal foul on the shooter AND kills any score — which is why late-game rim protectors position for charges instead of blocks. NBA nuance: inside the restricted arc a secondary defender can\'t draw this call, and a defender may always protect against a shooter\'s airborne path he legally owned. The punch signal ends more highlight dunks than any shot block.',
    },
  },
  {
    id: 'nba-sig-beg-4', level: 'beginner', signal: 'nba-count-basket',
    prompt: 'Contact on a made layup — whistle — and the referee punches one arm DOWN toward the floor. What is he saying?',
    options: ['The basket COUNTS, plus a foul — "and one"', 'The basket is waved off', 'Jump ball'],
    answer: 0,
    title: 'The down-punch: count the basket',
    exp: {
      kid: 'The downward punch means the basket COUNTS even though there was a foul! The shooter also gets one free throw — that\'s the famous "and one."',
      beginner: 'If a player is fouled while shooting and scores anyway: bucket counts + 1 free throw. The down-punch confirms the score; without it, the foul would\'ve meant two fresh free throws instead.',
      intermediate: 'The opposite ruling — foul BEFORE the shooting motion — gets a wave-off: no basket, side-out or two shots. The down-punch versus wave-off pair decides a possible 3-point swing on the same play.',
      expert: 'The judgment inside the signal is "continuation": had the shooting motion begun when the contact occurred? NBA continuation is famously generous (gather-to-finish counts); FIBA cuts it earlier. Same punch, different legal thresholds — knowing which rulebook you\'re watching changes what this signal predicts.',
    },
  },
  {
    id: 'nba-sig-beg-5', level: 'beginner', signal: 'nba-direction',
    prompt: 'The ball skips off two sets of fingers and out of bounds. The referee points firmly along the sideline. What does the point tell you?',
    options: ['Which team gets the throw-in — attack that way', 'A player must leave', 'A three-pointer'],
    answer: 0,
    title: 'The directional point: possession',
    exp: {
      kid: 'The point shows which team gets the ball now. The referee points the way THAT team is attacking — like a traffic sign for basketball.',
      beginner: 'Out-of-bounds calls come with a direction: last touch loses the ball. The arm points toward the basket the awarded team attacks, then the throw-in happens where the ball left.',
      intermediate: 'Deflection scrambles make this the most disputed routine call — hence players instantly pointing the other way like counter-referees. Officials confer or go to replay in crunch time precisely because the point IS the possession ruling.',
      expert: 'Watch mechanics on close ones: the official first signals the stoppage, then the point — sometimes after a crew conference where the referee with the best sightline overrides. In the last two minutes, out-of-bounds touches are replay-reviewable, so the point can flip after the monitor. The gesture is simple; the evidence chain behind it isn\'t.',
    },
  },
  {
    id: 'nba-sig-beg-6', level: 'beginner', signal: 'nba-shot-clock',
    prompt: 'The horn sounds and the referee taps fingers to the top of the shoulder. What ran out?',
    options: ['The shot clock — 24 seconds, turnover', 'The game clock', 'Substitution time'],
    answer: 0,
    title: 'The shoulder tap: shot-clock violation',
    exp: {
      kid: 'The tap means the attacking team took TOO LONG to shoot. You get 24 seconds to try a shot — miss the deadline and the other team gets the ball.',
      beginner: 'The shot must at least hit the rim within 24 seconds. Horn + this signal = violation: turnover at the nearest sideline spot. Rim contact resets the clock (to 14 on an offensive rebound in the NBA).',
      intermediate: 'The 24 defines basketball\'s tempo: defenses win by making teams burn clock, and the last 4 seconds of a possession produce the worst shots in the sport. This signal is the defense\'s reward for 24 seconds of good work.',
      expert: 'Fine points: the ball must LEAVE the hand before the horn and then hit the rim; an airball beaten by the horn is still a violation. The 14-second offensive-rebound reset (adopted to speed up play) means this signal now appears most often after long defensive stands, not lazy offense.',
    },
  },

  // ── intermediate ──────────────────────────────────────────────────────────
  {
    id: 'nba-sig-int-1', level: 'intermediate', signal: 'nba-foul',
    prompt: 'Fist up — then the referee holds up two fingers toward the scorer\'s table and points at the free-throw line. Assemble the full ruling.',
    options: ['Shooting foul: two free throws', 'Two players ejected', 'A 2-point basket counted'],
    answer: 0,
    title: 'Signal sentences: foul + shots',
    exp: {
      kid: 'Referees talk in steps: FIST (a foul happened), fingers (how many free shots), point to the line (go shoot them). Two fingers = two free throws!',
      beginner: 'A foul on a 2-point shot attempt that misses = 2 free throws; on a 3-point attempt, 3. The finger count relays to the scorer exactly what was awarded and to whom.',
      intermediate: 'If the shot had gone IN, you\'d have seen the down-punch (count it) and ONE finger instead. Reading fist → count-or-cancel → finger number lets you reconstruct the whole play with your ears off.',
      expert: 'The table communication layer is a distinct grammar: fouler\'s number (shown with fingers), foul type, shots. TV cuts away, but the sequence is contractual — the official scorer can\'t book anything until it\'s signaled. Every free-throw controversy traces back to this choreography.',
    },
  },
  {
    id: 'nba-sig-int-2', level: 'intermediate', signal: 'nba-blocking',
    prompt: 'Hands on hips near the rim — but the defender looked set. What single piece of court geography most likely turned this into blocking anyway?',
    options: ['He was inside the restricted-area arc', 'He was outside the three-point line', 'He was in the backcourt'],
    answer: 0,
    title: 'The restricted arc: no charges allowed',
    exp: {
      kid: 'There\'s a little curved line right under the basket. Defenders standing inside it can\'t win a crash — even standing super still. Too close to the hoop!',
      beginner: 'The restricted area (a 4-foot arc under the rim) exists so help defenders can\'t camp beneath a flying finisher. Inside it, a secondary defender\'s "perfect charge" is ruled blocking.',
      intermediate: 'That\'s why you see defenders straddle-checking their heels before contact — an inch decides fist-into-palm versus hands-on-hips. Replay reviews of arc position are standard on crunch-time crashes.',
      expert: 'Rationale: the arc trades a defensive right for player safety and dunk aesthetics — undercutting airborne players caused injuries. Note the exemption: the PRIMARY defender who beat the driver to the spot can still draw a charge in the arc. Geography modifies, never fully replaces, the position-first principle.',
    },
  },
  {
    id: 'nba-sig-int-3', level: 'intermediate', signal: 'nba-technical',
    prompt: 'A quiet moment — no argument anywhere — and a referee signals the T while pointing into the defense\'s paint. What was probably called?',
    options: ['Defensive three-seconds (illegal defense)', 'A fight', 'Hanging on the rim'],
    answer: 0,
    title: 'The administrative T',
    exp: {
      kid: 'Not every T is about being naughty! Here a defender stood in the painted area too long without guarding anyone — that\'s against NBA rules, and it costs a free shot.',
      beginner: 'NBA defenders may not camp in the key for 3+ seconds unless actively guarding someone. Penalty: a technical — one free throw and the offense keeps the ball.',
      intermediate: 'This rule bans zone-parking a giant under the rim: it forces defenses to guard people, not places, and keeps driving lanes open. FIBA/college have no such rule — zones are legal there.',
      expert: 'Reading the context is everything: T + argument = conduct; T + a point at the paint mid-possession = illegal defense; T at the scorer\'s table pregame = administrative (wrong lineup). One signal, three bureaucracies. The defensive-3 T uniquely doesn\'t count toward ejection-tracking totals for conduct.',
    },
  },
  {
    id: 'nba-sig-int-4', level: 'intermediate', signal: 'nba-jump-ball',
    prompt: 'Thumbs up on a floor scramble. This is the NBA. Who actually gets the ball next?',
    options: ['Whoever wins an actual jump ball between the two players', 'The possession arrow team', 'The home team'],
    answer: 0,
    title: 'NBA: a real jump settles it',
    exp: {
      kid: 'In the NBA the two players who tied up the ball JUMP for it — the referee tosses it up between them, just like the start of the game.',
      beginner: 'The tied-up players (no substitutes for the jump) meet at the nearest circle. Win the tip to a teammate, win possession. Other levels use the alternating arrow instead.',
      intermediate: 'This makes tie-ups a skill matchup: a guard who ties up a center regrets it at the circle. Teams angle for held balls only when their jumper wins the matchup — the signal starts a mini-game.',
      expert: 'Jump-ball tactics are genuinely coached: where teammates line up on the circle, tipping to space versus to hands, violating early on purpose. And note the asymmetry with college/FIBA, where this same thumbs-up signal simply reads the arrow — identical gesture, entirely different next 10 seconds. Rulebook context is part of the decode.',
    },
  },
  {
    id: 'nba-sig-int-5', level: 'intermediate', signal: 'nba-count-basket',
    prompt: 'The down-punch is given on a made three WITH contact. What is the maximum this single possession can now yield?',
    options: ['4 points — the three counts plus one free throw', '3 points', '5 points'],
    answer: 0,
    title: 'The four-point play',
    exp: {
      kid: 'Count it: 3 points for the long shot, PLUS 1 free shot for being fouled. Make it and that\'s FOUR points in one go — the rare four-point play!',
      beginner: 'And-one math scales with the shot: fouled making a 2 = up to 3 points; fouled making a 3 = up to 4. The down-punch plus the three-confirmation arms stack together.',
      intermediate: 'Four-point plays swing games disproportionately — a 3-point lead becomes even on one whistle. Shooters exaggerate rhythm through contact precisely to buy this signal combination.',
      expert: 'Rarer still: fouled ATTEMPTING a three that misses = 3 free throws (a different signal chain: fist, three fingers, no down-punch). The complete decoding table for perimeter contact — punch+arms = 4-point ceiling; fist+3 fingers = 3 shots — separates fans who watch the ball from fans who watch the officials.',
    },
  },
  {
    id: 'nba-sig-int-6', level: 'intermediate', signal: 'nba-travel',
    prompt: 'A player ends the dribble, jumps off both feet, and lands still holding the ball. Rolling fists follow. Which principle did he break?',
    options: ['You can\'t return to the floor with the ball after leaving it', 'He took one step', 'His dribble was too high'],
    answer: 0,
    title: 'Up is a promise: the jump stop rule',
    exp: {
      kid: 'Once you jump with the ball, you\'ve promised to let it go — shoot it or pass it! Landing while still holding it is traveling.',
      beginner: 'After ending the dribble, leaving the floor commits you: release before landing. Jumping and landing with the ball (the "up and down") is a travel — a common panic move under pressure.',
      intermediate: 'Legal cousins matter: a jump STOP executed while gathering can establish a legal landing; pump-faking on the floor is fine. The violation is specifically airborne-with-ball → floor-with-ball after your dribble is dead.',
      expert: 'Defensively this is exploitable: trap a driver who has used his dribble, wall the pass lanes, and his only legal options shrink to a forced shot or a jump-pass — pressure engineered to produce this exact rolling-fists signal. Elite defenses hunt travels as designed outcomes, not luck.',
    },
  },

  // ── expert ────────────────────────────────────────────────────────────────
  {
    id: 'nba-sig-exp-1', level: 'expert', signal: 'nba-violation',
    prompt: 'Open palm up — versus the closed fist you saw earlier. This pair is the referee\'s master binary. What EXACTLY does the open palm rule out?',
    options: ['Anyone being charged with a foul or shooting free throws', 'A change of possession', 'The clock stopping'],
    answer: 0,
    title: 'Palm vs fist: the master binary',
    exp: {
      kid: 'Open hand = broken rule, ball switches teams, nobody\'s in trouble. Closed fist = someone fouled and it goes on their record. Same arm, different hand, different world!',
      beginner: 'Both stop the clock. The palm guarantees: no personal foul charged, no free throws, no team-foul count increase — just possession. The fist opens the door to all three.',
      intermediate: 'This binary drives strategy: late in games, teams WANT defensive violations (nothing) over fouls (free throws in the bonus). A defender reaching must know which hand shape his mistake will produce.',
      expert: 'The bonus makes the distinction compound: after the team-foul threshold, EVERY fist means free throws, while palms stay free forever. Endgame fouling-to-stop-the-clock strategy is a deliberate purchase of fists; the palm is the one whistle that costs the defense nothing but the ball. Hand shape = economic category.',
    },
  },
  {
    id: 'nba-sig-exp-2', level: 'expert', signal: 'nba-charge',
    prompt: 'Fist-into-palm against the dribbler — but the defender was STILL SLIDING sideways at contact. What did the referee judge to make this legal defense anyway?',
    options: ['Lateral movement is allowed if position was established first and he didn\'t move INTO the dribbler', 'Defenders may always slide', 'The dribbler jumped'],
    answer: 0,
    title: 'Legal guarding position can move',
    exp: {
      kid: 'A defender who got in front FIRST is allowed to shuffle sideways to stay in front! He just can\'t lunge forward into the crash.',
      beginner: 'Legal guarding position = both feet down, facing the opponent, established before contact. After that, the defender may move laterally or backward and STILL draw the charge.',
      intermediate: 'The forbidden vector is toward the offensive player: moving into him transfers fault (blocking). Sliding to mirror the drive maintains rights. Officials track torso direction at the instant of contact.',
      expert: 'This kills the myth "he was moving, so it\'s a block." The real test is sequencing (who established first) plus vector (into vs alongside). Elite charge-takers slide INSIDE the driver\'s path early, then absorb — winning the sequencing question before contact ever happens. The punch signal is a verdict on half a second of footwork.',
    },
  },
  {
    id: 'nba-sig-exp-3', level: 'expert', signal: 'nba-shot-clock',
    prompt: 'Shot released before the horn, ball grazes only the NET, horn sounds, offense rebounds. The shoulder-tap follows. Why is this still a violation?',
    options: ['The ball must hit the RIM to satisfy the clock — net alone doesn\'t count', 'The rebound was illegal', 'The horn is always final'],
    answer: 0,
    title: 'Rim or nothing',
    exp: {
      kid: 'Touching just the stringy net doesn\'t count — the ball has to hit the metal ring! Since it never did before time ran out, the attack loses the ball.',
      beginner: 'The shot-clock test is rim contact (or a made basket). Airballs and net-grazers don\'t reset anything: if the horn sounds before rim contact, violation — even mid-flight rebounds don\'t save it.',
      intermediate: 'Corollary: a shot that leaves the hand before the horn and THEN hits the rim is fine — play on. The two-part test (release before horn AND eventual rim contact) is why officials sometimes let the horn play out before tapping the shoulder.',
      expert: 'The delayed decision creates a strange live-ball limbo: play continues while the ball flies, and the whistle arrives retroactively when it misses iron. Defenders are taught to box out through the horn for exactly this case. The signal often comes seconds after the "expired" moment — decoding it requires replaying the flight in your head.',
    },
  },
  {
    id: 'nba-sig-exp-4', level: 'expert', signal: 'nba-three-attempt',
    prompt: 'The attempt arm goes up on a shooter whose HEEL was later shown on the line. The shot missed, fouled in the act. How many free throws does the replay-corrected ruling give?',
    options: ['Two — it was really a 2-point attempt', 'Three — the original signal stands forever', 'One'],
    answer: 0,
    title: 'The signal is evidence, not law',
    exp: {
      kid: 'The referee first thought it was a three, but the picture showed a heel ON the line — that makes it a two. So the shooter gets 2 free shots, not 3.',
      beginner: 'A foot touching the arc line = a 2-point attempt. Free throws match the attempt value, so replay correcting 3→2 also corrects the shots from 3→2.',
      intermediate: 'This is a designated reviewable matter: 2-vs-3 (made or fouled) can be checked at the next stoppage or in the last two minutes. The live signal creates the presumption; the monitor can rebut it.',
      expert: 'The philosophical point: signals are contemporaneous EVIDENCE with a correction mechanism, not immutable rulings. Contrast judgment calls (block/charge contact) which replay largely cannot re-open. Knowing which signals are appealable — line calls, clock beats, out-of-bounds — versus which are final is the deepest layer of officiating literacy.',
    },
  },
  {
    id: 'nba-sig-exp-5', level: 'expert', signal: 'nba-direction',
    prompt: 'Under a minute left. The point signals possession after a deflection — then the crew heads to the monitor and REVERSES the point. What made this reviewable?',
    options: ['Out-of-bounds calls are reviewable in the final two minutes', 'All calls are reviewable at any time', 'The coach\'s protest'],
    answer: 0,
    title: 'The two-minute review window',
    exp: {
      kid: 'At the very end of close games, referees get extra help: cameras! For touches near the lines, they can check TV and switch the point the other way.',
      beginner: 'In the last two minutes (and OT), out-of-bounds possession calls become replay-eligible. The original point stands unless the video clearly shows the other team touched last.',
      intermediate: 'Earlier in the game the same play is NOT reviewable — crews live with the naked-eye point. The rulebook concentrates review capital where possessions are worth the most.',
      expert: 'The "clear and conclusive" standard means the on-court point is sticky: inconclusive frames keep the original call, so the FIRST signal still matters enormously even in the review era. Teams know this — players sprint to sell the point in real time precisely because the tie goes to whatever was signaled.',
    },
  },
  {
    id: 'nba-sig-exp-6', level: 'expert', signal: 'nba-travel',
    prompt: 'Post player catches, holds, steps left-right-left while pivoting on… wait. The rolling fists appear. What is the referee\'s actual accounting method here?',
    options: ['Tracking the established pivot foot — it lifted and returned before a dribble', 'Counting total steps: max three', 'Timing: five seconds to move'],
    answer: 0,
    title: 'Travel is about the pivot foot, not step-counting',
    exp: {
      kid: 'When you stop with the ball, one foot gets glued down — your pivot foot. You can spin on it all day, but if it lifts and comes BACK down while you still hold the ball, that\'s traveling.',
      beginner: 'Catch with both feet down: either foot may become the pivot. The pivot may lift to shoot or pass — but must not return to the floor before release, and must not lift before a dribble starts.',
      intermediate: 'Post play is where this shows: drop steps, up-and-unders, spin moves — all legal footwork ON a fixed pivot. The rolling fists come when the anchor secretly switched or re-planted. Officials watch the feet, not the fake.',
      expert: 'Why fans miss travels (and see phantom ones): they count steps, but the rule is a state machine — pivot established → allowed transitions (lift-to-release, step-through) → illegal transitions (re-plant, switch). The gather rule adds a pre-pivot state on the move. Referee vision is trained on state transitions; that\'s the whole call.',
    },
  },
];
