// Signal Decoder — NFL bank. Referee signals only (evergreen, rule-based; verified
// against the NFL official signal chart). 6 scenarios per tier × 4 tiers. Pure data.
import type { SignalScenario } from '../signalDecoder';

export const NFL_SIGNAL_SCENARIOS: SignalScenario[] = [
  // ── kid ────────────────────────────────────────────────────────────────────
  {
    id: 'nfl-sig-kid-1', level: 'kid', signal: 'nfl-touchdown',
    prompt: 'Both arms shoot straight up. What is the referee telling everyone?',
    options: ['Touchdown!', 'The game is over', 'A player is hurt'],
    answer: 0,
    title: 'Arms up = score!',
    exp: {
      kid: 'Both arms straight up means TOUCHDOWN — someone carried or caught the ball in the end zone. Six points!',
      beginner: 'This is the score signal: a touchdown (6 points). The same raised arms also confirm a successful field goal or extra point — any time the ball legally crosses for points.',
      intermediate: 'One signal, several scores: touchdown, field goal, extra point, and a successful two-point try all get the raised arms. Context (where the ball was) tells you which one it was.',
      expert: 'On field goals, watch for TWO officials under the uprights — both must agree the kick passed inside the posts before signaling. If they cross their arms instead (the incomplete/no-good wave), the kick missed.',
    },
  },
  {
    id: 'nfl-sig-kid-2', level: 'kid', signal: 'nfl-incomplete',
    prompt: 'The referee sweeps both arms side to side in front of the body. The quarterback just threw a pass. What happened?',
    options: ['The pass hit the ground — incomplete', 'Touchdown', 'Halftime'],
    answer: 0,
    title: 'The wave-off: incomplete pass',
    exp: {
      kid: 'The criss-cross wave means the pass was NOT caught. The ball hit the ground, so the play is over — no catch.',
      beginner: 'An incomplete pass stops the clock and the ball returns to the previous spot. The down is used up: 2nd down becomes 3rd down.',
      intermediate: 'The same wave-off also means "no good" on a missed kick and "penalty declined." It is the referee\'s all-purpose NO — nothing counts.',
      expert: 'A catch requires control + two feet (or another body part) in bounds + a football move. When a replay overturns a catch, the referee ends the announcement with this exact signal — the wave is the legal ruling, not just decoration.',
    },
  },
  {
    id: 'nfl-sig-kid-3', level: 'kid', signal: 'nfl-first-down',
    prompt: 'The referee points one straight arm down the field. What is being signaled?',
    options: ['First down — the offense keeps the ball', 'The stadium exit', 'A field goal'],
    answer: 0,
    title: 'Pointing the way: first down',
    exp: {
      kid: 'The point means FIRST DOWN! The team with the ball moved far enough (10 yards), so they get a fresh set of 4 tries.',
      beginner: 'The offense gets 4 downs to gain 10 yards. Make it, and the referee points toward the defense\'s goal: a new set of downs, counted from 1st again.',
      intermediate: 'The arm always points in the direction the OFFENSE is going. After a change of possession the point flips direction — a quick way to read a turnover from far away.',
      expert: 'Listen for pairing with the clock: an awarded first down near the sideline often comes with a winding signal to restart the game clock. The chain crew resets on the point — the signal literally moves the sticks.',
    },
  },
  {
    id: 'nfl-sig-kid-4', level: 'kid', signal: 'nfl-timeout',
    prompt: 'The referee waves both arms in a big X over the head. What does it mean?',
    options: ['Timeout — stop the clock', 'Touchdown', 'The kick was good'],
    answer: 0,
    title: 'The overhead crisscross: timeout',
    exp: {
      kid: 'Arms crossing above the head means TIME OUT. Everything stops — the clock, the play, everyone takes a break.',
      beginner: 'Each team gets 3 timeouts per half. The signal stops the game clock; you\'ll see it after a team calls one, or when officials need a stoppage.',
      intermediate: 'Height is the clue: crisscross ABOVE the head = timeout; a similar sweep at SHOULDER level = incomplete pass. Two different calls that beginners often mix up.',
      expert: 'When the referee follows the crisscross by placing one hand on the cap, it\'s a REFEREE\'S timeout — an official stoppage (injury, measurement, replay) that costs neither team a charged timeout.',
    },
  },
  {
    id: 'nfl-sig-kid-5', level: 'kid', signal: 'nfl-safety',
    prompt: 'The referee presses both palms together straight above the head. This rare signal means…',
    options: ['Safety — 2 points for the defense', 'The players must shake hands', 'A field goal is coming'],
    answer: 0,
    title: 'Palms together overhead: safety',
    exp: {
      kid: 'That\'s a SAFETY — the defense trapped the ball carrier in his own end zone. The defense gets 2 points!',
      beginner: 'A safety scores 2 points for the DEFENSE — the only way the team without the ball scores on a tackle. It happens when the offense is downed in its own end zone.',
      intermediate: 'After a safety comes a double prize: 2 points AND the ball — the conceding team must free-kick from its own 20. That swing is why teams avoid running plays from their own goal line.',
      expert: 'Safeties also come from penalties enforced in the offense\'s own end zone (e.g. holding there) — no tackle required. Don\'t confuse the joined-palms signal with a touchdown\'s two separate raised arms.',
    },
  },
  {
    id: 'nfl-sig-kid-6', level: 'kid', signal: 'nfl-false-start',
    prompt: 'Before the snap, the referee rolls both fists over each other in front of the chest. What happened?',
    options: ['An offensive player moved too soon', 'A touchdown was scored', 'The ball is flat'],
    answer: 0,
    title: 'Rolling fists: false start',
    exp: {
      kid: 'The rolling fists mean FALSE START — someone on the offense jumped before the ball was snapped. Everyone goes back and tries again.',
      beginner: 'Offensive players must be totally still before the snap. Flinch early and it\'s a false start: 5 yards backward, replay the down. The whistle kills the play immediately.',
      intermediate: 'False start is a DEAD-ball foul — the play never happens. Compare offside/encroachment on the defense, where the play may continue. The rolling forearms also signal an illegal formation.',
      expert: 'Why blow it dead? Because a false start, unlike defensive offside, gives the offense an unfair jump on the pass rush — the league removes any possibility of advantage by canceling the snap outright. Watch for it on hard counts in loud stadiums.',
    },
  },

  // ── beginner ──────────────────────────────────────────────────────────────
  {
    id: 'nfl-sig-beg-1', level: 'beginner', signal: 'nfl-holding',
    prompt: 'The referee grabs one wrist with the other hand in front of the chest. What foul is this?',
    options: ['Holding', 'False start', 'Timeout'],
    answer: 0,
    title: 'Grasping the wrist: holding',
    exp: {
      kid: 'Grabbing his own wrist means HOLDING — a player grabbed and held an opponent instead of blocking him fairly.',
      beginner: 'Blockers may push with their hands but not grab, hook, or tackle a defender. Offensive holding costs 10 yards; defensive holding costs 5 and an automatic first down.',
      intermediate: 'Watch the wrist-grab\'s context: on a long run called back, holding is the usual culprit. The penalty is enforced from the spot or the line of scrimmage depending on where it happened.',
      expert: 'Don\'t confuse the STATIC wrist-grab (holding) with the ROLLING forearms (false start) — one is a live-ball foul that lets the play finish under a flag, the other kills the snap instantly. That live/dead distinction decides whether a spectacular play can stand.',
    },
  },
  {
    id: 'nfl-sig-beg-2', level: 'beginner', signal: 'nfl-offside',
    prompt: 'Hands go to the hips. Which foul does this signal?',
    options: ['Offside or encroachment', 'Holding', 'Pass interference'],
    answer: 0,
    title: 'Hands on hips: offside',
    exp: {
      kid: 'Hands on hips means a DEFENDER was on the wrong side of the ball when the play started. 5 yards for the offense.',
      beginner: 'The neutral zone is the ball\'s length between the teams. A defender in it at the snap is offside (5 yards). Touch an opponent early and it\'s encroachment — play stops at once.',
      intermediate: 'Offside can be a FREE PLAY: if the defender jumps but the snap goes off, the offense knows a 5-yard penalty is banked — quarterbacks launch deep shots with nothing to lose.',
      expert: 'Three cousins share this signal: offside (in the zone at the snap, play runs), encroachment (contact before the snap, dead ball), and neutral-zone infraction (a lunge that MAKES a blocker flinch — charged to the defense, not a false start). Reading which one happened tells you why the whistle did or didn\'t blow.',
    },
  },
  {
    id: 'nfl-sig-beg-3', level: 'beginner', signal: 'nfl-delay',
    prompt: 'The referee folds both arms across the chest. What just happened?',
    options: ['The offense let the play clock hit zero', 'A touchdown', 'The ball was fumbled'],
    answer: 0,
    title: 'Folded arms: delay of game',
    exp: {
      kid: 'Folded arms mean DELAY OF GAME — the team took too long to start the play. They lose 5 yards.',
      beginner: 'The offense has a 40-second play clock between plays. If it hits zero before the snap: delay of game, 5 yards, replay the down.',
      intermediate: 'Teams sometimes take this penalty ON PURPOSE — e.g. backing up 5 yards to give the punter more room rather than burning a timeout. A cheap penalty can be a tactical purchase.',
      expert: 'Watch the interplay with timeouts late in halves: a team out of timeouts facing a dying play clock must snap something or eat this flag — that pressure is exactly what the two-minute defense is counting on when it declines to substitute.',
    },
  },
  {
    id: 'nfl-sig-beg-4', level: 'beginner', signal: 'nfl-pass-interference',
    prompt: 'The referee pushes both open hands forward from the shoulders. Which foul is being called?',
    options: ['Pass interference', 'Safety', 'First down'],
    answer: 0,
    title: 'The push: pass interference',
    exp: {
      kid: 'The pushing motion means PASS INTERFERENCE — a player shoved or grabbed someone who was trying to catch a pass. Not allowed!',
      beginner: 'Once the ball is in the air, defenders may play the BALL but not the receiver. Grab an arm or shove early and it\'s interference — the offense gets the ball at the foul spot.',
      intermediate: 'Defensive PI is a SPOT foul in the NFL — a 45-yard bomb interfered with is a 45-yard penalty. That is why deep desperation throws are dangerous for defenses even when incomplete.',
      expert: 'It cuts both ways: OFFENSIVE pass interference (a receiver shoving off) is 10 yards backward from the previous spot, not a spot foul. And contact within one yard of the line, or when both players are "playing the ball," is legal — the judgment is about advantage, not touch.',
    },
  },
  {
    id: 'nfl-sig-beg-5', level: 'beginner', signal: 'nfl-personal-foul',
    prompt: 'One wrist strikes the other above the referee\'s head. What class of foul is this?',
    options: ['Personal foul — dangerous play, 15 yards', 'Delay of game — 5 yards', 'Incomplete pass'],
    answer: 0,
    title: 'Wrist strike overhead: personal foul',
    exp: {
      kid: 'That\'s a PERSONAL FOUL — a hit that was too rough or dangerous. The team that did it loses 15 big yards.',
      beginner: 'Personal fouls are the serious class: late hits, hits on defenseless players, roughing the passer. They cost 15 yards, and many carry an automatic first down.',
      intermediate: 'The wrist-strike is a PREFIX: the referee follows it with a second gesture naming the specific act — e.g. a throwing motion for roughing the passer, or a facemask pull. Read it as "15-yarder, details incoming."',
      expert: 'Flagrant, unnecessary contact can also bring disqualification — and two unsportsmanlike-conduct fouls eject automatically. Note the officiating logic: yardage penalties deter tactical fouls, but 15-yard personal fouls exist to deter INJURY, so they\'re enforced even after the whistle.',
    },
  },
  {
    id: 'nfl-sig-beg-6', level: 'beginner', signal: 'nfl-facemask',
    prompt: 'The referee mimes grabbing something in front of the face and pulling down. What foul is it?',
    options: ['Facemask', 'Holding', 'False start'],
    answer: 0,
    title: 'The grab-and-pull: facemask',
    exp: {
      kid: 'That\'s a FACEMASK — a player grabbed the cage on someone\'s helmet. That can hurt necks, so it\'s a big 15-yard penalty.',
      beginner: 'Grasping and twisting, turning, or pulling an opponent\'s facemask is a personal foul: 15 yards. Tacklers must aim for the body, never the helmet\'s bars.',
      intermediate: 'The referee mirrors the act — a grip at face height pulled downward. It usually appears right after the personal-foul wrist strike, which classes it as a 15-yard safety-of-players foul.',
      expert: 'The modern rule removed the old 5-yard "incidental" grade: ANY grasp-and-pull is 15. On a ball carrier, watch for it called against the DEFENSE mid-tackle; against the OFFENSE, stiff-arms to the mask draw the same flag — symmetry many fans miss.',
    },
  },

  // ── intermediate ──────────────────────────────────────────────────────────
  {
    id: 'nfl-sig-int-1', level: 'intermediate', signal: 'nfl-incomplete',
    prompt: 'A penalty flag flew earlier in the down. Now the referee gives this side-to-side wave. In THIS context, what is he most likely announcing?',
    options: ['The penalty was declined — the play stands', 'A touchdown', 'A new penalty on the defense'],
    answer: 0,
    title: 'One wave, many "no"s',
    exp: {
      kid: 'The wave can also mean "no penalty counts" — the team that was fouled liked the play better, so they said no thanks to the penalty.',
      beginner: 'Fouled teams may DECLINE penalties. If the play gained more than the penalty would, taking the result is smarter — and the referee wipes the flag away with this same wave.',
      intermediate: 'The wave-off is context-driven: after a pass, incomplete; after a kick, no good; after a flag discussion, penalty declined. Same grammar, three sentences — the game situation is the decoder.',
      expert: 'Decline decisions are real strategy: a defense offside on 3rd-and-8 that gives up a 6-yard completion faces 4th down if the offense declines… so the offense takes the 5 yards and replays 3rd-and-3 instead. Watching which option the captain picks tells you how coaches value downs vs distance.',
    },
  },
  {
    id: 'nfl-sig-int-2', level: 'intermediate', signal: 'nfl-unsportsmanlike',
    prompt: 'Both arms are held straight out to the sides, palms down — held static, no wave. Which foul is this?',
    options: ['Unsportsmanlike conduct', 'Incomplete pass', 'Safe at the base'],
    answer: 0,
    title: 'Outstretched arms, palms down: unsportsmanlike',
    exp: {
      kid: 'Arms straight out means UNSPORTSMANLIKE CONDUCT — someone was rude or taunted the other team. Football punishes bad manners: 15 yards.',
      beginner: 'This covers non-contact bad behavior: taunting, abusive language, prolonged celebrations aimed at an opponent. It costs 15 yards even though nobody was touched.',
      intermediate: 'STATIC arms = unsportsmanlike; the same arms SWEEPING = incomplete pass. Motion is the difference between a conduct foul and a routine ruling — a great example of why the pose alone isn\'t always enough; watch the movement.',
      expert: 'Two unsportsmanlike fouls on the same player = automatic ejection, and these fouls are enforced as "between downs" — tacked on after the play result, which is why a touchdown can stand but the kickoff gets moved 15 yards back.',
    },
  },
  {
    id: 'nfl-sig-int-3', level: 'intermediate', signal: 'nfl-holding',
    prompt: 'A 60-yard run just came back because of this signal against the offense. What does the offense actually lose?',
    options: ['The gain is wiped out AND 10 yards are marked off', 'Only 5 yards, run counts', 'The ball — automatic turnover'],
    answer: 0,
    title: 'Holding erases the play',
    exp: {
      kid: 'The big run doesn\'t count! HOLDING cancels the play, and the team also goes 10 yards backward. Grabbing shirts is expensive.',
      beginner: 'Accepted offensive holding = no gain + 10 yards from the previous spot + replay the down. A huge play can vanish because one blocker grabbed a jersey behind the action.',
      intermediate: 'This is why you never celebrate until you scan for flags: penalties are enforced from the previous spot on most live-ball offensive fouls, so the 60 yards were provisional the moment the flag flew.',
      expert: 'Enforcement nuance: holding BEHIND the line is marked from the previous spot; in the field of play beyond the line during a run, spot-of-foul rules can apply. And defensive holding is a different animal entirely — 5 yards plus automatic first down, which is why DBs\' grabs on 3rd-and-long are drive-extending gold for the offense.',
    },
  },
  {
    id: 'nfl-sig-int-4', level: 'intermediate', signal: 'nfl-safety',
    prompt: 'This signal was just given. What does the scoring team ALSO receive besides 2 points?',
    options: ['The ball back via a free kick', 'A timeout', 'An extra-point attempt'],
    answer: 0,
    title: 'Safety = points AND possession',
    exp: {
      kid: 'After a safety, the other team has to KICK the ball away too. So the defense gets 2 points and then gets the ball. Double win!',
      beginner: 'Post-safety, the conceding team free-kicks from its own 20-yard line. The scoring team gets 2 points plus excellent field position — the most lopsided exchange in football.',
      intermediate: 'That double reward is why intentional safeties exist as strategy: a team pinned at its own 1, leading late, may concede 2 on purpose to earn a free kick from the 20 rather than risk a blocked punt for a touchdown.',
      expert: 'Rare trivia-free corner: the free kick after a safety may be a punt (unique in the game), and a "one-point safety" technically exists on conversion attempts. The signal itself — palms joined overhead — is deliberately unlike the two-armed touchdown so a stadium can\'t misread 2 points as 6.',
    },
  },
  {
    id: 'nfl-sig-int-5', level: 'intermediate', signal: 'nfl-pass-interference',
    prompt: 'This signal is given against the DEFENSE on a deep ball at the 50. Where does the offense get the ball?',
    options: ['At the spot of the foul — the 50', 'Back 10 yards', 'Where the pass was thrown from'],
    answer: 0,
    title: 'DPI: the spot-foul hammer',
    exp: {
      kid: 'The team throwing the ball gets to move ALL the way to where the pushing happened. A long throw plus a push = a huge gain!',
      beginner: 'Defensive pass interference places the ball at the spot of the foul with an automatic first down — the defense pays for the whole route, not a flat rate.',
      intermediate: 'Compare the college rule (capped at 15 yards) to see the NFL\'s intent: pro defenders must never trade a small penalty for a sure touchdown, so the penalty equals the theft.',
      expert: 'Edge cases officials weigh: uncatchable balls (no foul), simultaneous "both playing the ball" contact (legal), and contact within one yard of the line (legal). In the end zone, DPI spots the ball at the 1 — effectively a touchdown-value flag, which is why Hail Marys are officiated so permissively.',
    },
  },
  {
    id: 'nfl-sig-int-6', level: 'intermediate', signal: 'nfl-first-down',
    prompt: 'Third-and-6. The catch is short of the sticks, but the referee gives THIS signal anyway right after a defensive-holding flag. Why?',
    options: ['The penalty carries an automatic first down', 'The receiver asked politely', 'All catches are first downs'],
    answer: 0,
    title: 'Automatic first downs ride on flags',
    exp: {
      kid: 'Some penalties give the offense a FREE first down even if they didn\'t go far enough. Grabby defense = fresh set of downs.',
      beginner: 'Defensive holding, pass interference, roughing the passer — these all award an automatic first down regardless of yardage. 3rd-and-forever can reset on a single grab.',
      intermediate: 'This is why analysts track defensive penalties per drive: a 5-yard defensive-holding call on 3rd-and-15 is worth far more than 5 yards — it converts an almost-certain punt into a fresh series.',
      expert: 'Not every defensive flag qualifies (offside is 5 yards, but the down usually repeats without an automatic first). Distinguishing "yardage + repeat down" from "yardage + automatic first" is the difference between annoyance and drive extension — the referee\'s follow-up point tells you which you got.',
    },
  },

  // ── expert ────────────────────────────────────────────────────────────────
  {
    id: 'nfl-sig-exp-1', level: 'expert', signal: 'nfl-touchdown',
    prompt: 'Fourth quarter, 4th-and-goal, the kicker swings — and the officials under the posts give THIS signal. What scored?',
    options: ['A field goal — 3 points', 'A touchdown — 6 points', 'A safety — 2 points'],
    answer: 0,
    title: 'Same arms, different points',
    exp: {
      kid: 'The arms-up signal is used for kicks too! Here the ball was KICKED through the tall posts, so it\'s 3 points, not 6.',
      beginner: 'Raised arms confirm ANY successful score by ball placement — touchdown (6), field goal (3), extra point (1), two-point try (2). The play type, not the signal, sets the number.',
      intermediate: 'On kicks the ruling belongs to the two officials stationed under each upright; the referee relays it. Inside the posts and over the crossbar = good — even if the ball passes above the top of an upright, as long as it\'s inside the inner edge.',
      expert: 'Decoding tip: signal + spot = score. Arms up from under the uprights after a snap-hold-kick = 3. Arms up in the end zone during a scrimmage play = 6. Arms up after a conversion snap = 1 or 2 depending on kick vs run/pass. One gesture, four point values — the scoreboard reader\'s classic trap.',
    },
  },
  {
    id: 'nfl-sig-exp-2', level: 'expert', signal: 'nfl-false-start',
    prompt: 'Rolling forearms, whistle, play dead instantly. Its lookalike foul — the static wrist-GRAB — lets play continue. Which pair is this?',
    options: ['False start (dead) vs holding (live)', 'Timeout vs incomplete', 'Offside vs safety'],
    answer: 0,
    title: 'Dead-ball vs live-ball: the rolling/grabbing pair',
    exp: {
      kid: 'Rolling fists = false start, and the play STOPS right away. The wrist-grab = holding, and the play keeps going until the end. Similar hands, different rules!',
      beginner: 'False start kills the snap — no play happens. Holding is flagged silently and the play runs to completion; only afterward do the teams choose penalty or play result.',
      intermediate: 'The distinction is about advantage: a false start could unfairly beat the pass rush, so it must die instantly. Holding\'s damage can be measured after the fact, so the league lets the down finish and offers a choice.',
      expert: 'This dead/live split organizes ALL football fouls: pre-snap offense = dead (false start, illegal formation via the same rolling signal); pre-snap defense = often live (offside creates free plays); during play = live with enforcement options. Learn the split and every flag becomes predictable.',
    },
  },
  {
    id: 'nfl-sig-exp-3', level: 'expert', signal: 'nfl-personal-foul',
    prompt: 'The wrist-strike prefix is followed by the referee swinging a leg. Decode the full sentence.',
    options: ['Personal foul: roughing the KICKER', 'Personal foul: facemask', 'Delay of game'],
    answer: 0,
    title: 'Signal grammar: prefix + suffix',
    exp: {
      kid: 'Referees talk in two parts! First "this was a rough play" (the wrist strike), then HOW — the leg swing means someone crashed into the kicker.',
      beginner: 'Personal-foul signals compound: wrist strike + throwing motion = roughing the passer; + leg swing = roughing the kicker; + face grab = facemask. First the class, then the specific act.',
      intermediate: 'Roughing the kicker is 15 yards + automatic first down; the lighter "running into the kicker" (5 yards) gets a different, softer treatment. The distinction is force and contact point — block the kick itself and all contact is excused.',
      expert: 'Why kickers get special protection: mid-swing they are defenseless with a planted leg — career-ending injury territory. Officiating grammar mirrors the rulebook\'s structure: family (personal foul) → species (roughing) → enforcement (15 + auto first). Once you hear signals as sentences, no announcement is needed.',
    },
  },
  {
    id: 'nfl-sig-exp-4', level: 'expert', signal: 'nfl-offside',
    prompt: 'Hands-on-hips is given, but the play was ALLOWED to finish — a 40-yard completion. The offense will obviously decline. Why did the referee let it run?',
    options: ['Offside without contact = a free play for the offense', 'The referee was too slow', 'Offside always stops play'],
    answer: 0,
    title: 'The free play, decoded',
    exp: {
      kid: 'The defense jumped early, but nobody touched anybody — so the offense got a FREE try! If something great happens, they keep it. If not, they take the penalty.',
      beginner: 'A defender offside at the snap (no contact) doesn\'t stop the play. The offense effectively plays with a safety net: worst case, accept 5 free yards; best case, keep the big gain.',
      intermediate: 'Quarterbacks are coached to spot the jump and immediately go deep or take a shot into tight coverage — an interception on a free play usually doesn\'t count, since the offense just accepts the flag instead.',
      expert: 'Contrast encroachment: the instant a defender TOUCHES a blocker pre-snap, the play is dead — no free play. So the same hands-on-hips signal follows two different timelines: silent flag + full play (offside) versus immediate whistle (encroachment). Whether you saw 6 seconds of football first IS the decode.',
    },
  },
  {
    id: 'nfl-sig-exp-5', level: 'expert', signal: 'nfl-timeout',
    prompt: 'The overhead crisscross is followed by the referee tapping a hand on his cap. What KIND of stoppage is this?',
    options: ['An official\'s timeout — charged to neither team', 'The offense\'s final timeout', 'End of the game'],
    answer: 0,
    title: 'The cap tap: referee\'s timeout',
    exp: {
      kid: 'When the referee touches his hat after the X, HE is calling the timeout — not the teams. Nobody loses one of their 3 timeouts.',
      beginner: 'Officials stop play for injuries, measurements, equipment issues, and replay reviews. The crisscross + cap touch marks it as administrative — team timeout counts are untouched.',
      intermediate: 'This matters most inside two minutes, where team timeouts are gold. An injury stoppage that costs the injured player\'s team nothing (except the player leaving for a play) is a very different resource event than a charged timeout.',
      expert: 'Clock literacy: after an official\'s timeout the game clock restarts per the prior situation (running play in-bounds = wind on ready; incomplete = on snap). Coaches game this — feigning confusion near a measurement can buy a free huddle. The cap tap tells you whether strategy or rest just happened.',
    },
  },
  {
    id: 'nfl-sig-exp-6', level: 'expert', signal: 'nfl-delay',
    prompt: 'Leading by 4 with 30 seconds left, backed up at their own 2, the offense deliberately draws THIS folded-arms flag. What are they buying?',
    options: ['5 free yards of punting room without using a timeout', 'An extra down', 'A 2-point safety'],
    answer: 0,
    title: 'Buying space with a 5-yard flag',
    exp: {
      kid: 'Sometimes a team WANTS the little penalty! Moving back 5 steps gives their kicker more room to punt without the kick being blocked.',
      beginner: 'Delay of game is only 5 yards and a replayed down. Near your own goal line, that trade can be worth it: more operating room for the punter, and the clock kept running during the delay.',
      intermediate: 'The real currency here is CLOCK + SPACE: letting the play clock die burns ~40 game seconds pre-snap while the leading team backs up for a safer punt — two wins for one cheap flag.',
      expert: 'Officiating wrinkle: inside the final two minutes, deliberate delay tactics can trigger a 10-second runoff conversation in some situations, and repeated intentional fouling invites an unsportsmanlike escalation. The folded arms look mundane — but late-game, this signal is often the visible tip of a clock-management chess move.',
    },
  },
];
