// Signal Decoder — NHL bank. Referee/linesman signals only (evergreen, rule-based;
// verified against USA Hockey Appendix 3 / NHL officiating signal charts).
// 6 scenarios per tier × 4 tiers. Pure data, zero RN imports.
import type { SignalScenario } from '../signalDecoder';

export const NHL_SIGNAL_SCENARIOS: SignalScenario[] = [
  // ── kid ────────────────────────────────────────────────────────────────────
  {
    id: 'nhl-sig-kid-1', level: 'kid', signal: 'nhl-goal',
    prompt: 'The puck crosses the line and the referee points straight into the net. What is he signaling?',
    options: ['Goal!', 'The net is broken', 'A penalty'],
    answer: 0,
    title: 'The point at the net: goal',
    exp: {
      kid: 'Pointing into the net means GOAL! The puck went all the way across the red line inside the goal. The red light spins and everyone celebrates!',
      beginner: 'A goal counts when the puck FULLY crosses the goal line between the posts. The referee\'s emphatic point confirms it — often paired with the goal judge\'s red light.',
      intermediate: 'The point matters most on scrambles: pucks under pads, bounced off skates, wedged in the crossbar. The referee\'s decision — point (goal) or the two-armed washout (no goal) — is the on-ice verdict replay must overturn.',
      expert: 'Every goal is subject to video review from the situation room, but the on-ice signal sets the presumption: "good goal called on the ice" survives inconclusive video. Kicked in, batted with a high stick, or knocked in after the whistle = washed out. The point is the anchor of hockey\'s most-reviewed decision.',
    },
  },
  {
    id: 'nhl-sig-kid-2', level: 'kid', signal: 'nhl-trip',
    prompt: 'The referee sweeps a hand low, below his own knee. A player just went flying. What\'s the call?',
    options: ['Tripping — 2 minutes in the box', 'A goal', 'The ice is slippery'],
    answer: 0,
    title: 'The low chop: tripping',
    exp: {
      kid: 'The low sweep means TRIPPING — someone used a stick or leg to knock an opponent down. The tripper sits in the penalty box for 2 minutes!',
      beginner: 'Tripping is a minor penalty: 2 minutes, and the other team plays with an extra skater (a power play). The signal mimics the stick chopping at skates.',
      intermediate: 'Key exception: if the defender clearly plays the PUCK first (a clean poke check) and the attacker falls over the follow-through, no penalty. The referee is judging what was contacted first — puck or feet.',
      expert: 'Tripping a breakaway attacker with no defender between him and the goalie escalates: penalty SHOT instead of 2 minutes (that\'s the crossed-arms-overhead signal). Same act, different geometry, dramatically different price. Where the foul happens on the ice changes which signal you\'ll see.',
    },
  },
  {
    id: 'nhl-sig-kid-3', level: 'kid', signal: 'nhl-highstick',
    prompt: 'The referee holds two fists stacked, one above the other, up near his forehead. What happened?',
    options: ['High-sticking — a stick hit someone up high', 'A great save', 'A face-off'],
    answer: 0,
    title: 'Stacked fists at the head: high-sticking',
    exp: {
      kid: 'That means HIGH-STICKING — a player\'s stick blade hit an opponent above the shoulders. Sticks must stay down! 2 minutes in the box.',
      beginner: 'Contacting an opponent above the shoulders with your stick is a minor penalty (2 minutes). The stacked fists mime holding a stick too high.',
      intermediate: 'Draw BLOOD with a high stick and it doubles to 4 minutes automatically. The referee checks the victim\'s face before choosing the 2-or-4 announcement — same signal, escalating price.',
      expert: 'Two separate rules share this signal family: high-sticking the OPPONENT (penalty) versus playing the PUCK with a stick above the shoulders (no penalty, but play is stopped/goals disallowed). Accidental follow-through on your own shot? Still a penalty — hockey holds you responsible for your blade, full stop.',
    },
  },
  {
    id: 'nhl-sig-kid-4', level: 'kid', signal: 'nhl-hold',
    prompt: 'The referee clasps one wrist with his other hand in front of his chest. Which penalty is this?',
    options: ['Holding — grabbing an opponent', 'Icing', 'Goal'],
    answer: 0,
    title: 'Clasping the wrist: holding',
    exp: {
      kid: 'Grabbing his own wrist means HOLDING — a player grabbed an opponent (or his stick) to slow him down. No grabbing allowed: 2 minutes!',
      beginner: 'Holding is impeding an opponent with hands or arms — a jersey grab, a wrap-up, pinning a stick. Minor penalty: 2 minutes, power play the other way.',
      intermediate: 'The wrist-clasp family: HOLDING (this static clasp) versus HOOKING (a two-fisted tugging motion — using the STICK to pull). Hands = holding; stick-as-tool = hooking. Two neighbors on the restraining-foul spectrum.',
      expert: 'The same clasped-wrist signal means holding in FOOTBALL too — one of the few genuinely cross-sport gestures. Restraining fouls (hold/hook/interference) are hockey\'s "obstruction" package; crackdowns on them are exactly what people mean when they say the league "opened up the game."',
    },
  },
  {
    id: 'nhl-sig-kid-5', level: 'kid', signal: 'nhl-washout',
    prompt: 'The puck sits in the crease chaos, and the referee sweeps BOTH arms out flat, palms down. What is he ruling?',
    options: ['No goal — doesn\'t count', 'Goal', 'Timeout'],
    answer: 0,
    title: 'The washout: no goal',
    exp: {
      kid: 'Arms sweeping wide means NO GOAL — the puck didn\'t fully cross the line, or something illegal happened first. Keep playing (or face off)!',
      beginner: 'The washout is hockey\'s big NO: no goal on a scramble, or a possible icing/offside waved off by the linesman. Context tells you which "no" it is.',
      intermediate: 'On goal-mouth pileups the washout usually means one of three things: puck never crossed, kicked in with a distinct kicking motion, or the net was dislodged first. The referee often follows with a miming gesture explaining which.',
      expert: 'The washout\'s power is presumption: "no goal on the ice" means replay must find conclusive evidence the puck fully crossed — camera angles into a goalie\'s pads rarely provide it. Identical pileups become goals or non-goals based mostly on which signal came first. On-ice calls are sticky.',
    },
  },
  {
    id: 'nhl-sig-kid-6', level: 'kid', signal: 'nhl-slash',
    prompt: 'The referee chops the edge of one hand down onto his other forearm. What just happened on the ice?',
    options: ['Slashing — a stick swung at an opponent', 'A broken skate', 'A line change'],
    answer: 0,
    title: 'The chop: slashing',
    exp: {
      kid: 'The chopping motion means SLASHING — a player swung his stick at an opponent like an axe. Sticks are for the puck, not people! 2 minutes.',
      beginner: 'Slashing is swinging your stick into an opponent\'s body or hands. Minor penalty (2 min); a hard slash that injures can bring a major. Breaking your stick on someone is nearly automatic.',
      intermediate: 'The modern crackdown targets hand slashes: even light chops at a puck carrier\'s gloves now draw this signal, since broken fingers were epidemic. Defenders had to relearn stick-lifts instead of stick-chops.',
      expert: 'Distinguish the stick-foul trio by referee mime: SLASH = chop to the forearm; CROSS-CHECK = two fists pushed outward (stick shaft, both hands, no ice contact); HIGH-STICK = stacked fists at the head. Three sticks misused, three distinct pictograms — the mime always re-enacts the crime.',
    },
  },

  // ── beginner ──────────────────────────────────────────────────────────────
  {
    id: 'nhl-sig-beg-1', level: 'beginner', signal: 'nhl-delayed-penalty',
    prompt: 'The referee skates with one arm raised straight up — but play continues and there\'s no whistle. What\'s going on?',
    options: ['A delayed penalty — whistle comes when the offending team touches the puck', 'He\'s waving to the crowd', 'A goal was scored'],
    answer: 0,
    title: 'The raised arm: delayed penalty',
    exp: {
      kid: 'The arm up means "I saw a penalty!" — but the referee waits to blow the whistle until the naughty team touches the puck. The other team gets to keep attacking!',
      beginner: 'Play continues while the non-offending team has the puck; the whistle comes only when the penalized team gains possession. The fouled team can\'t be punished by a stoppage of its own attack.',
      intermediate: 'Watch what the attacking team does: goalie SPRINTS to the bench for a sixth skater — risk-free, since the whistle kills play the instant the other team touches the puck. Score during the delay and (for a minor) the penalty is washed out.',
      expert: 'The 6-on-5-with-no-risk mechanic makes delayed calls mini power plays before the power play. Note the subtlety: a goal during delay cancels a MINOR but a major is still served. And "possession" means control, not a deflection — refs let play run through blocked shots. The raised arm is hockey\'s advantage rule, worn on a sleeve.',
    },
  },
  {
    id: 'nhl-sig-beg-2', level: 'beginner', signal: 'nhl-hook',
    prompt: 'Both fists tug back toward the referee\'s body, like pulling on a rope. Which penalty is being signaled?',
    options: ['Hooking — using the stick to tug an opponent', 'Tripping', 'Goal'],
    answer: 0,
    title: 'The tug: hooking',
    exp: {
      kid: 'The pulling motion means HOOKING — a player used the curved blade of his stick like a hook to slow someone down. 2 minutes in the box!',
      beginner: 'Hooking = impeding an opponent with the stick blade (typically tugging at hands or midsection from behind). Minor penalty; it\'s the classic "beaten defender panics" foul.',
      intermediate: 'Hooking vs holding vs tripping is a decision about the TOOL: stick-tug = hooking (this signal); hands/arms = holding (wrist clasp); stick-to-skates bringing them down = tripping (low chop). One chase-down foul, three possible mimes.',
      expert: 'Hooking is a speed tax: it happens when footspeed loses to footspeed. The post-2005 obstruction standard made even one-handed tugs automatic — which re-valued fast skaters league-wide. Count this signal in a game and you\'re literally counting which defensemen can\'t keep up tonight.',
    },
  },
  {
    id: 'nhl-sig-beg-3', level: 'beginner', signal: 'nhl-board',
    prompt: 'The referee pounds one fist into an open palm. A player was just smashed dangerously into the wall. The call is…',
    options: ['Boarding', 'Icing', 'A face-off'],
    answer: 0,
    title: 'Fist into palm: boarding',
    exp: {
      kid: 'The fist-pound means BOARDING — pushing or checking someone dangerously into the wall (the boards). That can really hurt, so it\'s a penalty.',
      beginner: 'Boarding is a check that sends a defenseless player violently into the boards. Severity scales: minor, major, or match penalty depending on violence and injury.',
      intermediate: 'The judgment hinges on the victim\'s position: was he DEFENSELESS (back turned, numbers showing) and was the distance to the boards dangerous? The identical hit in open ice might be perfectly legal.',
      expert: 'Cross-sport note: fist-into-palm means CHARGING in basketball — same pictogram, different crime. In hockey, boarding sits in a player-safety cluster with charging (distance/leaping) and checking-from-behind; the referee\'s choice among those signals tells you which aggravating factor he saw. The mime is the verdict\'s reasoning.',
    },
  },
  {
    id: 'nhl-sig-beg-4', level: 'beginner', signal: 'nhl-interference',
    prompt: 'Crossed arms with closed fists, held static at the chest. The player who was hit never had the puck. What\'s the call?',
    options: ['Interference — hitting a player without the puck', 'High-sticking', 'Delay of game'],
    answer: 0,
    title: 'Crossed arms: interference',
    exp: {
      kid: 'Crossed arms mean INTERFERENCE — you\'re only allowed to check the player who HAS the puck. Blocking or hitting anyone else is unfair. 2 minutes!',
      beginner: 'Only the puck carrier is fair game. Impeding anyone else — picking, blocking a path, finishing a hit long after the pass — is interference: a 2-minute minor.',
      intermediate: 'The gray zone is the JUST-released pass: hitters get a beat to finish a check on a player who moved the puck. Too late = this signal. The window is fractions of a second, judged live.',
      expert: 'Interference also covers goalie protection: contact with the goaltender in his crease routinely wipes out goals (washout + crossed arms). And watch for the pick-play version on zone entries — hockey borrowed screening from basketball, and referees police it with basketball-like positional judgment. Body position legally earned vs a path illegally blocked: that\'s the whole call.',
    },
  },
  {
    id: 'nhl-sig-beg-5', level: 'beginner', signal: 'nhl-misconduct',
    prompt: 'Both hands land on the referee\'s hips. What kind of penalty is this — and how long?',
    options: ['Misconduct — 10 minutes, but no power play', 'A 2-minute minor', 'Game over'],
    answer: 0,
    title: 'Hands on hips: misconduct',
    exp: {
      kid: 'Hands on hips means MISCONDUCT — usually for arguing or bad behavior. That player sits for 10 whole minutes, but his team doesn\'t play short-handed.',
      beginner: 'A misconduct removes the PLAYER for 10 minutes without making his team short-handed — a substitute steps in. It punishes the individual, not the team\'s manpower.',
      intermediate: 'That\'s the key difference from minors/majors: no power play results. Misconducts typically follow abuse of officials or escalating scrums — a cooling-off tool. A "game misconduct" ejects entirely.',
      expert: 'Misconducts often ride on top of other penalties (2+10 combos): the minor creates the power play, the misconduct removes the agitator. Cross-sport echo: hands-on-hips means OFFSIDE in football and BLOCKING in basketball — proof that pictograms only mean anything inside their own sport\'s dictionary.',
    },
  },
  {
    id: 'nhl-sig-beg-6', level: 'beginner', signal: 'nhl-charge',
    prompt: 'The referee rotates two clenched fists around each other in front of his chest after a violent open-ice hit. In HOCKEY this means…',
    options: ['Charging — too much distance or leaving the feet to hit', 'Traveling', 'A power play is over'],
    answer: 0,
    title: 'Rotating fists: charging (hockey edition)',
    exp: {
      kid: 'In hockey, the rolling fists mean CHARGING — a player skated a long way or jumped to smash into someone extra hard. Too much run-up! 2 minutes.',
      beginner: 'Charging punishes checks amplified by distance traveled or by leaving the ice. A legal check uses body position; a charge uses a runway.',
      intermediate: 'The referee weighs speed, strides, and elevation at contact. Compare its neighbor boarding (the fist-pound): charging is about the RUN-UP anywhere on the ice; boarding is about the dangerous WALL destination.',
      expert: 'The same rotating-fists gesture means traveling in basketball and false start in football — the most reused pictogram in sports, three sports, three meanings. Within hockey, charging vs a clean finished check is today\'s hardest line: the league permits full-speed hits but not hits WHERE speed was manufactured beyond the play\'s natural flow.',
    },
  },

  // ── intermediate ──────────────────────────────────────────────────────────
  {
    id: 'nhl-sig-int-1', level: 'intermediate', signal: 'nhl-penalty-shot',
    prompt: 'Arms crossed in a static X ABOVE the head at a stoppage. What dramatic award did the referee just make?',
    options: ['A penalty shot — one skater vs the goalie', 'A 10-minute misconduct', 'Game misconduct'],
    answer: 0,
    title: 'The overhead X: penalty shot',
    exp: {
      kid: 'Arms crossed high means PENALTY SHOT — the most exciting call in hockey! One player skates in all alone against the goalie for a free chance to score.',
      beginner: 'When a clear breakaway is illegally denied (a trip from behind, a thrown stick, covering the puck in the crease), the referee can award a solo attempt instead of a mere 2-minute penalty.',
      intermediate: 'The classic test for a foul-from-behind award: full control of the puck, beyond the defenders, no opponent between him and the goal, foul from behind denying a shot. Miss any prong and it\'s just the minor.',
      expert: 'Some triggers are automatic regardless of breakaway math — a defender (not the goalie) deliberately covering the puck in the crease, or throwing a stick at the puck carrier. Note the pictogram cousin: the same X made WAVING at chest height by a football referee means timeout; the static overhead X in hockey means theater is coming.',
    },
  },
  {
    id: 'nhl-sig-int-2', level: 'intermediate', signal: 'nhl-crosscheck',
    prompt: 'Both fists thrust forward and back at chest height, as if pushing a bar. What stick foul is this?',
    options: ['Cross-checking — checking with the stick shaft held in both hands', 'Hooking', 'Slashing'],
    answer: 0,
    title: 'The push: cross-checking',
    exp: {
      kid: 'The two-handed push means CROSS-CHECKING — using the middle of the stick like a battering ram to shove someone. That\'s not a legal check! 2 minutes.',
      beginner: 'A cross-check is a hit delivered with the stick shaft held in both hands, no part of the stick on the ice. Minor penalty, escalating to a major for violence.',
      intermediate: 'Habitat: the front of the net, where defensemen "move bodies" with shaft shoves between whistles. The crackdown standard is force + location — back and neck cross-checks draw calls that chest-level leverage battles may not.',
      expert: 'The stick-foul mime table completes here: chop-to-forearm = slashing (swing), tug-to-body = hooking (pull), two-fist push = cross-checking (shove), stacked fists high = high-sticking (elevation). Four grips, four verbs, four crimes — hockey\'s referees are mime artists with a complete grammar of stick misuse.',
    },
  },
  {
    id: 'nhl-sig-int-3', level: 'intermediate', signal: 'nhl-delayed-penalty',
    prompt: 'Arm raised (delayed call), the attacking team\'s goalie races to the bench — and the ATTACKERS accidentally shoot the puck into their own empty net. What\'s the ruling?',
    options: ['Own goal counts for the defending team — the delayed call doesn\'t protect against your own mistake', 'No goal — dead play', 'The goal is replayed'],
    answer: 0,
    title: 'The empty-net risk that isn\'t supposed to exist',
    exp: {
      kid: 'Oops! If the attacking team knocks the puck into their OWN empty net, that goal counts for the other side — pulling the goalie is only safe from the OTHER team scoring.',
      beginner: 'During a delayed penalty, the offending team can\'t score (their touch stops play) — but the puck entering the attackers\' own net off an ATTACKER still counts. The safety net has exactly one hole: you.',
      intermediate: 'Precision matters: if the penalized team shoots or deflects it in, no goal — play was dead at their touch/control. Historic own-goals during delayed calls have all come off the attacking team\'s own sticks or skates.',
      expert: 'This is a beautiful rules-lawyering edge: "the whistle blows when the offending team gains POSSESSION" — a puck they never touched that slides 180 feet into the vacated net involved no such possession. The raised arm promises a whistle conditional on THEIR touch, not yours. Reading signals precisely includes reading their conditions.',
    },
  },
  {
    id: 'nhl-sig-int-4', level: 'intermediate', signal: 'nhl-washout',
    prompt: 'A defender rifles the puck from behind his own red line all the way down; the linesman raises an arm, then this washout sweep comes as the puck is touched. Which "no" was this?',
    options: ['Icing was waved off / completed context — the washout covers icing rulings too', 'No goal', 'No penalty on the play'],
    answer: 0,
    title: 'One sweep, several negatives',
    exp: {
      kid: 'The big arm sweep is the referee\'s way of saying "NO" — here it\'s about the long shoot-away called icing. The same signal answers different questions at different moments!',
      beginner: 'Icing: shooting the puck from your own half past the other team\'s goal line untouched. It\'s a linesman\'s call — arm up for potential icing, then either a face-off comes back OR the washout waves it off (e.g. the goalie played it, or the pass was touchable).',
      intermediate: 'The washout is context-dependent by role: from a REFEREE at the net = no goal; from a LINESMAN on a long dump = no icing / no offside. Who gives it and where they\'re standing is part of the message.',
      expert: 'NHL icing nuance worth decoding: it\'s "hybrid" — the linesman judges the race to the face-off dots, not the puck touch, and a team SHORT-HANDED may ice freely (no call at all). Plus the offending team can\'t change lines after an icing. One dashed-arm sweep thus implies an entire tactical state: who\'s tired, who\'s trapped on the ice, where the face-off goes.',
    },
  },
  {
    id: 'nhl-sig-int-5', level: 'intermediate', signal: 'nhl-goal',
    prompt: 'The point-at-the-net is given, but the attacking player was standing IN the crease bumping the goalie as the puck went in. What usually happens next?',
    options: ['Review/announcement: goal disallowed for goaltender interference', 'The goal always stands', 'A penalty shot'],
    answer: 0,
    title: 'The goal that gets un-pointed',
    exp: {
      kid: 'The goalie has a special safe zone. If an attacker bumps him while the puck goes in, the "goal" gets taken back — the goalie must have a fair chance to make the save.',
      beginner: 'Goals scored while an attacker impairs the goaltender in his crease are disallowed. Coaches can challenge an on-ice goal call for goaltender interference — the review checks the contact, not the puck.',
      intermediate: 'The test: did contact (or crease presence) actually IMPAIR the goalie\'s ability to play his position? Incidental touches outside the crease, or contact initiated by the goalie, generally let the goal stand.',
      expert: 'This is hockey\'s most protested review category because it\'s judgment stacked on judgment. Decoding tip: watch the referee after review — pointing again re-confirms the goal; the washout after a huddle reverses it. A failed coach\'s challenge costs a delay-of-game minor, so the challenge itself is a wager on how the signal will flip.',
    },
  },
  {
    id: 'nhl-sig-int-6', level: 'intermediate', signal: 'nhl-trip',
    prompt: 'A defender dives, clearly pokes the PUCK away first — the attacker tumbles over the follow-through. The referee shows… no signal at all. Why is the low-chop staying holstered?',
    options: ['Puck first = legal play; contact after a clean poke is not tripping', 'The referee missed it', 'Diving is always legal'],
    answer: 0,
    title: 'The signal that correctly doesn\'t come',
    exp: {
      kid: 'The defender hit the PUCK first, fair and square! If the attacker trips over afterward, that\'s just hockey — no penalty, keep playing.',
      beginner: 'A sweep or poke that clearly contacts the puck before any contact with the opponent\'s body is a legal defensive play, even if the attacker ends up on the ice.',
      intermediate: 'Officials\' sightline decides everything: puck-first-then-legs looks identical to legs-first at full speed from the wrong angle. This is why the trailing referee, not the closest one, often makes the call.',
      expert: 'And the counter-signal exists too: an attacker who exaggerates the tumble may see the referee\'s DIVING/embellishment call — sometimes both trips AND a dive are called on the same play (matching minors). Reading non-signals is expert literacy: silence after a tumble is itself a ruling that the puck was won cleanly.',
    },
  },

  // ── expert ────────────────────────────────────────────────────────────────
  {
    id: 'nhl-sig-exp-1', level: 'expert', signal: 'nhl-highstick',
    prompt: 'Stacked fists — but the announcement is FOUR minutes, not two. What single fact doubled the penalty?',
    options: ['The high stick drew blood', 'It happened in overtime', 'The victim was a goalie'],
    answer: 0,
    title: 'The blood double',
    exp: {
      kid: 'If a high stick makes the other player bleed, the penalty automatically doubles: 4 minutes instead of 2. More harm, more time out.',
      beginner: 'High-sticking that causes injury (blood) is an automatic double minor: two back-to-back 2-minute penalties. The power play can last a full 4 minutes.',
      intermediate: 'Double-minor mechanics matter: if the opposition scores during the FIRST two minutes, only that minor ends — the second still runs. A bleeding cut can cost two goals against.',
      expert: 'Note what the rule does NOT ask: intent. Accidental follow-through, deflected sticks — blood is blood, 4 minutes (careless is the doctrine; a deliberate swing is a different, match-penalty conversation). Referees literally check the player\'s face before announcing — watching THAT inspection is how you predict a 2 or a 4 before the microphone.',
    },
  },
  {
    id: 'nhl-sig-exp-2', level: 'expert', signal: 'nhl-interference',
    prompt: 'Crossed fists again — but this time the "victim" WAS about to receive a pass that arrived a half-second later. What concept is the referee weighing?',
    options: ['Possession timing: you may only finish a check within a beat of puck release', 'Whether the pass was accurate', 'Player height'],
    answer: 0,
    title: 'The half-second between legal and interference',
    exp: {
      kid: 'You\'re allowed to bump the player with the puck — and for one tiny moment after he passes it. Hit him too long after the puck is gone, and it\'s interference.',
      beginner: 'A defender may "finish" a check on a player who has just released the puck. Beyond that grace beat, the target is a non-puck-carrier and contact is interference.',
      intermediate: 'The judgment fuses timing and knowledge: did the hitter commit before the release (legal momentum) or accelerate after it (predatory)? The same principle governs late hits on quarterbacks — every collision sport has a "too late" line.',
      expert: 'And there\'s the inverse case: a player WITHOUT the puck who initiates position (setting a pick) draws the same crossed arms in reverse. Interference is really a possession-rights doctrine: rights to hit attach to the puck and detach on release. The signal marks a property-law violation, enforced at 30 km/h.',
    },
  },
  {
    id: 'nhl-sig-exp-3', level: 'expert', signal: 'nhl-penalty-shot',
    prompt: 'The overhead X — but the foul was a defender deliberately FLOPPING on the puck in his own crease, no breakaway anywhere. Why does this still earn the X?',
    options: ['Crease puck-covering by a skater is an automatic penalty-shot trigger', 'The referee upgraded for style', 'All crease fouls are penalty shots'],
    answer: 0,
    title: 'The automatic triggers',
    exp: {
      kid: 'Only the GOALIE is allowed to lie on the puck in the crease! A regular player who smothers it there gives the other team a free breakaway shot.',
      beginner: 'Certain acts award a penalty shot automatically, no breakaway needed: a skater covering the puck in his own crease, throwing a stick at the puck, and a few others. The crease belongs to goalies.',
      intermediate: 'Logic: these acts steal a near-certain goal in ways a 2-minute minor under-punishes. The rulebook pre-priced them at "one free scoring chance" — the closest thing hockey has to a penalty kick.',
      expert: 'The full automatic list is worth knowing (deliberate displacement of the net in the final two minutes to stop a chance also qualifies at some levels). Contrast the DISCRETIONARY breakaway-foul award, which needs the four-prong control test. Two roads to the same X — one mechanical, one judged. Which road it was tells you whether the argument at the scorer\'s table is even worth having.',
    },
  },
  {
    id: 'nhl-sig-exp-4', level: 'expert', signal: 'nhl-board',
    prompt: 'Fist-into-palm plus a follow-up gesture, and the player is ejected — a MAJOR plus game misconduct. Which factor most reliably escalates boarding to this level?',
    options: ['A defenseless player injured — violence and vulnerability, not just the wall', 'The score of the game', 'The victim\'s size'],
    answer: 0,
    title: 'When the mime escalates',
    exp: {
      kid: 'If the smashed player was helpless (back turned) and got hurt, the penalty jumps from 2 minutes to ejection. Protecting players comes first.',
      beginner: 'Boarding scales: minor (2), major (5, team plays short the whole time even if scored on) and game misconduct for reckless hits injuring a defenseless opponent.',
      intermediate: 'The refs\' checklist: numbers-on-back visible? distance to boards? did the hitter have alternatives? injury on the play? Each yes climbs the ladder. The severity announcement, not the pictogram, carries the grade.',
      expert: 'League discipline layers on top: majors for boarding get automatic video review (they can be confirmed or reduced to a minor on the spot), and supplemental suspension follows separately. So this one fist-pound can fork into four institutional processes — on-ice minor, reviewed major, ejection, and a hearing. Signals are the visible tip of a legal system.',
    },
  },
  {
    id: 'nhl-sig-exp-5', level: 'expert', signal: 'nhl-hold',
    prompt: 'The wrist-clasp is announced against YOUR team, already killing a penalty. What is your situation for the next stretch of play?',
    options: ['A 5-on-3 — two skaters short until one penalty expires', 'The penalties merge into one', 'Nothing changes'],
    answer: 0,
    title: 'Stacked penalties: the 5-on-3',
    exp: {
      kid: 'Two players in the box at once means your team plays with only THREE skaters plus the goalie against five. Super hard! Hang on until one timer runs out.',
      beginner: 'Penalties run concurrently but each player serves his own: two overlapping minors = 5-on-3 for the overlap. Teams never drop below 3 skaters — additional penalties queue instead.',
      intermediate: 'A 5-on-3 converts at a huge rate, so coaches burn their timeout, ice their four best defenders in rotation, and hunt any excuse to eat clock (freezing pucks along the wall, which itself risks a delay-of-game).',
      expert: 'Queue mechanics are the deep cut: with two already serving, a THIRD penalized player waits — his time starts only when a teammate\'s ends, but he sits immediately and his team stays at 3 skaters with substitution allowed on the ice. Decoding the box math (who returns when, which goal releases whom) is genuine expert literacy that even broadcasters botch.',
    },
  },
  {
    id: 'nhl-sig-exp-6', level: 'expert', signal: 'nhl-charge',
    prompt: 'Open-ice collision, rotating fists follow. The defense argues the hit was shoulder-to-chest, puck ON the carrier\'s stick. What is the referee saying was illegal ANYWAY?',
    options: ['The run-up — distance traveled/leaving feet made a legal-looking hit a charge', 'The puck possession', 'The hit\'s location on the body'],
    answer: 0,
    title: 'Legal target, illegal delivery',
    exp: {
      kid: 'Even a "fair" bump becomes unfair if you take a giant running start or jump into it. HOW you arrive matters as much as WHERE you hit!',
      beginner: 'Charging isolates the delivery: target legal (puck carrier, body contact, no head) but the checker traveled excessive distance or left his feet to maximize impact. The energy, not the target, is the crime.',
      intermediate: 'This is why announcers say "he came from a zip code away." The modern game permits violent collisions that arise from positioning, and punishes identical collisions manufactured by runway. Officials reconstruct strides backward from the impact.',
      expert: 'Doctrinally, hockey checks are licensed force: the license covers contesting the puck, not launching projectiles. Charging, boarding, and interference form a delivery-condition triad — WHERE the victim ends (boards), WHEN rights existed (possession), HOW energy was built (runway). The rotating fists answer only the HOW question. Expert decoding means knowing which question each pictogram answers.',
    },
  },
];
