// Signal Decoder — Rugby bank. World Rugby referee signals only (evergreen, rule-based;
// verified against passport.world.rugby match-official signals — primary + secondary).
// 6 scenarios per tier × 4 tiers. Pure data, zero RN imports.
import type { SignalScenario } from '../signalDecoder';

export const RUGBY_SIGNAL_SCENARIOS: SignalScenario[] = [
  // ── kid ────────────────────────────────────────────────────────────────────
  {
    id: 'rug-sig-kid-1', level: 'kid', signal: 'rug-try',
    prompt: 'The whistle blows and the referee raises one arm straight up to the sky. What just happened?',
    options: ['A try — 5 points!', 'The game is over', 'A player is offside'],
    answer: 0,
    title: 'Arm to the sky: try!',
    exp: {
      kid: 'The straight-up arm means TRY — a player pressed the ball down on the ground over the goal line. That\'s rugby\'s big score: 5 points!',
      beginner: 'A try requires GROUNDING: downward pressure on the ball, on or over the try line. Five points, plus a conversion kick attempt worth 2 more.',
      intermediate: 'Detail in the pose: the referee faces up the field with his BACK toward the dead-ball line, arm vertical — positioned to mark where the grounding happened for the conversion\'s angle (kicks are taken in line with the grounding spot).',
      expert: 'Grounding is stricter than crossing: carrying the ball over means nothing until it touches down with pressure — held up by defenders = no try (goal-line drop-out under modern law). This is why players stretch to plant the ball and why "held up" reviews stare at daylight between ball and grass.',
    },
  },
  {
    id: 'rug-sig-kid-2', level: 'kid', signal: 'rug-knock-on',
    prompt: 'A player fumbles the ball forward off his hands. The referee raises an open hand above his head and waves it back and forth. What is he signaling?',
    options: ['A knock-on — the ball was fumbled forward', 'A try', 'Full time'],
    answer: 0,
    title: 'The overhead wave: knock-on',
    exp: {
      kid: 'The waving hand means KNOCK-ON — the ball bounced FORWARD off someone\'s hands or arms. In rugby the ball may only go backward from your hands!',
      beginner: 'Losing the ball forward (hand/arm to ground or another player) is a knock-on. Unless advantage applies, the other team gets a scrum where it happened.',
      intermediate: 'The wave mimics the ball\'s forward journey. Key nuance: forward is judged relative to the DIRECTION OF PLAY, and a ball knocked backward that bounces forward off the ground is fine — hands, not bounce, define the offence.',
      expert: 'Fine print worth knowing: a charge-down of a kick is NOT a knock-on (blocking a kick is legal even if it flies forward), and a juggled ball knocked forward then caught before it lands is play on. Distinguish this waving open hand from the try\'s still, straight arm — motion is the entire difference between celebration and a scrum.',
    },
  },
  {
    id: 'rug-sig-kid-3', level: 'kid', signal: 'rug-scrum',
    prompt: 'The referee points one arm straight out, level with his shoulder, toward one team. What restart is being awarded?',
    options: ['A scrum — that team throws the ball in', 'A penalty kick at goal', 'A try'],
    answer: 0,
    title: 'The level arm: scrum',
    exp: {
      kid: 'The flat, level arm means SCRUM — the big eight-person pushing huddle! The arm points at the team that gets to feed the ball into the tunnel.',
      beginner: 'Scrums restart play after minor errors (knock-ons, forward passes). Eight forwards from each side bind and push; the team the arm points to throws the ball in — a real advantage.',
      intermediate: 'The scrum is a contest, not a formality: a dominant pack can shove the other backward, steal the ball, or win penalties. Watching which way the arm points tells you who just gained that platform.',
      expert: 'Arm HEIGHT is rugby\'s secret code: shoulder-level horizontal = scrum; angled UP at 45° = penalty; bent square at the elbow = free kick; dropped to waist height = advantage. Four heights, four different games about to break out. This game will test you on that ladder.',
    },
  },
  {
    id: 'rug-sig-kid-4', level: 'kid', signal: 'rug-high-tackle',
    prompt: 'The referee draws a flat hand across his own neck area. What foul is he showing?',
    options: ['A high tackle — contact above the shoulders', 'The game is finished', 'A knock-on'],
    answer: 0,
    title: 'Hand across the neck: high tackle',
    exp: {
      kid: 'The hand across the neck means HIGH TACKLE — someone tackled around the head or neck. That\'s dangerous, so it\'s a penalty (and maybe a card).',
      beginner: 'Tackles must be below the line of the shoulders. Contact with the head or neck is foul play: penalty minimum, with yellow or red cards for force and recklessness.',
      intermediate: 'The referee\'s neck-swipe is a foul-play signal that usually precedes a sanction process: penalty → was there head contact? → degree of danger → mitigation (sudden dip?). You\'ll often see the TMO box signal follow it.',
      expert: 'World Rugby\'s head-contact framework made this the most consequential signal in the modern game: head contact + high force + no mitigation = red. The framework\'s decision tree is public — you can genuinely predict the card color by running the same questions the referee verbalizes on the mic.',
    },
  },
  {
    id: 'rug-sig-kid-5', level: 'kid', signal: 'rug-penalty',
    prompt: 'The referee blows a sharp whistle and raises one arm at a steep upward angle toward one team. What have they won?',
    options: ['A penalty', 'A scrum', 'A 22 drop-out'],
    answer: 0,
    title: 'The angled arm: penalty',
    exp: {
      kid: 'The arm slanting UP means PENALTY — the other team broke a big rule. The pointed-at team gets a free kick and lots of choices!',
      beginner: 'A penalty offers a menu: kick at goal (3 points), kick to touch and KEEP the throw-in, tap and run, or take a scrum. Serious offences (offside, foul play, ruck offences) earn it.',
      intermediate: 'The choice reveals strategy: down by 2 late = shot at goal; chasing a bonus point = corner lineout for a try. Reading the captain\'s decision after this signal is reading the scoreboard math in real time.',
      expert: 'Contrast the bent-arm FREE KICK: no shot at goal allowed and a kick to touch doesn\'t keep the throw. The 45°-vs-bent distinction therefore changes the point-scoring universe — the most valuable single visual discrimination a new rugby fan can learn.',
    },
  },
  {
    id: 'rug-sig-kid-6', level: 'kid', signal: 'rug-tmo',
    prompt: 'The referee draws a big rectangle in the air with both hands. What is he asking for?',
    options: ['A TV replay check (the TMO)', 'A bigger scoreboard', 'A team photo'],
    answer: 0,
    title: 'The air rectangle: TMO review',
    exp: {
      kid: 'The rectangle means "let\'s check the TV!" A special referee watching replays — the TMO — helps decide tricky things, like whether the ball was really touched down for a try.',
      beginner: 'The Television Match Official reviews tries, groundings, touch decisions in the act of scoring, and foul play. The box signal formally opens the review; the big screen shows everyone the replays.',
      intermediate: 'Referees phrase the question precisely — "try or no try?" vs "is there any reason I cannot award the try?" — and the phrasing sets the burden of proof. The second phrasing means the on-field instinct is TRY unless video disproves it.',
      expert: 'Rugby\'s referee-mic transparency makes this the best review system to LEARN from: the whole evidentiary conversation is broadcast. Note the scope: foul play can be reviewed retroactively within the game, and the same rectangle in soccer (VAR) covers a much narrower category list. Same pictogram, different constitutions.',
    },
  },

  // ── beginner ──────────────────────────────────────────────────────────────
  {
    id: 'rug-sig-beg-1', level: 'beginner', signal: 'rug-advantage',
    prompt: 'Play rumbles on after an error, and the referee holds one arm outstretched toward one team at WAIST height — no whistle. What\'s happening?',
    options: ['Advantage — the non-offending team gets a chance to profit', 'A penalty kick is being lined up', 'A try was scored'],
    answer: 0,
    title: 'The waist-high arm: advantage',
    exp: {
      kid: 'The low arm means ADVANTAGE — the other team broke a rule, but instead of stopping the fun, the referee lets the good team keep playing to see if something better happens!',
      beginner: 'After an infringement, play continues while the non-offending team can gain territory or opportunity. If nothing comes of it, the whistle brings play back for the original scrum/penalty.',
      intermediate: 'Advantage is the only primary signal WITHOUT a whistle first, and it\'s held toward the non-offending team while both possibilities stay alive. "Advantage over" (called aloud) ends the safety net; until then, teams can try risky plays for free.',
      expert: 'Two grades exist: scrum advantage (short — roughly a clean possession) and penalty advantage (long — real territorial/tactical gain required). Teams weaponize the penalty version: a drop-goal attempt or miracle pass with a guaranteed penalty behind it. Watch flyhalves peek at the referee\'s arm before choosing the audacious option.',
    },
  },
  {
    id: 'rug-sig-beg-2', level: 'beginner', signal: 'rug-free-kick',
    prompt: 'The referee raises an arm BENT square at the elbow, upper arm level with the shoulder. What lesser award is this?',
    options: ['A free kick — no shot at goal allowed', 'A full penalty', 'A conversion'],
    answer: 0,
    title: 'The bent arm: free kick',
    exp: {
      kid: 'The bent arm (like making a muscle!) means FREE KICK — a smaller prize than a penalty. You can kick or run, but you\'re NOT allowed to kick at the posts for points.',
      beginner: 'Free kicks come from technical offences (scrum early engage, lineout numbers, mark). Options: tap and run, kick, or scrum — but no goal attempt, and a kick to touch doesn\'t keep the throw.',
      intermediate: 'That last limit matters: penalty to touch = YOUR lineout; free kick to touch = the OTHER team throws in. So free kicks are usually tapped quickly or turned into attacking scrums by strong packs.',
      expert: 'The bent arm vs the straight 45° penalty arm is rugby\'s subtlest big distinction — one elbow angle separates "3 points available" from "none." Recent law experiments keep adjusting what free-kick offences exist (scrum infringements especially), but the signal split has been stable for decades: geometry outlives the lawbook.',
    },
  },
  {
    id: 'rug-sig-beg-3', level: 'beginner', signal: 'rug-forward-pass',
    prompt: 'The referee mimes a two-handed pass drifting ahead of him. Which offence is being explained?',
    options: ['A forward pass', 'A high tackle', 'Obstruction'],
    answer: 0,
    title: 'The mime: forward pass',
    exp: {
      kid: 'The pretend-pass motion means FORWARD PASS — the ball was thrown toward the other team\'s goal line. Passes must go sideways or backward! Scrum to the other team.',
      beginner: 'Throwing the ball forward (toward the opponents\' dead-ball line) is illegal. Sanction: scrum to the non-offending team where it was thrown, unless advantage runs.',
      intermediate: 'The referee\'s mime re-enacts the crime — rugby\'s secondary signals explain WHY the primary award (the scrum arm) happened. Watch the sequence: level arm (scrum) → passing mime (because: forward pass).',
      expert: 'The physics wrinkle experts argue about: "forward" is judged from the passer\'s hands relative to his running momentum — a ball released backward from a sprinting player can DRIFT forward over the grass and still be legal. Officials watch hand direction, not landing point. TMOs get this wrong less than crowds do, but only barely.',
    },
  },
  {
    id: 'rug-sig-beg-4', level: 'beginner', signal: 'rug-not-release',
    prompt: 'After a tackle, the referee mimics hugging a ball tight to his chest. Penalty! Who did what wrong?',
    options: ['The tackled player didn\'t release the ball on the ground', 'The tackler hit too high', 'The scrum-half threw forward'],
    answer: 0,
    title: 'The chest-clutch: not releasing',
    exp: {
      kid: 'The ball-hug mime means a tackled player on the ground HELD ON too long. On the floor you must let the ball go so the game keeps flowing — hogging it is a penalty.',
      beginner: 'A tackled player must release the ball (and the tackler must release the player and roll away). Holding on when opponents contest = penalty against the ball carrier.',
      intermediate: 'This is the heart of the breakdown battle: "jackal" defenders latch onto the ball the instant a tackle lands, trying to force this exact signal. Support players must arrive first to protect the ball.',
      expert: 'The referee is adjudicating a race with three clocks: tackler release, carrier release/placement, and the jackal\'s legal entry (through the gate, supporting own weight). The chest-clutch mime tells you which clock expired first. Breakdown penalties swing elite matches more than any other category — learn this mime and its siblings and you can referee the ruck from your couch.',
    },
  },
  {
    id: 'rug-sig-beg-5', level: 'beginner', signal: 'rug-try',
    prompt: 'A ball carrier crosses the line but is held up off the ground by two defenders — the arm never rises. Why is the try signal missing?',
    options: ['No grounding: the ball must be pressed down, not just carried over', 'The referee was unsighted', 'The carrier was too fast'],
    answer: 0,
    title: 'Crossing isn\'t scoring',
    exp: {
      kid: 'Being over the line isn\'t enough — the ball has to TOUCH THE GROUND with a push. The defenders held it up in the air, so no try!',
      beginner: '"Held up" means no grounding, no try. Under current law, being held up over the line results in a goal-line drop-out to the defending team — a huge defensive win.',
      intermediate: 'This makes goal-line defense a specific skill: defenders dive UNDER the ball, wedging arms between ball and grass. Attackers counter with pick-and-drives low to the turf where holding up is impossible.',
      expert: 'The law change (held-up = defending drop-out, not an attacking 5m scrum) rebalanced endgames: mauling over from close range got riskier, since a failed grounding now surrenders territory entirely. The absence of the raised arm — and what restart follows — is a live lesson in how lawmakers tune attacking incentives.',
    },
  },
  {
    id: 'rug-sig-beg-6', level: 'beginner', signal: 'rug-obstruction',
    prompt: 'The referee crosses his arms in front of his chest with a scissors motion. Penalty. What happened off the ball?',
    options: ['Obstruction — blocking a defender who was chasing the ball carrier', 'A knock-on', 'Not releasing'],
    answer: 0,
    title: 'The scissors: obstruction',
    exp: {
      kid: 'The crossed-arms scissors means OBSTRUCTION — a player without the ball got in a defender\'s way on purpose, like a bodyguard. In rugby you can\'t block for your teammate!',
      beginner: 'Unlike American football, blocking is illegal: teammates can\'t shield the ball carrier or impede chasers. Running interference = penalty to the defense.',
      intermediate: 'Most common sightings: "crossing" (a decoy runner clips the defender marking the real receiver) and blockers screening kick-chasers. Decoy runners are legal only while they could plausibly receive the ball.',
      expert: 'The gray zone is the modern power play: pre-planned "block" lines off the scrum-half, maul formation (legal organized obstruction — the one sanctioned exception, since defenders may attack the maul itself), and escort screens on kick returns. Referees judge whether the blocker CHANGED the defender\'s line. The scissors signal is rugby\'s antitrust law: no illegal shields.',
    },
  },

  // ── intermediate ──────────────────────────────────────────────────────────
  {
    id: 'rug-sig-int-1', level: 'intermediate', signal: 'rug-scrum',
    prompt: 'Level-arm scrum signal toward the attacking team after their own knock-on was played through… wait, toward the ATTACKERS? What must have preceded this?',
    options: ['The DEFENSE infringed after advantage ended or committed the more recent offence', 'Referee error', 'Attackers always feed scrums'],
    answer: 0,
    title: 'Reading who the arm favors',
    exp: {
      kid: 'The arm always points at the team that gets the ball — so if it points at the attackers, the OTHER team must have made the newer mistake!',
      beginner: 'The scrum feed goes to the non-offending team of the LAST ruled offence. Stacked errors resolve in sequence: their knock-on, then your offside = the later/graver offence usually decides.',
      intermediate: 'When both sides infringe, referees weigh order and severity — a penalty offence trumps a scrum offence, and the second offence can\'t profit from the first. The pointing arm is the conclusion of that little adjudication.',
      expert: 'Special case that fools everyone: after an unsuccessful advantage from THEIR offence, the ball comes BACK — arm toward you — even though you just had possession for 20 seconds. The signal marks legal bookkeeping, not the last thing you watched. Reading rugby means tracking the open advantage in your head like the referee does.',
    },
  },
  {
    id: 'rug-sig-int-2', level: 'intermediate', signal: 'rug-penalty',
    prompt: 'Penalty arm goes up. The captain points at the posts. What EXACTLY has he chosen, and what does it lock in?',
    options: ['A place-kick at goal for 3 — and the kick must be taken; no changing to a run', 'A scrum', 'A conversion worth 2'],
    answer: 0,
    title: 'The shot-at-goal election',
    exp: {
      kid: 'Pointing at the posts means "we\'ll kick for 3 points, please!" Once you ask for the tee, you have to kick — no tricks allowed after choosing.',
      beginner: 'Indicating a kick at goal commits the team: the kick must be attempted within the time limit (60 seconds), from the mark, with the ball on a tee or the ground.',
      intermediate: 'The commitment rule prevents gamesmanship — you can\'t summon the tee to let your forwards rest, then tap and run at a flat-footed defense. Time-wasting around the tee is itself policed.',
      expert: 'The decision matrix behind the point: distance/kicker range, wind, score state, bonus-point math, and forward dominance (a heavy pack may prefer the corner lineout + maul). Analysts grade captains on "points-per-penalty-decision" — this one gesture after the referee\'s 45° arm is the most quantifiable leadership moment in the sport.',
    },
  },
  {
    id: 'rug-sig-int-3', level: 'intermediate', signal: 'rug-knock-on',
    prompt: 'A defender lunges at an attempted intercept, the ball squirts forward off his hands. The overhead wave follows — but when is an intercept attempt NOT a knock-on?',
    options: ['When the ball is caught before touching ground or another player — a clean juggle is play on', 'Intercepts are always knock-ons', 'When the defender meant well'],
    answer: 0,
    title: 'The juggle exception',
    exp: {
      kid: 'If you bobble the ball forward but CATCH it again before it lands — no knock-on! The wave only comes when the ball escapes to the ground or another player.',
      beginner: 'A knock-on completes when the fumbled ball touches ground or another player. Recover your own juggle in the air: play continues. Fail: scrum to the opposition.',
      intermediate: 'For intercepts, referees historically judged "deliberate knock-on" harshly: slapping the ball down to kill a pass = penalty (and often a yellow if it kills a clear attack). A genuine ATTEMPT TO CATCH that fails = just the scrum.',
      expert: 'The catch-attempt test got explicit in recent law rewrites: one hand reaching to intercept with a realistic catching motion = knock-on (scrum); a cynical volleyball swat = penalty + card exposure. The referee reconstructs finger position at contact. One wave, but the SANCTION depends on a hand-shape judgment made at full speed.',
    },
  },
  {
    id: 'rug-sig-int-4', level: 'intermediate', signal: 'rug-advantage',
    prompt: 'The waist-high arm is out for a defensive knock-on inside their 22 — and the attacking fly-half immediately attempts a drop goal. Why is this the textbook moment for it?',
    options: ['A miss costs nothing — the scrum advantage is still waiting behind the attempt', 'Drop goals are worth more during advantage', 'The defense must stand still'],
    answer: 0,
    title: 'The free shot',
    exp: {
      kid: 'The referee\'s low arm is a safety net! If the drop kick misses, no problem — the attackers still get the scrum they were owed. It\'s a totally free try at 3 points.',
      beginner: 'During advantage, the pending award floors your worst case: miss the droppie, play returns for the scrum/penalty. Make it — 3 points and the advantage is consumed.',
      intermediate: 'Coaches script this: fly-halves drift into the pocket the moment the arm drops to waist height. The same logic powers "miracle plays" — cross-kicks and 30-metre floated passes attempted only under the net.',
      expert: 'Referee counter-craft: an advantage is called OVER once a "tactical opportunity" is exercised — some referees rule the drop-goal ATTEMPT itself as advantage taken (opportunity used), meaning a badly shanked kick may NOT come back. Elite 10s know each referee\'s interpretation. The waist-high arm has micro-jurisprudence attached to it.',
    },
  },
  {
    id: 'rug-sig-int-5', level: 'intermediate', signal: 'rug-high-tackle',
    prompt: 'Neck-swipe signal, then the referee crosses to the touchline and shows a YELLOW card. What does yellow mean in rugby specifically?',
    options: ['Sin bin — 10 minutes off, team plays with 14', 'A warning with no other effect', 'Ejection for the match'],
    answer: 0,
    title: 'Rugby\'s yellow: the sin bin',
    exp: {
      kid: 'In rugby a yellow card isn\'t just a warning — the player must SIT OUT for 10 minutes in the "sin bin," and his team plays a man short. Teams often get scored on during those 10 minutes!',
      beginner: 'Yellow = 10 minutes in the sin bin, team down to 14. Red = off for good. Cards punish foul play and cynical/repeated infringements (e.g. collapsing a maul near your line).',
      intermediate: 'The 10 minutes are statistically brutal: point-scoring rates jump against 14. That\'s why professional captains ask "who, and why?" — repeated team offences mean the NEXT offender goes, changing how the whole side defends.',
      expert: 'Modern layer: the 20-minute red card (in some competitions) allows a replacement after 20 minutes for non-deliberate dangerous play — and the "bunker" review lets a yellow be upgraded to red off-field while the game continues. So the touchline card ceremony you see may only be the opening bid; the TMO bunker holds the final grade.',
    },
  },
  {
    id: 'rug-sig-int-6', level: 'intermediate', signal: 'rug-forward-pass',
    prompt: 'Flat attacking line, the ball leaves the passer\'s hands aimed at a runner LEVEL with him, and the referee\'s mime stays holstered despite the crowd\'s roar. What did the officials judge?',
    options: ['Hands passed backward/flat; drift from momentum isn\'t an offence', 'The crowd was right', 'Level passes are always illegal'],
    answer: 0,
    title: 'The flat pass that\'s legal',
    exp: {
      kid: 'A pass that looks flat can still be fair! The referee watches the HANDS — if they pushed the ball sideways or backward, it\'s fine, even if the ball floats forward a bit while everyone runs.',
      beginner: 'The test is the direction of release from the hands, not where the ball lands. Sprinting players carry momentum: a backward-released ball can land ahead of where it left. Legal.',
      intermediate: 'This is why touch judges and TMOs use the passer\'s hand snap on replay, not field markings. The faster the game gets, the more legal "forward-looking" passes exist — physics scales with speed.',
      expert: 'Officially: "thrown forward" means toward the opponents\' dead-ball line RELATIVE to the passer. The momentum doctrine is settled law but eternally contested folklore — expect the mime to stay away on flat screamers unless hand direction clearly broke the plane. Understanding the non-signal here marks you as someone who watches officials, not just outcomes.',
    },
  },

  // ── expert ────────────────────────────────────────────────────────────────
  {
    id: 'rug-sig-exp-1', level: 'expert', signal: 'rug-advantage',
    prompt: 'The arm ladder exam: WAIST-height outstretched arm versus the SHOULDER-height level arm. Decode both, and what single visual property separates them?',
    options: ['Advantage (waist) vs scrum award (shoulder) — arm HEIGHT alone distinguishes them', 'Penalty vs free kick — hand shape', 'Try vs touch — motion'],
    answer: 0,
    title: 'Height is meaning',
    exp: {
      kid: 'Same arm, different height! Held LOW at the waist = "keep playing, advantage." Held FLAT at the shoulder = "stop, scrum time." The referee\'s arm is like a clock hand.',
      beginner: 'Rugby\'s primary signals form a ladder on one arm: vertical = try; 45° up = penalty; bent square = free kick; horizontal = scrum; waist-low = advantage. Learn five angles and you\'ve learned the game\'s grammar.',
      intermediate: 'Context confirms: advantage comes WITHOUT a whistle while play continues; the scrum arm follows a whistle and a stoppage. Sound + geometry together make the signals unambiguous even from the far stand.',
      expert: 'This ladder is the best-designed signal system in sport — one limb, five meanings, ordered roughly by reward magnitude. Note the pedagogy trap this game exploits: freeze-framed, waist vs shoulder is a pure angle judgment. In live play you\'d also have the whistle channel. Officials\' systems are multi-modal; pictograms test the geometric channel alone.',
    },
  },
  {
    id: 'rug-sig-exp-2', level: 'expert', signal: 'rug-free-kick',
    prompt: 'Bent-arm free kick to the defense at their own scrum, 5m from their line, clock red past 80:00. They tap… and the referee lets play run. Why hasn\'t the game simply ended?',
    options: ['The ball must go dead or an infringement occur — a free kick restart keeps the match alive', 'Games end exactly at 80:00', 'Free kicks stop the clock'],
    answer: 0,
    title: 'Rugby time: the ball decides',
    exp: {
      kid: 'Rugby doesn\'t end when the clock hits zero — it ends when the ball STOPS being in play. So the team had to take their free kick and boot the ball out to finish the game!',
      beginner: 'After 80:00, play continues until the next dead ball. Standard endgame: win any kick award, tap or set, and boot to touch — the touch kick ends the match.',
      intermediate: 'Trap in this exact scenario: a free kick to touch still gives the OTHER team a lineout — but the game ends when the ball is dead ONLY if the whistle rules it over; kicking out on the full from a free kick outside the 22… the endgame kicking decision tree is genuinely intricate.',
      expert: 'Famous endgame law: a match cannot end on an un-taken award — penalties and free kicks after the hooter must still be played, and scoring chances play out fully. Teams have won matches through multi-minute post-hooter possession chains. The bent arm at 80:03 isn\'t a formality; it\'s the doorway to the most dramatic law in rugby.',
    },
  },
  {
    id: 'rug-sig-exp-3', level: 'expert', signal: 'rug-not-release',
    prompt: 'The chest-clutch mime — but the penalty goes AGAINST the arriving defender, not the tackled player. Which sibling offence did the referee actually pair it with?',
    options: ['The jackal wasn\'t supporting his own weight / sealed off — his rights were never earned', 'Tacklers may never touch the ball', 'The mime was accidental'],
    answer: 0,
    title: 'Breakdown rights are earned, not assumed',
    exp: {
      kid: 'The defender tried to steal the ball, but he was LYING on the pile instead of standing on his own feet — so HE broke the rules, not the tackled player!',
      beginner: 'A jackal may contest the ball only if he stays on his feet, enters from behind the tackle ("through the gate"), and supports his own weight. Flopping over the ball = penalty against HIM.',
      intermediate: 'The breakdown is a rights sequence: tackler releases → carrier places → jackal (if legal) locks on → arriving cleaners may drive him off. The referee\'s decision names whichever right was violated FIRST — mimes and mic explain which.',
      expert: 'Reading elite breakdown refereeing = tracking earned rights frame by frame: a jackal beaten to position who then collapses is "off feet" even though the carrier ALSO held on — first offence wins. Referees\' pre-match briefings tell teams their tolerance ordering. The same chest-clutch mime thus flips direction based on a half-second sequencing call only the referee\'s angle can see.',
    },
  },
  {
    id: 'rug-sig-exp-4', level: 'expert', signal: 'rug-obstruction',
    prompt: 'The scissors signal against an attacking MAUL that had formed cleanly, after defenders tried to fold in and the ball-carrier detached at the back. What is the offence commonly called?',
    options: ['Obstruction — the "truck and trailer": ball carrier detached behind the shield', 'A knock-on', 'Offside at the ruck'],
    answer: 0,
    title: 'Truck and trailer',
    exp: {
      kid: 'The ball carrier can\'t hide BEHIND his teammates\' wall while walking forward — that\'s like driving a trailer behind a truck! Defenders must be able to reach him.',
      beginner: 'A maul is legal organized obstruction ONLY while the ball carrier is bound to it. If he detaches and trails behind teammates who keep shielding him, it becomes obstruction: scrum or penalty against the attack.',
      intermediate: 'Watch lineout drives: the ball transfers to the back immediately, and the front players must stay BOUND as one unit. The moment a gap opens between shield and carrier, defenders scream for exactly this scissors signal.',
      expert: 'The doctrinal point: mauling is a licensed exception to the no-blocking rule, and the license\'s condition is connectivity. Referees police "same maul or new one?" through collapse-reform cycles, swimming defenders, and pre-latched pods at kick receipt. Truck-and-trailer is where rugby\'s deepest principle (contest must remain possible) gets enforced against its most effective tactic.',
    },
  },
  {
    id: 'rug-sig-exp-5', level: 'expert', signal: 'rug-tmo',
    prompt: 'The rectangle is drawn AFTER a try was already signaled, and the referee\'s question to the TMO is: "Is there any reason I cannot award the try?" What does this phrasing legally establish?',
    options: ['The on-field decision is TRY — video must find clear evidence to overturn it', 'The TMO now decides from scratch', 'The try is already final'],
    answer: 0,
    title: 'Burden of proof, spoken aloud',
    exp: {
      kid: 'The referee already believes it\'s a try — he\'s asking the TV referee to double-check for any problem. Unless the replay clearly shows something wrong, the try counts!',
      beginner: 'Rugby reviews start from the on-field decision: "reason I cannot award" = default TRY, video must disprove; "try or no try?" = genuinely unsure, video decides openly. The question sets the standard.',
      intermediate: 'This mirrors on-ice/on-field presumptions in hockey and cricket\'s umpire\'s call: officiating systems worldwide anchor to the live decision and demand clear evidence for reversal — a deliberate defense against inconclusive replays.',
      expert: 'Why anchor at all? Because video is incomplete evidence (angles, frame rates, occlusion) and someone must own the tie-break. Rugby\'s innovation is making the anchor AUDIBLE — the mic\'d phrasing tells 80,000 people the burden of proof before the replays roll. The rectangle opens a courtroom; the question names who\'s presumed innocent.',
    },
  },
  {
    id: 'rug-sig-exp-6', level: 'expert', signal: 'rug-penalty',
    prompt: 'The 45° arm rises against a defense caught offside at a ruck for the FOURTH time in ten minutes, in the same 10m channel. Beyond the 3 points on offer, what should everyone expect next?',
    options: ['A team warning then a yellow card for repeated infringement — cynical patterns escalate', 'Nothing — penalties never escalate', 'An automatic penalty try'],
    answer: 0,
    title: 'Penalties compound: the cynical-pattern ladder',
    exp: {
      kid: 'Breaking the same rule again and again is cheating on purpose! The referee warns the captain, and the NEXT player who does it sits in the sin bin for 10 minutes.',
      beginner: 'Referees track repeated team offences: penalty → captain\'s warning → yellow card to the next offender. Deliberately killing attacks with professional fouls costs a player, not just 3 points.',
      intermediate: 'The economics referees are correcting: near the line, conceding 3 beats conceding 7, so defenses would happily trade penalties forever. Cards (and penalty tries when a foul prevents a probable try) re-price the trade.',
      expert: 'A penalty TRY (7 points, no conversion needed, plus a card) is the terminal rung — awarded when foul play prevents a try that PROBABLY would have been scored. So the full ladder reads: penalty → warning → yellow → penalty try + card. Elite defenses infringe exactly up to the warning and then stop; reading where a team sits on the ladder explains their sudden discipline. The 45° arm is one rung of a staircase.',
    },
  },
];
