// Signal Decoder — Soccer bank. Referee + assistant-referee signals only (evergreen,
// rule-based; verified against the IFAB Laws of the Game and standard AR signal guides).
// 6 scenarios per tier × 4 tiers. Pure data, zero RN imports.
import type { SignalScenario } from '../signalDecoder';

export const SOCCER_SIGNAL_SCENARIOS: SignalScenario[] = [
  // ── kid ────────────────────────────────────────────────────────────────────
  {
    id: 'soc-sig-kid-1', level: 'kid', signal: 'soc-yellow',
    prompt: 'The referee holds a YELLOW card high in the air toward a player. What does it mean?',
    options: ['A warning — behave, or you\'re off!', 'That player scored', 'Time for a substitution'],
    answer: 0,
    title: 'Yellow card: the official warning',
    exp: {
      kid: 'A yellow card is a WARNING for breaking the rules — like a reckless tackle or arguing. It says: one more and you\'re out of the game!',
      beginner: 'A caution (yellow) is booked for reckless fouls, dissent, time-wasting, shirt-off celebrations and more. Two yellows in one match = a red card = off you go.',
      intermediate: 'The card system is cumulative pressure: a cautioned defender must tackle more carefully for the rest of the match — managers often substitute booked players before a second yellow becomes inevitable.',
      expert: 'Why cards exist at all: they were invented so sanctions cross language barriers — a signal system precisely because referees and players often share no language. Yellow\'s tactical layer: accumulating cautions across matches triggers suspensions in most competitions, so a "cheap" yellow in a safe win still has a price next week.',
    },
  },
  {
    id: 'soc-sig-kid-2', level: 'kid', signal: 'soc-red',
    prompt: 'Now the referee raises a RED card. What happens to the player?',
    options: ['Sent off — out of the game, no replacement', 'He takes a penalty', 'A short break'],
    answer: 0,
    title: 'Red card: sent off',
    exp: {
      kid: 'RED means OFF! The player must leave the field for the whole game, and his team plays with one fewer player. Red is for really bad fouls.',
      beginner: 'A sending-off (red) follows serious foul play, violent conduct, denying an obvious goal chance, or a second yellow. The team plays the rest a player short — no substitute allowed.',
      intermediate: 'Playing 10 v 11 changes everything: the short team usually drops deep and defends. That\'s why late reds effectively decide matches even at 0-0 — the numerical advantage compounds every minute.',
      expert: 'Decoding detail: a straight red for denying a goal-scoring opportunity (DOGSO) depends on distance to goal, direction of play, defenders present, and control of the ball — the four-factor test. In the box, a genuine attempt to play the ball downgrades DOGSO to yellow + penalty. One card, an entire jurisprudence.',
    },
  },
  {
    id: 'soc-sig-kid-3', level: 'kid', signal: 'soc-penalty',
    prompt: 'A defender fouls inside his own big box, and the referee points firmly at a spot on the ground near the goal. The call is…',
    options: ['Penalty kick!', 'A goal kick', 'Halftime'],
    answer: 0,
    title: 'Pointing at the spot: penalty!',
    exp: {
      kid: 'The point at the little white dot means PENALTY — a free shot at goal from 12 yards, just the kicker against the goalie. Fouls in the box are expensive!',
      beginner: 'A direct-free-kick foul by defenders inside their own penalty area = penalty kick from the spot. Only the goalkeeper may defend it; everyone else waits outside the area.',
      intermediate: 'Penalties convert at roughly three in four, so the whistle-and-point is close to awarding a goal. It\'s why defenders keep arms behind their backs in the box — handball risk changes everything inside those lines.',
      expert: 'Precision points: the keeper needs one foot on (or level with) the line at the kick; encroachment matters only if it interferes; and a penalty can be retaken for violations. The referee\'s emphatic run-and-point exists to be unmistakable amid protest — this is the single most contested pointing gesture in sport.',
    },
  },
  {
    id: 'soc-sig-kid-4', level: 'kid', signal: 'soc-offside-flag',
    prompt: 'The assistant on the sideline stops running and raises the flag straight up. What is being flagged?',
    options: ['Offside', 'A goal', 'The end of the match'],
    answer: 0,
    title: 'Flag up: offside',
    exp: {
      kid: 'The raised flag means OFFSIDE — an attacker was hiding too close to the goal (past the last defender) when a teammate passed the ball. Free kick to the defense!',
      beginner: 'A player is offside if, when the ball is played FORWARD to them, they\'re nearer the goal than both the second-last defender and the ball. The flag goes up when they get involved.',
      intermediate: 'Two-step signal: flag straight up = offence spotted; after the whistle, the AR points the flag to near/middle/far side to show WHERE the offside was. Also key: it\'s judged at the moment the pass is struck, not received.',
      expert: 'Modern nuance: assistants are trained to DELAY the flag on tight scoring chances (letting VAR check the completed play) — so a late flag isn\'t a slow assistant, it\'s protocol. And "offside position" alone is legal; the offence needs involvement: touching the ball, obstructing the keeper\'s view, or gaining advantage from a rebound.',
    },
  },
  {
    id: 'soc-sig-kid-5', level: 'kid', signal: 'soc-corner',
    prompt: 'The ball rolls over the goal line, last touched by a defender. The referee points up toward the flag in the field\'s corner. What\'s awarded?',
    options: ['A corner kick for the attackers', 'A penalty', 'A throw-in'],
    answer: 0,
    title: 'Pointing at the corner: corner kick',
    exp: {
      kid: 'That point means CORNER KICK — the defending team knocked the ball over their own goal line, so the attackers get to cross it in from the corner. Great chance to score!',
      beginner: 'Ball out over the goal line, last touched by the defense (and no goal) = corner. Last touched by the attack = goal kick instead. The angled point to the arc settles which.',
      intermediate: 'Corners are set-piece currency: teams score a meaningful share of goals from them, which is why you\'ll see goalkeepers sprint forward for last-minute corners — the award converts a dead ball into a scoring lottery.',
      expert: 'Reading the paired signals: referee points to the corner arc = corner; horizontal arm toward the goal area = goal kick. On deflections neither team agrees who touched last — watch the ASSISTANT\'s flag (pointed at the arc vs extended toward the goal area); the referee usually mirrors the AR\'s read on these.',
    },
  },
  {
    id: 'soc-sig-kid-6', level: 'kid', signal: 'soc-sub-flag',
    prompt: 'The assistant holds the flag horizontally above his head with BOTH hands. What is he telling the referee?',
    options: ['A substitution is ready', 'Offside', 'A goal was scored'],
    answer: 0,
    title: 'Flag overhead in both hands: substitution',
    exp: {
      kid: 'Held flat overhead with two hands, the flag means SUBSTITUTION — a fresh player is ready to come on. The referee will stop play at the next chance.',
      beginner: 'Substitutions happen at stoppages with the referee\'s permission: the leaving player exits (at the nearest boundary in most competitions), then the new one enters at halfway. The AR\'s two-handed flag alerts the referee it\'s pending.',
      intermediate: 'The fourth official usually runs the actual swap with the number board; the AR\'s flag is the attention-getter. Teams get a limited number of subs and stoppage windows — burn them wisely.',
      expert: 'Why the distinct two-handed pose? A one-handed vertical flag = offside, an angled flag = throw-in; the substitution signal had to be unmistakably different from both since it carries no ruling about play. It\'s pure administrative semaphore — the only AR signal that never affects the ball.',
    },
  },

  // ── beginner ──────────────────────────────────────────────────────────────
  {
    id: 'soc-sig-beg-1', level: 'beginner', signal: 'soc-indirect',
    prompt: 'The referee awards a free kick and keeps one arm raised straight up — holding it there as play restarts. What kind of free kick is this?',
    options: ['Indirect — someone else must touch it before a goal counts', 'Direct — shoot away', 'A penalty'],
    answer: 0,
    title: 'The held-up arm: indirect free kick',
    exp: {
      kid: 'The raised arm means INDIRECT — you can\'t score straight from this kick! The ball must touch another player first. That\'s why the arm stays up: it\'s a reminder.',
      beginner: 'Indirect free kicks follow non-physical offences (offside, dangerous play, keeper handling a back-pass). The referee\'s arm stays raised until the ball touches a second player or goes out.',
      intermediate: 'Shoot an indirect kick straight in and the "goal" becomes a goal kick for the defense. Teams therefore build two-touch routines — one tap, then the strike — to legalize the shot.',
      expert: 'This is soccer\'s classic paired-signal exam: raised-and-HELD arm = indirect; a mere directional point (arm then lowered) = direct. The most theatrical version is the indirect kick INSIDE the box (back-pass offence): the defending wall lines up on the goal line, and the two-touch choreography plays out at point-blank range.',
    },
  },
  {
    id: 'soc-sig-beg-2', level: 'beginner', signal: 'soc-direct',
    prompt: 'After a crunching tackle, the referee blows the whistle and simply points one arm toward the attacking direction — then lowers it. What was given?',
    options: ['A direct free kick — a goal can be scored straight from it', 'An indirect free kick', 'A drop ball'],
    answer: 0,
    title: 'Point and lower: direct free kick',
    exp: {
      kid: 'The quick point means DIRECT free kick — the fouled team can shoot straight at goal from the spot of the foul. No raised arm = shoot away!',
      beginner: 'Direct free kicks follow physical/handball offences: kicks, trips, pushes, holds, handballs. The signal is just a directional point; the arm doesn\'t stay up.',
      intermediate: 'The direct/indirect split is about offence TYPE, not location: contact and handball offences = direct (and become penalties in the box); technical offences = indirect (never a penalty, even in the box).',
      expert: 'Free-kick geometry is a science: within ~25 yards of goal, a direct award spawns the wall ritual (10 yards, vanishing spray, jostling for rebounds). Decode the absence: fans often can\'t tell why a dangerous kick wasn\'t shot at goal — the answer is usually an arm you didn\'t notice staying up.',
    },
  },
  {
    id: 'soc-sig-beg-3', level: 'beginner', signal: 'soc-throwin-flag',
    prompt: 'The ball crosses the sideline and the assistant angles the flag up at 45°, pointing along the touchline. What is signaled?',
    options: ['A throw-in — for the team attacking in the pointed direction', 'Offside', 'A corner kick'],
    answer: 0,
    title: 'The angled flag: throw-in',
    exp: {
      kid: 'The tilted flag means THROW-IN — and it points the way the team who gets the ball is attacking. The other team touched it last before it went out!',
      beginner: 'Ball fully over the touchline = throw-in against whoever touched it last. The AR\'s flag angle shows direction; both hands, over the head, feet on the ground for the thrower.',
      intermediate: 'Illegal throws (lifted foot, one-handed, from the wrong spot) hand the throw to the opponents. Watch how the flag\'s direction sometimes flips after referee–AR eye contact: last-touch is genuinely hard on deflections.',
      expert: 'A rule everyone forgets, encoded in no signal: you cannot score directly from a throw-in (into the opponents\' goal = goal kick; comically, into your OWN = corner to them). And there\'s no offside from a throw-in — which is why long-throw specialists turn every deep throw into a de-facto corner.',
    },
  },
  {
    id: 'soc-sig-beg-4', level: 'beginner', signal: 'soc-advantage',
    prompt: 'A player is fouled but keeps the ball; the referee, without whistling, sweeps both arms forward and shouts "Play on!" What did he decide?',
    options: ['Advantage — the foul is noted, but stopping play would help the fouling team', 'No foul occurred', 'A penalty'],
    answer: 0,
    title: 'Arms sweeping on: advantage',
    exp: {
      kid: 'The referee saw the foul but the fouled team STILL has the ball and a good attack — so he lets them keep going. Stopping would only help the team that fouled!',
      beginner: 'Advantage: play continues if the offended team benefits more from possession than from a free kick. If the promised advantage dies within seconds, the referee whistles the original foul after all.',
      intermediate: 'The referee runs a value calculation in real time: position on pitch, attack\'s momentum, chance of the free kick being better. Near the box the free kick is often WORTH more — advantage is rarer there.',
      expert: 'Cards survive advantage: a caution-worthy foul played through gets the yellow at the next stoppage; a red-card offence too (with the nuance that the offender\'s further involvement can be curtailed). One more decode: modern law allows the signal with one OR both arms — but the both-arm sweep remains the canonical classroom image.',
    },
  },
  {
    id: 'soc-sig-beg-5', level: 'beginner', signal: 'soc-var',
    prompt: 'The referee stops, presses a finger to his earpiece, then draws a big RECTANGLE in the air. What is happening?',
    options: ['A VAR review — the video referees are checking a decision', 'A tactics board is requested', 'The match is abandoned'],
    answer: 0,
    title: 'The TV-screen rectangle: VAR',
    exp: {
      kid: 'The air-rectangle means TV CHECK! Referees watching video replays are helping to make sure a big decision — like a goal or red card — is right.',
      beginner: 'VAR only touches four match-changing categories: goals, penalties, straight red cards, and mistaken identity. The rectangle announces either an on-field review or an overturned decision.',
      intermediate: 'Protocol grammar: finger-to-ear = a check is running (play may quietly wait); the drawn rectangle = the referee is formally reviewing or announcing the outcome. Only the referee may make the TV sign — a player demanding one with the same gesture earns a yellow.',
      expert: 'The standard is "clear and obvious error" — VAR isn\'t a re-refereeing service, it\'s an error-catching net, and factual calls (offside position) are corrected outright while subjective ones go to the pitch-side monitor. Decoding tip: rectangle WITHOUT a monitor visit = factual overturn; rectangle + jog to the screen = the referee is re-judging his own call.',
    },
  },
  {
    id: 'soc-sig-beg-6', level: 'beginner', signal: 'soc-offside-flag',
    prompt: 'After the whistle, the assistant lowers the raised flag and holds it out horizontally, parallel to the ground, at mid height. What is this second position saying?',
    options: ['Where the offside happened — middle of the pitch', 'The offside is cancelled', 'A substitution'],
    answer: 0,
    title: 'The flag\'s second act: location',
    exp: {
      kid: 'After showing offside, the flag becomes a pointer! Held level in the middle means the offside player was in the MIDDLE of the field. It shows where the free kick goes.',
      beginner: 'The AR signals offside in two beats: straight up (offence), then — after the whistle — angled down / level / angled up to mark near side, middle, or far side. The kick is taken from that zone.',
      intermediate: 'This is the fastest way to read tight calls from your seat: the flag\'s final angle tells you WHICH attacker was caught, resolving those "surely the winger was on!" arguments — the flag may be for the striker in the middle.',
      expert: 'Complete AR semaphore: up = offside; angled 45° = throw-in direction; both hands overhead = sub; flag toward the goal area vs corner arc = goal kick vs corner; and a quick flag-wag then stillness = "ball out and back in, play on." Assistants speak a full flag language — the offside two-parter is just its most famous sentence.',
    },
  },

  // ── intermediate ──────────────────────────────────────────────────────────
  {
    id: 'soc-sig-int-1', level: 'intermediate', signal: 'soc-indirect',
    prompt: 'Indirect free kick — and the taker blasts it straight into the net, untouched by anyone. The referee\'s arm was up the whole time. What\'s the restart?',
    options: ['Goal kick to the defending team — the "goal" doesn\'t count', 'The goal stands', 'Retake the free kick'],
    answer: 0,
    title: 'The un-goal',
    exp: {
      kid: 'No goal! Remember the raised arm: someone ELSE had to touch the ball first. Since nobody did, the other team gets a goal kick instead. The rule really matters!',
      beginner: 'Straight in from an indirect kick = no goal, goal kick to the defense. Had it deflected off ANY player (either team) on the way, it would count.',
      intermediate: 'The arm coming DOWN is your live indicator: watch the referee during the kick — the moment a second player touches the ball, the arm drops and a subsequent goal is good.',
      expert: 'Mirror case for completeness: an indirect kick straight into your OWN goal = corner to the opponents (the ball technically can\'t score unassisted in either direction). These restart tables — who touched, which line, which restart — are the deep grammar the raised arm compresses into one held pose.',
    },
  },
  {
    id: 'soc-sig-int-2', level: 'intermediate', signal: 'soc-advantage',
    prompt: 'Advantage is signaled after a nasty, yellow-worthy foul. The attack fizzles three seconds later with a harmless backpass. What does the referee do now?',
    options: ['Whistle, give the original free kick, and book the fouler', 'Nothing — advantage waived everything', 'Award a penalty'],
    answer: 0,
    title: 'Advantage has a return policy',
    exp: {
      kid: 'The referee gave the attackers a chance, but it went nowhere — so he rewinds! Free kick where the foul happened, AND the fouler still gets his yellow card.',
      beginner: 'If the anticipated advantage doesn\'t develop within a few seconds, the referee brings play back for the original offence. The card, when deserved, is shown either now or at the next stoppage.',
      intermediate: 'The "few seconds" window is real refereeing craft: too quick a whistle wastes real advantages; too slow and the foul becomes unenforceable (you can\'t rewind after a full new phase of play). Watch top referees hold the sweep with the whistle already at their lips.',
      expert: 'One critical asymmetry: if the advantage DOES develop, the free kick is gone forever, but misconduct is not — the yellow comes at the stoppage, and a DOGSO red played under advantage that ends in a goal downgrades to yellow (the denial evaporated). Advantage trades the restart, never the discipline.',
    },
  },
  {
    id: 'soc-sig-int-3', level: 'intermediate', signal: 'soc-penalty',
    prompt: 'The point-to-the-spot is given for a handball — but the defender\'s arm was tight against his chest when the ball struck it. Modern law says the referee judged what?',
    options: ['This shouldn\'t be a penalty — handball needs an arm making the body bigger or deliberate movement', 'Any ball-to-arm contact is a penalty', 'Handballs are judged by pain'],
    answer: 0,
    title: 'Handball: position, not just contact',
    exp: {
      kid: 'Ball touching an arm isn\'t automatically a foul! It matters WHERE the arm was — stuck out wide (unfair blocking) or held in close to the body (just part of standing).',
      beginner: 'Handball requires the arm to make the body "unnaturally bigger," to move toward the ball, or a deliberate play. An arm pinned to the chest is a natural position — normally no offence.',
      intermediate: 'The judgment axis is silhouette: outstretched or raised arms extend your blocking area and get punished regardless of intent; arms in a natural running/falling shape don\'t. That\'s why box defenders adopt the "arms behind back" insurance posture.',
      expert: 'The law has oscillated for years (accidental handball before a goal, arm-above-shoulder presumptions), which is exactly why VAR reviews cluster on this call. Decode the sequence: point-to-spot → rectangle → monitor jog = the referee is re-checking silhouette, proximity (no time to react?), and whether the arm moved to ball or ball to arm.',
    },
  },
  {
    id: 'soc-sig-int-4', level: 'intermediate', signal: 'soc-red',
    prompt: 'A midfielder already on a yellow dives to win a free kick. The referee shows yellow… then immediately red. Explain the two-card sequence.',
    options: ['Second caution = automatic red; the sequence shows the red is for accumulation, not one act', 'The referee changed his mind', 'Diving is always a straight red'],
    answer: 0,
    title: 'Yellow + yellow = red, shown in order',
    exp: {
      kid: 'Two warnings in one game means you\'re off! The referee shows the second yellow first, THEN the red, so everyone knows the sending-off is because of TWO yellows.',
      beginner: 'Simulation (diving) is a caution. A player\'s second caution triggers a mandatory sending-off, always displayed as yellow-then-red so the record shows accumulation, not violent conduct.',
      intermediate: 'The distinction matters beyond the day: a two-yellow red usually carries a lighter suspension than a straight red for serious foul play. The card choreography IS the paper trail.',
      expert: 'Referee craft: managing a match means knowing who\'s "on a yellow" — players bait booked opponents into second-yellow situations, and referees consciously raise the bar for a second caution to avoid deciding matches on trifles. The two-card flourish looks bureaucratic; it\'s actually the visible tip of game-management strategy on both sides.',
    },
  },
  {
    id: 'soc-sig-int-5', level: 'intermediate', signal: 'soc-corner',
    prompt: 'Attacker shoots, the keeper tips it over the bar brilliantly. The referee points to the corner arc. Why a corner when the DEFENSE saved it?',
    options: ['The keeper\'s touch counts as the defense playing it out over the goal line', 'Saves are penalized', 'It should be a goal kick'],
    answer: 0,
    title: 'The save that concedes a corner',
    exp: {
      kid: 'The goalie touched the ball last before it flew over the goal! Any defender\'s touch — even a great save — means corner kick for the attackers.',
      beginner: 'The rule is purely about last touch and which line: over the goal line, last touched by defense (keeper included) = corner. The quality or intent of the touch is irrelevant.',
      intermediate: 'This creates the goalkeeper\'s dilemma on shots drifting near the frame: tip it over (concede a dangerous corner) or trust it\'s going wide (risk a goal). Elite keepers make that read in a tenth of a second.',
      expert: 'Deflection chains complicate the read: shot → defender\'s shin → keeper\'s glove → over. Still a corner (all defensive touches). Attacker\'s toe last = goal kick. The referee is doing touch-forensics at full speed, often deferring to the AR\'s flag or, in elite matches, goal-line-adjacent camera checks for the near-impossible calls.',
    },
  },
  {
    id: 'soc-sig-int-6', level: 'intermediate', signal: 'soc-offside-flag',
    prompt: 'A striker in an offside position doesn\'t touch the through-ball — but stands in front of the keeper\'s face as it rolls in. Flag goes up. What made him "involved"?',
    options: ['Obstructing the keeper\'s line of vision — interference without touching', 'Being in the box at all', 'His teammate\'s intent'],
    answer: 0,
    title: 'Offside without touching the ball',
    exp: {
      kid: 'You can be offside without even touching the ball! Standing where the goalie can\'t see past you counts as joining the play — and he was standing in the wrong place.',
      beginner: 'Offside needs position AND involvement. Involvement includes: playing the ball, blocking an opponent\'s line of vision, challenging for the ball, or gaining advantage from a rebound.',
      intermediate: 'This is the "phantom offside" that confuses stadiums: the goal-scorer was onside, but a teammate lurking offside in the keeper\'s eyeline poisons the goal. The flag is for the lurker, not the scorer.',
      expert: 'The line-of-vision test is deliberately narrow: the attacker must be in the keeper\'s sightline to the BALL and clearly impact his ability to play it — merely standing offside in the box is legal. VAR reviews of disallowed goals now hinge on frame-by-frame sightline reconstruction. When a whole crowd asks "offside on WHO?", you now know the answer.',
    },
  },

  // ── expert ────────────────────────────────────────────────────────────────
  {
    id: 'soc-sig-exp-1', level: 'expert', signal: 'soc-direct',
    prompt: 'Direct vs indirect is the classic signal pair. A keeper picks up a deliberate back-pass from his defender\'s FOOT. Which free kick — and thus which signal — follows?',
    options: ['Indirect (arm held up), inside the box, where he handled it', 'Direct — penalty kick', 'No offence at all'],
    answer: 0,
    title: 'The back-pass: technical, therefore indirect',
    exp: {
      kid: 'Goalies can\'t pick up a pass a teammate kicked to them on purpose! But it\'s the "polite" kind of foul — an indirect free kick, so the arm goes up and two touches are needed.',
      beginner: 'Keeper handling a deliberate foot-pass from a teammate is a TECHNICAL offence: always an indirect free kick (never a penalty), taken where the handling happened — even deep inside the six-yard box.',
      intermediate: 'This is why the direct/indirect distinction exists: physical offences threaten opponents (direct/penalty); technical ones only break procedure (indirect). Header or chest back to the keeper: perfectly legal to catch.',
      expert: 'The full test: deliberate KICK (not a miskick or deflection), by a TEAMMATE, handled by the keeper in his own area. Circumventions count too — the flick-up-and-head trick is booked as unsporting. And the resulting box-indirect produces soccer\'s strangest set piece: eleven defenders lawfully packed on their own goal line against a two-touch missile.',
    },
  },
  {
    id: 'soc-sig-exp-2', level: 'expert', signal: 'soc-var',
    prompt: 'The rectangle is drawn, the referee jogs to the monitor, watches, returns — and reverses his penalty call to a corner. What standard did the video evidence have to meet?',
    options: ['Clear and obvious error in the on-field decision', 'Any doubt at all', 'A 50/50 balance of probability'],
    answer: 0,
    title: 'The bar for the overturn',
    exp: {
      kid: 'The TV check doesn\'t redo every decision — it only fixes CLEAR mistakes. The replay must basically shout "that was wrong!" before the referee changes his call.',
      beginner: 'VAR\'s threshold is "clear and obvious error" (or a serious missed incident). Marginal, debatable calls stay with the on-field decision — the referee\'s original ruling has weight.',
      intermediate: 'That\'s why identical-looking penalties get opposite outcomes: one was CALLED on-field and survives review (not clearly wrong); the other wasn\'t called and isn\'t clearly right either. The initial signal sets the default.',
      expert: 'Structural insight: the monitor visit is reserved for SUBJECTIVE reversals (the referee must own the new judgment); factual matters — offside geometry, ball out of play, wrong player identified — are corrected without a review, no rectangle jog needed. Decode the two workflows and every VAR delay becomes legible: monitor = judgment; no monitor = math.',
    },
  },
  {
    id: 'soc-sig-exp-3', level: 'expert', signal: 'soc-advantage',
    prompt: 'DOGSO scenario: last defender trips a striker who somehow stays up — advantage sweep — and the striker SCORES three seconds later. What card does the defender get now?',
    options: ['Yellow — the goal repaired the denied opportunity', 'Red — DOGSO is always red', 'No card'],
    answer: 0,
    title: 'The goal that saves the defender',
    exp: {
      kid: 'The trip tried to steal a goal chance — but the striker scored anyway! Since nothing was actually stolen, the defender gets a warning instead of being sent off.',
      beginner: 'Denying an obvious goal-scoring opportunity is a red — but if advantage is played and the goal is scored, the "denial" no longer exists: law downgrades it to a caution for unsporting behaviour.',
      intermediate: 'The logic is restorative: cards protect opportunities. Opportunity restored (goal!) → punish the attempt (yellow), not the outcome. If the advantage had fizzled, back comes the free kick AND the full red.',
      expert: 'This is the most elegant interaction in the Laws: advantage, DOGSO, and misconduct downgrade all triggered by one sweep of the arms. Note the same downgrade logic in the box: genuine ball-playing attempt + penalty awarded = yellow not red (the penalty restores the chance). The Laws consistently price sanctions against what was actually lost.',
    },
  },
  {
    id: 'soc-sig-exp-4', level: 'expert', signal: 'soc-offside-flag',
    prompt: 'The flag stays DOWN as a striker races through and finishes; only after the ball hits the net does it rise. Furious defenders surround the assistant. Explain the delayed flag.',
    options: ['VAR-era protocol: on tight scoring chances, let play finish so the review can rescue a wrong flag', 'The assistant fell asleep', 'Flags may only rise after goals'],
    answer: 0,
    title: 'The deliberate late flag',
    exp: {
      kid: 'The assistant waited ON PURPOSE! If he flags too early and he\'s wrong, the goal is lost forever. By waiting, the TV check can still fix everything either way.',
      beginner: 'Instruction to ARs: on close offsides leading directly to a scoring chance, keep the flag down, let the attack conclude, THEN flag. VAR can cancel a wrong goal — but can\'t resurrect an attack killed by a wrong early flag.',
      intermediate: 'The asymmetry drives the protocol: a wrong "onside" is fully correctable (disallow the goal); a wrong "offside" whistle is irreversible. So doubt = delay. Defenders must play to the whistle even when certain.',
      expert: 'Consequences ripple: defenders can no longer stop on a raised arm (there isn\'t one), collision risk shifts, and semi-automated offside tech now often replaces the judgment entirely at top level. The late flag is the perfect case study of how review systems reshape live signals — the gesture\'s TIMING became part of its meaning.',
    },
  },
  {
    id: 'soc-sig-exp-5', level: 'expert', signal: 'soc-yellow',
    prompt: 'The referee shows yellow to the TEAM CAPTAIN while pointing at the whole protesting group. Under modern dissent protocols, what is this booking managing?',
    options: ['Mass confrontation — the captain answers for collective dissent', 'The captain\'s tackle', 'The crowd\'s behavior'],
    answer: 0,
    title: 'The captain-accountability yellow',
    exp: {
      kid: 'When lots of players surround the referee shouting, the CAPTAIN can get the warning card for the whole group. He\'s the boss — so he\'s responsible for his teammates\' manners!',
      beginner: 'Modern protocols route dissent through captains: only the captain may approach the referee on major decisions, and mobbing officials draws cautions — with the captain as the accountable card-bearer.',
      intermediate: 'The design goal is de-escalation economics: one predictable yellow beats five heat-of-the-moment ones. Captains now physically herd teammates away — an on-pitch compliance role created by a card policy.',
      expert: 'Signal-reading level: a yellow shown AWAY from any tackle, with the referee\'s other arm sweeping the crowd of players back, is a conduct-management card — it will appear in the book as dissent, and it resets the tolerance threshold for the rest of the match. Referees spend cards to buy control; that\'s match management, visible in card choreography.',
    },
  },
  {
    id: 'soc-sig-exp-6', level: 'expert', signal: 'soc-penalty',
    prompt: 'Penalty pointed. The kicker stutter-steps, stops completely at the end of his run, then scores. The referee orders a RETAKE and books him. Which law bit?',
    options: ['Feinting after completing the run-up is illegal — stopping at the end to fool the keeper', 'Stuttering is always illegal', 'He kicked too hard'],
    answer: 0,
    title: 'Feinting: allowed in the run, not at the end',
    exp: {
      kid: 'Trick steps DURING the run-up are okay — but you can\'t fully stop right at the end to trick the goalie into diving first. That\'s too sneaky! Kick again (and a warning).',
      beginner: 'Law: feinting in the run-up is permitted; feinting to kick once the run-up is COMPLETED is an offence — caution, and the kick is retaken only per the outcome table (scored = retake; missed = indirect FK out).',
      intermediate: 'The line is the final planting step: hesitation rhythm upstream = art; a full stop at the ball = illegal. Keepers, meanwhile, must keep part of one foot on/level with the line — both sides have choreography laws.',
      expert: 'The outcome matrix is the expert layer: illegal feint + goal = retake + yellow; illegal feint + miss = indirect free kick to defense + yellow; keeper off the line early + save = retake (+ warning/caution regime); both offend = context decides. Every penalty is a tiny procedural courtroom, and the point-to-the-spot is just its opening gavel.',
    },
  },
];
