import { Sport } from './api';

// Academy content banks — used by the Academy tab's "Did You Know" card and
// "Quick Quiz". English-only for v1 (no translation layer yet); flag for native
// localization before launch alongside the tennis/golf/cricket FAQ sets.

const FACTS: Record<Sport, string[]> = {
  mlb: [
    "A baseball has exactly 108 stitches — always hand-sewn.",
    "The fastest pitch ever recorded in MLB was 105.1 mph by Aroldis Chapman in 2010.",
    "Baseball is the only major sport where the defense controls the ball.",
    "An MLB baseball only lasts about 6 pitches before being replaced.",
    "Babe Ruth hit 714 home runs — a record that stood for 39 years until Hank Aaron broke it in 1974.",
    "The seventh-inning stretch tradition dates back to 1910 when President Taft stood up to leave and everyone stood out of respect.",
    "A regulation MLB game uses approximately 70 baseballs."
  ],
  nfl: [
    "An NFL game lasts about 3 hours but the ball is actually in play for only about 11 minutes.",
    "The Super Bowl is the most watched TV event in American history — over 100 million viewers annually.",
    "An NFL football is made from cowhide leather — four panels stitched together with a rubber bladder inside.",
    "The forward pass was not legal in American football until 1906.",
    "Jerry Rice holds the NFL record for career receiving touchdowns with 197.",
    "The NFL uses approximately 780,000 footballs per season.",
    "A standard NFL field is 100 yards long with two 10-yard end zones."
  ],
  nba: [
    "An NBA basketball hoop is exactly 10 feet high — a standard that has never changed since 1891.",
    "Wilt Chamberlain scored 100 points in a single NBA game on March 2, 1962.",
    "The three-point line was added to the NBA in 1979.",
    "Michael Jordan was cut from his high school basketball team as a sophomore.",
    "The NBA shot clock (24 seconds) was introduced in 1954 to speed up the game.",
    "LeBron James has played over 50,000 minutes in the NBA.",
    "A regulation NBA basketball must be inflated to between 7.5 and 8.5 pounds per square inch."
  ],
  nhl: [
    "The Stanley Cup is the oldest professional sports trophy in North America, first awarded in 1893.",
    "NHL players skate approximately 3-5 miles per game.",
    "The fastest hockey shot ever recorded was 108.8 mph by Zdeno Chara.",
    "A hockey puck is frozen before games to reduce bouncing on the ice.",
    "Wayne Gretzky scored more career assists (1,963) than any other player scored total points.",
    "NHL referees skate approximately 4-5 miles per game.",
    "The goalie mask was not widely used until 1959."
  ],
  soccer: [
    "Soccer is played by over 250 million players in more than 200 countries.",
    "The fastest goal ever scored in professional soccer was after 2.8 seconds.",
    "A soccer player runs approximately 7 miles per game.",
    "The FIFA World Cup final is the most watched single sporting event on Earth.",
    "Brazil is the only country to have played in every FIFA World Cup.",
    "The first World Cup was held in Uruguay in 1930.",
    "A regulation soccer ball has 32 panels — 20 hexagons and 12 pentagons."
  ],
  worldcup: [
    "The FIFA World Cup trophy weighs 6.175 kg and is made of 18-carat gold.",
    "Brazil has won the most World Cups — 5 times.",
    "The 1950 World Cup final was watched by 199,954 fans.",
    "Miroslav Klose holds the record for most World Cup goals — 16 for Germany.",
    "Only 8 countries have ever won the World Cup.",
    "VAR was first used at the 2018 World Cup in Russia.",
    "The 2026 World Cup is hosted by USA, Canada, and Mexico."
  ],
  rugby: [
    "Rugby was invented in 1823 when William Webb Ellis picked up a soccer ball and ran with it.",
    "The Rugby World Cup trophy is named the Webb Ellis Cup.",
    "A rugby player runs approximately 4-7 km per game.",
    "New Zealand's All Blacks have the best win percentage of any national team in any sport.",
    "The haka performed by the All Blacks is a traditional Maori war dance.",
    "A rugby ball is oval-shaped to make it easier to carry while running.",
    "The 2023 Rugby World Cup was watched by over 2 billion people worldwide."
  ],
  mlr: [
    "Major League Rugby was founded in 2018 — one of the newest professional leagues in the USA.",
    "MLR is the first Division 1 professional rugby union league in the United States.",
    "MLR teams play a 14-game regular season from February to June.",
    "Rugby union has 15 players per side — rugby league has 13.",
    "MLR has helped grow rugby participation in the USA by over 20% since its founding.",
    "The USA Rugby team is nicknamed the Eagles.",
    "The Chicago Hounds play at SeatGeek Stadium in Bridgeview, Illinois."
  ],
  wnba: [
    "The WNBA was founded in 1996 and played its first season in 1997.",
    "A WNBA basketball is slightly smaller than an NBA ball — 28.5 inches vs 29.5 inches.",
    "The WNBA season runs from May to October.",
    "Breanna Stewart is the only player to win MVP in NCAA, WNBA regular season, and WNBA Finals.",
    "The WNBA has 12 teams across the United States.",
    "Diana Taurasi holds the WNBA record for career points — over 10,000.",
    "WNBA quarters are 10 minutes long — shorter than NBA quarters."
  ],
  epl: [
    "The Premier League is the most-watched sports league in the world — broadcast in 212 territories.",
    "Manchester United has won the most Premier League titles — 13.",
    "The Premier League was founded in 1992.",
    "A Premier League season has 380 matches total.",
    "The fastest Premier League goal was scored after 7.69 seconds by Shane Long in 2019.",
    "Liverpool's Anfield stadium has hosted football since 1884.",
    "Premier League clubs earn over 3 billion pounds per season from TV rights."
  ],
  laliga: [
    "Real Madrid and Barcelona have won over 60 La Liga titles between them.",
    "Real Madrid is the most successful club in UEFA Champions League history with 14 titles.",
    "La Liga was founded in 1929.",
    "Lionel Messi scored 50 La Liga goals in the 2011-12 season — a record.",
    "El Clasico between Real Madrid and Barcelona is the most watched club football match.",
    "La Liga has 20 teams — the bottom 3 are relegated each season.",
    "Spain won three consecutive international tournaments from 2008 to 2012."
  ],
  tennis: [
    "The word love in tennis means zero — from the French l'oeuf meaning egg.",
    "A tennis ball is only in play for about 20 minutes of a 5-set match.",
    "Wimbledon uses approximately 54,000 tennis balls every tournament.",
    "The fastest serve ever recorded was 263 km/h by Sam Groth in 2012.",
    "Tennis was originally called lawn tennis.",
    "Rafael Nadal has won the French Open more times than any other player.",
    "A standard tennis court is 78 feet long and 36 feet wide for doubles."
  ],
  golf: [
    "The term birdie comes from American slang — bird meant something excellent.",
    "Golf is one of only two sports played on the Moon — Alan Shepard hit a ball there in 1971.",
    "The dimples on a golf ball (usually 336) help it travel up to twice as far as a smooth ball.",
    "Augusta National was built on a former plant nursery — hence all the flowers.",
    "The odds of a hole-in-one for an average golfer are about 1 in 12,500.",
    "Golf courses have 18 holes because 18 shots would consume one bottle of whisky.",
    "Tiger Woods has won 15 major championships."
  ],
  cricket: [
    "A cricket match can last up to 5 days and still end in a draw.",
    "The Ashes is named after a tiny urn containing burned cricket bails.",
    "Sachin Tendulkar scored 100 international centuries.",
    "Cricket was the first sport to use Hawk-Eye ball tracking technology.",
    "The longest cricket match lasted 14 days — abandoned so England could catch their boat home.",
    "A cricket ball is harder than a baseball and can travel over 90 mph.",
    "The IPL has over 400 million viewers — one of the most watched leagues in the world."
  ],
};

export default FACTS;

export type QuizQuestion = {
  q: string;
  options: string[];
  answer: number; // 0-based index of correct answer
  explanation: string;
  difficulty: 'kid' | 'beginner' | 'intermediate' | 'expert';
};

export const QUIZ: Record<Sport, QuizQuestion[]> = {
  mlb: [
    { q: "How many strikes to strike out?", options: ["2","3","4","5"], answer: 1, explanation: "Three strikes and you are out — one of baseball's most fundamental rules.", difficulty: "beginner" },
    { q: "What is an RBI?", options: ["A pitching stat","A run batted in","A type of pitch","A defensive play"], answer: 1, explanation: "RBI stands for Run Batted In — credited when a batter's hit causes a runner to score.", difficulty: "beginner" },
    { q: "How many innings in a standard MLB game?", options: ["7","8","9","10"], answer: 2, explanation: "A standard MLB game has 9 innings; tied games go to extra innings.", difficulty: "beginner" },
    { q: "What is a 'grand slam'?", options: ["Any home run","A home run with the bases loaded, scoring four runs","A walk-off hit","A hit that scores three runs"], answer: 1, explanation: "A grand slam is a home run with all three bases occupied, scoring four runs at once.", difficulty: "beginner" },
    { q: "How many balls result in a walk?", options: ["3","4","5","6"], answer: 1, explanation: "After four balls, the batter is awarded first base — a walk.", difficulty: "beginner" },
    { q: "Which player holds the MLB record for most career home runs?", options: ["Babe Ruth","Hank Aaron","Barry Bonds","Willie Mays"], answer: 2, explanation: "Barry Bonds holds the record with 762 career home runs.", difficulty: "intermediate" },
    { q: "Which pitcher has the most career strikeouts in MLB history?", options: ["Roger Clemens","Randy Johnson","Nolan Ryan","Pedro Martinez"], answer: 2, explanation: "Nolan Ryan struck out 5,714 batters over his career — the all-time record.", difficulty: "intermediate" },
    { q: "In what year did Jackie Robinson break the MLB color barrier?", options: ["1942","1945","1947","1951"], answer: 2, explanation: "Jackie Robinson debuted for the Brooklyn Dodgers on April 15, 1947.", difficulty: "intermediate" },
    { q: "What is a 'perfect game'?", options: ["A no-hitter with no walks","Retiring all 27 batters with no one reaching base","Winning 1-0 with 9 strikeouts","A shutout with only three hits"], answer: 1, explanation: "In a perfect game the pitcher retires all 27 batters faced — no hits, walks, or errors.", difficulty: "intermediate" },
    { q: "What is the Mendoza Line?", options: [".200 batting average","250 strikeouts","A 3.00 ERA","100 RBIs"], answer: 0, explanation: "The Mendoza Line is a .200 batting average, a benchmark for offensive struggles.", difficulty: "expert" },
    { q: "Who holds the record for most consecutive games played?", options: ["Lou Gehrig","Pete Rose","Cal Ripken Jr.","Everett Scott"], answer: 2, explanation: "Cal Ripken Jr. played 2,632 straight games from 1982 to 1998.", difficulty: "expert" },
    { q: "What is 'pitch tunneling'?", options: ["Throwing pitches that share the same path before breaking differently","Pitching only inside","Hiding the ball before release","Maximizing spin for vertical movement"], answer: 0, explanation: "Pitch tunneling makes different pitches look identical early, so hitters can't tell them apart in time.", difficulty: "expert" },
    { q: "When did MLB restrict the defensive shift?", options: ["Starting the 2023 season — two infielders required on each side of second base","Banned in 2019","Banned in 2020","Never officially restricted"], answer: 0, explanation: "From 2023, teams must keep two infielders on each side of second base, limiting extreme shifts.", difficulty: "expert" },
    { q: "What do MLB players use to hit the baseball?", options: ["A bat","A hockey stick","A tennis racket","A golf club"], answer: 0, explanation: "A bat is like the player's magic wand for sending the ball flying.", difficulty: "kid" },
    { q: "What is the main goal in a baseball game?", options: ["Score more runs than the other team","Kick the ball into a net","Bounce the ball with your hands","Knock down all the pins"], answer: 0, explanation: "Teams race to score the most runs by going around the bases and back home.", difficulty: "kid" },
    { q: "How does a player score a run?", options: ["By touching home plate after going around the bases","By catching three balls in a row","By standing on the pitcher's mound","By throwing the ball into the crowd"], answer: 0, explanation: "Touching home plate is like reaching the finish line after a big lap.", difficulty: "kid" },
    { q: "What are the white square spots players run to called?", options: ["Bases","Goals","Hoops","Nets"], answer: 0, explanation: "Bases are like safe little islands in a game of tag.", difficulty: "kid" },
    { q: "Where does the batter stand to hit?", options: ["Next to home plate","On second base","In the outfield seats","Behind the pitcher"], answer: 0, explanation: "The batter stands by home plate like a knight guarding a castle gate, ready to swing.", difficulty: "kid" },
    { q: "What is it called when a batter hits the ball over the outfield fence and it stays fair?", options: ["A home run","A foul ball","A timeout","A shortstop"], answer: 0, explanation: "A home run is like blasting the ball on a super long trip — you get to jog around the bases for free.", difficulty: "kid" },
    { q: "Which player throws the ball to the batter?", options: ["The pitcher","The catcher","The coach","The umpire"], answer: 0, explanation: "The pitcher starts each play by tossing the ball toward home plate.", difficulty: "kid" },
    { q: "Who wears a mask and crouches behind the batter?", options: ["The catcher","The shortstop","The first-base coach","The outfielder"], answer: 0, explanation: "The catcher is like the goalie of home plate, ready for fast throws.", difficulty: "kid" },
    { q: "What is the big glove on a player's hand called?", options: ["A mitt","A helmet","A backpack","A whistle"], answer: 0, explanation: "A mitt helps players scoop up the ball like a little leather basket.", difficulty: "kid" },
    { q: "What does the umpire do?", options: ["Makes the calls and keeps the game fair","Sells popcorn in the stands","Paints the bases","Chooses the music"], answer: 0, explanation: "The umpire is like a fair playground helper who says what happened.", difficulty: "kid" },
    { q: "What happens when a fielder catches a hit ball before it touches the ground?", options: ["The batter is out","Everyone takes a snack break","It's a goal","The batter gets a free base"], answer: 0, explanation: "Catching the ball in the air can stop the batter right away.", difficulty: "kid" },
    { q: "Why do batters wear helmets?", options: ["To help protect their heads","To make them run backward","To hold snacks","To catch rainwater"], answer: 0, explanation: "A helmet is like a strong shell that helps keep a player safe.", difficulty: "kid" },
    { q: "How many players does one team have on the field on defense?", options: ["Nine","Three","Twelve","One"], answer: 0, explanation: "Nine players spread out like a team of superheroes, each guarding a spot.", difficulty: "kid" },
    { q: "About how fast can some MLB pitchers throw?", options: ["Over 100 miles per hour","As slow as walking","Only 5 miles per hour","Slower than a falling leaf"], answer: 0, explanation: "Some pitches zoom faster than cars on the highway — they look like a white blur!", difficulty: "kid" },
    { q: "What is Major League Baseball (MLB)?", options: ["A big league with many pro baseball teams","A single school team","A video game you play alone","A swimming club"], answer: 0, explanation: "MLB is a huge group of pro teams where the best players all compete.", difficulty: "kid" },
  ],
  nfl: [
    { q: "How many points is a touchdown worth?", options: ["3","5","6","7"], answer: 2, explanation: "A touchdown is worth 6 points; the extra point or two-point try comes after.", difficulty: "beginner" },
    { q: "How many players are on the field per team during a play?", options: ["9","10","11","12"], answer: 2, explanation: "Each team has 11 players on the field at a time.", difficulty: "beginner" },
    { q: "How many downs does an offense have to gain 10 yards?", options: ["3","4","5","6"], answer: 1, explanation: "The offense gets four downs to advance 10 yards for a fresh set of downs.", difficulty: "beginner" },
    { q: "What is a 'sack'?", options: ["An interception","A fumble recovery","Tackling the quarterback behind the line of scrimmage","A blocked field goal"], answer: 2, explanation: "A sack is tackling the quarterback behind the line of scrimmage before he can throw.", difficulty: "beginner" },
    { q: "Which quarterback has won the most Super Bowl titles?", options: ["Joe Montana","Tom Brady","Terry Bradshaw","Peyton Manning"], answer: 1, explanation: "Tom Brady won a record seven Super Bowls.", difficulty: "intermediate" },
    { q: "What is a '4-3 defense'?", options: ["Four linebackers and three DBs","Four defensive linemen and three linebackers","Four cornerbacks and three safeties","Three linemen and four linebackers"], answer: 1, explanation: "A 4-3 uses four defensive linemen and three linebackers.", difficulty: "intermediate" },
    { q: "Which running back set the single-season rushing record with 2,105 yards in 1984?", options: ["Barry Sanders","Eric Dickerson","Adrian Peterson","O.J. Simpson"], answer: 1, explanation: "Eric Dickerson rushed for 2,105 yards in 1984, still the single-season record.", difficulty: "intermediate" },
    { q: "What does a safety score, and how many points is it?", options: ["1 point","2 points","3 points","6 points"], answer: 1, explanation: "A safety is worth 2 points, scored when the ball carrier is tackled in his own end zone.", difficulty: "intermediate" },
    { q: "What was the 'tuck rule' controversially called in 2001?", options: ["A rule letting the QB tuck and run","Any forward arm motion counts as a pass even when pulled back","Protecting the QB from late hits","A rule about ball security"], answer: 1, explanation: "The tuck rule treated forward arm motion as a pass attempt even if pulled back, leading to a famous Raiders-Patriots call.", difficulty: "expert" },
    { q: "What is 'Cover 2'?", options: ["Two deep safeties splitting the field","Man coverage with two cornerbacks","A blitz with two extra rushers","Two linebackers in short zones"], answer: 0, explanation: "In Cover 2, two safeties each guard half the deep field while defenders below cover short zones.", difficulty: "expert" },
    { q: "What is 'play-action' and its purpose?", options: ["A QB sneak after a fake field goal","A fake handoff to draw defenders up and open deep passes","A direct snap to a running back","A screen disguised as a deep route"], answer: 1, explanation: "Play-action fakes a handoff to freeze the defense, opening up the passing game.", difficulty: "expert" },
    { q: "How does 'Tampa 2' differ from standard Cover 2?", options: ["It uses three deep safeties","It's identical to Cover 2","The middle linebacker drops deep to cover the middle seam","It's a man coverage scheme"], answer: 2, explanation: "Tampa 2 sends the middle linebacker into a deep middle zone, closing the seam that standard Cover 2 leaves open.", difficulty: "expert" },
    { q: "What is the main goal in a football game?", options: ["Score more points than the other team","Dig the deepest hole","Stay on the field the longest","Kick the ball the highest"], answer: 0, explanation: "Each team races to a bigger number on the big scoreboard.", difficulty: "kid" },
    { q: "What shape is a football?", options: ["An oval with pointy ends","A perfect round circle","A flat square","A triangle"], answer: 0, explanation: "The pointy ends help it fly through the air like a brown rocket.", difficulty: "kid" },
    { q: "How does a team score a touchdown?", options: ["By bringing the ball into the end zone","By standing still in the middle","By dropping the ball on purpose","By walking off the field"], answer: 0, explanation: "A touchdown is like crossing a magic finish line with the ball for big points.", difficulty: "kid" },
    { q: "What is the special scoring area at each end of the field called?", options: ["The end zone","The snack zone","The locker room","The bench line"], answer: 0, explanation: "The end zone is like the treasure spot players want to reach.", difficulty: "kid" },
    { q: "What is the quarterback's main job?", options: ["Throw or hand off the ball to teammates","Blow the whistle","Paint the field lines","Control the scoreboard"], answer: 0, explanation: "The quarterback is like the team's driver, choosing where the ball goes each play.", difficulty: "kid" },
    { q: "What is it called when a player kicks the ball through the tall yellow posts?", options: ["A field goal","A home run","A slam dunk","A spike"], answer: 0, explanation: "A field goal is like kicking the ball through a giant letter H for points.", difficulty: "kid" },
    { q: "How many players are on the field for one team during a play?", options: ["Eleven","Five","Twenty","Two"], answer: 0, explanation: "Eleven players per team, like a small army of friends in helmets.", difficulty: "kid" },
    { q: "Why do players wear helmets and pads?", options: ["To stay safe when they bump and tackle","To look taller","To run slower","To hide their faces"], answer: 0, explanation: "Helmets and pads are like armor that protects players in a real-life adventure.", difficulty: "kid" },
    { q: "What does the defense try to do?", options: ["Stop the other team from scoring","Help the other team score","Sit on the bench and rest","Run away from the ball"], answer: 0, explanation: "Defense guards their goal like protecting a fort in a game of tag.", difficulty: "kid" },
    { q: "What happens at the very start of a game?", options: ["One team kicks off the ball","Everyone takes a nap","The field is painted again","The game ends right away"], answer: 0, explanation: "A kickoff sends the ball flying down the field to begin the action.", difficulty: "kid" },
    { q: "What happens when a player catches a pass?", options: ["The team can keep moving the ball forward","The game turns into soccer","Everyone sits down","The ball becomes invisible"], answer: 0, explanation: "A catch moves the team forward, like taking another step in a board game.", difficulty: "kid" },
    { q: "What is a football field covered with?", options: ["Grass or turf","Ice","Only sand","Wooden boards"], answer: 0, explanation: "Football fields are like big green playgrounds made for running.", difficulty: "kid" },
    { q: "Why do players huddle together before a play?", options: ["To talk about the next plan","To tell jokes to the crowd","To tie everyone's shoes","To take a nap"], answer: 0, explanation: "A huddle is like a tiny team meeting before the action starts.", difficulty: "kid" },
    { q: "What does the kicker do?", options: ["Kicks the football","Paints the field","Counts the fans","Washes the helmets"], answer: 0, explanation: "The kicker uses their foot to send the ball flying high and far.", difficulty: "kid" },
    { q: "How fast can some football players run?", options: ["As fast as a zooming bike","As slow as a sleepy snail","Only a baby crawl","Slower than a rolling marble"], answer: 0, explanation: "Some players sprint so fast it looks like they hit a turbo button!", difficulty: "kid" },
    { q: "What is the NFL?", options: ["A big league of pro football teams","One small school team","A single backyard game","A swimming club"], answer: 0, explanation: "The NFL is the top level where many pro teams battle it out.", difficulty: "kid" },
  ],
  nba: [
    { q: "How many points is a three-point shot worth?", options: ["1","2","3","4"], answer: 2, explanation: "A shot from behind the three-point arc is worth 3 points.", difficulty: "beginner" },
    { q: "How many players per team are on the court at once?", options: ["4","5","6","7"], answer: 1, explanation: "Each team has five players on the court.", difficulty: "beginner" },
    { q: "How long is each quarter in an NBA game?", options: ["10 minutes","12 minutes","15 minutes","20 minutes"], answer: 1, explanation: "NBA games have four 12-minute quarters.", difficulty: "beginner" },
    { q: "How many fouls until a player fouls out?", options: ["4","5","6","7"], answer: 2, explanation: "A player is disqualified after six personal fouls.", difficulty: "beginner" },
    { q: "Who holds the NBA record for most career points?", options: ["Kareem Abdul-Jabbar","Michael Jordan","Kobe Bryant","LeBron James"], answer: 3, explanation: "LeBron James passed Kareem Abdul-Jabbar in 2023 to become the all-time scoring leader.", difficulty: "intermediate" },
    { q: "Which franchise has won the most NBA championships?", options: ["Los Angeles Lakers","Chicago Bulls","Boston Celtics","Golden State Warriors"], answer: 2, explanation: "The Boston Celtics lead with 18 championships.", difficulty: "intermediate" },
    { q: "Which player scored 100 points in a single NBA game in 1962?", options: ["Bill Russell","Oscar Robertson","Wilt Chamberlain","Jerry West"], answer: 2, explanation: "Wilt Chamberlain scored 100 against the Knicks on March 2, 1962.", difficulty: "intermediate" },
    { q: "Which team holds the record for most regular-season wins at 73-9?", options: ["Chicago Bulls 1995-96","LA Lakers 1971-72","Golden State Warriors 2015-16","Boston Celtics 2007-08"], answer: 2, explanation: "The 2015-16 Warriors went 73-9, the best regular-season record ever.", difficulty: "intermediate" },
    { q: "What is the 'elbow' in basketball?", options: ["A foul for hitting an opponent","The intersection of the free throw line and lane line","The corner three-point area","The low block"], answer: 1, explanation: "The elbow is where the free throw line meets the lane line — a key mid-range spot.", difficulty: "expert" },
    { q: "In which season did the NBA introduce the three-point line?", options: ["1975-76","1978-79","1979-80","1982-83"], answer: 2, explanation: "The three-point line arrived for the 1979-80 season.", difficulty: "expert" },
    { q: "What does 'pace and space' describe?", options: ["A trapping defense","Fast tempo with floor spacing to maximize threes and drives","A slow-down possession system","A minutes-management strategy"], answer: 1, explanation: "Pace and space pairs a fast tempo with wide spacing to open driving lanes and three-point looks.", difficulty: "expert" },
    { q: "What is the 'Spain pick-and-roll'?", options: ["A pick-and-roll plus a back screen on the screener's defender","A double screen at the elbow","A handoff into a fade","An isolation set"], answer: 0, explanation: "The Spain pick-and-roll adds a back screen on the roller's defender, creating confusion and an open lane.", difficulty: "expert" },
    { q: "What is the main goal in a basketball game?", options: ["Score more points than the other team","Kick the ball the farthest","Knock down all the pins","Slide the fastest on the floor"], answer: 0, explanation: "Both teams race to a bigger number on the scoreboard.", difficulty: "kid" },
    { q: "What kind of ball is used in an NBA game?", options: ["A round orange basketball","A tiny marble","A hard metal ball","A long foam noodle"], answer: 0, explanation: "It's a bouncy orange ball that's easy to see and fun to dribble.", difficulty: "kid" },
    { q: "Where do players try to shoot the ball to score?", options: ["Through the hoop with the net","Into a hole in the floor","Over the coach's head","Into the crowd"], answer: 0, explanation: "They aim for the hoop, like tossing a toy into a basket.", difficulty: "kid" },
    { q: "How many players from one team are on the court at once?", options: ["Five","Two","Eight","Ten"], answer: 0, explanation: "Five players per team, like a small squad of friends working together.", difficulty: "kid" },
    { q: "What is it called when a player bounces the ball while moving?", options: ["Dribbling","Throwing","Kicking","Balancing"], answer: 0, explanation: "Dribbling is like walking the ball along with little bounces.", difficulty: "kid" },
    { q: "How many points is a basket from close to the hoop usually worth?", options: ["Two points","Ten points","Zero points","One hundred points"], answer: 0, explanation: "Most close baskets are worth two points, like earning two stars for a good move.", difficulty: "kid" },
    { q: "What is it called when a player jumps and pushes the ball down through the hoop?", options: ["A slam dunk","A free throw","A slide","A kick shot"], answer: 0, explanation: "A dunk is a big wow play where the player reaches all the way to the hoop.", difficulty: "kid" },
    { q: "What does a player do when a teammate is open?", options: ["Pass the ball so they can try to score","Hide the ball under their shirt","Throw the ball out of bounds","Kick it into the stands"], answer: 0, explanation: "Passing is like sharing a toy so your friend gets a turn.", difficulty: "kid" },
    { q: "What do players wear on their feet to run and jump?", options: ["Sneakers","Skates","Flippers","Boots with wheels"], answer: 0, explanation: "Sneakers help players zoom, stop, and jump like superheroes.", difficulty: "kid" },
    { q: "Who helps make sure players follow the rules?", options: ["The referee","The popcorn seller","The mascot","The music player"], answer: 0, explanation: "The referee is like the playground helper who keeps things fair.", difficulty: "kid" },
    { q: "What is a rebound?", options: ["Grabbing the ball after a missed shot","Bouncing on a trampoline","Waving to the crowd","Changing the scoreboard"], answer: 0, explanation: "A rebound is like catching a ball that bounced off a wall.", difficulty: "kid" },
    { q: "What does the team on defense try to do?", options: ["Stop the other team from scoring","Give the other team snacks","Carry the hoop away","Take a nap"], answer: 0, explanation: "Defense is like guarding a castle so the other team can't get easy points.", difficulty: "kid" },
    { q: "How high is an NBA hoop from the floor?", options: ["About as high as two grown-ups stacked tall","As high as a kitchen chair","As high as a backpack","As high as a shoebox"], answer: 0, explanation: "The hoop is super high, which makes big jumps look extra amazing.", difficulty: "kid" },
    { q: "Why are many NBA players called tall even among adults?", options: ["Many are much taller than most grown-ups","They wear tall shoes","They stand on boxes","They always jump"], answer: 0, explanation: "Lots of NBA players are taller than almost anyone you know — like real-life giants.", difficulty: "kid" },
    { q: "Why do players practice shooting so much?", options: ["To get better at making baskets","To make the ball heavier","To learn magic tricks","To turn the court to ice"], answer: 0, explanation: "Practice makes their shots as smooth as tossing socks into a laundry basket.", difficulty: "kid" },
    { q: "What is the NBA?", options: ["A big league of pro basketball teams","One small school team","A single playground game","A swimming club"], answer: 0, explanation: "The NBA is a giant group of top teams where the best players in the world compete.", difficulty: "kid" },
  ],
  nhl: [
    { q: "How many players per team are on the ice at once?", options: ["4","5","6","7"], answer: 2, explanation: "Six per side: a goalie, two defensemen, and three forwards.", difficulty: "beginner" },
    { q: "What is the NHL's championship trophy called?", options: ["Presidents' Trophy","Norris Trophy","Stanley Cup","Hart Trophy"], answer: 2, explanation: "The Stanley Cup goes to the NHL champion each year.", difficulty: "beginner" },
    { q: "How long is each period in an NHL game?", options: ["15 minutes","20 minutes","25 minutes","30 minutes"], answer: 1, explanation: "Each of the three periods lasts 20 minutes.", difficulty: "beginner" },
    { q: "What is 'offsides' in hockey?", options: ["A player entering the offensive zone before the puck","Delay of game","High-sticking","Goalie interference"], answer: 0, explanation: "Offsides is called when an attacker crosses into the offensive zone before the puck does.", difficulty: "beginner" },
    { q: "Who holds the NHL record for most career goals?", options: ["Gordie Howe","Mario Lemieux","Brett Hull","Wayne Gretzky"], answer: 3, explanation: "Wayne Gretzky scored 894 career goals, the most ever.", difficulty: "intermediate" },
    { q: "Which franchise has won the most Stanley Cups?", options: ["Toronto Maple Leafs","Detroit Red Wings","Boston Bruins","Montreal Canadiens"], answer: 3, explanation: "The Montreal Canadiens have won 24 Stanley Cups.", difficulty: "intermediate" },
    { q: "What is the 'neutral zone trap'?", options: ["A strategy clogging the neutral zone to limit rushes","A power play formation","An icing play to rest defenders","A breakout system"], answer: 0, explanation: "The trap jams the neutral zone to choke off the other team's rushes.", difficulty: "intermediate" },
    { q: "What is the Conn Smythe Trophy awarded for?", options: ["Best regular-season record","Top regular-season scorer","MVP of the playoffs","Best defensive player"], answer: 2, explanation: "The Conn Smythe goes to the most valuable player of the Stanley Cup playoffs.", difficulty: "intermediate" },
    { q: "What were Wayne Gretzky's total career points?", options: ["2,457","2,857","3,012","2,600"], answer: 1, explanation: "Gretzky tallied 2,857 points — his assists alone (1,963) would top the all-time list.", difficulty: "expert" },
    { q: "What is 'cycling' in offensive strategy?", options: ["Line changes during play","Rotating the puck along the boards in the offensive zone to tire defenders","A power-play overload","A backward-skating drill"], answer: 1, explanation: "Cycling keeps possession by moving the puck along the boards, wearing down the defense until a chance opens.", difficulty: "expert" },
    { q: "What is the 'trapezoid' rule for goaltenders?", options: ["Limiting goalie equipment size","Restricting goalies to playing the puck only within the marked area behind the goal line","A salary cap exception","A rule requiring neck guards"], answer: 1, explanation: "Goalies may only handle the puck inside the trapezoid behind the net, limiting how much they can help on dump-ins.", difficulty: "expert" },
    { q: "What is 'Expected Goals' (xG) in hockey analytics?", options: ["A model predicting career goal totals","A probability that a given shot becomes a goal, based on location, type, and situation","A shooter-vs-goalie comparison tool","A power-play conversion model"], answer: 1, explanation: "xG assigns each shot a scoring probability from its location, angle, and type — measuring chance quality, not just shot count.", difficulty: "expert" },
    { q: "What do hockey players skate on during a game?", options: ["Ice","Grass","Sand","Carpet"], answer: 0, explanation: "Hockey is played on ice, so players glide around like super-fast penguins.", difficulty: "kid" },
    { q: "What do players use to move the puck?", options: ["A hockey stick","A baseball bat","A tennis racket","A golf club"], answer: 0, explanation: "A hockey stick helps players push, pass, and shoot the puck like a magic pointer.", difficulty: "kid" },
    { q: "What is the small black thing players shoot into the net?", options: ["A puck","A marble","A cookie","A button"], answer: 0, explanation: "The puck is flat and slides on the ice like a tiny flying saucer.", difficulty: "kid" },
    { q: "How does a hockey team score?", options: ["By getting the puck into the net","By catching the puck in a hat","By skating in a circle","By touching the boards"], answer: 0, explanation: "Putting the puck in the net is like getting a coin into a piggy bank slot.", difficulty: "kid" },
    { q: "How many players are usually on the ice for one team?", options: ["Six","Two","Eleven","Fifteen"], answer: 0, explanation: "Six players per team, like a small squad of friends skating together.", difficulty: "kid" },
    { q: "Who tries to stop the puck from going into the net?", options: ["The goalie","The coach","The mascot","The announcer"], answer: 0, explanation: "The goalie guards the net like a castle door, trying to block every puck.", difficulty: "kid" },
    { q: "What do hockey players wear on their feet?", options: ["Skates","Sneakers","Flip-flops","Snow boots"], answer: 0, explanation: "Skates have sharp blades that help players zoom across the ice.", difficulty: "kid" },
    { q: "Why do players wear helmets and pads?", options: ["To stay safe when they bump and fall","To look taller","To skate slower","To keep the ice warm"], answer: 0, explanation: "Helmets and pads protect them like armor in a snowy adventure.", difficulty: "kid" },
    { q: "What happens when a player passes the puck?", options: ["They send it to a teammate","They hide it under the ice","They throw it into the seats","They give it to the referee"], answer: 0, explanation: "A pass is like sharing a toy so the team can play together.", difficulty: "kid" },
    { q: "What is the big wall around the ice called?", options: ["The boards","Fences","Bookshelves","Curtains"], answer: 0, explanation: "The boards keep the puck and players inside the icy playground.", difficulty: "kid" },
    { q: "How many periods are in a regular NHL game?", options: ["Three","One","Two","Five"], answer: 0, explanation: "An NHL game has three periods, like three mini-games in one big show.", difficulty: "kid" },
    { q: "Where do players sit while waiting for their turn?", options: ["The bench","A tree stump","A couch on the ice","A giant pillow"], answer: 0, explanation: "The bench is the team's waiting spot before they jump back into the game.", difficulty: "kid" },
    { q: "How fast can a puck move after a big shot?", options: ["Faster than many cars on a road","As slow as a sleepy turtle","Only as fast as a walking kid","Slower than a drifting feather"], answer: 0, explanation: "A hard shot makes the puck zip by like a little black rocket.", difficulty: "kid" },
    { q: "What do players often do after their team scores?", options: ["Celebrate with teammates","Take off their skates","Leave the rink","Turn off the lights"], answer: 0, explanation: "A goal is a big happy moment, so teammates cheer together.", difficulty: "kid" },
    { q: "What is the NHL?", options: ["A big league of pro ice hockey teams","One tiny local team","A swimming club","A track race"], answer: 0, explanation: "The NHL is a huge league where pro teams battle for the shiny Stanley Cup.", difficulty: "kid" },
  ],
  wnba: [
    { q: "How long is each quarter in a WNBA game?", options: ["10 minutes","12 minutes","15 minutes","8 minutes"], answer: 0, explanation: "WNBA games have four 10-minute quarters.", difficulty: "beginner" },
    { q: "In what year did the WNBA play its first season?", options: ["1990","1994","1996","1997"], answer: 3, explanation: "The WNBA was founded in 1996 and tipped off its first season in 1997.", difficulty: "beginner" },
    { q: "Who is the WNBA's all-time leading scorer?", options: ["Lisa Leslie","Sue Bird","Diana Taurasi","Tina Thompson"], answer: 2, explanation: "Diana Taurasi is the league's all-time leading scorer.", difficulty: "beginner" },
    { q: "How many WNBA titles did the Houston Comets win in a row?", options: ["2","3","4","5"], answer: 2, explanation: "The Comets won the first four WNBA championships, 1997 through 2000.", difficulty: "intermediate" },
    { q: "Which player has won the most WNBA MVP awards?", options: ["Cynthia Cooper","Lisa Leslie","Lauren Jackson","Breanna Stewart"], answer: 2, explanation: "Lauren Jackson won three WNBA MVP awards (2003, 2007, 2010).", difficulty: "intermediate" },
    { q: "Who holds the record for most points in a single WNBA game?", options: ["Diana Taurasi","Riquna Williams","Maya Moore","Brittney Griner"], answer: 1, explanation: "Riquna Williams scored 51 points in a single game in 2013.", difficulty: "intermediate" },
    { q: "What defensive rule did the WNBA adopt in 2013?", options: ["Three-point line extension","Elimination of zone restrictions","The defensive three-second rule","A reduced foul limit"], answer: 2, explanation: "The WNBA adopted the defensive three-second rule in 2013.", difficulty: "expert" },
    { q: "What did the WNBA's 2020 CBA include for maternity leave?", options: ["6 weeks paid leave only","Full salary continuation, childcare stipends, and guaranteed roster spots","A guaranteed roster spot only","Childcare support only"], answer: 1, explanation: "The 2020 CBA added full salary during maternity leave, childcare support, and guaranteed roster spots.", difficulty: "expert" },
    { q: "Who has the most coaching wins in WNBA history?", options: ["Van Chancellor","Cheryl Reeve","Marianne Stanley","Sandy Brondello"], answer: 1, explanation: "Cheryl Reeve holds the record for most WNBA coaching victories.", difficulty: "expert" },
    { q: "What sport is played in the WNBA?", options: ["Basketball","Soccer","Baseball","Ice hockey"], answer: 0, explanation: "The WNBA is all about basketball — dribbling and shooting just like on your school court.", difficulty: "kid" },
    { q: "Who plays in the WNBA?", options: ["Women professional basketball players","Robots with wheels","Only kids from one school","Only cartoon characters"], answer: 0, explanation: "The WNBA is a league where amazing women play pro basketball, like real-life superheroes.", difficulty: "kid" },
    { q: "What kind of ball do WNBA players use?", options: ["A smaller orange basketball","A giant beach ball","A metal cube","A snowball"], answer: 0, explanation: "They use a slightly smaller orange ball that fits their hands, like a just-right-size toy.", difficulty: "kid" },
    { q: "Where do players try to throw the ball to score?", options: ["Through the hoop with the net","At the scoreboard","Into the locker room","Onto the bench"], answer: 0, explanation: "They aim for the hoop, like tossing a stuffed animal into a laundry basket.", difficulty: "kid" },
    { q: "How many players from one team are on the court at once?", options: ["Five","Two","Ten","Eight"], answer: 0, explanation: "Five players per team, like a small group of friends working together.", difficulty: "kid" },
    { q: "How many points is a close basket usually worth?", options: ["Two points","One point","Zero points","One hundred points"], answer: 0, explanation: "Most close baskets are worth two points, like earning two stars for a good move.", difficulty: "kid" },
    { q: "What does it mean to dribble?", options: ["Bounce the ball while moving","Hold the ball and stand still","Kick the ball like soccer","Hide the ball forever"], answer: 0, explanation: "Dribbling is bouncing the ball as you go, like taking it for a bouncy walk.", difficulty: "kid" },
    { q: "What do players do when a teammate is open?", options: ["Pass the ball","Hide the ball","Sit on the floor","Kick it into the seats"], answer: 0, explanation: "Passing is like sharing with a friend so the team can work together.", difficulty: "kid" },
    { q: "What does the team on defense try to do?", options: ["Stop the other team from scoring","Help the other team score","Move the basket away","Carry the popcorn"], answer: 0, explanation: "Defense is like guarding a castle from easy points.", difficulty: "kid" },
    { q: "What is a rebound?", options: ["Grabbing the ball after a missed shot","Running in a circle","Waving to the crowd","Changing the lights"], answer: 0, explanation: "A rebound is like catching a ball after it bounces off a wall.", difficulty: "kid" },
    { q: "Who makes sure players follow the rules?", options: ["The referee","The mascot","The ticket scanner","The snack seller"], answer: 0, explanation: "The referee is like a fair playground helper for the game.", difficulty: "kid" },
    { q: "What is a layup?", options: ["A close shot near the basket","A kick across the court","A throw from the seats","A nap during the game"], answer: 0, explanation: "A layup is a close shot, like gently putting the ball near its home.", difficulty: "kid" },
    { q: "Why do players practice shooting?", options: ["To get better at making baskets","To make the ball louder","To turn the court to ice","To make their shoes glow"], answer: 0, explanation: "Practice makes shots feel as easy as tossing laundry into a basket.", difficulty: "kid" },
    { q: "How high is a WNBA hoop from the floor?", options: ["About as high as two grown-ups stacked tall","As high as a backpack","As high as a kitchen chair","As high as a shoebox"], answer: 0, explanation: "The hoop is really high, which makes great shots look extra awesome.", difficulty: "kid" },
    { q: "What do players wear on their feet to run and jump?", options: ["Basketball shoes","Ice skates","Swim fins","Roller skates"], answer: 0, explanation: "Basketball shoes help players stop, zoom, and jump like superheroes.", difficulty: "kid" },
    { q: "Why is Lisa Leslie famous in WNBA history?", options: ["She was the first to dunk in a WNBA game","She invented basketball","She only played soccer","She built every arena"], answer: 0, explanation: "Lisa Leslie wowed fans by dunking — flying up to slam the ball straight down!", difficulty: "kid" },
    { q: "What is the WNBA?", options: ["A big league of women's pro basketball teams","One tiny school club","A swimming event","A video game you play alone"], answer: 0, explanation: "The WNBA is a whole league where many women's teams battle to be champions.", difficulty: "kid" },
  ],
  soccer: [
    { q: "What year did MLS play its first season?", options: ["1990","1993","1996","2000"], answer: 2, explanation: "Major League Soccer kicked off its first season in 1996.", difficulty: "beginner" },
    { q: "Which famous Argentine player joined Inter Miami in 2023?", options: ["Cristiano Ronaldo","Neymar","Lionel Messi","Karim Benzema"], answer: 2, explanation: "Lionel Messi signed with Inter Miami in 2023.", difficulty: "beginner" },
    { q: "What is the 'Supporters' Shield'?", options: ["Award for top goal scorer","Trophy for the best regular-season record","A fan attendance award","The playoff trophy"], answer: 1, explanation: "The Supporters' Shield goes to the MLS team with the best regular-season record.", difficulty: "beginner" },
    { q: "How long is a standard soccer match?", options: ["80 minutes","90 minutes","100 minutes","120 minutes"], answer: 1, explanation: "A match is 90 minutes, split into two 45-minute halves, plus stoppage time.", difficulty: "beginner" },
    { q: "Which MLS club has won the most MLS Cups?", options: ["New England Revolution","LA Galaxy","D.C. United","Seattle Sounders"], answer: 1, explanation: "LA Galaxy has won five MLS Cup championships.", difficulty: "intermediate" },
    { q: "What is the 'Designated Player' rule?", options: ["Limits foreign players","Lets clubs sign players whose salary exceeds the budget cap","Requires homegrown players","A salary floor rule"], answer: 1, explanation: "The Designated Player rule lets teams sign up to three players whose salaries exceed the cap.", difficulty: "intermediate" },
    { q: "Who is MLS's all-time leading scorer?", options: ["David Villa","Landon Donovan","Chris Wondolowski","Josef Martinez"], answer: 2, explanation: "Chris Wondolowski scored 171 career goals, the MLS record.", difficulty: "intermediate" },
    { q: "What is an 'offside' in soccer?", options: ["Being behind the last defender when the ball is played","Being ahead of the second-to-last defender when the ball is played to you","Touching the ball with your hands","Entering the penalty box early"], answer: 1, explanation: "You're offside if you're nearer the goal than the second-to-last defender when a teammate plays you the ball.", difficulty: "intermediate" },
    { q: "What is 'gegenpressing'?", options: ["A deep defensive block","Immediately pressing to win the ball back right after losing it","A slow possession style","A long-ball strategy"], answer: 1, explanation: "Gegenpressing means counter-pressing instantly after losing the ball, before the opponent can organize.", difficulty: "expert" },
    { q: "How does MLS's single-entity structure differ from European leagues?", options: ["Player contracts are owned by the league, and there's no promotion/relegation","Teams have no salary cap","Clubs are fully independent","It uses a draft only"], answer: 0, explanation: "MLS operates as a single entity — the league owns contracts — and has no promotion or relegation.", difficulty: "expert" },
    { q: "What is the maximum number of Designated Players an MLS team can have?", options: ["2","3","4","5"], answer: 1, explanation: "Teams are allowed a maximum of three Designated Players.", difficulty: "expert" },
    { q: "What do soccer players mostly use to move the ball?", options: ["Their feet","Their hands","Their elbows","Their helmets"], answer: 0, explanation: "Soccer is a feet-first game, like giving the ball tiny kicks on a walk.", difficulty: "kid" },
    { q: "What is the main goal in a soccer game?", options: ["Score more goals than the other team","Hold the ball the longest","Sit on the grass the most","Kick the ball the highest"], answer: 0, explanation: "Both teams race to a bigger number on the scoreboard.", difficulty: "kid" },
    { q: "What kind of ball is used in soccer?", options: ["A round soccer ball","A square stone","A tiny marble","A paper plane"], answer: 0, explanation: "It's a round, bouncy ball that rolls easily on the grass.", difficulty: "kid" },
    { q: "How does a team score a goal?", options: ["By kicking the ball into the net","By catching the ball in a glove","By bouncing it into a hoop","By throwing it over a fence"], answer: 0, explanation: "A goal is like getting the ball into its special home.", difficulty: "kid" },
    { q: "Who tries to stop the ball from going into the net?", options: ["The goalkeeper","The mascot","The snack seller","The announcer"], answer: 0, explanation: "The goalkeeper is like the castle guard protecting the goal.", difficulty: "kid" },
    { q: "Who is the only player usually allowed to use their hands during play?", options: ["The goalkeeper","The striker","The referee","The coach"], answer: 0, explanation: "The goalkeeper can use their hands near the goal, like a special guard in a giant game of keep-away.", difficulty: "kid" },
    { q: "What do soccer players wear on their feet to grip the grass?", options: ["Cleats","Ice skates","Flip-flops","Rain boots"], answer: 0, explanation: "Cleats have little grips underneath, like tiny teeth for the grass.", difficulty: "kid" },
    { q: "What do players wear on their shins to protect their legs?", options: ["Shin guards","Knee pillows","Arm bands","Snow socks"], answer: 0, explanation: "Shin guards are like little shields for the front of your legs.", difficulty: "kid" },
    { q: "What is it called when a player taps the ball along while moving?", options: ["Dribbling","Sleeping","Balancing","Jumping"], answer: 0, explanation: "Dribbling keeps the ball close with little taps, like guiding a puppy on a leash.", difficulty: "kid" },
    { q: "What happens when a player passes the ball?", options: ["They send it to a teammate","They hide it in their shirt","They throw it into the crowd","They give it to the referee"], answer: 0, explanation: "Passing is like sharing a toy so the team can play together.", difficulty: "kid" },
    { q: "What is the big rectangle with a net called?", options: ["The goal","The basket","The dugout","The rink"], answer: 0, explanation: "The goal is the big target players aim for when they shoot.", difficulty: "kid" },
    { q: "What is it called when a player kicks the ball toward the goal?", options: ["A shot","A nap","A slide","A picnic"], answer: 0, explanation: "A shot is a try to score, like aiming for a target at recess.", difficulty: "kid" },
    { q: "What does the referee do?", options: ["Helps make sure everyone follows the rules","Plays music for the players","Paints the ball","Counts the clouds"], answer: 0, explanation: "The referee is like a fair playground helper for the game.", difficulty: "kid" },
    { q: "What does the team without the ball try to do?", options: ["Win the ball back","Give the other team cupcakes","Move the goal away","Sit in the grass"], answer: 0, explanation: "Trying to win the ball back is like a friendly game of tag.", difficulty: "kid" },
    { q: "How many players are on the field for one team in regular soccer?", options: ["Eleven","Three","Twenty","Seven"], answer: 0, explanation: "Eleven players per team, like a whole class split into two big groups.", difficulty: "kid" },
    { q: "What is the big grassy area where soccer is played called?", options: ["A field or pitch","A swimming lane","A skating rink","A classroom"], answer: 0, explanation: "Soccer is played on a big grass field, like a giant backyard for running and kicking.", difficulty: "kid" },
    { q: "How far can a strong kick send the ball?", options: ["Across a big part of the field","Only one tiny step","Straight into the clouds","Under the grass"], answer: 0, explanation: "A powerful kick can make the ball zoom like it has wings.", difficulty: "kid" },
    { q: "About how long does a normal soccer game last?", options: ["About 90 minutes, in two halves","Only five minutes total","All day with no breaks","Exactly ten minutes"], answer: 0, explanation: "A regular game is about 90 minutes — like two cartoon episodes back to back.", difficulty: "kid" },
  ],
  worldcup: [
    { q: "How often is the FIFA World Cup held?", options: ["Every 2 years","Every 3 years","Every 4 years","Every 5 years"], answer: 2, explanation: "The World Cup is held every four years.", difficulty: "beginner" },
    { q: "Which country has won the most FIFA World Cups?", options: ["Germany","Argentina","Italy","Brazil"], answer: 3, explanation: "Brazil has won a record five World Cups.", difficulty: "beginner" },
    { q: "Who is the all-time top scorer in World Cup history?", options: ["Ronaldo Nazario","Miroslav Klose","Pele","Gerd Muller"], answer: 1, explanation: "Germany's Miroslav Klose scored 16 goals across World Cups, the all-time record.", difficulty: "beginner" },
    { q: "Where was the 2022 FIFA World Cup held?", options: ["Russia","Brazil","Qatar","France"], answer: 2, explanation: "The 2022 World Cup was held in Qatar.", difficulty: "beginner" },
    { q: "Which nation won the first World Cup in 1930?", options: ["Brazil","Argentina","Uruguay","Italy"], answer: 2, explanation: "Uruguay won the inaugural 1930 World Cup, which it also hosted.", difficulty: "intermediate" },
    { q: "Who scored the 'Hand of God' goal in 1986?", options: ["Pele","Ronaldo","Diego Maradona","Zinedine Zidane"], answer: 2, explanation: "Diego Maradona punched in the infamous 'Hand of God' goal against England in 1986.", difficulty: "intermediate" },
    { q: "Which three countries are co-hosting the 2026 World Cup?", options: ["USA, Mexico, Canada","USA, Brazil, Mexico","Canada, UK, USA","France, Spain, Portugal"], answer: 0, explanation: "The 2026 World Cup is jointly hosted by the United States, Mexico, and Canada.", difficulty: "intermediate" },
    { q: "What is the 'Maracanazo'?", options: ["Brazil's 1970 title","Uruguay's shock defeat of host Brazil in the 1950 deciding match","The 1982 final","Argentina's 1978 win"], answer: 1, explanation: "The Maracanazo was Uruguay's stunning win over Brazil in the decisive 1950 match at the Maracana.", difficulty: "expert" },
    { q: "Which player has made the most World Cup appearances all-time?", options: ["Lothar Matthaus","Paolo Maldini","Lionel Messi","Miroslav Klose"], answer: 2, explanation: "Lionel Messi passed Matthaus in the 2022 final, reaching the most World Cup appearances ever.", difficulty: "expert" },
    { q: "Which nation is the only one to play in every World Cup since 1930?", options: ["Italy","Argentina","Germany","Brazil"], answer: 3, explanation: "Brazil is the only country to appear in every World Cup.", difficulty: "expert" },
  ],
  rugby: [
    { q: "How many players are on the field per team in rugby union?", options: ["13","14","15","16"], answer: 2, explanation: "Each rugby union team fields 15 players.", difficulty: "beginner" },
    { q: "How many points is a try worth in rugby union?", options: ["3","4","5","6"], answer: 2, explanation: "A try is worth 5 points.", difficulty: "beginner" },
    { q: "What does URC stand for?", options: ["United Rugby Championship","Universal Rugby Competition","United Rugby Cup","Unified Rugby Confederation"], answer: 0, explanation: "URC is the United Rugby Championship.", difficulty: "beginner" },
    { q: "What is a 'scrum'?", options: ["A high tackle","A restart where the two packs of forwards bind and push for the ball","A type of kick","A scoring play"], answer: 1, explanation: "A scrum restarts play after a minor infringement — the forwards bind together and push to win the ball.", difficulty: "beginner" },
    { q: "What is a 'maul' in rugby union?", options: ["A high tackle","A phase where the ball carrier is held up and players from both teams bind on, on their feet","A contested lineout","A collapsed scrum"], answer: 1, explanation: "A maul forms when the ball carrier is held up and teammates and opponents bind on while still on their feet.", difficulty: "intermediate" },
    { q: "Which South African franchise won the inaugural URC title in 2021-22?", options: ["Lions","Sharks","Bulls","Stormers"], answer: 3, explanation: "The Stormers won the first United Rugby Championship in 2021-22.", difficulty: "intermediate" },
    { q: "What does a yellow card mean in rugby union?", options: ["Ejection for the match","A 10-minute sin bin","A 5-minute suspension","A warning only"], answer: 1, explanation: "A yellow card sends a player to the sin bin for 10 minutes.", difficulty: "intermediate" },
    { q: "When a player knocks the ball forward (a 'knock-on'), which team gets the scrum?", options: ["The team that knocked on","The opposing team","The team last touching the ball","The referee decides"], answer: 1, explanation: "A knock-on hands a scrum to the opposing team.", difficulty: "intermediate" },
    { q: "What is 'pod' rugby in modern attacking tactics?", options: ["A fast-break three-man unit","Splitting forwards into small groups across the field to create multiple attack options","A kicking strategy","A defensive formation"], answer: 1, explanation: "Pod-based attack spreads forwards into small groups across the pitch, creating several simultaneous attacking threats.", difficulty: "expert" },
    { q: "What is 'jackling' at the breakdown?", options: ["Kicking from behind the ruck","A turnover technique where a player on their feet steals the ball after a tackle","A maul formation","A counter-rucking move"], answer: 1, explanation: "Jackling is contesting the ball over a tackled player while staying on your feet — risky, since being off your feet concedes a penalty.", difficulty: "expert" },
    { q: "What is a 'drift defense'?", options: ["Defenders pushing outward toward the touchline to deny space","Cover defense drifting to the ball carrier","A rush-up blitz","A maul defense"], answer: 0, explanation: "In a drift defense, defenders slide outward toward the touchline to shut down width and force play into the corner.", difficulty: "expert" },
    { q: "What kind of ball is used in rugby?", options: ["An oval ball with pointy ends","A tiny marble","A flat square","A round bowling ball"], answer: 0, explanation: "Rugby uses an oval ball that looks like a chubby brown rocket you can hug and carry.", difficulty: "kid" },
    { q: "What is the main goal in a rugby game?", options: ["Score more points than the other team","Sit on the grass the longest","Spin in circles","Yell the loudest"], answer: 0, explanation: "Both teams race to a bigger number on the big scoreboard.", difficulty: "kid" },
    { q: "How does a team score a 'try' in rugby?", options: ["By touching the ball down over the other team's goal line","By kicking it into the crowd","By dropping the ball and walking away","By sitting on the ball"], answer: 0, explanation: "A try is carrying the ball over the line and putting it down, like planting a flag on new land.", difficulty: "kid" },
    { q: "Where do rugby teams play?", options: ["On a big grassy field","On an icy rink","On a sandy beach","On a wooden stage"], answer: 0, explanation: "Rugby is played on a big grass field, like a giant backyard made for running.", difficulty: "kid" },
    { q: "What do players mostly use to carry the ball?", options: ["Their hands and arms","Only their feet","Only their head","Only their knees"], answer: 0, explanation: "Players hug the ball with their hands and arms, like carrying a stuffed animal while you run.", difficulty: "kid" },
    { q: "Which way are players allowed to pass the ball to teammates?", options: ["Sideways or backwards","Straight up into the sky","Only straight forward","Only into the crowd"], answer: 0, explanation: "You pass sideways or backwards, like handing a snack to the friend behind you in line.", difficulty: "kid" },
    { q: "Can rugby players run while holding the ball?", options: ["Yes, they can carry it","No, they must roll it","Only if they hop on one foot","Only the referee can carry it"], answer: 0, explanation: "Players carry the ball and zoom forward like they're in a playground chase.", difficulty: "kid" },
    { q: "What do teammates often do with the ball?", options: ["Pass it to each other","Hide it under the grass","Put it in a backpack","Trade it for snacks"], answer: 0, explanation: "Passing is like sharing a toy so the whole team can help.", difficulty: "kid" },
    { q: "What does the other team try to do when someone has the ball?", options: ["Stop them safely","Give them a balloon","Move the field away","Sit down and clap"], answer: 0, explanation: "Stopping the runner is like a careful game of tag with rules.", difficulty: "kid" },
    { q: "What are the tall H-shaped posts at each end of the field called?", options: ["Goalposts","Tree trunks","Flag poles","Ladders"], answer: 0, explanation: "The tall H-shaped posts are the goalposts — like giant doors you try to kick the ball through.", difficulty: "kid" },
    { q: "What happens when a player kicks the ball through the goalposts?", options: ["Their team scores points","The game ends right away","Everyone must sit down","The ball isn't allowed anymore"], answer: 0, explanation: "Kicking it through the posts scores points, like winning bonus stars.", difficulty: "kid" },
    { q: "What happens after a team scores a try?", options: ["They may get a special kick for extra points","Everyone switches to basketball","The ball turns blue","The game ends"], answer: 0, explanation: "After a try, the team may try a kick for extra points, like a bonus round.", difficulty: "kid" },
    { q: "How many players are on the field for one rugby union team?", options: ["Fifteen","Three","Nine","Twenty"], answer: 0, explanation: "Fifteen players per team, like a whole class split into two big squads.", difficulty: "kid" },
    { q: "What do rugby players wear on their feet to grip the grass?", options: ["Cleats","Ice skates","Slippers","Swim fins"], answer: 0, explanation: "Cleats have little grips underneath, like tiny teeth for the field.", difficulty: "kid" },
    { q: "How does a rugby ball bounce?", options: ["In funny, surprising directions","Only straight up every time","Only backward into a box","It can't bounce at all"], answer: 0, explanation: "Because of its oval shape, the ball can bounce like it has a sneaky plan.", difficulty: "kid" },
    { q: "What does a referee do in rugby?", options: ["Helps keep the game fair","Sells popcorn","Paints the goalposts","Chooses everyone's shoes"], answer: 0, explanation: "The referee is like a fair playground helper who watches the action.", difficulty: "kid" },
    { q: "Where did rugby first begin, according to a popular story?", options: ["At Rugby School in England","On a spaceship","Under the ocean","In a treehouse"], answer: 0, explanation: "The story says a kid at Rugby School grabbed the ball and ran — starting a whole new game!", difficulty: "kid" },
  ],
  mlr: [
    { q: "What does MLR stand for?", options: ["Major League Rugby","Major League Rugby Americas","Modern League Rugby","Major League Rugby Union"], answer: 0, explanation: "MLR is Major League Rugby, the top professional rugby union league in the United States.", difficulty: "beginner" },
    { q: "In what year was Major League Rugby founded?", options: ["2014","2016","2018","2020"], answer: 2, explanation: "Major League Rugby was founded in 2018.", difficulty: "beginner" },
    { q: "Which team won the inaugural 2018 MLR championship?", options: ["New Orleans Gold","Seattle Seawolves","San Diego Legion","Rugby United New York"], answer: 1, explanation: "The Seattle Seawolves won the first MLR title in 2018.", difficulty: "beginner" },
    { q: "Which MLR club has won the most championships?", options: ["San Diego Legion","New England Free Jacks","Seattle Seawolves","Houston SaberCats"], answer: 2, explanation: "The Seattle Seawolves are MLR's most decorated club.", difficulty: "intermediate" },
    { q: "What is MLR's 'Global Player Exception'?", options: ["Unlimited international players","A designated slot for one marquee international player outside normal cap rules","An exception for tier-2 nations","A cap exemption for under-23 players"], answer: 1, explanation: "The Global Player Exception lets each club sign one high-profile international player outside the standard salary cap.", difficulty: "intermediate" },
    { q: "What is 'choke tackling' as a defensive strategy?", options: ["Tackling high to dislodge the ball","A tackle that keeps the carrier upright to prevent a ruck and force a turnover","Tackling low to slow play","A wrap tackle near the try line"], answer: 1, explanation: "A choke tackle holds the ball carrier up so no ruck forms, forcing a turnover scrum.", difficulty: "expert" },
  ],
  epl: [
    { q: "How many teams are in the Premier League?", options: ["16","18","20","22"], answer: 2, explanation: "The Premier League has 20 clubs.", difficulty: "beginner" },
    { q: "What does 'relegation' mean?", options: ["Getting promoted","The bottom three teams dropping to the Championship","A points deduction","Losing a cup competition"], answer: 1, explanation: "The bottom three clubs are relegated to the Championship each season.", difficulty: "beginner" },
    { q: "Who has scored the most Premier League goals all-time?", options: ["Frank Lampard","Alan Shearer","Wayne Rooney","Thierry Henry"], answer: 1, explanation: "Alan Shearer holds the record with 260 Premier League goals.", difficulty: "beginner" },
    { q: "In what year was the Premier League founded?", options: ["1985","1988","1992","1996"], answer: 2, explanation: "The Premier League was founded in 1992.", difficulty: "beginner" },
    { q: "Which club went unbeaten across an entire 38-game season?", options: ["Manchester United","Chelsea","Arsenal","Liverpool"], answer: 2, explanation: "Arsenal's 2003-04 'Invincibles' went the whole season undefeated.", difficulty: "intermediate" },
    { q: "Which manager has won the most Premier League titles?", options: ["Pep Guardiola","Jose Mourinho","Arsene Wenger","Sir Alex Ferguson"], answer: 3, explanation: "Sir Alex Ferguson won 13 Premier League titles with Manchester United.", difficulty: "intermediate" },
    { q: "When was VAR fully introduced in the Premier League?", options: ["2017-18","2018-19","2019-20","2020-21"], answer: 2, explanation: "Video Assistant Referee was introduced for the 2019-20 season.", difficulty: "intermediate" },
    { q: "What is the maximum senior squad size a Premier League club can register?", options: ["20","25","28","30"], answer: 1, explanation: "Clubs may register up to 25 senior players.", difficulty: "expert" },
    { q: "What is the Premier League's PSR allowable loss limit?", options: ["35m pounds over 3 years","105m pounds over 3 years","50m pounds per year","200m pounds over 5 years"], answer: 1, explanation: "Profitability and Sustainability Rules cap losses at 105 million pounds over a rolling three-year period.", difficulty: "expert" },
    { q: "What is a 'false nine'?", options: ["A defender who pushes forward","A striker who drops deep into midfield instead of staying up front","A wide winger","A defensive midfielder"], answer: 1, explanation: "A false nine is a center-forward who drops into midfield, dragging defenders out of position.", difficulty: "expert" },
  ],
  laliga: [
    { q: "Which club has won the most La Liga titles?", options: ["FC Barcelona","Atletico Madrid","Valencia","Real Madrid"], answer: 3, explanation: "Real Madrid has won the most La Liga titles in history.", difficulty: "beginner" },
    { q: "What is 'El Clasico'?", options: ["A cup final","The match between Real Madrid and FC Barcelona","Any Madrid derby","The Copa del Rey final"], answer: 1, explanation: "El Clasico is the storied match between Real Madrid and Barcelona.", difficulty: "beginner" },
    { q: "Who is La Liga's all-time top scorer?", options: ["Raul","Alfredo Di Stefano","Lionel Messi","Cristiano Ronaldo"], answer: 2, explanation: "Lionel Messi is La Liga's all-time leading scorer with 474 goals.", difficulty: "beginner" },
    { q: "Which manager led Barcelona's tiki-taka era to four straight La Liga titles?", options: ["Louis van Gaal","Frank Rijkaard","Pep Guardiola","Johan Cruyff"], answer: 2, explanation: "Pep Guardiola won four consecutive La Liga titles at Barcelona from 2008 to 2012.", difficulty: "intermediate" },
    { q: "Who scored a record 50 La Liga goals in a single season?", options: ["Cristiano Ronaldo","Hugo Sanchez","Lionel Messi","Ronaldo Nazario"], answer: 2, explanation: "Messi scored 50 La Liga goals in 2011-12, a single-season record.", difficulty: "intermediate" },
    { q: "What principle underlies Johan Cruyff's 'Total Football'?", options: ["Defensive solidity and counter-attacking","Every outfield player can play any position, rotating constantly","A high-pressing 4-4-2","A 5-3-2 defensive system"], answer: 1, explanation: "Total Football holds that any outfield player can fluidly take over any teammate's position.", difficulty: "expert" },
    { q: "What is a 'half-space' in positional play?", options: ["The area just inside the sideline","The zone between the central and wide lanes, ideal for creating overloads","The area behind the defensive line","The zone between the penalty areas"], answer: 1, explanation: "Half-spaces are the channels between center and flank, prized for creating overloads and pulling defenses apart.", difficulty: "expert" },
    { q: "What does 'juego de posicion' (positional play) describe?", options: ["Counter-attacking football","Controlling space through positional and numerical superiority in specific zones","A high defensive line","Front-line pressing"], answer: 1, explanation: "Juego de posicion focuses on occupying and controlling zones to create superiority rather than chasing the ball.", difficulty: "expert" },
  ],
  tennis: [
    { q: "What are the four Grand Slam tournaments?", options: ["Australian Open, French Open, Wimbledon, US Open","Australian Open, French Open, Queen's Club, US Open","Australian Open, French Open, Wimbledon, Davis Cup","Australian Open, French Open, Wimbledon, ATP Finals"], answer: 0, explanation: "The four Grand Slams are the Australian Open, French Open, Wimbledon, and US Open.", difficulty: "beginner" },
    { q: "What surface is Wimbledon played on?", options: ["Clay","Hard court","Grass","Carpet"], answer: 2, explanation: "Wimbledon is played on grass — the oldest and fastest surface.", difficulty: "beginner" },
    { q: "What does 'love' mean in tennis?", options: ["A score of 1","A score of 15","Zero points","A tie"], answer: 2, explanation: "'Love' means zero — a score of nil in the current game.", difficulty: "beginner" },
    { q: "What is a 'bagel' in tennis slang?", options: ["A 7-6 tiebreak win","Winning a set 6-0","Losing in straight sets","A perfect service game"], answer: 1, explanation: "Winning a set 6-0 is a 'bagel' — the zero looks like one.", difficulty: "beginner" },
    { q: "Who holds the all-time record for most men's Grand Slam singles titles?", options: ["Roger Federer","Rafael Nadal","Novak Djokovic","Pete Sampras"], answer: 2, explanation: "Novak Djokovic leads the men with 24 Grand Slam singles titles.", difficulty: "intermediate" },
    { q: "Who holds the women's record for most Grand Slam singles titles?", options: ["Serena Williams","Steffi Graf","Margaret Court","Martina Navratilova"], answer: 2, explanation: "Margaret Court holds the all-time record with 24 Grand Slam singles titles.", difficulty: "intermediate" },
    { q: "Which player completed the 'Golden Slam' in 1988?", options: ["Martina Navratilova","Chris Evert","Steffi Graf","Monica Seles"], answer: 2, explanation: "Steffi Graf won all four Grand Slams plus Olympic gold in 1988 — the only singles Golden Slam.", difficulty: "intermediate" },
    { q: "What is the ATP Finals?", options: ["The year-end event for the top 8 ranked players","ATP's version of the French Open","A team tournament","A wildcard tournament"], answer: 0, explanation: "The ATP Finals is the season-ending championship for the top 8 singles players.", difficulty: "intermediate" },
    { q: "What is a 'super tiebreak' and when is it used?", options: ["A 7-point tiebreak in every final set","A 10-point tiebreak replacing a full final set at certain tournaments","A 12-point tiebreak only at Wimbledon","An exhibition format"], answer: 1, explanation: "A super tiebreak (first to 10, win by 2) decides the final set at several majors instead of a full set.", difficulty: "expert" },
    { q: "What does the Eastern vs. Western grip distinction signify?", options: ["Eastern is grass-era only; Western is modern","Eastern produces flatter shots for fast surfaces; Western creates heavy topspin suited to clay","They're interchangeable","Western for serves, Eastern for groundstrokes"], answer: 1, explanation: "The shift from Eastern to Western grips mirrors tennis's move toward heavy topspin baseline play.", difficulty: "expert" },
    { q: "What does the 'dominance ratio' measure in tennis analytics?", options: ["Aces divided by double faults","A combined measure of service and return points won, indicating overall control of a match","Head-to-head record","Percentage of sets won after winning the first"], answer: 1, explanation: "The dominance ratio blends service and return points won — above 100 signals near-total control of a match.", difficulty: "expert" },
    { q: "What kind of sport is tennis?", options: ["A game where players hit a ball over a net","A game where players swim in a pool","A game where players climb trees","A game where players drive cars"], answer: 0, explanation: "Tennis is hitting a ball over a net, like a fun game of catch with extra bounces.", difficulty: "kid" },
    { q: "What do players use to hit the ball?", options: ["A tennis racket","A hockey stick","A golf club","A wooden spoon"], answer: 0, explanation: "A racket is like a big net-on-a-handle that helps send the ball back.", difficulty: "kid" },
    { q: "What does a tennis ball look like?", options: ["A small, bouncy fuzzy yellow ball","A giant beach ball","A square rubber block","A heavy bowling ball"], answer: 0, explanation: "Tennis balls are light, fuzzy, and bouncy — like tiny springy lemons.", difficulty: "kid" },
    { q: "What is the net in the middle of the court for?", options: ["Players hit the ball over it","Players sit on it","Players hide under it","Players use it as a blanket"], answer: 0, explanation: "The net is like a little wall the ball has to fly over.", difficulty: "kid" },
    { q: "How does a tennis point start?", options: ["One player serves the ball","A player throws a shoe","The referee rolls dice","The crowd kicks the ball"], answer: 0, explanation: "A serve is the first hit, like pressing start on a game.", difficulty: "kid" },
    { q: "Where do players try to land the ball to win a point?", options: ["Inside the other player's side of the court","In the crowd's seats","Over the fence","At the umpire's chair"], answer: 0, explanation: "They aim to land it inside the other side's lines, like dropping a toy right on a target.", difficulty: "kid" },
    { q: "What happens when the ball bounces outside the lines?", options: ["It is out","It becomes two balls","The court turns blue","Everyone switches rackets"], answer: 0, explanation: "The lines are the court's border, so outside means the ball went too far.", difficulty: "kid" },
    { q: "What is the flat area where tennis is played called?", options: ["A court","A swimming lane","A forest trail","A ski slope"], answer: 0, explanation: "Tennis is played on a court, like a big flat playground with painted lines.", difficulty: "kid" },
    { q: "What do players try to do during a rally?", options: ["Hit the ball back and forth","Build a tower of balls","Carry the net away","Run in the stands"], answer: 0, explanation: "A rally is a friendly back-and-forth, like ping pong with bigger paddles.", difficulty: "kid" },
    { q: "What is it called when two players play against each other?", options: ["Singles","Twins","Crowd time","Snack break"], answer: 0, explanation: "Singles means one player on each side, like a one-on-one challenge.", difficulty: "kid" },
    { q: "What is it called when two players team up on each side?", options: ["Doubles","Solo play","Hide-and-seek","Three-ball"], answer: 0, explanation: "Doubles means partners work together, like teammates in a playground game.", difficulty: "kid" },
    { q: "Why do tennis players move their feet so much?", options: ["To get ready to hit the ball","To make music with their shoes","To chase butterflies","To sweep the court"], answer: 0, explanation: "Quick feet help players meet the ball, like racing to catch a bouncing balloon.", difficulty: "kid" },
    { q: "Why is it good for kids to use smaller rackets?", options: ["So the racket fits their size and is easy to swing","So they can't hit the ball at all","So it's too heavy to lift","So they must drag it on the ground"], answer: 0, explanation: "A smaller racket feels just right in their hand, like a bike that fits their size.", difficulty: "kid" },
    { q: "What happens if a player hits the ball and the other can't hit it back in time?", options: ["The hitter wins a point","Both players lose a point","The game stops forever","They restart the match"], answer: 0, explanation: "When the other player misses, you win a point, like tagging someone in tag.", difficulty: "kid" },
    { q: "How fast can some tennis serves go?", options: ["Faster than many cars on a street","As slow as a sleepy turtle","Only as fast as a falling leaf","Slower than a rolling sock"], answer: 0, explanation: "Some serves zoom so fast they look like a bright yellow rocket.", difficulty: "kid" },
  ],
  golf: [
    { q: "What does 'par' mean in golf?", options: ["Maximum score allowed","The expected number of strokes for a skilled golfer on a hole","Minimum score to make the cut","Number of bunkers on a hole"], answer: 1, explanation: "Par is the number of strokes an expert golfer is expected to need on a hole.", difficulty: "beginner" },
    { q: "What is a 'birdie'?", options: ["One over par","One under par on a hole","Two under par","A hole-in-one"], answer: 1, explanation: "A birdie is finishing a hole in one stroke under par.", difficulty: "beginner" },
    { q: "Which major is always played at Augusta National?", options: ["US Open","The Open Championship","The Masters","PGA Championship"], answer: 2, explanation: "The Masters is held at Augusta National every year.", difficulty: "beginner" },
    { q: "What is an 'eagle' in golf?", options: ["One under par","Two under par on a hole","Three under par","A missed putt"], answer: 1, explanation: "An eagle is two strokes under par on a hole.", difficulty: "beginner" },
    { q: "Who holds the record for most men's major championships?", options: ["Arnold Palmer","Ben Hogan","Tiger Woods","Jack Nicklaus"], answer: 3, explanation: "Jack Nicklaus won 18 majors, the men's record.", difficulty: "intermediate" },
    { q: "What is the Ryder Cup?", options: ["A major championship","A biennial team match-play competition between Europe and the USA","An individual stroke-play event","A senior tour event"], answer: 1, explanation: "The Ryder Cup is a team match-play contest held every two years between Europe and the United States.", difficulty: "intermediate" },
    { q: "What does 'GIR' stand for in golf stats?", options: ["Greens in Regulation","Golf Impact Rating","Green Impact Ratio","Game Index Rating"], answer: 0, explanation: "GIR is Greens in Regulation — reaching the green with strokes to spare for two putts.", difficulty: "intermediate" },
    { q: "What is 'smash factor'?", options: ["A golf ball's compression rating","The ratio of ball speed to clubhead speed, measuring energy transfer","Force applied by the grip","Rotational speed of the clubhead"], answer: 1, explanation: "Smash factor is ball speed divided by clubhead speed — about 1.5 is the driver maximum.", difficulty: "expert" },
    { q: "What is 'attack angle' in launch-monitor analytics?", options: ["Clubface angle to the target line","Whether the clubhead is moving up or down at impact","Swing plane at the top of the backswing","Ball launch angle above the horizon"], answer: 1, explanation: "Attack angle is whether the club is ascending or descending at impact — a positive angle maximizes driver carry.", difficulty: "expert" },
    { q: "What was the 'Tiger Slam'?", options: ["Winning all four majors in one calendar year","Holding all four major titles at once across 2000-01","Winning three straight majors","Completing a career Grand Slam"], answer: 1, explanation: "The Tiger Slam was Tiger Woods holding all four major titles simultaneously — three in 2000, the Masters in 2001.", difficulty: "expert" },
    { q: "What kind of game is golf?", options: ["A game where you hit a small ball into holes","Swimming in a pool","Climbing tall trees","Riding bikes in circles"], answer: 0, explanation: "Golf is hitting a tiny ball into holes, like a long outdoor treasure hunt.", difficulty: "kid" },
    { q: "What do golfers use to hit the ball?", options: ["A golf club","A hockey stick","A tennis racket","A baseball glove"], answer: 0, explanation: "A golf club is like a special stick made just for sending the ball forward.", difficulty: "kid" },
    { q: "What does a golf ball look like?", options: ["A small white ball with tiny dimples","A giant square block","A long flat stick","A fuzzy tennis ball"], answer: 0, explanation: "Golf balls are small and bumpy, like little white planets covered in craters.", difficulty: "kid" },
    { q: "What is the goal in golf?", options: ["Get the ball into each hole in as few hits as possible","Hit the ball as many times as you can","Keep the ball in your pocket","Throw the club the farthest"], answer: 0, explanation: "In golf you want fewer swings, like finishing a level using the fewest moves.", difficulty: "kid" },
    { q: "What is the big grassy place where golf is played called?", options: ["A golf course","A rink","A court","A dugout"], answer: 0, explanation: "A golf course is like a giant outdoor puzzle with grass, sand, and holes.", difficulty: "kid" },
    { q: "What does a golfer stand the ball on for the first hit on many holes?", options: ["A tee","A spoon","A pillow","A skate"], answer: 0, explanation: "A tee is like a tiny stand that holds the ball up for its big start.", difficulty: "kid" },
    { q: "What is the first shot on each hole, hit off the tee, called?", options: ["A tee shot","A splash shot","A sky jump","A home run"], answer: 0, explanation: "The tee shot is your opening swing, like pressing start on a new level.", difficulty: "kid" },
    { q: "What is a putt?", options: ["A gentle hit near the hole","A jump into water","A kick with your foot","A throw to a teammate"], answer: 0, explanation: "A putt is a soft little roll, like tucking the ball into bed inside the hole.", difficulty: "kid" },
    { q: "What is the flag near the hole for?", options: ["To show where the hole is","To make music","To scare birds","To hold snacks"], answer: 0, explanation: "The flag is like a bright sign saying 'Aim over here!'", difficulty: "kid" },
    { q: "What might happen if a golf ball lands in sand?", options: ["The golfer hits it out of the sand","The ball turns into a shell","The game becomes beach volleyball","Everyone stops playing"], answer: 0, explanation: "Golfers rescue the ball from the sand, like helping a toy out of a sandbox.", difficulty: "kid" },
    { q: "What do golfers shout when a ball might fly near people?", options: ["Fore!","Bingo!","Splash!","Zoomie!"], answer: 0, explanation: "'Fore!' is a warning word that means 'Watch out, a ball is coming!'", difficulty: "kid" },
    { q: "What happens if you hit the ball into the hole in one swing on a short hole?", options: ["You made a hole in one","You start over","You lose all your points","You give your club away"], answer: 0, explanation: "A hole in one is like beating a whole level in one perfect move.", difficulty: "kid" },
    { q: "How do golfers keep score?", options: ["They count every hit and try for the smallest number","They count how many times they shout","They count trees they see","They add points for every miss"], answer: 0, explanation: "Golfers add up their swings — the smallest total wins, so the lowest number is the champion.", difficulty: "kid" },
    { q: "Why is it good for kids to use smaller clubs?", options: ["So the clubs are light and easy to swing","So they drag on the ground","So they can't lift them","So they need two people to swing"], answer: 0, explanation: "Right-size clubs feel comfy, like shoes that fit instead of your parent's giant boots.", difficulty: "kid" },
    { q: "How far can some golfers hit the ball?", options: ["Farther than several playgrounds","Only as far as a pencil","Just one tiny step","Not past their shoes"], answer: 0, explanation: "A big golf hit can send the ball flying across the grass like a tiny moon.", difficulty: "kid" },
    { q: "Why do golfers look carefully before they hit?", options: ["To aim at the right place","To count every cloud","To pick a dance move","To find hidden candy"], answer: 0, explanation: "Aiming helps golfers plan the ball's path, like planning a turn in a maze.", difficulty: "kid" },
    { q: "What's a cool fact about how long golf has been around?", options: ["People have played golf for hundreds of years","Golf was invented last week","Golf started after video games","Golf came from outer space"], answer: 0, explanation: "Golf is an old game played for centuries — a classic people still love today.", difficulty: "kid" },
  ],
  cricket: [
    { q: "How many players are in a cricket team?", options: ["9","10","11","12"], answer: 2, explanation: "A cricket team has 11 players.", difficulty: "beginner" },
    { q: "How many runs is a ball hit over the boundary without bouncing worth?", options: ["4","5","6","8"], answer: 2, explanation: "Clearing the boundary on the full scores 6 runs; along the ground it's 4.", difficulty: "beginner" },
    { q: "What does 'LBW' stand for?", options: ["Left Behind Wicket","Leg Before Wicket","Lower Body Warning","Last Ball Win"], answer: 1, explanation: "LBW is Leg Before Wicket — out when the ball would have hit the stumps but struck the batter's leg first.", difficulty: "beginner" },
    { q: "What is the 'Ashes'?", options: ["A T20 competition","A Test cricket series between England and Australia","A World Cup qualifier","A domestic English competition"], answer: 1, explanation: "The Ashes is the historic Test series between England and Australia.", difficulty: "intermediate" },
    { q: "What is Don Bradman's Test batting average, the highest in history?", options: ["89.78","92.34","99.94","105.62"], answer: 2, explanation: "Don Bradman averaged 99.94 in Test cricket — a record many consider unbeatable.", difficulty: "intermediate" },
    { q: "Who holds the record for most Test wickets?", options: ["Shane Warne","Glenn McGrath","Muttiah Muralitharan","James Anderson"], answer: 2, explanation: "Muttiah Muralitharan took 800 Test wickets, the all-time record.", difficulty: "intermediate" },
    { q: "What is a 'doosra' in spin bowling?", options: ["A faster off-break","An off-spinner's delivery that turns the opposite way with the same action","A top-spinning googly","A reverse-spinning leg-break"], answer: 1, explanation: "The doosra spins opposite to a normal off-break while looking identical out of the hand, deceiving the batter.", difficulty: "expert" },
    { q: "What does the Duckworth-Lewis-Stern method calculate?", options: ["A bowling economy rate","Revised target scores for rain-shortened limited-overs matches","Batting averages across formats","Net run rate"], answer: 1, explanation: "The DLS method recalculates a fair target when rain cuts overs from a limited-overs match.", difficulty: "expert" },
    { q: "Under the laws of cricket, what is the penalty for ball tampering?", options: ["Warning only for a first offense","A 5-run penalty to the batting side and ball replacement","Match forfeiture","Automatic captain suspension"], answer: 1, explanation: "Illegally altering the ball gives the batting side 5 penalty runs and the ball is changed.", difficulty: "expert" },
    { q: "What kind of game is cricket?", options: ["A bat-and-ball game between two teams","A swimming race","A snowball fight","A bike race"], answer: 0, explanation: "Cricket is a team game with a bat and ball, like a long backyard game with friends.", difficulty: "kid" },
    { q: "What do cricket players use to hit the ball?", options: ["A flat bat","A hockey stick","A golf club","A tennis net"], answer: 0, explanation: "A cricket bat is flat, like a paddle made for sending the ball zooming.", difficulty: "kid" },
    { q: "What does the bowler do?", options: ["Throws the ball toward the batter","Guards the snack table","Counts the clouds","Carries the scoreboard"], answer: 0, explanation: "The bowler starts the action by sending the ball toward the batter, aiming at a tiny target.", difficulty: "kid" },
    { q: "What does the batter try to do?", options: ["Hit the ball and score runs","Hide the bat","Kick the ball into a net","Sit on the grass"], answer: 0, explanation: "The batter hits the ball and helps the team score, like collecting points in a game.", difficulty: "kid" },
    { q: "What are runs in cricket?", options: ["Points a team scores","Shoes players wear","Clouds over the field","Songs fans sing"], answer: 0, explanation: "Runs are cricket points, and teams try to collect lots of them.", difficulty: "kid" },
    { q: "How can a batter score by running?", options: ["Run back and forth between the wickets","Run to the parking lot","Run around the crowd","Run behind the snack stand"], answer: 0, explanation: "Batters dash between the wickets, like racing between two cones in gym class.", difficulty: "kid" },
    { q: "What are the three sticks behind the batter called?", options: ["Stumps","Branches","Pencils","Towers"], answer: 0, explanation: "Stumps are like a tiny wooden castle the bowler tries to knock over.", difficulty: "kid" },
    { q: "What happens if the ball knocks over the stumps?", options: ["The batter is out","The ball gets a medal","The game turns into soccer","Everyone changes hats"], answer: 0, explanation: "Knocking the stumps is a big win for the bowling team.", difficulty: "kid" },
    { q: "What do fielders try to do after the ball is hit?", options: ["Catch or stop the ball","Paint the bat","Move the clouds","Build a sandcastle"], answer: 0, explanation: "Fielders chase the ball like quick helpers trying to stop extra points.", difficulty: "kid" },
    { q: "What happens if a fielder catches the ball before it touches the ground?", options: ["The batter is out","The batter gets a crown","The ball disappears","The crowd must whisper"], answer: 0, explanation: "A catch is like grabbing a flying treasure before it lands.", difficulty: "kid" },
    { q: "What is the long rectangle in the middle of the field called?", options: ["The pitch","The pool","The tunnel","The bench"], answer: 0, explanation: "The pitch is the strip where most of the action happens, like the main stage in a play.", difficulty: "kid" },
    { q: "Where is cricket usually played?", options: ["On a big grass field","On an ice rink","In a swimming pool","On a tiny table"], answer: 0, explanation: "A cricket field is a big green space with lots of room to run and chase.", difficulty: "kid" },
    { q: "How many players are on one cricket team in a full game?", options: ["Eleven","Three","Seven","Fifteen"], answer: 0, explanation: "Eleven players per team, taking turns to bat and field.", difficulty: "kid" },
    { q: "What do batters wear on their legs for safety?", options: ["Pads","Skates","Flippers","Paper bags"], answer: 0, explanation: "Pads are like soft shields that help protect a batter's legs from the hard ball.", difficulty: "kid" },
    { q: "How many runs is a hit that reaches the boundary along the ground worth?", options: ["Four runs","One run","Zero runs","Ten runs"], answer: 0, explanation: "A ball that rolls or bounces to the edge is worth four runs — a nice bonus in one hit!", difficulty: "kid" },
    { q: "How many runs is a hit over the boundary on the full worth?", options: ["Six runs","One run","Two runs","Zero runs"], answer: 0, explanation: "A big shot that flies over the edge without bouncing is worth six runs, like a super move!", difficulty: "kid" },
    { q: "How fast can some cricket balls be bowled?", options: ["Faster than many cars on a street","As slow as a sleepy snail","Only as fast as a falling leaf","Slower than a walking teddy bear"], answer: 0, explanation: "Some balls zip toward the batter like a tiny red rocket.", difficulty: "kid" },
  ],
};
