import { Sport, Language } from './api';

// Per-sport "Common Questions" — the "new to this sport, start here" entry point.
// Pre-translated into all 10 languages so the entry-point text renders instantly,
// offline, with no runtime API calls. `label` is the full section heading.
//
// NOTE: ja/zh/ko/ar are a v1 first pass and need native review before App Store
// submission (see FEATURE_IDEAS.md).
export type LocalizedText = Record<Language, string>;

// English-first-pass localized text: the same English string in all 10 slots.
// Used for the tennis/golf/cricket FAQ sets — TODO: translate before launch
// (CJK/Arabic especially need native review).
const allEn = (s: string): LocalizedText => ({ en: s, es: s, fr: s, pt: s, de: s, it: s, ja: s, zh: s, ko: s, ar: s });

export interface SportFaq {
  label: LocalizedText;
  questions: LocalizedText[];
}

// Base sports with their own authored question sets. Drop-in leagues below
// reuse these question arrays with their own heading.
const BASE_FAQS = {
  mlb: {
    label: {
      en: `Common Baseball Questions`,
      es: `Preguntas comunes de béisbol`,
      fr: `Questions courantes sur le baseball`,
      pt: `Perguntas comuns sobre beisebol`,
      de: `Häufige Fragen zum Baseball`,
      it: `Domande comuni sul baseball`,
      ja: `野球のよくある質問`,
      zh: `棒球常见问题`,
      ko: `야구 자주 묻는 질문`,
      ar: `أسئلة شائعة عن البيسبول`,
    },
    questions: [
      {
        en: `What's the difference between a ball and a strike?`,
        es: `¿Cuál es la diferencia entre una bola y un strike?`,
        fr: `Quelle est la différence entre une balle et une prise (strike) ?`,
        pt: `Qual é a diferença entre uma bola e um strike?`,
        de: `Was ist der Unterschied zwischen einem Ball und einem Strike?`,
        it: `Qual è la differenza tra un "ball" e uno "strike"?`,
        ja: `ボールとストライクの違いは何ですか？`,
        zh: `坏球和好球有什么区别？`,
        ko: `볼과 스트라이크의 차이는 무엇인가요?`,
        ar: `ما الفرق بين الكرة (ball) والضربة (strike)؟`,
      },
      {
        en: `What does it mean to strike out?`,
        es: `¿Qué significa ponchar (strike out)?`,
        fr: `Que signifie « être retiré sur des prises » (strike out) ?`,
        pt: `O que significa ser eliminado por strikes (strike out)?`,
        de: `Was bedeutet es, "auszustriken" (strike out)?`,
        it: `Cosa significa essere eliminati con tre strike (strike out)?`,
        ja: `三振とはどういう意味ですか？`,
        zh: `三振出局是什么意思？`,
        ko: `삼진 아웃은 무슨 뜻인가요?`,
        ar: `ماذا يعني الخروج بالضربات (strike out)؟`,
      },
      {
        en: `What's an RBI?`,
        es: `¿Qué es una carrera impulsada (RBI)?`,
        fr: `Qu'est-ce qu'un point produit (RBI) ?`,
        pt: `O que é uma corrida impulsionada (RBI)?`,
        de: `Was ist ein RBI (erzielter Run)?`,
        it: `Che cos'è un RBI (punto battuto a casa)?`,
        ja: `打点（RBI）とは何ですか？`,
        zh: `什么是打点（RBI）？`,
        ko: `타점(RBI)이란 무엇인가요?`,
        ar: `ما هو الـ RBI (الركضة المنتجة)؟`,
      },
      {
        en: `What's the infield fly rule?`,
        es: `¿Qué es la regla del fly del cuadro interior (infield fly)?`,
        fr: `Qu'est-ce que la règle du « infield fly » (chandelle dans le champ intérieur) ?`,
        pt: `O que é a regra do "infield fly" (voadora no campo interno)?`,
        de: `Was ist die Infield-Fly-Regel?`,
        it: `Che cos'è la regola dell'infield fly?`,
        ja: `インフィールドフライのルールとは何ですか？`,
        zh: `什么是内野高飞球规则（infield fly）？`,
        ko: `인필드 플라이 규칙이란 무엇인가요?`,
        ar: `ما هي قاعدة "إنفيلد فلاي" (الكرة الطائرة في الملعب الداخلي)؟`,
      },
      {
        en: `What does a "full count" mean?`,
        es: `¿Qué significa una "cuenta llena" (full count)?`,
        fr: `Que signifie un « compte plein » (full count) ?`,
        pt: `O que significa uma "contagem cheia" (full count)?`,
        de: `Was bedeutet ein "Full Count"?`,
        it: `Cosa significa un "full count" (conteggio pieno)?`,
        ja: `「フルカウント」とはどういう意味ですか？`,
        zh: `“满球数”（full count）是什么意思？`,
        ko: `"풀카운트"는 무슨 뜻인가요?`,
        ar: `ماذا يعني "العد الكامل" (full count)؟`,
      },
      {
        en: `Why do pitchers get taken out of the game?`,
        es: `¿Por qué sacan a los lanzadores del juego?`,
        fr: `Pourquoi remplace-t-on les lanceurs en cours de match ?`,
        pt: `Por que os arremessadores são tirados do jogo?`,
        de: `Warum werden Pitcher während des Spiels ausgewechselt?`,
        it: `Perché i lanciatori vengono tolti dalla partita?`,
        ja: `なぜ投手は試合の途中で交代するのですか？`,
        zh: `为什么投手会被换下场？`,
        ko: `투수는 왜 경기 도중 교체되나요?`,
        ar: `لماذا يتم إخراج الرماة (pitchers) من المباراة؟`,
      },
      {
        en: `How long is a game — what's an inning?`,
        es: `¿Cuánto dura un partido? ¿Qué es una entrada (inning)?`,
        fr: `Combien de temps dure un match — qu'est-ce qu'une manche (inning) ?`,
        pt: `Quanto tempo dura um jogo — o que é uma entrada (inning)?`,
        de: `Wie lange dauert ein Spiel – was ist ein Inning?`,
        it: `Quanto dura una partita? Che cos'è un inning?`,
        ja: `試合はどのくらいの長さですか？イニングとは何ですか？`,
        zh: `一场比赛多长？什么是一局（inning）？`,
        ko: `경기는 얼마나 길고, 이닝이란 무엇인가요?`,
        ar: `كم تدوم المباراة؟ وما هو الشوط (inning)؟`,
      },
    ],
  },

  nfl: {
    label: {
      en: `Common Football Questions`,
      es: `Preguntas comunes de fútbol americano`,
      fr: `Questions courantes sur le football américain`,
      pt: `Perguntas comuns sobre futebol americano`,
      de: `Häufige Fragen zum American Football`,
      it: `Domande comuni sul football americano`,
      ja: `アメフトのよくある質問`,
      zh: `美式橄榄球常见问题`,
      ko: `미식축구 자주 묻는 질문`,
      ar: `أسئلة شائعة عن كرة القدم الأمريكية`,
    },
    questions: [
      {
        en: `What does "1st and 10" mean?`,
        es: `¿Qué significa "1.º y 10" (1st and 10)?`,
        fr: `Que signifie « 1st and 10 » (1er essai et 10 yards) ?`,
        pt: `O que significa "1st and 10" (1ª descida e 10 jardas)?`,
        de: `Was bedeutet "1st and 10" (1. Versuch und 10 Yards)?`,
        it: `Cosa significa "1st and 10" (1º down e 10 yard)?`,
        ja: `「1stアンド10」とはどういう意味ですか？`,
        zh: `“第一档10码”（1st and 10）是什么意思？`,
        ko: `"1st and 10"은 무슨 뜻인가요?`,
        ar: `ماذا يعني "1st and 10" (المحاولة الأولى و10 ياردات)؟`,
      },
      {
        en: `What's the difference between a touchdown and a field goal?`,
        es: `¿Cuál es la diferencia entre un touchdown y un gol de campo (field goal)?`,
        fr: `Quelle est la différence entre un touchdown et un field goal ?`,
        pt: `Qual é a diferença entre um touchdown e um field goal?`,
        de: `Was ist der Unterschied zwischen einem Touchdown und einem Field Goal?`,
        it: `Qual è la differenza tra un touchdown e un field goal?`,
        ja: `タッチダウンとフィールドゴールの違いは何ですか？`,
        zh: `达阵（touchdown）和射门得分（field goal）有什么区别？`,
        ko: `터치다운과 필드골의 차이는 무엇인가요?`,
        ar: `ما الفرق بين التاتشداون (touchdown) والهدف الميداني (field goal)؟`,
      },
      {
        en: `Why do teams punt the ball away?`,
        es: `¿Por qué los equipos despejan el balón (punt)?`,
        fr: `Pourquoi les équipes dégagent-elles le ballon (punt) ?`,
        pt: `Por que os times chutam a bola para o outro lado (punt)?`,
        de: `Warum punten Teams den Ball weg?`,
        it: `Perché le squadre calciano via il pallone (punt)?`,
        ja: `なぜチームはボールをパント（punt）で蹴るのですか？`,
        zh: `球队为什么要弃踢（punt）把球踢走？`,
        ko: `팀은 왜 공을 펀트(punt)로 차 보내나요?`,
        ar: `لماذا تركل الفرق الكرة بعيدًا (punt)؟`,
      },
      {
        en: `What's a turnover?`,
        es: `¿Qué es una pérdida de balón (turnover)?`,
        fr: `Qu'est-ce qu'un revirement (turnover) ?`,
        pt: `O que é uma perda de posse (turnover)?`,
        de: `Was ist ein Turnover (Ballverlust)?`,
        it: `Che cos'è un turnover (perdita di palla)?`,
        ja: `ターンオーバーとは何ですか？`,
        zh: `什么是失误转换（turnover）？`,
        ko: `턴오버란 무엇인가요?`,
        ar: `ما هو فقدان الاستحواذ (turnover)؟`,
      },
      {
        en: `What does the quarterback actually do?`,
        es: `¿Qué hace exactamente el mariscal de campo (quarterback)?`,
        fr: `Que fait exactement le quarterback ?`,
        pt: `O que o quarterback realmente faz?`,
        de: `Was macht der Quarterback eigentlich?`,
        it: `Che cosa fa esattamente il quarterback?`,
        ja: `クォーターバックは実際に何をするのですか？`,
        zh: `四分卫（quarterback）到底是做什么的？`,
        ko: `쿼터백은 실제로 무슨 일을 하나요?`,
        ar: `ماذا يفعل الكوارتربك (quarterback) فعليًا؟`,
      },
      {
        en: `What's a sack?`,
        es: `¿Qué es una captura del mariscal (sack)?`,
        fr: `Qu'est-ce qu'un sack (plaquage du quarterback) ?`,
        pt: `O que é um sack (derrubar o quarterback)?`,
        de: `Was ist ein Sack?`,
        it: `Che cos'è un sack?`,
        ja: `サックとは何ですか？`,
        zh: `什么是擒杀（sack）？`,
        ko: `색(sack)이란 무엇인가요?`,
        ar: `ما هو الـ "ساك" (sack)؟`,
      },
      {
        en: `What's the difference between offense and defense?`,
        es: `¿Cuál es la diferencia entre el ataque (ofensiva) y la defensa?`,
        fr: `Quelle est la différence entre l'attaque et la défense ?`,
        pt: `Qual é a diferença entre o ataque e a defesa?`,
        de: `Was ist der Unterschied zwischen Offense und Defense?`,
        it: `Qual è la differenza tra attacco e difesa?`,
        ja: `オフェンスとディフェンスの違いは何ですか？`,
        zh: `进攻和防守有什么区别？`,
        ko: `공격과 수비의 차이는 무엇인가요?`,
        ar: `ما الفرق بين الهجوم والدفاع؟`,
      },
    ],
  },

  nba: {
    label: {
      en: `Common Basketball Questions`,
      es: `Preguntas comunes de baloncesto`,
      fr: `Questions courantes sur le basket-ball`,
      pt: `Perguntas comuns sobre basquete`,
      de: `Häufige Fragen zum Basketball`,
      it: `Domande comuni sul basket`,
      ja: `バスケットボールのよくある質問`,
      zh: `篮球常见问题`,
      ko: `농구 자주 묻는 질문`,
      ar: `أسئلة شائعة عن كرة السلة`,
    },
    questions: [
      {
        en: `What's the shot clock and why does it matter?`,
        es: `¿Qué es el reloj de tiro y por qué es importante?`,
        fr: `Qu'est-ce que le chronomètre des tirs (shot clock) et pourquoi est-il important ?`,
        pt: `O que é o relógio de arremesso (shot clock) e por que ele importa?`,
        de: `Was ist die Wurfuhr (Shot Clock) und warum ist sie wichtig?`,
        it: `Che cos'è il cronometro dei tiri (shot clock) e perché è importante?`,
        ja: `ショットクロックとは何で、なぜ重要なのですか？`,
        zh: `什么是进攻时限（shot clock），它为什么重要？`,
        ko: `샷 클락이란 무엇이고 왜 중요한가요?`,
        ar: `ما هي ساعة التسديد (shot clock) ولماذا هي مهمة؟`,
      },
      {
        en: `What's the difference between a 2-pointer and a 3-pointer?`,
        es: `¿Cuál es la diferencia entre un tiro de 2 puntos y uno de 3 puntos?`,
        fr: `Quelle est la différence entre un tir à 2 points et un tir à 3 points ?`,
        pt: `Qual é a diferença entre uma cesta de 2 pontos e uma de 3 pontos?`,
        de: `Was ist der Unterschied zwischen einem 2-Punkte- und einem 3-Punkte-Wurf?`,
        it: `Qual è la differenza tra un tiro da 2 punti e uno da 3 punti?`,
        ja: `2ポイントシュートと3ポイントシュートの違いは何ですか？`,
        zh: `两分球和三分球有什么区别？`,
        ko: `2점슛과 3점슛의 차이는 무엇인가요?`,
        ar: `ما الفرق بين التسديدة الثنائية والثلاثية؟`,
      },
      {
        en: `What's a foul, and when do you get free throws?`,
        es: `¿Qué es una falta y cuándo se lanzan tiros libres?`,
        fr: `Qu'est-ce qu'une faute, et quand obtient-on des lancers francs ?`,
        pt: `O que é uma falta e quando se ganham lances livres?`,
        de: `Was ist ein Foul, und wann gibt es Freiwürfe?`,
        it: `Che cos'è un fallo e quando si tirano i tiri liberi?`,
        ja: `ファウルとは何で、いつフリースローが与えられますか？`,
        zh: `什么是犯规？什么时候罚球？`,
        ko: `파울이란 무엇이고 언제 자유투를 얻나요?`,
        ar: `ما هي المخالفة، ومتى تحصل على الرميات الحرة؟`,
      },
      {
        en: `What does "in the paint" mean?`,
        es: `¿Qué significa "en la pintura" (in the paint)?`,
        fr: `Que signifie « dans la raquette » (in the paint) ?`,
        pt: `O que significa "no garrafão" (in the paint)?`,
        de: `Was bedeutet "in the paint" (in der Zone)?`,
        it: `Cosa significa "in the paint" (in area)?`,
        ja: `「ペイントエリア内」とはどういう意味ですか？`,
        zh: `“油漆区内”（in the paint）是什么意思？`,
        ko: `"페인트 존 안"이란 무슨 뜻인가요?`,
        ar: `ماذا تعني عبارة "داخل المنطقة" (in the paint)؟`,
      },
      {
        en: `What's a pick-and-roll?`,
        es: `¿Qué es un bloqueo y continuación (pick-and-roll)?`,
        fr: `Qu'est-ce qu'un pick-and-roll (écran et glissement) ?`,
        pt: `O que é um pick-and-roll (bloqueio e rolagem)?`,
        de: `Was ist ein Pick-and-Roll?`,
        it: `Che cos'è un pick-and-roll (blocco e taglio)?`,
        ja: `ピック・アンド・ロールとは何ですか？`,
        zh: `什么是挡拆（pick-and-roll）？`,
        ko: `픽 앤 롤이란 무엇인가요?`,
        ar: `ما هو الـ "بيك أند رول" (pick-and-roll)؟`,
      },
      {
        en: `What's a turnover?`,
        es: `¿Qué es una pérdida de balón (turnover)?`,
        fr: `Qu'est-ce qu'une perte de balle (turnover) ?`,
        pt: `O que é um turnover (perda de bola)?`,
        de: `Was ist ein Turnover (Ballverlust)?`,
        it: `Che cos'è un turnover (palla persa)?`,
        ja: `ターンオーバーとは何ですか？`,
        zh: `什么是失误（turnover）？`,
        ko: `턴오버란 무엇인가요?`,
        ar: `ما هو فقدان الكرة (turnover)؟`,
      },
      {
        en: `What's a double-double?`,
        es: `¿Qué es un doble-doble (double-double)?`,
        fr: `Qu'est-ce qu'un double-double ?`,
        pt: `O que é um duplo-duplo (double-double)?`,
        de: `Was ist ein Double-Double?`,
        it: `Che cos'è un double-double?`,
        ja: `ダブルダブルとは何ですか？`,
        zh: `什么是两双（double-double）？`,
        ko: `더블더블이란 무엇인가요?`,
        ar: `ما هو الـ "دابل دابل" (double-double)؟`,
      },
    ],
  },

  nhl: {
    label: {
      en: `Common Hockey Questions`,
      es: `Preguntas comunes de hockey`,
      fr: `Questions courantes sur le hockey`,
      pt: `Perguntas comuns sobre hóquei`,
      de: `Häufige Fragen zum Eishockey`,
      it: `Domande comuni sull'hockey`,
      ja: `アイスホッケーのよくある質問`,
      zh: `冰球常见问题`,
      ko: `아이스하키 자주 묻는 질문`,
      ar: `أسئلة شائعة عن الهوكي`,
    },
    questions: [
      {
        en: `What is icing?`,
        es: `¿Qué es el icing (despeje prohibido)?`,
        fr: `Qu'est-ce que le dégagement interdit (icing) ?`,
        pt: `O que é o icing (lançamento proibido)?`,
        de: `Was ist Icing (unerlaubter Befreiungsschlag)?`,
        it: `Che cos'è l'icing?`,
        ja: `アイシングとは何ですか？`,
        zh: `什么是“死球”（icing，违例长传）？`,
        ko: `아이싱이란 무엇인가요?`,
        ar: `ما هو الـ "آيسينغ" (icing)؟`,
      },
      {
        en: `What's offside in hockey?`,
        es: `¿Qué es el fuera de juego (offside) en hockey?`,
        fr: `Qu'est-ce que le hors-jeu (offside) au hockey ?`,
        pt: `O que é o impedimento (offside) no hóquei?`,
        de: `Was ist Abseits (Offside) beim Eishockey?`,
        it: `Che cos'è il fuorigioco (offside) nell'hockey?`,
        ja: `アイスホッケーのオフサイドとは何ですか？`,
        zh: `冰球里的越位（offside）是什么？`,
        ko: `아이스하키에서 오프사이드란 무엇인가요?`,
        ar: `ما هو التسلل (offside) في الهوكي؟`,
      },
      {
        en: `What's a power play?`,
        es: `¿Qué es un power play (superioridad numérica)?`,
        fr: `Qu'est-ce qu'un avantage numérique (power play) ?`,
        pt: `O que é um power play (superioridade numérica)?`,
        de: `Was ist ein Powerplay (Überzahlspiel)?`,
        it: `Che cos'è un power play (superiorità numerica)?`,
        ja: `パワープレーとは何ですか？`,
        zh: `什么是强打（power play，多打少）？`,
        ko: `파워 플레이란 무엇인가요?`,
        ar: `ما هو الـ "باور بلاي" (power play، التفوق العددي)؟`,
      },
      {
        en: `Why do players go to the penalty box?`,
        es: `¿Por qué los jugadores van al banquillo de penalizaciones?`,
        fr: `Pourquoi les joueurs vont-ils au banc des pénalités ?`,
        pt: `Por que os jogadores vão para a área de penalidades?`,
        de: `Warum müssen Spieler auf die Strafbank?`,
        it: `Perché i giocatori vanno in panchina puniti (penalty box)?`,
        ja: `選手はなぜペナルティボックスに入るのですか？`,
        zh: `球员为什么会被罚进受罚席？`,
        ko: `선수는 왜 페널티 박스에 들어가나요?`,
        ar: `لماذا يذهب اللاعبون إلى صندوق العقوبات؟`,
      },
      {
        en: `What's a hat trick?`,
        es: `¿Qué es un hat-trick (tres goles)?`,
        fr: `Qu'est-ce qu'un coup du chapeau (hat trick) ?`,
        pt: `O que é um hat-trick (três gols)?`,
        de: `Was ist ein Hattrick?`,
        it: `Che cos'è una tripletta (hat trick)?`,
        ja: `ハットトリックとは何ですか？`,
        zh: `什么是帽子戏法（hat trick）？`,
        ko: `해트트릭이란 무엇인가요?`,
        ar: `ما هو الـ "هاتريك" (hat trick، ثلاثة أهداف)؟`,
      },
      {
        en: `What happens at a face-off?`,
        es: `¿Qué ocurre en un saque neutral (face-off)?`,
        fr: `Que se passe-t-il lors d'une mise au jeu (face-off) ?`,
        pt: `O que acontece em uma disputa de bola (face-off)?`,
        de: `Was passiert bei einem Bully (Face-off)?`,
        it: `Cosa succede in un ingaggio (face-off)?`,
        ja: `フェイスオフでは何が起こりますか？`,
        zh: `争球（face-off）时会发生什么？`,
        ko: `페이스오프에서는 무슨 일이 일어나나요?`,
        ar: `ماذا يحدث في إسقاط القرص (face-off)؟`,
      },
      {
        en: `What does the goalie's job involve?`,
        es: `¿En qué consiste el trabajo del portero?`,
        fr: `En quoi consiste le rôle du gardien de but ?`,
        pt: `O que envolve o trabalho do goleiro?`,
        de: `Worin besteht die Aufgabe des Torwarts?`,
        it: `In che cosa consiste il ruolo del portiere?`,
        ja: `ゴーリー（ゴールキーパー）の役割は何ですか？`,
        zh: `守门员的职责是什么？`,
        ko: `골리(골키퍼)의 역할은 무엇인가요?`,
        ar: `ما هي مهمة حارس المرمى؟`,
      },
    ],
  },

  soccer: {
    label: {
      en: `Common Soccer Questions`,
      es: `Preguntas comunes de fútbol`,
      fr: `Questions courantes sur le football`,
      pt: `Perguntas comuns sobre futebol`,
      de: `Häufige Fragen zum Fußball`,
      it: `Domande comuni sul calcio`,
      ja: `サッカーのよくある質問`,
      zh: `足球常见问题`,
      ko: `축구 자주 묻는 질문`,
      ar: `أسئلة شائعة عن كرة القدم`,
    },
    questions: [
      {
        en: `What is offside?`,
        es: `¿Qué es el fuera de juego (offside)?`,
        fr: `Qu'est-ce que le hors-jeu ?`,
        pt: `O que é o impedimento?`,
        de: `Was ist Abseits?`,
        it: `Che cos'è il fuorigioco?`,
        ja: `オフサイドとは何ですか？`,
        zh: `什么是越位？`,
        ko: `오프사이드란 무엇인가요?`,
        ar: `ما هو التسلل (offside)؟`,
      },
      {
        en: `What's the difference between a yellow and a red card?`,
        es: `¿Cuál es la diferencia entre una tarjeta amarilla y una roja?`,
        fr: `Quelle est la différence entre un carton jaune et un carton rouge ?`,
        pt: `Qual é a diferença entre um cartão amarelo e um vermelho?`,
        de: `Was ist der Unterschied zwischen einer gelben und einer roten Karte?`,
        it: `Qual è la differenza tra un cartellino giallo e uno rosso?`,
        ja: `イエローカードとレッドカードの違いは何ですか？`,
        zh: `黄牌和红牌有什么区别？`,
        ko: `옐로카드와 레드카드의 차이는 무엇인가요?`,
        ar: `ما الفرق بين البطاقة الصفراء والحمراء؟`,
      },
      {
        en: `What's a penalty kick?`,
        es: `¿Qué es un penalti (tiro penal)?`,
        fr: `Qu'est-ce qu'un penalty (coup de pied de réparation) ?`,
        pt: `O que é um pênalti?`,
        de: `Was ist ein Elfmeter (Penalty)?`,
        it: `Che cos'è un calcio di rigore?`,
        ja: `ペナルティーキック（PK）とは何ですか？`,
        zh: `什么是点球（penalty kick）？`,
        ko: `페널티킥이란 무엇인가요?`,
        ar: `ما هي ركلة الجزاء (penalty)؟`,
      },
      {
        en: `Why do games sometimes end in a tie?`,
        es: `¿Por qué a veces los partidos terminan en empate?`,
        fr: `Pourquoi les matchs se terminent-ils parfois par un match nul ?`,
        pt: `Por que às vezes os jogos terminam empatados?`,
        de: `Warum enden Spiele manchmal unentschieden?`,
        it: `Perché a volte le partite finiscono in pareggio?`,
        ja: `なぜ試合が引き分けで終わることがあるのですか？`,
        zh: `为什么比赛有时会以平局结束？`,
        ko: `경기는 왜 가끔 무승부로 끝나나요?`,
        ar: `لماذا تنتهي المباريات أحيانًا بالتعادل؟`,
      },
      {
        en: `What's stoppage (injury) time?`,
        es: `¿Qué es el tiempo de descuento (tiempo añadido)?`,
        fr: `Qu'est-ce que le temps additionnel (arrêts de jeu) ?`,
        pt: `O que são os acréscimos (tempo de compensação)?`,
        de: `Was ist die Nachspielzeit?`,
        it: `Che cos'è il recupero (tempo aggiuntivo)?`,
        ja: `アディショナルタイム（ロスタイム）とは何ですか？`,
        zh: `什么是补时（伤停补时）？`,
        ko: `추가 시간(부상 시간)이란 무엇인가요?`,
        ar: `ما هو الوقت بدل الضائع؟`,
      },
      {
        en: `What's the difference between a free kick and a corner kick?`,
        es: `¿Cuál es la diferencia entre un tiro libre y un saque de esquina (córner)?`,
        fr: `Quelle est la différence entre un coup franc et un corner ?`,
        pt: `Qual é a diferença entre uma falta (tiro livre) e um escanteio?`,
        de: `Was ist der Unterschied zwischen einem Freistoß und einem Eckstoß?`,
        it: `Qual è la differenza tra un calcio di punizione e un calcio d'angolo?`,
        ja: `フリーキックとコーナーキックの違いは何ですか？`,
        zh: `任意球和角球有什么区别？`,
        ko: `프리킥과 코너킥의 차이는 무엇인가요?`,
        ar: `ما الفرق بين الركلة الحرة والركلة الركنية؟`,
      },
      {
        en: `What does a "clean sheet" mean?`,
        es: `¿Qué significa una "portería a cero" (clean sheet)?`,
        fr: `Que signifie un « clean sheet » (match sans encaisser de but) ?`,
        pt: `O que significa um "clean sheet" (jogo sem sofrer gols)?`,
        de: `Was bedeutet ein "Clean Sheet" (Spiel ohne Gegentor)?`,
        it: `Cosa significa "clean sheet" (porta inviolata)?`,
        ja: `「クリーンシート」（無失点）とはどういう意味ですか？`,
        zh: `“零封”（clean sheet，不失球）是什么意思？`,
        ko: `"클린시트"(무실점)는 무슨 뜻인가요?`,
        ar: `ماذا تعني "الشباك النظيفة" (clean sheet)؟`,
      },
    ],
  },

  worldcup: {
    label: {
      en: `Common World Cup Questions`,
      es: `Preguntas comunes sobre el Mundial`,
      fr: `Questions courantes sur la Coupe du Monde`,
      pt: `Perguntas comuns sobre a Copa do Mundo`,
      de: `Häufige Fragen zur WM`,
      it: `Domande comuni sui Mondiali`,
      ja: `ワールドカップのよくある質問`,
      zh: `世界杯常见问题`,
      ko: `월드컵 자주 묻는 질문`,
      ar: `أسئلة شائعة عن كأس العالم`,
    },
    questions: [
      {
        en: `How does the group stage work?`,
        es: `¿Cómo funciona la fase de grupos?`,
        fr: `Comment fonctionne la phase de groupes ?`,
        pt: `Como funciona a fase de grupos?`,
        de: `Wie funktioniert die Gruppenphase?`,
        it: `Come funziona la fase a gironi?`,
        ja: `グループステージはどのように行われますか？`,
        zh: `小组赛是怎么进行的？`,
        ko: `조별 리그는 어떻게 진행되나요?`,
        ar: `كيف يعمل دور المجموعات؟`,
      },
      {
        en: `What's the knockout round?`,
        es: `¿Qué es la fase eliminatoria?`,
        fr: `Qu'est-ce que la phase à élimination directe ?`,
        pt: `O que é a fase eliminatória (mata-mata)?`,
        de: `Was ist die K.-o.-Runde?`,
        it: `Che cos'è la fase a eliminazione diretta?`,
        ja: `決勝トーナメント（ノックアウト）とは何ですか？`,
        zh: `什么是淘汰赛阶段？`,
        ko: `녹아웃(토너먼트) 라운드란 무엇인가요?`,
        ar: `ما هو دور خروج المغلوب؟`,
      },
      {
        en: `What happens if a knockout game ends in a tie?`,
        es: `¿Qué pasa si un partido de eliminatoria termina en empate?`,
        fr: `Que se passe-t-il si un match à élimination directe se termine par un nul ?`,
        pt: `O que acontece se um jogo eliminatório terminar empatado?`,
        de: `Was passiert, wenn ein K.-o.-Spiel unentschieden endet?`,
        it: `Cosa succede se una partita a eliminazione finisce in pareggio?`,
        ja: `決勝トーナメントの試合が引き分けに終わったらどうなりますか？`,
        zh: `如果淘汰赛打成平局会怎样？`,
        ko: `녹아웃 경기가 무승부로 끝나면 어떻게 되나요?`,
        ar: `ماذا يحدث إذا انتهت مباراة خروج المغلوب بالتعادل؟`,
      },
      {
        en: `What is offside?`,
        es: `¿Qué es el fuera de juego (offside)?`,
        fr: `Qu'est-ce que le hors-jeu ?`,
        pt: `O que é o impedimento?`,
        de: `Was ist Abseits?`,
        it: `Che cos'è il fuorigioco?`,
        ja: `オフサイドとは何ですか？`,
        zh: `什么是越位？`,
        ko: `오프사이드란 무엇인가요?`,
        ar: `ما هو التسلل (offside)؟`,
      },
      {
        en: `What do yellow and red cards mean?`,
        es: `¿Qué significan las tarjetas amarilla y roja?`,
        fr: `Que signifient les cartons jaune et rouge ?`,
        pt: `O que significam os cartões amarelo e vermelho?`,
        de: `Was bedeuten gelbe und rote Karten?`,
        it: `Cosa significano i cartellini giallo e rosso?`,
        ja: `イエローカードとレッドカードは何を意味しますか？`,
        zh: `黄牌和红牌代表什么？`,
        ko: `옐로카드와 레드카드는 무엇을 의미하나요?`,
        ar: `ماذا تعني البطاقتان الصفراء والحمراء؟`,
      },
      {
        en: `How do countries qualify for the World Cup?`,
        es: `¿Cómo se clasifican los países para el Mundial?`,
        fr: `Comment les pays se qualifient-ils pour la Coupe du Monde ?`,
        pt: `Como os países se classificam para a Copa do Mundo?`,
        de: `Wie qualifizieren sich Länder für die WM?`,
        it: `Come si qualificano le nazionali ai Mondiali?`,
        ja: `各国はどうやってワールドカップの出場権を得るのですか？`,
        zh: `各国是如何获得世界杯参赛资格的？`,
        ko: `각국은 어떻게 월드컵 본선에 진출하나요?`,
        ar: `كيف تتأهل المنتخبات إلى كأس العالم؟`,
      },
      {
        en: `Why is winning the World Cup such a huge deal?`,
        es: `¿Por qué ganar el Mundial es algo tan importante?`,
        fr: `Pourquoi gagner la Coupe du Monde est-il si important ?`,
        pt: `Por que ganhar a Copa do Mundo é algo tão grandioso?`,
        de: `Warum ist der WM-Titel so eine große Sache?`,
        it: `Perché vincere i Mondiali è così importante?`,
        ja: `ワールドカップ優勝はなぜそれほど大きな意味を持つのですか？`,
        zh: `为什么赢得世界杯是如此了不起的成就？`,
        ko: `월드컵 우승이 왜 그렇게 대단한 일인가요?`,
        ar: `لماذا يُعدّ الفوز بكأس العالم إنجازًا ضخمًا؟`,
      },
    ],
  },

  rugby: {
    label: {
      en: `Common Rugby Questions`,
      es: `Preguntas comunes de rugby`,
      fr: `Questions courantes sur le rugby`,
      pt: `Perguntas comuns sobre rugby`,
      de: `Häufige Fragen zum Rugby`,
      it: `Domande comuni sul rugby`,
      ja: `ラグビーのよくある質問`,
      zh: `橄榄球常见问题`,
      ko: `럭비 자주 묻는 질문`,
      ar: `أسئلة شائعة عن الرغبي`,
    },
    questions: [
      {
        en: `What's a "try" and how many points is it?`,
        es: `¿Qué es un "try" (ensayo) y cuántos puntos vale?`,
        fr: `Qu'est-ce qu'un essai (try) et combien de points vaut-il ?`,
        pt: `O que é um "try" (ensaio) e quantos pontos vale?`,
        de: `Was ist ein "Try" (Versuch) und wie viele Punkte gibt es dafür?`,
        it: `Che cos'è una "meta" (try) e quanti punti vale?`,
        ja: `「トライ」とは何で、何点になりますか？`,
        zh: `什么是“达阵”（try），它值多少分？`,
        ko: `"트라이"란 무엇이고 몇 점인가요?`,
        ar: `ما هي "المحاولة" (try) وكم نقطة تساوي؟`,
      },
      {
        en: `How is rugby different from American football?`,
        es: `¿En qué se diferencia el rugby del fútbol americano?`,
        fr: `En quoi le rugby est-il différent du football américain ?`,
        pt: `Como o rugby é diferente do futebol americano?`,
        de: `Wie unterscheidet sich Rugby vom American Football?`,
        it: `In cosa è diverso il rugby dal football americano?`,
        ja: `ラグビーはアメフトとどう違うのですか？`,
        zh: `橄榄球和美式橄榄球有什么不同？`,
        ko: `럭비는 미식축구와 어떻게 다른가요?`,
        ar: `كيف يختلف الرغبي عن كرة القدم الأمريكية؟`,
      },
      {
        en: `Why can't you pass the ball forward?`,
        es: `¿Por qué no se puede pasar el balón hacia adelante?`,
        fr: `Pourquoi ne peut-on pas faire une passe en avant ?`,
        pt: `Por que não se pode passar a bola para a frente?`,
        de: `Warum darf man den Ball nicht nach vorne passen?`,
        it: `Perché non si può passare la palla in avanti?`,
        ja: `なぜボールを前にパスできないのですか？`,
        zh: `为什么不能向前传球？`,
        ko: `왜 공을 앞으로 패스할 수 없나요?`,
        ar: `لماذا لا يمكن تمرير الكرة إلى الأمام؟`,
      },
      {
        en: `What's a scrum?`,
        es: `¿Qué es una melé (scrum)?`,
        fr: `Qu'est-ce qu'une mêlée (scrum) ?`,
        pt: `O que é um scrum (formação ordenada)?`,
        de: `Was ist ein Gedränge (Scrum)?`,
        it: `Che cos'è una mischia (scrum)?`,
        ja: `スクラムとは何ですか？`,
        zh: `什么是争球（scrum，并列争球）？`,
        ko: `스크럼이란 무엇인가요?`,
        ar: `ما هو الـ "سكرم" (scrum، الالتحام)؟`,
      },
      {
        en: `What's a lineout?`,
        es: `¿Qué es un line-out (saque de lateral)?`,
        fr: `Qu'est-ce qu'une touche (line-out) ?`,
        pt: `O que é um line-out (lateral)?`,
        de: `Was ist eine Gasse (Lineout)?`,
        it: `Che cos'è una rimessa laterale (line-out)?`,
        ja: `ラインアウトとは何ですか？`,
        zh: `什么是边线球（lineout）？`,
        ko: `라인아웃이란 무엇인가요?`,
        ar: `ما هو الـ "لاين أوت" (line-out، رمية التماس)؟`,
      },
      {
        en: `What's a conversion?`,
        es: `¿Qué es una conversión (transformación)?`,
        fr: `Qu'est-ce qu'une transformation (conversion) ?`,
        pt: `O que é uma conversão?`,
        de: `Was ist eine Erhöhung (Conversion)?`,
        it: `Che cos'è una trasformazione (conversion)?`,
        ja: `コンバージョン（ゴールキック）とは何ですか？`,
        zh: `什么是附加分（conversion，达阵后射门）？`,
        ko: `컨버전(추가 킥)이란 무엇인가요?`,
        ar: `ما هو التحويل (conversion)؟`,
      },
      {
        en: `What's a ruck?`,
        es: `¿Qué es un ruck (agrupamiento)?`,
        fr: `Qu'est-ce qu'un ruck (regroupement) ?`,
        pt: `O que é um ruck?`,
        de: `Was ist ein Ruck (offenes Gedränge)?`,
        it: `Che cos'è un ruck (raggruppamento)?`,
        ja: `ラックとは何ですか？`,
        zh: `什么是 ruck（持球触地后的争夺）？`,
        ko: `럭(ruck)이란 무엇인가요?`,
        ar: `ما هو الـ "راك" (ruck)؟`,
      },
      {
        en: `What's the difference between rugby union and rugby league?`,
        es: `¿Cuál es la diferencia entre el rugby union y el rugby league?`,
        fr: `Quelle est la différence entre le rugby à XV (union) et le rugby à XIII (league) ?`,
        pt: `Qual é a diferença entre rugby union e rugby league?`,
        de: `Was ist der Unterschied zwischen Rugby Union und Rugby League?`,
        it: `Qual è la differenza tra rugby union e rugby league?`,
        ja: `ラグビーユニオンとラグビーリーグの違いは何ですか？`,
        zh: `联合式橄榄球（union）和联盟式橄榄球（league）有什么区别？`,
        ko: `럭비 유니온과 럭비 리그의 차이는 무엇인가요?`,
        ar: `ما الفرق بين رغبي الاتحاد (union) ورغبي الدوري (league)؟`,
      },
    ],
  },
};

// Drop-in leagues: same rules as the parent sport, so they reuse its question
// set with their own localized heading. WNBA -> basketball; EPL / La Liga -> soccer.
// (ja/zh/ko/ar headings are a v1 first pass — flag for native review.)
export const SPORT_FAQS: Record<Sport, SportFaq> = {
  ...BASE_FAQS,
  wnba: {
    label: {
      en: `Common WNBA Questions`,
      es: `Preguntas comunes de la WNBA`,
      fr: `Questions courantes sur la WNBA`,
      pt: `Perguntas comuns sobre a WNBA`,
      de: `Häufige Fragen zur WNBA`,
      it: `Domande comuni sulla WNBA`,
      ja: `WNBAのよくある質問`,
      zh: `WNBA常见问题`,
      ko: `WNBA 자주 묻는 질문`,
      ar: `أسئلة شائعة عن WNBA`,
    },
    questions: BASE_FAQS.nba.questions,
  },
  epl: {
    label: {
      en: `Common Premier League Questions`,
      es: `Preguntas comunes de la Premier League`,
      fr: `Questions courantes sur la Premier League`,
      pt: `Perguntas comuns sobre a Premier League`,
      de: `Häufige Fragen zur Premier League`,
      it: `Domande comuni sulla Premier League`,
      ja: `プレミアリーグのよくある質問`,
      zh: `英超联赛常见问题`,
      ko: `프리미어리그 자주 묻는 질문`,
      ar: `أسئلة شائعة عن الدوري الإنجليزي الممتاز`,
    },
    questions: BASE_FAQS.soccer.questions,
  },
  laliga: {
    label: {
      en: `Common La Liga Questions`,
      es: `Preguntas comunes de La Liga`,
      fr: `Questions courantes sur la Liga`,
      pt: `Perguntas comuns sobre a La Liga`,
      de: `Häufige Fragen zur La Liga`,
      it: `Domande comuni sulla Liga`,
      ja: `ラ・リーガのよくある質問`,
      zh: `西甲联赛常见问题`,
      ko: `라리가 자주 묻는 질문`,
      ar: `أسئلة شائعة عن الدوري الإسباني`,
    },
    questions: BASE_FAQS.soccer.questions,
  },
  mlr: {
    label: {
      en: `Common MLR Questions`,
      es: `Preguntas comunes de MLR`,
      fr: `Questions courantes sur la MLR`,
      pt: `Perguntas comuns sobre a MLR`,
      de: `Häufige Fragen zur MLR`,
      it: `Domande comuni sulla MLR`,
      ja: `MLRのよくある質問`,
      zh: `MLR常见问题`,
      ko: `MLR 자주 묻는 질문`,
      ar: `أسئلة شائعة عن MLR`,
    },
    questions: BASE_FAQS.rugby.questions,
  },
  nationscup: {
    label: allEn(`Common Rugby Questions`),
    questions: BASE_FAQS.rugby.questions,
  },
  sixnations: {
    label: allEn(`Common Rugby Questions`),
    questions: BASE_FAQS.rugby.questions,
  },
  nationschamp: {
    label: allEn(`Common Rugby Questions`),
    questions: BASE_FAQS.rugby.questions,
  },
  tennis: {
    label: allEn(`Common Tennis Questions`),
    questions: [
      allEn(`What does 'love' mean in tennis?`),
      allEn(`Why are the scores 15, 30, 40?`),
      allEn(`What's the difference between sets and games?`),
      allEn(`What is a tiebreak?`),
      allEn(`What's the difference between clay, grass, and hard courts?`),
      allEn(`What is a Grand Slam?`),
      allEn(`What does 'deuce' mean?`),
    ],
  },
  golf: {
    label: allEn(`Common Golf Questions`),
    questions: [
      allEn(`What does 'under par' mean?`),
      allEn(`What's the difference between birdie, eagle, and bogey?`),
      allEn(`What is a handicap?`),
      allEn(`What does 'the cut' mean?`),
      allEn(`Why do golfers yell 'fore'?`),
      allEn(`What's a mulligan?`),
      allEn(`What is match play vs stroke play?`),
    ],
  },
  cricket: {
    label: allEn(`Common Cricket Questions`),
    questions: [
      allEn(`What is a wicket?`),
      allEn(`What does it mean to be 'out for a duck'?`),
      allEn(`What's the difference between Test cricket and T20?`),
      allEn(`Why can a cricket match last 5 days?`),
      allEn(`What is an over?`),
      allEn(`What does LBW mean?`),
      allEn(`What's the difference between batting and bowling?`),
    ],
  },
};
