// Read the Score — Cricket bank. Scoring-RULE scenarios only (evergreen); team names
// are fictional set dressing. 6 scenarios per tier × 4 tiers. Pure data, zero RN imports.
import type { ScoreScenario } from '../readTheScore';

export const CRICKET_SCENARIOS: ScoreScenario[] = [
  // ── kid ────────────────────────────────────────────────────────────────────
  {
    id: 'crk-kid-1', level: 'kid',
    board: { kind: 'cricket', batting: { name: 'Falcons', runs: 245, wickets: 6, overs: '43.2' }, oversLimit: 50, header: 'FALCONS BATTING' },
    prompt: 'The board shows “245/6.” What do the two numbers mean?',
    options: ['245 runs scored, 6 wickets lost', '245 balls left, 6 runs', '245 minutes played, 6 overs'],
    answer: 0,
    title: 'Runs / wickets: cricket’s core scoreline',
    exp: {
      kid: 'The first number is RUNS (the score) — 245. The second is WICKETS — how many batters are out. The Falcons have lost 6.',
      beginner: 'Cricket’s score is always “runs for wickets”: 245/6 = 245 runs, 6 of the 10 wickets gone. Both numbers matter — 245/2 is a much stronger position than 245/9.',
      intermediate: 'Runs are the currency, wickets are the fuel: with 4 wickets left, the Falcons must balance scoring speed against the risk of running out of batters. The pair together IS the game state.',
      expert: 'Note the convention varies: most of the world writes runs/wickets (245/6), but Australia flips it (6/245). Same information, reversed — a classic trap when reading international coverage. Context (which number can exceed 10) disambiguates instantly.',
    },
  },
  {
    id: 'crk-kid-2', level: 'kid',
    board: { kind: 'cricket', batting: { name: 'Kingfishers', runs: 187, wickets: 4, overs: '32.0' }, oversLimit: 50, target: 260, note: 'SUNBIRDS MADE 259' },
    prompt: 'The Sunbirds scored 259. The Kingfishers are batting second. Who wins the match?',
    options: ['Whoever ends with more runs', 'Whoever loses fewer wickets', 'The team that bats last'],
    answer: 0,
    title: 'Most runs wins — wickets are the means, not the score',
    exp: {
      kid: 'It’s all about runs! The Kingfishers need MORE runs than 259 to win. Wickets just tell you how many chances they have left.',
      beginner: 'One team bats and sets a total; the other chases it. More runs = win. Wickets lost don’t decide the winner directly — they limit how long you can keep batting.',
      intermediate: 'The chase has two clocks: the target (260 to win) and resources (wickets + remaining overs). Reading a chase means comparing runs-needed against balls-remaining and wickets-in-hand.',
      expert: 'Formally the chasing team wins by reaching target = (first innings score + 1); the defending team wins by dismissing them or exhausting the overs with the score short. Every limited-overs endgame reduces to that triangle: runs needed, balls left, wickets in hand.',
    },
  },
  {
    id: 'crk-kid-3', level: 'kid',
    board: { kind: 'cricket', batting: { name: 'Sunbirds', runs: 42, wickets: 1, overs: '8.0' }, oversLimit: 20 },
    prompt: 'The bowler has bowled one full OVER. How many (legal) balls is that?',
    options: ['6 balls', '10 balls', '3 balls'],
    answer: 0,
    title: 'An over = 6 balls',
    exp: {
      kid: 'An over is 6 throws (balls) by the same bowler. Then a different bowler takes over from the other end!',
      beginner: 'Bowling is batched into 6-ball overs. After each over, the bowling switches ends and a new bowler must take the next one — nobody bowls two overs in a row.',
      intermediate: 'Overs are cricket’s clock: a 20-over innings = 120 legal balls, full stop. Illegal deliveries (wides, no-balls) don’t count toward the 6 and must be re-bowled — an over can take 7+ deliveries.',
      expert: 'The over structure creates matchup chess: captains sequence bowlers’ 4-over (T20) or 10-over (ODI) allocations against batting phases — powerplay, middle, death. Reading “overs 8.0 of 20” tells you which tactical phase you’re watching.',
    },
  },
  {
    id: 'crk-kid-4', level: 'kid',
    board: { kind: 'cricket', batting: { name: 'Cobras', runs: 118, wickets: 9, overs: '36.4' }, oversLimit: 50 },
    prompt: 'The Cobras are 118/9. What happens when ONE more wicket falls?',
    options: ['All out — the innings ends, even with overs left', 'A substitute bats', 'They keep batting to 50 overs'],
    answer: 0,
    title: 'Ten wickets = all out',
    exp: {
      kid: 'A team has 11 players, and batters must bat in PAIRS. When the 10th is out, only one player is left — no partner! The innings is over.',
      beginner: 'Two batters are always at the crease together. Losing the 10th wicket leaves the last player stranded without a partner, so the innings closes immediately — remaining overs are forfeited.',
      intermediate: 'That’s why 118/9 is a cliffhanger: one ball can end everything. The “last-wicket stand” pairs a real batter with a bowler who can barely bat — every run they add is a bonus.',
      expert: 'The pairs requirement drives endgame tactics: the competent batter “farms the strike” (takes singles only at over’s end to face most balls), and captains weigh batting order by who can protect the tail. 9 down changes field settings, running decisions, everything — the scoreboard’s second number is shouting.',
    },
  },
  {
    id: 'crk-kid-5', level: 'kid',
    board: { kind: 'cricket', batting: { name: 'Falcons', runs: 156, wickets: 3, overs: '18.3' }, oversLimit: 20, note: 'SIX! OVER THE ROPE' },
    prompt: 'The batter hits the ball over the boundary rope WITHOUT it bouncing. How many runs?',
    options: ['6 runs', '4 runs', '1 run'],
    answer: 0,
    title: 'Over the rope on the full = six',
    exp: {
      kid: 'Clearing the rope in the air is the biggest hit in cricket — 6 runs at once! If it bounces before crossing, it’s 4.',
      beginner: 'Boundaries are automatic runs: ball reaches the rope after bouncing = 4; carries it on the full = 6. No running required — the umpire signals and the score jumps.',
      intermediate: 'Everything else is run by hand: batters sprint between the wickets, 1s, 2s, occasionally 3s. Boundary-hitting vs strike-rotation is the core batting trade-off — power scores faster, running scores safer.',
      expert: 'Format economics: T20 innings are boundary-driven (50%+ of runs from 4s/6s is common), while Test batting lives on rotation and leaves. When a chase needs 12 an over, the required-boundary-rate — not the run rate — is the real constraint; singles literally cannot keep pace.',
    },
  },
  {
    id: 'crk-kid-6', level: 'kid',
    board: { kind: 'cricket', batting: { name: 'Kingfishers', runs: 0, wickets: 0, overs: '0.0' }, oversLimit: 50, note: 'INNINGS 2 — SUNBIRDS MADE 231' },
    prompt: 'The Sunbirds finished batting with 231. What happens now?',
    options: ['The teams swap — Kingfishers bat, Sunbirds bowl', 'The Sunbirds bat again', 'The game is over'],
    answer: 0,
    title: 'Innings: taking turns at bat',
    exp: {
      kid: 'Cricket is turn-based: one team bats while the other bowls and fields. Now they swap! The Kingfishers know exactly what they need — 232 to win.',
      beginner: 'Each team’s turn is an “innings.” In limited-overs cricket there’s one innings each: team 1 sets the total, team 2 chases it knowing precisely the target.',
      intermediate: 'Batting second means perfect information (the exact target) but added pressure and, sometimes, a worn pitch. The toss-winning captain’s bat-or-bowl-first decision weighs exactly these factors.',
      expert: 'The asymmetry is studied endlessly: chasing teams win slightly more often in T20 (information advantage dominates), while batting first can pay in day-night ODIs (dew) or on deteriorating pitches. One innings each is also what separates the limited-overs formats from Tests — where each side bats TWICE and the arithmetic gets richer.',
    },
  },

  // ── beginner ──────────────────────────────────────────────────────────────
  {
    id: 'crk-beg-1', level: 'beginner',
    board: { kind: 'cricket', batting: { name: 'Sunbirds', runs: 201, wickets: 5, overs: '43.2' }, oversLimit: 50 },
    prompt: 'The overs column reads “43.2”. What does the “.2” mean?',
    options: ['2 balls of the 44th over have been bowled', '43 overs and 20% of the innings left', '43 overs, 2 minutes'],
    answer: 0,
    title: 'Overs notation: 43.2 = 43 overs + 2 balls',
    exp: {
      kid: 'The number after the dot counts BALLS, not tenths! 43.2 means 43 full overs plus 2 balls of the next one.',
      beginner: 'Overs count in base 6: 43.2 → 43×6 + 2 = 260 balls bowled. After 43.5 comes 44.0 (never 43.6!). It’s the most common misread in cricket.',
      intermediate: 'Balls-remaining math flows from it: in a 50-over innings at 43.2, there are 6×50 − 260 = 40 balls left. Required-rate calculations all start with this conversion.',
      expert: 'The base-6 trap bites real analysts: 43.3 overs is 43.5 in decimal, so computing run rates as runs ÷ “43.3” understates the rate. Broadcasters’ RRR graphics do the conversion silently; now you can audit them — runs remaining ÷ (balls remaining ÷ 6) is the true required rate.',
    },
  },
  {
    id: 'crk-beg-2', level: 'beginner',
    board: { kind: 'cricket', batting: { name: 'Cobras', runs: 88, wickets: 2, overs: '9.0' }, oversLimit: 20, header: 'T20 MATCH' },
    prompt: 'This is a T20 match. How long is each team’s innings?',
    options: ['20 overs', '50 overs', 'Unlimited — until all out'],
    answer: 0,
    title: 'The formats: T20 (20), ODI (50), Test (unlimited)',
    exp: {
      kid: 'T20 means “Twenty20” — each team bats for up to 20 overs. It’s cricket’s short, exciting version, done in about 3 hours!',
      beginner: 'The three main formats: T20 = 20 overs a side (~3 hours); ODI (One-Day International) = 50 overs (~8 hours); Test = two innings each, no over limit, up to 5 days.',
      intermediate: 'Format changes everything on the board: 88/2 after 9 overs is a strong T20 position (nearly 10/over) but a reckless ODI start would read differently. Always check the overs limit before judging a score.',
      expert: 'Scoring norms by format (rules of thumb): T20 par ≈ 160–180, ODI par ≈ 270–300, Tests ~3–3.5 runs per over across long innings. The same 250 is a monster in T20, routine in an ODI, and a modest first innings in a Test — the overs-limit field is the interpretive key to every cricket scoreboard.',
    },
  },
  {
    id: 'crk-beg-3', level: 'beginner',
    board: { kind: 'cricket', batting: { name: 'Falcons', runs: 0, wickets: 0, overs: '0.0' }, oversLimit: 50, target: 288, note: 'KINGFISHERS MADE 287' },
    prompt: 'The Kingfishers made 287. The board sets the Falcons’ TARGET at 288. Why one more?',
    options: ['They must PASS 287 to win — equal is only a tie', 'Scorers add a courtesy run', 'The target includes extras'],
    answer: 0,
    title: 'Target = opponent’s score + 1',
    exp: {
      kid: 'To WIN you need more runs, not the same. So the target is 287 + 1 = 288. Reaching exactly 287 would be a tie!',
      beginner: 'The chasing team wins the moment it reaches target (opponent + 1) — the innings stops right there, even mid-over. Finishing level is a tie, a genuinely rare result.',
      intermediate: 'This defines the endgame grammar: “Falcons need 43 from 40 balls” means 43 to WIN (reaching 287 ties). Winning “with 10 balls to spare” means they hit the target early and the rest of the innings never happened.',
      expert: 'The instant-stop rule affects stats and strategy: batters can’t pad totals in a completed chase (strike rates in chases are truncated), and the margin is reported in WICKETS (e.g., “won by 4 wickets”) precisely because unused runs don’t exist — only unused batting resources do.',
    },
  },
  {
    id: 'crk-beg-4', level: 'beginner',
    board: { kind: 'cricket', batting: { name: 'Sunbirds', runs: 143, wickets: 10, overs: '38.4' }, oversLimit: 50, note: 'ALL OUT' },
    prompt: 'The Sunbirds are ALL OUT for 143 after only 38.4 of their 50 overs. What happens to the remaining 11.2 overs?',
    options: ['Gone — the innings is over; 143 is the final total', 'The last batter plays them alone', 'They carry over to the next innings'],
    answer: 0,
    title: 'All out ends the innings early',
    exp: {
      kid: 'Once 10 batters are out, the innings is finished — the leftover overs just disappear. 143 is all they get!',
      beginner: 'An innings ends at EITHER the over limit OR the 10th wicket, whichever comes first. Getting bowled out inside your overs is the batting side wasting its scarcest resource.',
      intermediate: 'That dual constraint is the core batting dilemma: attack too hard and you’re all out at 143 with overs unused; too soft and you crawl to 210/4 with wickets unused. Elite sides aim to use BOTH resources fully — 10th wicket falling near over 50.',
      expert: 'This resources framing (overs × wickets) is literally the basis of the DLS rain-adjustment method: the tables model exactly how many runs remaining overs are worth GIVEN wickets in hand. All out at 38.4 = 100% of resources consumed; the scoreboard concept and the statistical model are the same idea.',
    },
  },
  {
    id: 'crk-beg-5', level: 'beginner',
    board: { kind: 'cricket', batting: { name: 'Cobras', runs: 245, wickets: 6, overs: '44.0' }, oversLimit: 50 },
    prompt: 'The Cobras are 245/6. How many wickets do they have “in hand”?',
    options: ['4', '6', '5'],
    answer: 0,
    title: 'Wickets in hand: 10 minus wickets lost',
    exp: {
      kid: 'Teams start with 10 wickets. They’ve lost 6, so 10 − 6 = 4 chances left.',
      beginner: '“In hand” counts what remains: 245/6 = 4 wickets in hand. Commentators use it constantly because remaining resources matter more than spent ones.',
      intermediate: 'Wickets in hand set the risk budget for the death overs: 4 in hand at over 44 permits controlled aggression; 8 in hand would mean all-out attack. The chase/setting calculus reads this number first.',
      expert: 'Quantified: DLS-style resource tables say the last 6 overs are worth far more runs with 6 wickets in hand than with 2 — the marginal value of a wicket rises steeply late. That’s why a wicket in over 40 — especially of a set batter — swings projected totals by 15–20 runs.',
    },
  },
  {
    id: 'crk-beg-6', level: 'beginner',
    board: { kind: 'cricket', batting: { name: 'Falcons', runs: 261, wickets: 7, overs: '49.0' }, oversLimit: 50, note: 'EXTRAS: 18 (W 9, NB 2, B 4, LB 3)' },
    prompt: 'The board lists “EXTRAS: 18.” What are extras?',
    options: ['Runs the fielding side concedes without the bat hitting the ball', 'Bonus runs for boundaries', 'Runs scored by substitutes'],
    answer: 0,
    title: 'Extras: free runs from the fielding side',
    exp: {
      kid: 'Extras are runs the batting team gets for FREE — like when the bowler throws too wide, or the ball sneaks past everyone without being hit.',
      beginner: 'The main kinds: wides (unreachable balls, +1 and re-bowled), no-balls (illegal deliveries, +1 and re-bowled), byes (missed by everyone, runs taken) and leg byes (off the batter’s body). All count to the TEAM total only.',
      intermediate: 'Wides and no-balls also cost an extra BALL — the delivery doesn’t count toward the over. In tight T20 finishes, a wide is a double punishment: a run AND another chance to be hit.',
      expert: 'The modern no-ball cascade: an over-the-line no-ball triggers a FREE HIT next ball (batter can’t be out except run out) in white-ball cricket — so one overstep can cost 1 + 6 + the re-bowl. Disciplined attacks treat extras as the most controllable stat on the board; 18 extras is roughly an extra three overs gifted.',
    },
  },

  // ── intermediate ──────────────────────────────────────────────────────────
  {
    id: 'crk-int-1', level: 'intermediate',
    board: { kind: 'cricket', batting: { name: 'Kingfishers', runs: 245, wickets: 6, overs: '43.2' }, oversLimit: 50, target: 288 },
    prompt: 'Chasing a target of 288, the Kingfishers are 245/6 after 43.2 overs. Exactly how many more runs do they need to WIN?',
    options: ['43', '44', '42'],
    answer: 0,
    title: 'Runs required = target − current score',
    exp: {
      kid: 'The target already includes the “one more to win”: 288 − 245 = 43 runs needed!',
      beginner: 'Target (288) is the winning score, so required runs = 288 − 245 = 43. Reaching 287 would only tie. Balls left: 50 overs = 300 balls, minus 260 bowled = 40.',
      intermediate: 'So the equation is 43 off 40 balls with 4 wickets in hand — a required rate of about 6.5 an over: tight but very gettable. Endgame cricket is exactly this arithmetic, updated ball by ball.',
      expert: 'The three-variable dashboard: 43 needed, 40 balls, 4 wickets. Win-probability models weight wickets heavily here — 4 in hand at 6.45 RRR is roughly a coin flip, while 7 in hand at the same rate is strongly favored. Wickets are volatility armor: they let you absorb dot balls without panic-hitting.',
    },
  },
  {
    id: 'crk-int-2', level: 'intermediate',
    board: { kind: 'cricket', batting: { name: 'Cobras', runs: 289, wickets: 6, overs: '48.3' }, oversLimit: 50, target: 288, note: 'COBRAS WIN' },
    prompt: 'The Cobras (batting second) just passed the target with 6 wickets down. How is this victory described?',
    options: ['“Won by 4 wickets” — the chaser’s margin is unused wickets', '“Won by 1 run”', '“Won by 9 balls”'],
    answer: 0,
    title: 'Chasers win by wickets, setters win by runs',
    exp: {
      kid: 'The winning team was still batting, so we say how many batters they had spare: 10 − 6 = won by 4 wickets!',
      beginner: 'Two margin languages: if the team batting FIRST defends its total, it “wins by N runs” (the shortfall). If the CHASING team gets there, it “wins by N wickets” (10 − wickets lost). The board tells you which story happened.',
      intermediate: 'The margins measure different resources: runs-margin measures scoreboard distance, wickets-margin measures batting depth to spare. “By 1 wicket” and “by 2 runs” are both photo finishes — in opposite directions.',
      expert: 'Some competitions add “balls remaining” color for chases (won by 4 wickets with 9 balls to spare) since wickets alone understate dominance. Note the asymmetry’s statistical wrinkle: chase wins truncate the innings, so chasing teams’ totals and strike rates are systematically censored data — a real adjustment in cricket analytics.',
    },
  },
  {
    id: 'crk-int-3', level: 'intermediate',
    board: { kind: 'cricket', batting: { name: 'Falcons', runs: 228, wickets: 5, overs: '45.0' }, oversLimit: 50, target: 289, note: 'REQUIRED RATE: 12.2' },
    prompt: 'Falcons need 61 off the last 5 overs (30 balls). The board says required rate 12.2. What does that number mean?',
    options: ['They must score 12.2 runs per over from here to win', 'They’re scoring 12.2 per over now', '12.2 wickets remain'],
    answer: 0,
    title: 'RRR: the pace the chase demands',
    exp: {
      kid: 'It’s the speed they MUST score from now on: about 12 runs every over. That’s a lot — basically two boundaries an over!',
      beginner: 'Required run rate = runs needed ÷ overs left: 61 ÷ 5 = 12.2. Compare it to the CURRENT run rate (228 ÷ 45 ≈ 5.1) to see how much the tempo must jump.',
      intermediate: 'RRR above ~10 means singles can’t sustain the chase — they need boundaries. The bowling side’s counter is dot balls and yorkers: every dot raises the RRR sharply this late (a dot at RRR 12 pushes it past 13).',
      expert: 'Late-chase RRR is hyper-convex: with 30 balls left, each dot ball adds ~0.5 to the rate, each boundary drops it ~1.5. That’s why death-overs cricket is sequenced in “boundary-per-over minimum” terms and why a single 18-run over flips win probability entirely. Read RRR trend, not level: rising = defenders winning, falling = chasers winning, regardless of the score.',
    },
  },
  {
    id: 'crk-int-4', level: 'intermediate',
    board: { kind: 'cricket', batting: { name: 'Sunbirds', runs: 287, wickets: 10, overs: '49.4' }, oversLimit: 50, target: 288, note: 'MATCH TIED' },
    prompt: 'Chasing 288, the Sunbirds are all out for exactly 287. What is the result?',
    options: ['A tie — scores level with the chase complete', 'A draw', 'Sunbirds win on fewer overs used'],
    answer: 0,
    title: 'Tie ≠ draw: cricket’s two different “equals”',
    exp: {
      kid: 'Both teams scored exactly the same — that’s a TIE, super rare and super dramatic!',
      beginner: 'A TIE = both sides finish with identical scores and the chase is complete (all out or overs done). A DRAW is different — it’s a Test match running out of time with no result. Two words, two distinct outcomes.',
      intermediate: 'In league ODIs a tie usually splits the points; in knockouts a Super Over (a one-over shootout per side) breaks it. The distinction matters: ties are decided-but-level; draws are undecided.',
      expert: 'The draw exists ONLY where time can expire before completion (Tests / first-class); limited-overs formats can tie but never draw. Famous rules trivia: a Test can even end in a tie (scores level, final wicket falling) — it has happened only twice in 140+ years. Precision with tie/draw vocabulary is an instant marker of cricket literacy.',
    },
  },
  {
    id: 'crk-int-5', level: 'intermediate',
    board: { kind: 'cricket', batting: { name: 'Cobras', runs: 164, wickets: 3, overs: '58.0' }, header: 'TEST MATCH — DAY 4, INNINGS 3', note: 'COBRAS LEAD BY 212' },
    prompt: 'This TEST match board shows “Innings 3” and a lead of 212. How do Test innings work?',
    options: ['Each team bats twice; the aggregate decides the winner', 'One innings each, like ODIs', 'Best of three innings'],
    answer: 0,
    title: 'Tests: two innings each, added together',
    exp: {
      kid: 'In a Test match each team bats TWICE. All the runs from both turns get added up — most in total wins!',
      beginner: 'Innings order is usually A, B, A, B. “Innings 3” = team A batting again. The LEAD (212) is the running aggregate difference — what team B would need to overhaul in innings 4.',
      intermediate: 'The endgame: when the third innings closes, the lead + 1 becomes team B’s fourth-innings target. But there’s a second axis — TIME. If five days expire before 40 wickets or a chase completes, it’s a draw, regardless of the scores.',
      expert: 'The time axis makes Test scoreboards uniquely rich: a team can be miles ahead on runs but short on time to take 10 wickets, making the lead almost irrelevant. Reading “lead 212, day 4, 3 wickets down” means computing BOTH arithmetic (how big a target) and clock (how many overs remain to bowl them out) — the declaration decision lives exactly at that intersection.',
    },
  },
  {
    id: 'crk-int-6', level: 'intermediate',
    board: { kind: 'cricket', batting: { name: 'Falcons', runs: 45, wickets: 9, overs: '17.2' }, oversLimit: 20, target: 52, note: 'LAST PAIR AT THE CREASE' },
    prompt: 'Chasing 52, the Falcons are 45/9 — the LAST PAIR is batting. What’s the situation?',
    options: ['7 runs needed but ONE mistake ends everything', 'They need 7 and have plenty of margin', 'The match is already lost'],
    answer: 0,
    title: 'Nine down: the knife’s edge',
    exp: {
      kid: 'They only need 7 more runs — so close! But if even ONE more batter gets out, the whole team is done. Every ball is heart-stopping.',
      beginner: 'At 9 wickets down, the equation inverts: runs required (7) is tiny, but the resource buffer is zero. The bowling side needs one good ball; the batters need a couple of lucky swings.',
      intermediate: 'Watch strike management: the stronger batter of the pair will refuse singles early in the over and take one on the last ball, monopolizing the danger. The fielding captain crowds the tail-ender with catchers and spreads for the batter — chess with nine lives spent.',
      expert: 'Win-probability at 7-needed-9-down sits far below what the tiny run gap suggests — the last wicket falls fast. This is the purest case of cricket’s two-resource model: the chase is 87% complete by runs and ~100% spent by wickets, and the second number dominates. One-wicket wins are all-time-classic rarities for exactly this reason.',
    },
  },

  // ── expert ────────────────────────────────────────────────────────────────
  {
    id: 'crk-exp-1', level: 'expert',
    board: { kind: 'cricket', batting: { name: 'Kingfishers', runs: 156, wickets: 10, overs: '54.1' }, header: 'TEST — INNINGS 2 COMPLETE', note: 'SUNBIRDS MADE 401 · LEAD 245 — FOLLOW ON?' },
    prompt: 'Test match: Sunbirds made 401; Kingfishers all out for 156 (245 behind). What option does the Sunbirds captain now have?',
    options: ['Enforce the follow-on — make the Kingfishers bat AGAIN immediately', 'Claim victory by 245 runs', 'Take a 245-run head start in innings 3'],
    answer: 0,
    title: 'The follow-on: bat again, right now',
    exp: {
      kid: 'Because the Kingfishers fell SO far behind (more than 200), the other captain can say “bat again right now!” If they fail again, the Sunbirds might not need to bat twice at all.',
      beginner: 'In Tests, a first-innings lead of 200+ lets the captain enforce the follow-on: the trailing team bats its second innings immediately. If they can’t clear the 245 deficit, the leaders win without batting again — the innings victory.',
      intermediate: 'Enforcing is a choice, not automatic: captains weigh bowler fatigue, pitch deterioration (batting last is hardest), and the rare-but-famous risk of a comeback. Declining means batting again to pile the lead astronomically instead.',
      expert: 'The decision matrix is a Test-cricket classic: enforce for time (more overs to take 10 wickets, the scarce resource in draws-possible cricket) vs bat again for safety and a 4th-innings pitch. The 200-run threshold (150 in shorter Tests) is one of the rulebook’s few explicit strategy switches, and its game theory still divides captains and analysts.',
    },
  },
  {
    id: 'crk-exp-2', level: 'expert',
    board: { kind: 'cricket', batting: { name: 'Cobras', runs: 387, wickets: 6, overs: '92.0' }, header: 'TEST — DAY 4, INNINGS 3', note: 'LEAD 430 — DECLARED' },
    prompt: 'The board flashes “DECLARED” with the Cobras 387/6. What did the captain just do?',
    options: ['Voluntarily ended his own innings to leave time to bowl the opponent out', 'Conceded the match', 'Requested bad-light relief'],
    answer: 0,
    title: 'The declaration: trading runs for time',
    exp: {
      kid: 'The captain said “we have enough runs — stop batting!” He gave up his own team’s turn early so his bowlers have time to get all 10 opponents out before the match ends.',
      beginner: 'Only in timed cricket (Tests) does this exist: the batting captain may close his innings at any moment. Lead 430 with 4+ sessions left = declare, set the target at 431, and spend every remaining over attacking.',
      intermediate: 'The declaration curve: too early risks losing (the opponent chases it), too late risks the draw (not enough overs to take 10 wickets). Great declarations dangle a target just tempting enough to keep the opponent attacking — and losing wickets.',
      expert: 'It’s the purest expression of Test cricket’s three-outcome structure: declarations exist BECAUSE draws exist. The captain is pricing runs (insurance against defeat) versus overs (the ammunition for victory), often targeting a specific overs-remaining number (e.g., “90 overs to bowl them out”). No other major sport lets a team voluntarily end its own scoring turn as an act of aggression.',
    },
  },
  {
    id: 'crk-exp-3', level: 'expert',
    board: { kind: 'cricket', batting: { name: 'Falcons', runs: 118, wickets: 3, overs: '24.0' }, oversLimit: 50, target: 273, note: 'RAIN — DLS REVISED TARGET: 196 IN 35 OVERS' },
    prompt: 'Rain interrupts the chase and the board announces a DLS revised target. What is DLS doing?',
    options: ['Recalculating a fair target for the shortened innings from runs AND wickets resources', 'Splitting the match points', 'Adding the lost overs tomorrow'],
    answer: 0,
    title: 'DLS: rain math, done fairly',
    exp: {
      kid: 'Rain stole some of their overs, so a special formula shrinks the target too — keeping the chase exactly as hard as it was before the rain.',
      beginner: 'The Duckworth–Lewis–Stern method converts an interrupted chase into an equivalent one: it models how many runs the lost overs were worth GIVEN the wickets in hand, and sets a revised target (here 196 in 35 overs instead of 273 in 50).',
      intermediate: 'The key insight is that overs and wickets are one combined resource: 10 overs with 8 wickets in hand is worth far more than 10 overs with 2. A simple run-rate proration would ignore wickets entirely — DLS’s resource tables don’t.',
      expert: 'DLS is the rare case of an academic statistical model written directly into playing conditions. Its edge cases are folklore: targets that jump oddly after early interruptions, teams keeping wickets in hand ahead of forecast rain, and captains chasing the “DLS par score” shown on modern boards ball-by-ball. When rain threatens, the par-score line becomes the REAL scoreboard.',
    },
  },
  {
    id: 'crk-exp-4', level: 'expert',
    board: { kind: 'cricket', batting: { name: 'Sunbirds', runs: 172, wickets: 8, overs: '20.0' }, oversLimit: 20, target: 173, note: 'SCORES LEVEL — SUPER OVER' },
    prompt: 'A T20 knockout ends with scores level. The board announces a SUPER OVER. How does it work?',
    options: ['Each side bats ONE over (2 wickets max); higher score wins', 'Five penalty hits each', 'The team with fewer wickets lost wins'],
    answer: 0,
    title: 'The Super Over: cricket’s shootout',
    exp: {
      kid: 'It’s a tiny rematch: each team bats for just ONE over with their best hitters. Whoever scores more in their over wins the whole match!',
      beginner: 'Each side nominates three batters and one bowler; an over apiece, and losing 2 wickets ends your over early. Higher super-over score takes the match. Still tied? Another super over.',
      intermediate: 'The tie-then-shootout structure mirrors soccer’s penalties, but with real cricket skills compressed: 6 balls of pure death-overs play. Selection puzzles abound — do you send your best batter or your best six-hitter? Your best bowler may not be your best one-over bowler.',
      expert: 'Rules history worth knowing: the boundary-count tiebreaker (most boundaries in the match wins) famously decided a World Cup final in 2019 and was abolished for repeated super overs afterward — a live example of scoring-rule design being debugged in public. Current standard: repeat super overs until decided.',
    },
  },
  {
    id: 'crk-exp-5', level: 'expert',
    board: { kind: 'cricket', batting: { name: 'Kingfishers', runs: 233, wickets: 10, overs: '77.3' }, header: 'TEST — MATCH COMPLETE', note: 'COBRAS WON BY AN INNINGS AND 42 RUNS' },
    prompt: 'The result reads “won by an innings and 42 runs.” What does an INNINGS victory mean?',
    options: ['The winner batted only once and still outscored both opposition innings — by 42', 'The winner won both innings by 42', 'The match ended 42 innings early'],
    answer: 0,
    title: 'Victory by an innings: total domination',
    exp: {
      kid: 'The winning team batted just ONE time and scored more than the other team managed in TWO tries — with 42 runs to spare. That’s the most crushing win in cricket!',
      beginner: 'Arithmetic: if the Cobras made, say, 500, and the Kingfishers’ two innings totaled 225 + 233 = 458, the gap is 42 — and since the Cobras never needed their second innings, it’s “an innings and 42 runs.”',
      intermediate: 'Innings victories usually follow an enforced follow-on (see the 200-lead rule): trail hugely, bat again immediately, fail to make the leader bat twice. The margin phrasing encodes the whole story — one team used half its resources.',
      expert: 'Margin taxonomy, fully decoded: “by N runs” (defended a target), “by N wickets” (chased successfully), “by an innings and N” (never batted twice), plus ties and draws. Five phrasings, five distinct game shapes — from the result line alone, an expert reconstructs which team batted when and how the match unfolded. That’s the deepest form of scoreboard reading cricket offers.',
    },
  },
  {
    id: 'crk-exp-6', level: 'expert',
    board: { kind: 'cricket', batting: { name: 'Falcons', runs: 197, wickets: 7, overs: '19.5' }, oversLimit: 20, target: 199, note: 'LAST BALL — 2 TO WIN, 1 TO TIE' },
    prompt: 'Last ball, 197 chasing 199: 2 runs win, 1 ties. The batters sprint two — the first run is completed, but the runner is run out attempting the SECOND. What’s the result?',
    options: ['A tie — only the completed first run counts, leveling the scores at 198', 'Falcons win — they attempted two', 'The ball is re-bowled'],
    answer: 0,
    title: 'Last-ball forensics: the incomplete second run',
    exp: {
      kid: 'They finished the first run — that makes the scores exactly equal at 198! But the second runner was out before reaching safety, so the extra run doesn’t count. The match ends as a TIE!',
      beginner: 'Runs only count when COMPLETED (both batters make their ground). The run-out voids the second run in progress, but the finished first run stands: 197 + 1 = 198, level with the defenders’ 198 — a tie, settled by the competition’s tiebreak (a super over in most T20s).',
      intermediate: 'The target arithmetic, slowly: defenders made 198, so the target is 199 (opponent + 1). Reaching 198 only levels it. That’s why the board said “2 to win, 1 to tie” — and why the incomplete second run leaves a tie, not a heartbreak defeat by one.',
      expert: 'The rules composed here: (1) target = first-innings score + 1; (2) a chase ends INSTANTLY on reaching the target, even mid-run; (3) a dismissed batter’s in-progress run is void, but previously completed runs stand; (4) whether the batters had CROSSED decides who is the one run out. Every famous last-ball finish — and the umpires’ long huddles after them — is these four rules composed. Count completed runs only, and you’ll out-read the broadcast graphics.',
    },
  },
];
