// Read the Score — Golf bank. Scoring-RULE scenarios only (evergreen); player names
// are fictional set dressing. 6 scenarios per tier × 4 tiers. Pure data, zero RN imports.
import type { ScoreScenario } from '../readTheScore';

export const GOLF_SCENARIOS: ScoreScenario[] = [
  // ── kid ────────────────────────────────────────────────────────────────────
  {
    id: 'glf-kid-1', level: 'kid',
    board: { kind: 'golf', rows: [
      { pos: '1', name: 'Moss', toPar: '-6', thru: '14' },
      { pos: '2', name: 'Varga', toPar: '-2', thru: '15' },
      { pos: '3', name: 'Reyes', toPar: '+1', thru: '13' },
    ] },
    prompt: 'Look at the TO PAR column. Who is winning?',
    options: ['Moss at −6', 'Reyes at +1', 'Varga at −2'],
    answer: 0,
    title: 'Golf is upside-down: LOWEST wins',
    exp: {
      kid: 'Golf is the flipped sport — the SMALLEST number wins! Minus 6 means 6 strokes better than expected. Moss leads!',
      beginner: 'Golf counts strokes (swings), and fewer is better. “−6” means 6 strokes UNDER the course’s expected total (par) — the most-minus player leads.',
      intermediate: 'The minus/plus is relative to par, which makes players comparable even mid-round: −6 beats −2 beats +1, regardless of which hole each is playing.',
      expert: 'The inversion trips up every crossover fan: red/minus numbers are GOOD, and a leaderboard is sorted ascending. Internalize “strokes are a cost, not a reward” and every golf graphic instantly makes sense.',
    },
  },
  {
    id: 'glf-kid-2', level: 'kid',
    board: { kind: 'golf-hole', hole: 7, par: 4, player: 'Varga', strokes: 0, note: 'TEEING OFF' },
    prompt: 'The sign says HOLE 7 — PAR 4. What does “par 4” mean?',
    options: ['A good golfer is expected to need 4 strokes on this hole', 'The hole is 4 meters wide', 'Only 4 players may play it'],
    answer: 0,
    title: 'Par: the expected number of strokes',
    exp: {
      kid: '“Par 4” means a really good golfer should get the ball in the hole in 4 hits. It’s the target to beat!',
      beginner: 'Every hole has a par — 3, 4, or 5 — based mostly on length. Par is the benchmark: match it and you “made par”; beat it and you’re under.',
      intermediate: 'The design logic: par = expected shots to reach the green (1 for par-3s, 2 for par-4s, 3 for par-5s) + 2 putts. A course’s 18 pars usually total 70–72.',
      expert: 'Par is a scoring UNIT, not a rule — nothing happens if you exceed it. Its genius is normalization: it converts holes of wildly different lengths into one comparable scale, which is what makes “−6 thru 14” meaningful at a glance.',
    },
  },
  {
    id: 'glf-kid-3', level: 'kid',
    board: { kind: 'golf-hole', hole: 12, par: 4, player: 'Moss', strokes: 3, note: 'HOLED OUT IN 3' },
    prompt: 'Moss finished a PAR 4 hole in just 3 strokes. What is that called?',
    options: ['A birdie', 'A bogey', 'A par'],
    answer: 0,
    title: 'One under par on a hole = birdie',
    exp: {
      kid: 'Beating par by one stroke is a BIRDIE — a little victory with a fun bird name!',
      beginner: 'Hole scores have names by their relation to par: 1 under = birdie, level = par, 1 over = bogey. A birdie moves your tournament score one shot “more minus.”',
      intermediate: 'The bird ladder continues: 2 under = eagle, 3 under = albatross. Birdies are the engine of leaderboard moves — a “bogey-free round with 6 birdies” is how a 66 happens on a par-72.',
      expert: 'Scoring vocabulary maps directly to the board’s arithmetic: each birdie decrements TO PAR by one, each bogey increments it. Announcers speaking “he’s two birdies from the lead” are just doing subtraction in bird-language.',
    },
  },
  {
    id: 'glf-kid-4', level: 'kid',
    board: { kind: 'golf-hole', hole: 3, par: 4, player: 'Reyes', strokes: 5, note: 'HOLED OUT IN 5' },
    prompt: 'Reyes needed 5 strokes on a PAR 4. What’s that score called?',
    options: ['A bogey', 'A birdie', 'An eagle'],
    answer: 0,
    title: 'One over par on a hole = bogey',
    exp: {
      kid: 'One more stroke than par is a BOGEY. Not a disaster — just one step backward.',
      beginner: 'Bogey = 1 over on the hole; it adds +1 to your tournament score. Two over is a double bogey, three over a triple.',
      intermediate: 'Golf’s asymmetry: bogeys are easier to make than birdies, so avoiding big numbers matters more than chasing hero shots. One triple bogey erases three birdies of work.',
      expert: 'Risk management IS golf scoring: the penal shots (water, out-of-bounds) create fat “double-or-worse” tails. Elite players’ edge is less about more birdies and more about fewer others — bogey avoidance correlates with winning as strongly as birdie rate.',
    },
  },
  {
    id: 'glf-kid-5', level: 'kid',
    board: { kind: 'golf', rows: [
      { pos: '1', name: 'Lindqvist', toPar: '-4', thru: 'F' },
      { pos: '2', name: 'Moss', toPar: 'E', thru: 'F' },
    ], note: 'ROUND COMPLETE — PAR 72 COURSE' },
    prompt: 'Lindqvist shot 68 on a par-72 course. Is 68 a GOOD score?',
    options: ['Yes — 4 strokes better than the course’s par', 'No — less than 72 means she fell short', 'Only if someone shot 80'],
    answer: 0,
    title: 'Lower round = better round',
    exp: {
      kid: 'Remember: golf is flipped! The course expects 72 strokes; she only needed 68. Four better than expected — great round!',
      beginner: '68 on a par-72 = 4 under (−4). Rounds in the 60s are excellent at any level; the board shows it as −4, the raw 68 and the relative score are the same fact.',
      intermediate: 'Boards toggle between raw strokes (68) and to-par (−4). To-par travels across courses: −4 means the same thing on a par-70 (66) and a par-72 (68) — that’s why broadcasts prefer it.',
      expert: 'Course pars differ (70–72 typically) precisely so raw totals never compare cleanly across venues — 268 might win one tournament and miss a playoff at another. To-par is golf’s exchange rate; always read the board in that currency.',
    },
  },
  {
    id: 'glf-kid-6', level: 'kid',
    board: { kind: 'golf', rows: [
      { pos: '1', name: 'Varga', toPar: '-3', thru: '9' },
      { pos: '2', name: 'Reyes', toPar: 'E', thru: '10' },
      { pos: '3', name: 'Okafor', toPar: '+2', thru: '8' },
    ] },
    prompt: 'Reyes shows “E” in the TO PAR column. What does E mean?',
    options: ['Even — exactly level with par', 'Eliminated', 'Eagle on the last hole'],
    answer: 0,
    title: 'E = even par',
    exp: {
      kid: '“E” stands for EVEN — Reyes has used exactly as many strokes as par so far. Not ahead, not behind!',
      beginner: 'Even par (E) is the zero point of the golf scale: birdies push you into minus territory, bogeys into plus. E thru 10 = 10 holes of exactly-expected golf.',
      intermediate: 'E is a real position, not a placeholder — many tournaments are won near even par when conditions are brutal. “Level par is a good score today” is commentary shorthand for course difficulty.',
      expert: 'Watching where E sits on the leaderboard calibrates the course instantly: E in 40th place means a birdie-fest; E in 5th means carnage. The distance between E and the lead is the single fastest read of playing conditions.',
    },
  },

  // ── beginner ──────────────────────────────────────────────────────────────
  {
    id: 'glf-beg-1', level: 'beginner',
    board: { kind: 'golf-hole', hole: 15, par: 5, player: 'Moss', strokes: 3, note: 'HOLED OUT IN 3' },
    prompt: 'Moss finished the PAR 5 in 3 strokes. What did she just make?',
    options: ['An eagle — 2 under on the hole', 'A birdie', 'A condor'],
    answer: 0,
    title: 'Two under on a hole = eagle',
    exp: {
      kid: 'Two strokes better than par is an EAGLE — a bigger, rarer bird than a birdie!',
      beginner: 'The ladder: birdie (−1), eagle (−2), albatross (−3). Eagles usually come on par 5s — reach the green in two big shots, then hole the putt.',
      intermediate: 'Par 5s are the scoring holes: pros treat them as birdie-or-better opportunities because two well-struck shots can reach the green. Tournament strategy is largely “capitalize on the par 5s, survive the hard par 4s.”',
      expert: 'Eagles move leaderboards two ticks at once, which is why Sunday par-5 decisions (go for the green over water vs lay up) are the most win-probability-dense choices in the sport. The scoreboard reflects strategy: an eagle at the right moment rewrites the final hour.',
    },
  },
  {
    id: 'glf-beg-2', level: 'beginner',
    board: { kind: 'golf', rows: [
      { pos: '1', name: 'Okafor', toPar: '-5', thru: '12' },
      { pos: '2', name: 'Varga', toPar: '-3', thru: 'F' },
    ] },
    prompt: 'Okafor’s line says “thru 12.” What does that mean?',
    options: ['He has completed 12 holes of his round today', 'He made 12 pars', 'He’s ranked 12th'],
    answer: 0,
    title: '“Thru” counts holes completed',
    exp: {
      kid: '“Thru 12” means he’s played 12 of the 18 holes so far today. Six more to go!',
      beginner: 'THRU tracks round progress: thru 12 = finished holes 1–12 (or his 12th hole if he started on the back nine). “F” = finished the round.',
      intermediate: 'Thru contextualizes the score: −5 thru 12 with six holes left could get better OR worse, while −3 F is locked in. Leaders still on the course carry both upside and risk.',
      expert: 'Pro reading habit: pair TO PAR with THRU and the remaining holes’ difficulty. −5 thru 12 with the easy par-5 15th coming is a projected −6/−7; the same score with a brutal closing stretch is fragile. Golf boards are forecasts, not results, until the F appears.',
    },
  },
  {
    id: 'glf-beg-3', level: 'beginner',
    board: { kind: 'golf', rows: [
      { pos: '—', name: 'Reyes', toPar: '-2', thru: 'F' },
    ], note: 'ROUND: 70 · COURSE PAR 72' },
    prompt: 'Reyes shot 70 on a par-72 course. What does the TO PAR column show?',
    options: ['−2', '+2', 'E'],
    answer: 0,
    title: 'Strokes − par = the score that matters',
    exp: {
      kid: 'The course expects 72; Reyes took 70. That’s 2 fewer — so the board shows minus 2!',
      beginner: 'To-par arithmetic: 70 − 72 = −2. Every board number is this subtraction, updated hole by hole as pars, birdies and bogeys accumulate.',
      intermediate: 'Multi-round totals stack the same way: rounds of 70 and 69 on a par-72 = 139, which is −5. The leaderboard usually shows the cumulative to-par plus today’s round in parentheses.',
      expert: 'Being fluent both directions (raw ↔ to-par) lets you sanity-check any graphic: “−11 total after three rounds on a par-71” must equal 202. Broadcasters occasionally get this wrong late on Sundays; now you can catch them.',
    },
  },
  {
    id: 'glf-beg-4', level: 'beginner',
    board: { kind: 'golf-hole', hole: 8, par: 3, player: 'Lindqvist', strokes: 5, note: 'HOLED OUT IN 5' },
    prompt: 'Lindqvist took 5 strokes on a PAR 3. What lands on her scorecard?',
    options: ['A double bogey (+2)', 'A bogey (+1)', 'A triple bogey (+3)'],
    answer: 0,
    title: 'Two over on a hole = double bogey',
    exp: {
      kid: 'Five strokes when par is 3 means 2 extra strokes — that’s a DOUBLE bogey. Ouch, but the round goes on!',
      beginner: '5 on a par 3 = +2 = double bogey. The over-par ladder: bogey (+1), double (+2), triple (+3)… each adds directly to the tournament score.',
      intermediate: 'Par 3s bite hard because there’s no recovery room: a tee shot in the water means hitting your THIRD shot after the penalty. Short holes, big numbers — the scorecard’s classic trap.',
      expert: 'Penalty mechanics are why doubles cluster on par 3s: water/OB converts one bad swing into two strokes lost (stroke + distance or drop penalties). Reading a leaderboard collapse usually traces to exactly one such hole — check the hole-by-hole and you’ll find the splash.',
    },
  },
  {
    id: 'glf-beg-5', level: 'beginner',
    board: { kind: 'golf', rows: [
      { pos: '1', name: 'Moss', toPar: '-8', thru: 'F' },
    ], note: 'ROUND 2 OF 4 COMPLETE' },
    prompt: 'The note says “Round 2 of 4.” How long is a standard professional tournament?',
    options: ['72 holes — four 18-hole rounds over four days', 'One 18-hole round', '36 holes over a weekend'],
    answer: 0,
    title: 'Four rounds, 72 holes, one champion',
    exp: {
      kid: 'Pros play the course four times — 18 holes a day for four days. All the strokes add up to one big total!',
      beginner: 'Standard format: Thursday–Sunday, 18 holes each day, 72 total. The winner has the lowest cumulative score. Halfway (36 holes), a “cut” trims the field.',
      intermediate: 'The cut typically keeps the top ~65 and ties for the weekend; miss it and the tournament ends Friday with no pay. That’s why Friday afternoon scoreboards show frantic “cut line” drama alongside the lead.',
      expert: 'Structure shapes strategy: rounds 1–2 are about staying alive relative to the cut line, “moving day” (round 3) is for position, Sunday is for winning. The same score means different things by day — a 68 Thursday builds cushion; a 68 Sunday from three back is a charge.',
    },
  },
  {
    id: 'glf-beg-6', level: 'beginner',
    board: { kind: 'golf', rows: [
      { pos: '1', name: 'Varga', toPar: '-7', thru: '6' },
      { pos: '2', name: 'Okafor', toPar: '-6', thru: '17' },
    ] },
    prompt: 'Varga is thru 6, Okafor thru 17 — different holes played. How can the board compare them fairly?',
    options: ['TO PAR is cumulative — it already accounts for holes played', 'It can’t — wait for both to finish', 'By strokes only'],
    answer: 0,
    title: 'To-par makes mid-round scores comparable',
    exp: {
      kid: 'The minus number already includes every hole each player has finished. Varga is 7 better than expected so far, Okafor 6 — Varga leads right now, even having played fewer holes.',
      beginner: 'To-par is a running total versus expectation, so “−7 thru 6” and “−6 thru 17” compare directly: Varga has simply gained more on par so far. Holes remaining are opportunity, not deficit.',
      intermediate: 'The nuance is trajectory: Varga (−7 thru 6!) is on a torrid pace with 12 holes of both upside and risk; Okafor’s −6 is nearly banked. Leaders with holes in hand are volatile leaders.',
      expert: 'Projection is the expert layer: pace like −7 thru 6 rarely sustains (regression per remaining hole is real), so live win models often favor the nearly-finished −6. When TV shows “projected” standings, it’s blending to-par with remaining-hole expectations — you can approximate it in your head with just these two columns.',
    },
  },

  // ── intermediate ──────────────────────────────────────────────────────────
  {
    id: 'glf-int-1', level: 'intermediate',
    board: { kind: 'golf-hole', hole: 11, par: 5, player: 'Okafor', strokes: 2, note: 'HOLED HIS SECOND SHOT!' },
    prompt: 'Okafor holed his SECOND shot on a par 5. What is this extremely rare score?',
    options: ['An albatross (−3), also called a double eagle', 'An eagle (−2)', 'A hole-in-one'],
    answer: 0,
    title: 'The albatross: 3 under on one hole',
    exp: {
      kid: 'Three strokes better than par — the rarest bird of all! It’s called an ALBATROSS. Some people call it a double eagle.',
      beginner: '2 on a par 5 = −3 = albatross. Rarer than a hole-in-one: it needs a huge drive AND holing a long second shot. The board instantly drops him three shots.',
      intermediate: 'The full ladder: birdie −1, eagle −2, albatross −3, and the mythical condor (−4, a holed tee shot on a par 5) with only a handful ever claimed. Albatrosses are so rare they famously swing entire tournaments.',
      expert: 'Scoreboard impact is what makes it strategic lore: a single hole moving a player −3 reorders a Sunday leaderboard in one swing. Odds are estimated around a million-plus to one per round for amateurs — when the board shows one, the roar tells you before the graphic does.',
    },
  },
  {
    id: 'glf-int-2', level: 'intermediate',
    board: { kind: 'golf-hole', hole: 16, par: 3, player: 'Lindqvist', strokes: 1, note: 'HOLE-IN-ONE!' },
    prompt: 'A hole-in-one on the par-3 16th! What does it do to her score?',
    options: ['−2 on the hole — an ace scores as an eagle', '−1 — aces count as birdies', '−3 automatically'],
    answer: 0,
    title: 'An ace on a par 3 = eagle',
    exp: {
      kid: 'One swing, in the hole! On a par 3, that’s 2 strokes better than expected — the same value as an eagle, with a special name: an ACE!',
      beginner: 'The ace is the event; the score is arithmetic: 1 on a par 3 = −2 = eagle. (An ace on a par 4 — vanishingly rare — would be an albatross.)',
      intermediate: 'This shows the system’s consistency: names attach to the RELATIVE score, not the act. The board doesn’t have an “ace” column — it just subtracts 2, same as holing out from a bunker for eagle.',
      expert: 'Aces run roughly 12,000-to-1 per round for pros on a given par 3 — rare enough for insurance policies on hole-in-one prizes, common enough that big tournaments see a few. Score-wise it’s “only” an eagle; narrative-wise it’s the sport’s lightning strike.',
    },
  },
  {
    id: 'glf-int-3', level: 'intermediate',
    board: { kind: 'golf', rows: [
      { pos: '1', name: 'Moss', toPar: '-12', thru: 'F' },
      { pos: '1', name: 'Varga', toPar: '-12', thru: 'F' },
    ], note: 'AFTER 72 HOLES' },
    prompt: 'Two players finish 72 holes tied at −12. How is the champion decided?',
    options: ['A playoff — extra holes until someone wins', 'They share the trophy', 'Back-nine scores decide it'],
    answer: 0,
    title: 'Ties at the top go to a playoff',
    exp: {
      kid: 'They keep playing! The tied players go back out for extra holes until one beats the other — winner takes the trophy.',
      beginner: 'Stroke-play ties for FIRST are broken on the course, not the scorecard: a playoff. Formats vary by event — sudden death (first hole won wins) or a short aggregate (2–4 holes, lowest total).',
      intermediate: 'Only the WIN goes to a playoff — every other position splits prize money among tied players. That asymmetry makes 72nd-hole putts for solo-second worth real money even with no playoff at stake.',
      expert: 'Format literacy: some events use sudden death immediately, others play 3–4 hole aggregates first (majors differ from each other!). Knowing the event’s playoff format changes 72nd-hole strategy — protecting a tie is rational under aggregate formats, while sudden death rewards gambling for the outright win now.',
    },
  },
  {
    id: 'glf-int-4', level: 'intermediate',
    board: { kind: 'golf', rows: [
      { pos: '58', name: 'Reyes', toPar: '+1', thru: 'F' },
    ], note: 'ROUND 2 COMPLETE · PROJECTED CUT: E' },
    prompt: 'After 36 holes Reyes is +1 and the projected CUT is E (even). What does that mean for him?',
    options: ['He’s outside the line — as it stands, his tournament ends today', 'He’s safely into the weekend', 'He starts round 3 with a penalty'],
    answer: 0,
    title: 'The cut line: make it or go home',
    exp: {
      kid: 'Halfway through, only the best players get to keep playing. The line is at even par — Reyes is one worse than that, so right now he’s OUT unless things change.',
      beginner: 'After round 2, the field is cut (commonly the top 65 and ties). “Projected cut E” means even par currently makes the weekend; +1 misses. The line MOVES as scores come in — cut-line sweating is a Friday ritual.',
      intermediate: 'Missing the cut = no weekend, no prize money at most events — which is why a Friday-evening bogey can cost more, financially, than a Sunday one. Players at the line late on Friday play visibly desperate golf.',
      expert: 'The projection mechanics: the line is a live quantile of the field’s scores, so afternoon scoring conditions literally move it under players who already finished. Expert viewers track “number at the line” (how many players sit exactly on it) to predict movement — ties at 65th push the line, and the rulebook’s “and ties” clause decides how many survive.',
    },
  },
  {
    id: 'glf-int-5', level: 'intermediate',
    board: { kind: 'golf', rows: [
      { pos: '1', name: 'Okafor', toPar: '-9', thru: 'F' },
    ], note: 'ROUNDS: 70 + 68 + 69 + 72 = 279 · PAR 72' },
    prompt: 'Verify the board: rounds of 70, 68, 69, 72 on a par-72 course. Is −9 right?',
    options: ['Yes — 279 total vs 288 par = −9', 'No — it should be −7', 'No — it should be +9'],
    answer: 0,
    title: 'Four-round arithmetic',
    exp: {
      kid: 'Add the four rounds: 70+68+69+72 = 279. Four rounds of par-72 would be 288. He beat the target by 9 — minus 9. The board checks out!',
      beginner: 'Tournament to-par = total strokes − (rounds × par). 279 − 288 = −9. Each round’s own to-par (−2, −4, −3, E) also sums to −9 — the two computations always agree.',
      intermediate: 'Per-round to-pars are how form is read: (−2, −4, −3, E) shows Sunday pressure flattening a great week. The identical −9 built as (E, E, E, −9) tells a completely different story — one historic final round.',
      expert: 'Round-shape analysis is real: leaders protecting a Sunday lead average over par relative to the field (pressure + conservative play), while “chasers” shoot the low finals. Given only the four round numbers, you can reconstruct the tournament’s narrative arc with surprising accuracy.',
    },
  },
  {
    id: 'glf-int-6', level: 'intermediate',
    board: { kind: 'golf', rows: [
      { pos: '1', name: 'Varga', toPar: '-14', thru: 'F' },
      { pos: '2', name: 'Moss', toPar: '-13', thru: '16' },
    ], note: 'SUNDAY — FINAL ROUND' },
    prompt: 'Varga is finished at −14; Moss is −13 with holes 17 and 18 to play. What’s the live situation?',
    options: ['Moss needs one birdie in two holes to force a playoff, two to win', 'Varga has already won', 'Moss must eagle 18'],
    answer: 0,
    title: 'The clubhouse lead',
    exp: {
      kid: 'Varga is done and can’t improve — she “posted” minus 14. Moss still has two holes: one birdie makes a tie, two birdies wins!',
      beginner: 'A finished score is a target: Moss (−13) needs −1 over her last two holes to tie (playoff) or −2 to win outright. Any bogey and it’s over. This is golf’s classic endgame geometry.',
      intermediate: '“Posting a number” pressures everyone behind: the finished player’s score is certain while the chaser faces execution risk on every remaining shot. Clubhouse leaders win more often than raw win-probability suggests — certainty is worth strokes.',
      expert: 'Endgame strategy flows from the target: needing −1 in two holes, Moss plays 17 conservatively only if 18 is birdieable (reachable par 5?), else attacks now. Course-closing design (many tours end on a gettable 5) exists precisely to make these Sunday arithmetic problems dramatic. Read THRU + deficit + closing-hole pars and you can call the strategy before the players do.',
    },
  },

  // ── expert ────────────────────────────────────────────────────────────────
  {
    id: 'glf-exp-1', level: 'expert',
    board: { kind: 'golf-match', p1: 'Moss', p2: 'Reyes', status: 'MOSS WINS 3&2', thru: '16', note: 'MATCH PLAY' },
    prompt: 'The match-play result reads “3&2.” What exactly does that notation mean?',
    options: ['Moss led by 3 holes with only 2 to play — the match ended on the 16th', 'Moss won 3 sets to 2', 'Moss won by 3 strokes over the last 2 holes'],
    answer: 0,
    title: 'Reading “3&2”',
    exp: {
      kid: 'In match play you win HOLES, not strokes. “3&2” means Moss was 3 holes ahead with only 2 holes left — Reyes couldn’t catch up, so the match ended early!',
      beginner: 'Match play scores each hole as win/lose/tie. When your lead exceeds the holes remaining, the match is over: 3 up with 2 to play = 3&2, finished on hole 16. “1 up” means it went the full 18.',
      intermediate: 'The notation grammar: “N&M” = N holes up, M remaining (N > M always). Biggest possible is 10&8. “2 up” (no &) = won at the 18th by two; “at the 19th” = extra holes after a tie.',
      expert: 'Match play inverts stroke-play values: a 9 on one hole costs exactly one hole — the same as a near-miss par. That containment of disasters is why match play produces upsets and aggressive lines stroke play never sees, and why some players’ games “fit” one format over the other.',
    },
  },
  {
    id: 'glf-exp-2', level: 'expert',
    board: { kind: 'golf-match', p1: 'Varga', p2: 'Lindqvist', status: 'VARGA 3 UP', thru: '15', note: 'MATCH PLAY — DORMIE' },
    prompt: 'Varga is 3 UP with 3 holes to play, and the board says “DORMIE.” What does dormie mean?',
    options: ['Her lead equals the holes remaining — she can’t lose in regulation', 'She must win the next hole', 'The match is suspended'],
    answer: 0,
    title: 'Dormie: the unlosable position',
    exp: {
      kid: 'Varga is ahead by exactly as many holes as are left. Even if she loses ALL of them, the worst is a tie — she cannot lose the match in the last 3 holes!',
      beginner: 'Dormie = lead equals holes remaining (3 up, 3 to play). The leader needs just one hole won or halved to close it out; the trailer must win EVERY remaining hole just to force extra holes.',
      intermediate: 'Dormie changes both players’ math: the leader can play safe (a halve anywhere ends it), while the trailer must attack flags with zero margin. Watch the leader aim for the middle of every green — the halve is her friend.',
      expert: 'Note the fine print: dormie guarantees no regulation loss, but competitions that require an outright winner continue to extra holes after a tie — so dormie is “can’t lose in 18,” not “can’t lose.” In team events where halved matches split points, dormie already banks half a point, which changes captaincy decisions about pressing or protecting.',
    },
  },
  {
    id: 'glf-exp-3', level: 'expert',
    board: { kind: 'golf-match', p1: 'Okafor', p2: 'Moss', status: 'ALL SQUARE', thru: '14', note: 'HOLE 14: BOTH MADE 4' },
    prompt: 'On the 14th both players made 4, and the status stayed ALL SQUARE. What happened to the hole?',
    options: ['It was halved — tied holes move no score in match play', 'It carries over to the 15th', 'It’s replayed at the end'],
    answer: 0,
    title: 'The halved hole',
    exp: {
      kid: 'Same score on the hole = nobody wins it. The hole is “halved” and the match stays exactly as it was. On to the next!',
      beginner: 'Match play holes have three outcomes: won, lost, halved. A halve moves nothing — there’s no carrying over (that’s a different game called skins). “All square” = level match.',
      intermediate: 'Halves are strategically alive: the player already on the green in two can watch her opponent’s troubles and safely two-putt for a halve, or press for the win. Concessions (“that putt’s good”) exist only in match play and are part of halve tactics.',
      expert: 'The concession is genuine strategy: giving short putts early builds an expectation you can weaponize by NOT conceding a knee-knocker on the 17th. Since halved holes preserve state, match play is a Markov chain the players actively manage — very different from stroke play’s pure accumulation.',
    },
  },
  {
    id: 'glf-exp-4', level: 'expert',
    board: { kind: 'golf', rows: [
      { pos: '1', name: 'Reyes', toPar: '-11', thru: 'F' },
      { pos: '1', name: 'Varga', toPar: '-11', thru: 'F' },
      { pos: '1', name: 'Moss', toPar: '-11', thru: 'F' },
    ], note: '3-WAY PLAYOFF — AGGREGATE: 3 HOLES' },
    prompt: 'Three players tied; the playoff is a 3-hole AGGREGATE. How does it differ from sudden death?',
    options: ['All three play 3 holes; lowest TOTAL wins (sudden death only if still tied)', 'First birdie wins immediately', 'Highest single-hole score is eliminated each hole'],
    answer: 0,
    title: 'Aggregate playoffs: a mini-tournament',
    exp: {
      kid: 'Instead of “first to win a hole,” they all play 3 extra holes and add them up — like a tiny 3-hole tournament. Still tied after that? THEN it’s hole-by-hole sudden death.',
      beginner: 'Aggregate = stroke play over a fixed set of holes (2, 3 or 4 depending on the event); sudden death = match-play-style instant elimination. Aggregate reduces the luck of one bad bounce deciding everything.',
      intermediate: 'The format changes strategy: in sudden death you must match heroics immediately; in aggregate you can accept a par on a hard hole and attack the gettable one. Multi-player playoffs add leaderboard-watching WITHIN the playoff.',
      expert: 'Each major championship historically chose differently — full-round playoffs (now largely abandoned), multi-hole aggregates, immediate sudden death — and regular tour events mostly use sudden death. Because formats change by event and era, the expert habit is checking the playoff format BEFORE judging 72nd-hole decisions: laying up to secure a tie is smart into an aggregate, timid into sudden death.',
    },
  },
  {
    id: 'glf-exp-5', level: 'expert',
    board: { kind: 'golf', rows: [
      { pos: '1', name: 'Lindqvist', toPar: '-10', thru: '11' },
      { pos: '2', name: 'Okafor', toPar: '-8', thru: '13' },
      { pos: '3', name: 'Reyes', toPar: '+3', thru: '12' },
    ], note: 'UNDER PAR SHOWN IN RED, OVER PAR IN BLUE/BLACK' },
    prompt: 'On golf broadcasts, under-par scores are traditionally shown in RED. Why is that worth knowing?',
    options: ['Red means GOOD in golf — the reverse of most scoreboard color codes', 'Red flags rule violations', 'Red marks players on the cut line'],
    answer: 0,
    title: 'Red numbers are good numbers',
    exp: {
      kid: 'In most sports red means danger — in golf, red means UNDER par, which is great! A board full of red numbers is a board full of good golf.',
      beginner: 'The convention: red = under par, black (or blue/green on some broadcasts) = over par or even. Scan a leaderboard: the red numbers at the top are the story.',
      intermediate: 'The convention is old accounting-in-reverse (red ink = negative = under par) and it’s near-universal across tours and graphics packages. It makes a wall of scores parseable in half a second — color IS information.',
      expert: 'Cross-sport literacy point: color semantics are sport-specific conventions, not universals — golf’s red-is-good coexists with soccer’s red-card-is-bad on the same TV. Expert scoreboard reading means loading the right convention set per sport; this game has been training exactly that skill all along.',
    },
  },
  {
    id: 'glf-exp-6', level: 'expert',
    board: { kind: 'golf-match', p1: 'Moss', p2: 'Varga', status: 'MOSS 1 UP', thru: '17', note: 'STROKES ON 17: MOSS 7, VARGA 4' },
    prompt: 'On the 17th Moss made a disastrous 7 to Varga’s 4 — yet Moss is still 1 UP. How?',
    options: ['She lost only that one hole — match play caps any disaster at −1 hole', 'The board is wrong', 'A 7 is disqualifying'],
    answer: 0,
    title: 'Match play forgives blowups',
    exp: {
      kid: 'In match play, losing a hole by 3 strokes counts the same as losing by 1 — it’s just ONE hole. Moss was 2 up, lost the hole, now she’s 1 up with one to play!',
      beginner: 'Hole outcomes are binary (win/lose/halve), so a triple bogey against a par costs exactly what a one-stroke loss costs: one hole. Moss went from 2 up to 1 up — the 7 is already irrelevant.',
      intermediate: 'This is the format’s core divergence from stroke play, where that 7 (+3) haunts the total forever. Match play resets every hole; it rewards recovery mentality and punishes nothing retroactively.',
      expert: 'Strategic consequence: in match play, once a hole is going badly, STOP rescuing it — pick up (concede the hole) and save energy, because minimizing the damage below “lost hole” has zero value. Stroke play demands grinding for the 6 instead of the 7; match play says walk to the next tee. Same sport, opposite optimization — and the scoreboard format is what flips it.',
    },
  },
];
