// Read the Score — MLB bank. Scoring-RULE scenarios only (evergreen); team names are
// fictional set dressing. 6 scenarios per tier × 4 tiers. Pure data, zero RN imports.
import type { ScoreScenario } from '../readTheScore';

export const MLB_SCENARIOS: ScoreScenario[] = [
  // ── kid ────────────────────────────────────────────────────────────────────
  {
    id: 'mlb-kid-1', level: 'kid',
    board: { kind: 'baseball', away: { name: 'Cyclones', abbr: 'CYC', score: 5 }, home: { name: 'Otters', abbr: 'OTT', score: 2 },
      inning: 4, half: 'top', balls: 1, strikes: 1, outs: 1, bases: [false, false, false] },
    prompt: 'Who is winning?',
    options: ['Cyclones', 'Otters', 'It’s a tie'],
    answer: 0,
    title: 'Cyclones lead 5–2 — most runs wins',
    exp: {
      kid: 'The big numbers are runs. The Cyclones have 5 and the Otters have 2, so the Cyclones are ahead.',
      beginner: 'In baseball the score counts RUNS — one run each time a player goes all the way around the bases and touches home plate. 5 runs beats 2.',
      intermediate: 'Runs are the only score that matters — hits and outs are on the board too, but only runs decide the game. The away team (top row) leads 5–2.',
      expert: 'The linescore convention: away team on top, home team below, and the run total is the game score. Everything else on the board (count, outs, baserunners) describes the current situation, not who wins.',
    },
  },
  {
    id: 'mlb-kid-2', level: 'kid',
    board: { kind: 'baseball', away: { name: 'Sailors', abbr: 'SAI', score: 3 }, home: { name: 'Otters', abbr: 'OTT', score: 3 },
      inning: 6, half: 'bottom', balls: 0, strikes: 2, outs: 2, bases: [true, false, false] },
    prompt: 'The OUTS lamps show 2. How many more outs before the batting team must stop?',
    options: ['1 more out', '2 more outs', '3 more outs'],
    answer: 0,
    title: 'Three outs end the turn at bat',
    exp: {
      kid: 'A team gets 3 outs each turn. Two lamps are lit, so one more out and their turn is over.',
      beginner: 'Each half-inning the batting team keeps hitting until it makes 3 outs. With 2 outs showing, the very next out ends the half-inning.',
      intermediate: 'Outs reset every half-inning. At 2 outs the defense needs just one more — that’s why announcers say a team is “an out away” from ending a threat.',
      expert: 'With two outs, everything changes: runners go on contact, there are no sacrifice plays, and the defense takes the easiest out anywhere. The board’s out lamps are the fastest read of how urgent the situation is.',
    },
  },
  {
    id: 'mlb-kid-3', level: 'kid',
    board: { kind: 'baseball', away: { name: 'Cyclones', abbr: 'CYC', score: 1 }, home: { name: 'Harbor Cats', abbr: 'HBC', score: 0 },
      inning: 3, half: 'top', balls: 2, strikes: 0, outs: 0, bases: [false, false, false] },
    prompt: 'The board shows ▲ 3 (top of the 3rd). Which team is batting right now?',
    options: ['Cyclones — the visiting team', 'Harbor Cats — the home team', 'Both teams'],
    answer: 0,
    title: 'Top = visitors bat, bottom = home bats',
    exp: {
      kid: 'The ▲ means “top” of the inning. The visiting team always bats in the top, and the home team bats in the bottom.',
      beginner: 'Every inning has two halves: the visitors hit in the TOP (▲), then the home team hits in the BOTTOM (▼). The home team always bats last.',
      intermediate: 'Visitors bat first by rule, which gives the home team the “last at-bat” — a real advantage late in close games, because they always know exactly how many runs they need.',
      expert: 'Batting last shapes late-game strategy: in the bottom of the 9th the home side plays for exactly the runs it needs, while the visitors must build a lead big enough to survive one final answer.',
    },
  },
  {
    id: 'mlb-kid-4', level: 'kid',
    board: { kind: 'baseball', away: { name: 'Sailors', abbr: 'SAI', score: 2 }, home: { name: 'Otters', abbr: 'OTT', score: 4 },
      inning: 5, half: 'bottom', balls: 1, strikes: 0, outs: 1, bases: [false, true, false] },
    prompt: 'Look at the little diamond. Where is the runner standing?',
    options: ['First base', 'Second base', 'Third base'],
    answer: 1,
    title: 'The lit base on the diamond is second',
    exp: {
      kid: 'The tiny diamond copies the real field. The glowing corner is second base — that’s where the runner is.',
      beginner: 'The mini diamond lights up each base that has a runner. Here only the top corner (second base) is lit, so there’s one runner, on second.',
      intermediate: 'Reading the diamond tells you the threat level: a runner on second is in “scoring position” — a normal single usually brings that runner home.',
      expert: 'Scoring position (2nd or 3rd) is the key split on the bases display. A runner on second scores on most singles; a runner on first usually needs two more hits or an extra-base hit. Broadcasters’ “RISP” stat comes straight from this read.',
    },
  },
  {
    id: 'mlb-kid-5', level: 'kid',
    board: { kind: 'baseball', away: { name: 'Cyclones', abbr: 'CYC', score: 3 }, home: { name: 'Otters', abbr: 'OTT', score: 3 },
      inning: 5, half: 'bottom', balls: 0, strikes: 0, outs: 0, bases: [false, false, false] },
    prompt: 'The Otters hit a home run with nobody on base. How many runs do they score?',
    options: ['1 run', '2 runs', '4 runs'],
    answer: 0,
    title: 'A solo home run scores exactly 1',
    exp: {
      kid: 'A home run lets the batter run all the way around and touch home — that’s 1 run. Nobody else was on base, so it’s 1 total.',
      beginner: 'A home run scores the batter PLUS every runner already on base. Empty bases + a homer = 1 run (a “solo” home run).',
      intermediate: 'Home run value depends entirely on the baserunners: solo = 1, with the bases loaded it’s 4 (a grand slam). The swing is the same; the situation sets the payoff.',
      expert: 'This is why the bases display matters more than the swing: the same home run is worth 1–4 runs depending on traffic. Teams built around solo homers score in ones; teams that put runners on first turn the same power into crooked numbers.',
    },
  },
  {
    id: 'mlb-kid-6', level: 'kid',
    board: { kind: 'baseball', away: { name: 'Sailors', abbr: 'SAI', score: 0 }, home: { name: 'Harbor Cats', abbr: 'HBC', score: 1 },
      inning: 2, half: 'top', balls: 2, strikes: 1, outs: 0, bases: [false, false, false] },
    prompt: 'The count shows B ●● and S ●. What do those two numbers mean?',
    options: ['Balls and strikes on this batter', 'Runs and hits', 'Innings left'],
    answer: 0,
    title: 'The count: 2 balls, 1 strike',
    exp: {
      kid: 'B is for balls (bad pitches the batter didn’t swing at) and S is for strikes. This batter has 2 balls and 1 strike.',
      beginner: 'Every batter gets a fresh count. Pitches out of the strike zone (not swung at) are balls; strikes come from swings-and-misses, called strikes, or foul balls. It resets for each new batter.',
      intermediate: 'The count is a mini battle: 4 balls = a free walk to first, 3 strikes = out. A count like 2–1 is said “two and one,” balls always first.',
      expert: 'Counts define leverage. Hitter-friendly counts (2–0, 3–1) force the pitcher into the zone, so hitters sit on fastballs; pitcher-friendly counts (0–2, 1–2) let the pitcher waste chase pitches. Reading the count tells you who controls the at-bat.',
    },
  },

  // ── beginner ──────────────────────────────────────────────────────────────
  {
    id: 'mlb-beg-1', level: 'beginner',
    board: { kind: 'baseball', away: { name: 'Cyclones', abbr: 'CYC', score: 2 }, home: { name: 'Otters', abbr: 'OTT', score: 2 },
      inning: 7, half: 'bottom', balls: 3, strikes: 2, outs: 1, bases: [false, false, false] },
    prompt: 'The count is 3–2. If the next pitch is ball four, what happens?',
    options: ['The batter walks to first base', 'The batter is out', 'The count resets to 0–0'],
    answer: 0,
    title: 'Ball four = a walk',
    exp: {
      kid: 'Four balls means the batter gets to go to first base for free. That’s called a walk.',
      beginner: 'A 3–2 count is a “full count” — the next ball is the fourth, and four balls award the batter first base automatically (a base on balls, or walk).',
      intermediate: 'On a full count something must give: ball four walks him, strike three ends the at-bat, and a foul keeps it alive at 3–2. That’s why full counts are the tensest pitches in an inning.',
      expert: 'The 3–2 payoff pitch is maximum leverage for both sides: the pitcher can’t nibble (a miss is a free baserunner) and the hitter must defend the zone (a called strike ends it). Expect something in or near the zone — and runners often moving.',
    },
  },
  {
    id: 'mlb-beg-2', level: 'beginner',
    board: { kind: 'baseball', away: { name: 'Sailors', abbr: 'SAI', score: 4 }, home: { name: 'Harbor Cats', abbr: 'HBC', score: 1 },
      inning: 5, half: 'bottom', balls: 1, strikes: 2, outs: 2, bases: [false, false, false] },
    prompt: 'The batter has 2 strikes. What happens if the next pitch is a swing and a miss?',
    options: ['Strikeout — the batter is out', 'The batter gets one more chance', 'It’s a ball'],
    answer: 0,
    title: 'Strike three is a strikeout',
    exp: {
      kid: 'Three strikes and you’re out! A miss here would be strike three, so the batter would be out.',
      beginner: 'Three strikes make a strikeout. A swing-and-miss or a called strike in the zone ends this at-bat — and since there are already 2 outs, it would end the half-inning too.',
      intermediate: 'With 2 strikes, hitters shorten their swing and protect the plate — any strike ends the at-bat, but a foul ball does NOT (fouls can’t be strike three, except a bunted foul).',
      expert: 'Two-strike counts flip the approach: the hitter defends anything close, the pitcher expands the zone with chase pitches. The foul-ball exception is why two-strike at-bats can last 10+ pitches — a hitter can foul off strikes indefinitely.',
    },
  },
  {
    id: 'mlb-beg-3', level: 'beginner',
    board: { kind: 'baseball', away: { name: 'Cyclones', abbr: 'CYC', score: 3 }, home: { name: 'Otters', abbr: 'OTT', score: 5 },
      inning: 6, half: 'top', balls: 0, strikes: 1, outs: 2, bases: [true, false, false] },
    prompt: 'There are 2 outs and a fielder catches a fly ball. What happens next?',
    options: ['The half-inning ends and the teams switch', 'The batter gets to re-hit', 'Only the runner is out'],
    answer: 0,
    title: 'Out number three flips the inning',
    exp: {
      kid: 'A caught fly ball is an out. That’s the third out, so this team’s turn is over — the other team comes in to bat.',
      beginner: 'A ball caught before it bounces is an out. It’s the third out here, so the half-inning ends: the fielding team comes in to hit the bottom of the 6th.',
      intermediate: 'The third out ends the half-inning instantly and strands the runner on first — stranded runners don’t carry over. Next inning starts with empty bases and 0 outs.',
      expert: 'Runners left on base (LOB) are the hidden story of close games — every third out wipes the bases clean. A team can out-hit its opponent all night and lose because its baserunners kept dying at the third out.',
    },
  },
  {
    id: 'mlb-beg-4', level: 'beginner',
    board: { kind: 'baseball', away: { name: 'Sailors', abbr: 'SAI', score: 2 }, home: { name: 'Otters', abbr: 'OTT', score: 6 },
      inning: 9, half: 'top', balls: 0, strikes: 0, outs: 0, bases: [false, false, false] },
    prompt: 'The board shows inning 9. How many innings does a standard game have?',
    options: ['9 innings', '7 innings', '12 innings'],
    answer: 0,
    title: 'A regulation game is 9 innings',
    exp: {
      kid: 'Baseball games are 9 innings long. This is the 9th, so it’s the last one — unless the game is tied.',
      beginner: 'A regulation game lasts 9 innings, and each inning has a top and a bottom. If the score is tied after 9, the game keeps going with extra innings.',
      intermediate: 'Nine innings, no clock — the game ends when the outs run out, not when time does. That’s baseball’s defining feature: a trailing team always gets its full turns.',
      expert: 'No clock means no “running out the clock”: the leading team can’t kneel on the ball. Every game ends with 27 outs recorded against the losing side (or 24-plus for a home winner that skips its last at-bat).',
    },
  },
  {
    id: 'mlb-beg-5', level: 'beginner',
    board: { kind: 'baseball', away: { name: 'Cyclones', abbr: 'CYC', score: 4 }, home: { name: 'Harbor Cats', abbr: 'HBC', score: 4 },
      inning: 8, half: 'bottom', balls: 3, strikes: 2, outs: 1, bases: [true, true, true] },
    prompt: 'Bases loaded, count 3–2. The next pitch is ball four. What happens?',
    options: ['Every runner moves up one base and a run scores', 'Only the batter goes to first', 'The runners hold and the bases stay loaded'],
    answer: 0,
    title: 'A bases-loaded walk forces in a run',
    exp: {
      kid: 'The batter walks to first — but first base is taken! So everyone has to move up one base, and the runner on third walks home. Free run!',
      beginner: 'A walk gives the batter first base. With the bases loaded, each runner is forced up one base to make room — so the runner on third scores. It’s a run without a swing.',
      intermediate: 'This is a “force” chain: the batter’s right to first pushes every occupied base forward. A bases-loaded walk (or hit-by-pitch) scores a run automatically — the ultimate free run.',
      expert: 'Walking in a run is the cardinal pitching sin — it converts zero contact into a run. It’s why, with the bases loaded, pitchers must attack the zone and hitters can hunt a very small target: the pressure of the force chain does the work.',
    },
  },
  {
    id: 'mlb-beg-6', level: 'beginner',
    board: { kind: 'baseball', away: { name: 'Sailors', abbr: 'SAI', score: 1 }, home: { name: 'Otters', abbr: 'OTT', score: 2 },
      inning: 7, half: 'bottom', balls: 0, strikes: 0, outs: 0, bases: [false, false, false] },
    prompt: 'The board shows ▼ 7. What does that tell you?',
    options: ['Bottom of the 7th — the home team is batting', 'Top of the 7th — the visitors are batting', 'Seven outs remain'],
    answer: 0,
    title: '▼ = bottom half: the home team hits',
    exp: {
      kid: 'The ▼ arrow points down — that means the bottom of the inning, and the home team always bats in the bottom.',
      beginner: '▲ is the top half (visitors bat), ▼ is the bottom half (home team bats). So ▼ 7 = home team hitting in the 7th.',
      intermediate: 'The half-inning arrow also tells you who’s on defense — in the bottom half, the visitors are in the field. One glance gives you batter, pitcher, and how deep into the game you are.',
      expert: 'Half-inning notation compounds with the score: a home team leading in the bottom of a late inning is in maximum control (they may not even need their remaining at-bats), while trailing at home late means the win must come from this half of each inning.',
    },
  },

  // ── intermediate ──────────────────────────────────────────────────────────
  {
    id: 'mlb-int-1', level: 'intermediate',
    board: { kind: 'baseball', away: { name: 'Cyclones', abbr: 'CYC', score: 3 }, home: { name: 'Otters', abbr: 'OTT', score: 5 },
      inning: 9, half: 'top', balls: 0, strikes: 2, outs: 2, bases: [false, false, false] },
    prompt: 'The Otters (home) lead 5–3, two outs in the top of the 9th. If this batter strikes out, what happens?',
    options: ['Game over — the bottom of the 9th isn’t played', 'The Otters still bat in the bottom of the 9th', 'Extra innings begin'],
    answer: 0,
    title: 'A leading home team skips its last at-bat',
    exp: {
      kid: 'If the home team is already winning after the other team’s last turn, they don’t need to bat again — the game just ends.',
      beginner: 'The home team bats last, so if they’re ahead after the visitors finish the top of the 9th, the bottom half is unnecessary — the game ends immediately.',
      intermediate: 'That’s why final lines sometimes show 8½ innings: the home side never used its ninth at-bat. Batting last means never batting when the game is already won.',
      expert: 'The skipped bottom-ninth is baked into stats and strategy: home wins average fewer offensive innings, and a home closer protecting a lead in the top of the 9th is pitching to END the game, not to hand it back to his offense.',
    },
  },
  {
    id: 'mlb-int-2', level: 'intermediate',
    board: { kind: 'baseball', away: { name: 'Sailors', abbr: 'SAI', score: 4 }, home: { name: 'Harbor Cats', abbr: 'HBC', score: 4 },
      inning: 9, half: 'bottom', balls: 1, strikes: 1, outs: 2, bases: [false, false, false] },
    prompt: 'Tied 4–4, two outs in the bottom of the 9th. If this batter makes an out, what happens?',
    options: ['The game goes to extra innings', 'The game ends in a tie', 'A shootout decides it'],
    answer: 0,
    title: 'Tied after 9 → extra innings',
    exp: {
      kid: 'Baseball games can’t end in a tie. If it’s still tied after 9 innings, they just keep playing more innings until someone wins.',
      beginner: 'If the score is level after 9 complete innings, the game continues with a 10th inning, an 11th, and so on — full innings, both teams bat — until one team leads after a completed inning.',
      intermediate: 'Extras keep the same structure: visitors bat the top, home bats the bottom, and the home team still gets the last word. The game ends the moment an inning completes with the score unlevel — or instantly if the home team takes the lead in the bottom half.',
      expert: 'Note the asymmetry in extras: the road team must post runs and then defend them; the home team always bats knowing the target. That last-at-bat edge is why walk-offs exist and why extra-inning home records historically edge road records.',
    },
  },
  {
    id: 'mlb-int-3', level: 'intermediate',
    board: { kind: 'baseball', away: { name: 'Cyclones', abbr: 'CYC', score: 2 }, home: { name: 'Otters', abbr: 'OTT', score: 1 },
      inning: 6, half: 'bottom', balls: 1, strikes: 2, outs: 1, bases: [false, false, false] },
    prompt: 'The count is 1–2 and the batter fouls the next pitch into the stands. What’s the count now?',
    options: ['Still 1–2', '1–3 — strikeout', '2–2'],
    answer: 0,
    title: 'A foul can’t be strike three',
    exp: {
      kid: 'A foul ball counts as a strike — but it can never be the THIRD strike. So the batter stays alive at 1 ball, 2 strikes.',
      beginner: 'Fouls count as strikes only up to two. With two strikes, a foul changes nothing — the count holds at 1–2 and the at-bat continues. (Exception: a bunted foul with two strikes IS strike three.)',
      intermediate: 'This rule is what makes two-strike battles possible: a hitter can spoil tough pitches foul over and over, forcing the pitcher to keep throwing. Long at-bats wear pitchers down pitch by pitch.',
      expert: 'Spoiling pitches is a real skill — fouling off the pitcher’s best two-strike offering flips leverage back toward the hitter as the count deepens the pitcher’s workload. The bunt exception exists because bunting foul is too easy a way to spoil indefinitely.',
    },
  },
  {
    id: 'mlb-int-4', level: 'intermediate',
    board: { kind: 'baseball', away: { name: 'Sailors', abbr: 'SAI', score: 3 }, home: { name: 'Otters', abbr: 'OTT', score: 3 },
      inning: 8, half: 'bottom', balls: 0, strikes: 1, outs: 1, bases: [false, false, true] },
    prompt: 'Runner on third, one out. The batter hits a deep fly ball that IS caught. Can a run score?',
    options: ['Yes — the runner can tag up and score', 'No — the catch ends the play', 'Only if the ball is dropped'],
    answer: 0,
    title: 'The sacrifice fly: an out that scores a run',
    exp: {
      kid: 'Yes! The runner waits on third until the catch, then races home. Trading an out for a run is called a sacrifice fly.',
      beginner: 'After a catch, a runner may advance if he “tags up” — touches his base after the ball is caught, then runs. From third, a deep fly is plenty of time to score. The batter is out, the run counts.',
      intermediate: 'That’s a sacrifice fly: with fewer than two outs, a deep fly with a runner on third is practically a run. It’s why the defense plays the outfield shallow in this spot — to give the fielder a throwing chance.',
      expert: 'The sac fly only works with fewer than two outs (with two, the catch is out three and nothing counts). It shapes at-bats: the hitter just needs air and depth, so expect pitchers to work low, hunting a ground ball or strikeout instead.',
    },
  },
  {
    id: 'mlb-int-5', level: 'intermediate',
    board: { kind: 'baseball', away: { name: 'Cyclones', abbr: 'CYC', score: 1 }, home: { name: 'Harbor Cats', abbr: 'HBC', score: 2 },
      inning: 5, half: 'top', balls: 0, strikes: 0, outs: 1, bases: [true, false, false] },
    prompt: 'Runner on first, one out. A ground ball goes to the shortstop. What’s the easy out?',
    options: ['Step on second base — the runner is forced', 'Tag the batter at home', 'Throw to third'],
    answer: 0,
    title: 'The force play at second',
    exp: {
      kid: 'The runner on first HAS to run to second (the batter needs his base). So the fielder just steps on second base before the runner gets there — out!',
      beginner: 'When the batter hits a ground ball, the runner on first is FORCED to second. A forced runner is out if the fielder touches the base first — no tag needed. That’s a force out.',
      intermediate: 'Better yet, it can be two outs: step on second, then relay to first for the double play. A ground ball with a runner on first is the classic double-play setup — the reason a walk can turn into two outs.',
      expert: 'Force logic drives infield positioning: with a runner on first, middle infielders shade toward second to turn two. It also explains intentional walks with first base open — putting a runner ON first creates force outs everywhere behind him.',
    },
  },
  {
    id: 'mlb-int-6', level: 'intermediate',
    board: { kind: 'baseball', away: { name: 'Sailors', abbr: 'SAI', score: 3 }, home: { name: 'Otters', abbr: 'OTT', score: 3 },
      inning: 9, half: 'bottom', balls: 0, strikes: 0, outs: 1, bases: [false, true, false] },
    prompt: 'Tied 3–3, bottom of the 9th, runner on second. The batter singles and the runner scores. What happens?',
    options: ['The game ends instantly — a walk-off win', 'The inning continues until 3 outs', 'The visitors get one more at-bat'],
    answer: 0,
    title: 'The walk-off: game over the moment the run scores',
    exp: {
      kid: 'The home team just took the lead in the last inning — the game is over right away! Everyone runs onto the field to celebrate. That’s a “walk-off.”',
      beginner: 'When the home team takes the lead in the bottom of the 9th (or any later inning), the game ends the instant the winning run touches home plate. The visitors never get another turn — they just walk off.',
      intermediate: 'Play stops mid-inning: the remaining outs don’t matter because the visitors have no way to answer. Only the winning run counts on the play — the final is 4–3 no matter how many runners were behind him.',
      expert: 'The one exception: a walk-off HOME RUN counts in full — batter and all runners score, even beyond the winning run (a rule fixed in 1920; before that a bases-loaded walk-off homer could be scored as a single). Any other walk-off hit ends at the winning run.',
    },
  },

  // ── expert ────────────────────────────────────────────────────────────────
  {
    id: 'mlb-exp-1', level: 'expert',
    board: { kind: 'baseball', away: { name: 'Cyclones', abbr: 'CYC', score: 5 }, home: { name: 'Otters', abbr: 'OTT', score: 3 },
      inning: 10, half: 'bottom', balls: 2, strikes: 1, outs: 1, bases: [true, true, false] },
    prompt: 'Bottom 10, Otters trail 5–3 with runners on first and second. The batter hits a home run. What’s the final score?',
    options: ['6–5 Otters — every run counts on a walk-off homer', '5–5 — play continues', '5–4 Cyclones win'],
    answer: 0,
    title: 'Walk-off homer: ALL runs count',
    exp: {
      kid: 'A home run means everyone on base gets to score, plus the batter. Two runners + the batter = 3 runs. The home team wins 6–5!',
      beginner: 'Normally a walk-off ends when the winning run scores — but a home run is the exception. The batter earned all his bases, so both runners and the batter score: 3 runs, final 6–5.',
      intermediate: 'Compare: a bases-clearing double in this spot would end 5–5 → 6–5? No — a double ends the game when the SECOND run (the winner) crosses; the batter’s run never counts. Only the home run counts in full.',
      expert: 'The rule: on a game-ending home run, the batter and all runners score and the batter is credited with the HR. On any other game-ending hit, the play is dead once the winning run scores, and the batter is credited only with the bases needed to drive it in.',
    },
  },
  {
    id: 'mlb-exp-2', level: 'expert',
    board: { kind: 'baseball', away: { name: 'Sailors', abbr: 'SAI', score: 2 }, home: { name: 'Harbor Cats', abbr: 'HBC', score: 2 },
      inning: 7, half: 'top', balls: 3, strikes: 2, outs: 2, bases: [true, true, false] },
    prompt: 'Full count, two outs, runners on first and second. Why do the runners sprint on the pitch?',
    options: ['There’s no risk — any outcome either advances them or ends the inning anyway', 'They’re trying to steal', 'The rules force them to run'],
    answer: 0,
    title: '3–2, two outs: runners go automatically',
    exp: {
      kid: 'The runners can’t get in trouble here. If it’s a strike, the inning is over anyway. If it’s a ball, they walk to the next base. So they just run!',
      beginner: 'With two outs and a full count, every outcome is safe to run on: strike three ends the inning regardless, ball four advances them anyway, and a foul just resets. On a hit, their head start might score an extra run.',
      intermediate: 'This is “runners in motion” by default — no tag-up worry (a caught fly is out three anyway) and no double-off risk that matters. The head start turns a single into first-and-third or a run instead of a station-to-station advance.',
      expert: 'It’s the only count where running is strictly free: 3–2 removes the walk/foul downside and 2 outs removes the tag-up/line-drive downside. Any coach who doesn’t start these runners is giving away expected runs — watch for it; it’s automatic at every level.',
    },
  },
  {
    id: 'mlb-exp-3', level: 'expert',
    board: { kind: 'baseball', away: { name: 'Cyclones', abbr: 'CYC', score: 4 }, home: { name: 'Otters', abbr: 'OTT', score: 4 },
      inning: 8, half: 'bottom', balls: 0, strikes: 0, outs: 2, bases: [false, true, false] },
    prompt: 'Tie game, runner on second, two outs, first base open. Why might the defense intentionally walk this batter?',
    options: ['To create force outs and face the next hitter', 'To speed the game up', 'Walks are worth half a run to the defense'],
    answer: 0,
    title: 'The intentional walk with first base open',
    exp: {
      kid: 'The team in the field can choose to walk a really good hitter on purpose, so a not-as-good hitter comes up instead.',
      beginner: 'With first base empty, a walk doesn’t push the runner on second anywhere. The defense trades a free base (that barely matters with two outs) to face a weaker hitter — and now a ground ball can be a force at any base.',
      intermediate: 'Two reasons stack: (1) matchup — skip the dangerous bat for a better matchup; (2) mechanics — putting a runner on first creates a force at second, so any grounder becomes the easy inning-ending out instead of a tag play.',
      expert: 'The calculus only works with first base OPEN and preferably two outs — otherwise you’re adding a baserunner who can score. It also flips leverage in the next at-bat: pitchers must throw strikes to the “weaker” hitter, which is why the strategy backfires just often enough to stay controversial.',
    },
  },
  {
    id: 'mlb-exp-4', level: 'expert',
    board: { kind: 'baseball', away: { name: 'Sailors', abbr: 'SAI', score: 1 }, home: { name: 'Otters', abbr: 'OTT', score: 1 },
      inning: 6, half: 'top', balls: 1, strikes: 1, outs: 0, bases: [true, true, false] },
    prompt: 'Runners on first and second, nobody out. The batter pops it up to the shortstop — and the umpire calls him out BEFORE the ball lands. Why?',
    options: ['Infield fly rule — it protects the runners from a trick double play', 'The umpire lost sight of the ball', 'Pop-ups are always automatic outs'],
    answer: 0,
    title: 'The infield fly rule',
    exp: {
      kid: 'It’s a special rule: on an easy pop-up, the batter is just out right away. It stops the fielders from dropping it on purpose to trick the runners.',
      beginner: 'With runners on first and second (or bases loaded) and fewer than two outs, an easy infield pop-up makes the batter automatically out. Without it, a fielder could drop the ball on purpose and force out two frozen runners.',
      intermediate: 'The trap it prevents: runners must hold near their bases on a pop-up (to avoid being doubled off), so an intentional drop would create forces at second and third — a cheap double play. Declaring the batter out removes all forces; runners can stay put safely.',
      expert: 'Conditions: runners at 1st+2nd or loaded, fewer than 2 outs, a fair fly an infielder can catch with ordinary effort (not a line drive or bunt). The ball stays LIVE — runners may advance at their own risk after a catch or if it drops. The umpire’s raised-fist “infield fly” call is what you saw.',
    },
  },
  {
    id: 'mlb-exp-5', level: 'expert',
    board: { kind: 'baseball', away: { name: 'Cyclones', abbr: 'CYC', score: 2 }, home: { name: 'Harbor Cats', abbr: 'HBC', score: 2 },
      inning: 9, half: 'top', balls: 0, strikes: 0, outs: 2, bases: [true, false, true] },
    prompt: 'Two outs, runners on the corners. The batter grounds out at first — but the runner from third crossed home BEFORE that out. Does the run count?',
    options: ['No — a run never scores when the third out is a force or the batter is retired at first', 'Yes — he touched home first', 'Yes, but only in extra innings'],
    answer: 0,
    title: 'No run on an inning-ending force',
    exp: {
      kid: 'No run. If the last out happens because the batter didn’t make it to first, nothing that inning counts — even if a runner already touched home.',
      beginner: 'When the third out is the batter thrown out at first (or any force out), no run can score on the play — timing doesn’t matter. The half-inning simply ends at 2–2.',
      intermediate: 'The distinction is force vs. tag: on a TAG play third out (a runner tagged between bases), a run DOES count if it crossed before the tag. On a force-type third out, never. Fielders know this — with two outs they always take the force.',
      expert: 'This is the “timing play” announcers flag with two outs: on a non-force third out, umpires judge whether the run beat the tag. On a force (including retiring the batter at first — technically not a force but treated identically by the rule), the run is dead by definition. Rule 5.08 territory.',
    },
  },
  {
    id: 'mlb-exp-6', level: 'expert',
    board: { kind: 'baseball', away: { name: 'Sailors', abbr: 'SAI', score: 3 }, home: { name: 'Otters', abbr: 'OTT', score: 4 },
      inning: 7, half: 'top', balls: 0, strikes: 0, outs: 1, bases: [false, true, false] },
    prompt: 'Runner on second, one out. A deep fly ball is hit to center. When may the runner legally leave second base to advance?',
    options: ['The moment the ball first touches the fielder', 'Only after the fielder throws it back in', 'Any time — fly balls don’t restrict runners'],
    answer: 0,
    title: 'Tagging up: leave on first touch',
    exp: {
      kid: 'On a catch, the runner has to wait on his base — but he can take off the second the ball touches the fielder’s glove.',
      beginner: 'On a fly ball, a runner must be touching his base when the ball is first touched (“tagging up”). From that instant he may run. Leave early and the defense can appeal — throw to the base — and he’s out.',
      intermediate: 'First TOUCH, not full control: if the fielder bobbles the catch, the runner could already be running — he doesn’t wait for the ball to be secured. That’s why outfielders try to catch deep flies moving forward, to throw immediately.',
      expert: 'The first-touch rule closes an old loophole: a fielder can’t juggle the ball while jogging in to freeze the runner. It also creates the deliberate-drop tension on shallow flies and the “timing the leap” appeal plays you’ll see reviewed — did the foot leave before the glove touched leather?',
    },
  },
];
