// Read the Score — NBA bank. Scoring-RULE scenarios only (evergreen); team names are
// fictional set dressing. 6 scenarios per tier × 4 tiers. Pure data, zero RN imports.
import type { ScoreScenario } from '../readTheScore';

export const NBA_SCENARIOS: ScoreScenario[] = [
  // ── kid ────────────────────────────────────────────────────────────────────
  {
    id: 'nba-kid-1', level: 'kid',
    board: { kind: 'basketball', away: { name: 'Meteors', abbr: 'MET', score: 88 }, home: { name: 'Foxes', abbr: 'FOX', score: 79 },
      period: 'Q4', clock: '6:31', shotClock: 14 },
    prompt: 'Who is winning?',
    options: ['Meteors', 'Foxes', 'It’s a tie'],
    answer: 0,
    title: 'Meteors lead 88–79',
    exp: {
      kid: 'The Meteors have 88 points and the Foxes have 79. Bigger number wins!',
      beginner: 'Basketball scores climb fast because baskets come every few possessions — 2 or 3 points at a time. 88–79 is a 9-point Meteors lead.',
      intermediate: 'Think in possessions: 9 points is a “three-possession game” (three 3-pointers). With 6:31 left that’s very catchable — a lead is only safe late.',
      expert: 'A rough pro pace is ~2 possessions per team per minute, so 6:31 ≈ 13 more cracks at the basket each. Down 9, the Foxes need to outscore by ~0.7 points per possession-pair — hard but routine. That’s why NBA games “stay alive” longer than the score suggests.',
    },
  },
  {
    id: 'nba-kid-2', level: 'kid',
    board: { kind: 'basketball', away: { name: 'Comets', abbr: 'COM', score: 42 }, home: { name: 'Herons', abbr: 'HER', score: 40 },
      period: 'Q2', clock: '4:12', shotClock: 18 },
    prompt: 'A player makes a normal shot inside the arc. How many points?',
    options: ['2 points', '1 point', '3 points'],
    answer: 0,
    title: 'Inside the arc = 2 points',
    exp: {
      kid: 'A regular basket counts 2 points. That’s the most common score in the game.',
      beginner: 'Shots taken inside the big curved line (the 3-point arc) score 2. Layups, dunks, and mid-range shots are all 2-pointers.',
      intermediate: 'The arc splits the floor into 2-point and 3-point zones — a shooter’s FEET decide it. Both feet inside (or on) the line at release: 2 points.',
      expert: 'On the line counts as INSIDE — a toe on the arc makes a 3 into a 2. That single shoe-length is why shooters exaggerate their spacing to the arc, and why reviews zoom in on feet at release.',
    },
  },
  {
    id: 'nba-kid-3', level: 'kid',
    board: { kind: 'basketball', away: { name: 'Meteors', abbr: 'MET', score: 15 }, home: { name: 'Foxes', abbr: 'FOX', score: 18 },
      period: 'Q1', clock: '3:58', shotClock: 9 },
    prompt: 'A player shoots from BEHIND the big curved line and scores. How many points?',
    options: ['3 points', '2 points', '4 points'],
    answer: 0,
    title: 'Beyond the arc = 3 points',
    exp: {
      kid: 'Shots from behind the big curve are worth 3 — one extra point for shooting from far away.',
      beginner: 'The 3-point line rewards distance: make it from beyond the arc and you get 3 instead of 2. It’s the biggest single-shot prize in basketball.',
      intermediate: 'That one extra point changed the sport: 3 > 2 by 50%, so a decent 3-point shooter can be worth more than a great 2-point shooter. Modern offenses hunt 3s and layups.',
      expert: 'The math that reshaped the NBA: 35% from three (1.05 points per shot) beats 50% from mid-range (1.00). Once teams internalized points-per-shot, the mid-range game faded and floor spacing became the core offensive skill.',
    },
  },
  {
    id: 'nba-kid-4', level: 'kid',
    board: { kind: 'basketball', away: { name: 'Comets', abbr: 'COM', score: 55 }, home: { name: 'Herons', abbr: 'HER', score: 51 },
      period: 'Q3', clock: '7:20', shotClock: 24 },
    prompt: 'A player was fouled and shoots free throws. How much is each made free throw?',
    options: ['1 point', '2 points', '3 points'],
    answer: 0,
    title: 'Free throws are 1 point each',
    exp: {
      kid: 'A free throw is a calm, no-defenders shot from the line. Each one you make is 1 point.',
      beginner: 'After certain fouls, the fouled player shoots from the free-throw line, unguarded — usually two shots, 1 point each.',
      intermediate: 'How many shots depends on the foul: 2 for a foul on a 2-point attempt, 3 on a 3-point attempt, and 1 (“and-one”) if the basket also went in.',
      expert: 'Free throws are the most efficient offense that exists (~78% league-wide ≈ 1.56 points per trip on two shots). “Getting to the line” is a skill teams scheme for — and late-game fouling hands the opponent exactly this efficiency.',
    },
  },
  {
    id: 'nba-kid-5', level: 'kid',
    board: { kind: 'basketball', away: { name: 'Meteors', abbr: 'MET', score: 61 }, home: { name: 'Foxes', abbr: 'FOX', score: 66 },
      period: 'Q3', clock: '0:44', shotClock: 16 },
    prompt: 'The board says Q3. How many quarters does a basketball game have?',
    options: ['4 quarters', '2 quarters', '3 quarters'],
    answer: 0,
    title: 'Four quarters',
    exp: {
      kid: 'Basketball has 4 quarters. Q3 means the third one — the game is over halfway done.',
      beginner: 'Four quarters, 12 minutes each in the NBA, with halftime after Q2. If the game is tied after Q4, they play overtime.',
      intermediate: '48 total minutes — but the clock stops constantly (fouls, out-of-bounds, timeouts), so a game takes well over two hours. The last “minute” of a close Q4 can take fifteen.',
      expert: 'The stop-clock design concentrates drama: roughly 20% of possessions happen in “clutch time” definitions, and per-minute scoring spikes late as fouling and timeouts multiply possessions. It’s the opposite of soccer’s continuous clock philosophy.',
    },
  },
  {
    id: 'nba-kid-6', level: 'kid',
    board: { kind: 'basketball', away: { name: 'Comets', abbr: 'COM', score: 96 }, home: { name: 'Herons', abbr: 'HER', score: 98 },
      period: 'Q4', clock: '0:00' },
    prompt: 'The Q4 clock just hit 0:00 with the Herons ahead 98–96. What happens?',
    options: ['Game over — Herons win', 'One more quarter is played', 'The Comets get a free shot'],
    answer: 0,
    title: 'Clock at zero + a leader = final',
    exp: {
      kid: 'When the last quarter’s clock hits zero and one team is ahead, the game is over. Herons win!',
      beginner: 'The game ends when Q4 expires with the score unlevel. Only a TIE at 0:00 sends it to overtime.',
      intermediate: 'One wrinkle: a shot released BEFORE the buzzer still counts if it drops after — so a game isn’t over until any airborne ball lands. 98–96 could still become 98–99 on a buzzer-beater three.',
      expert: 'That released-before-zero rule is why replay reviews measure the ball leaving the hand versus the red backboard light (which triggers exactly at 0:00). The light, not the horn sound, is the authoritative signal.',
    },
  },

  // ── beginner ──────────────────────────────────────────────────────────────
  {
    id: 'nba-beg-1', level: 'beginner',
    board: { kind: 'basketball', away: { name: 'Meteors', abbr: 'MET', score: 101 }, home: { name: 'Foxes', abbr: 'FOX', score: 104 },
      period: 'Q4', clock: '0:12', shotClock: 12 },
    prompt: 'The Meteors trail 104–101 with 12 seconds left and have the ball. What shot ties the game?',
    options: ['A 3-pointer', 'Any basket', 'Two free throws'],
    answer: 0,
    title: 'Down 3 → only a three ties',
    exp: {
      kid: 'They’re 3 points behind, so they need a 3-point shot — a long one from behind the arc — to make it even.',
      beginner: 'Margin math: down 3, a 2-pointer leaves you losing by 1. Expect the offense to pass around the arc hunting a 3, and the defense to guard the line hard.',
      intermediate: 'The defense’s counter is to concede the 2: they’d happily give up a quick layup (still ahead by 1, clock burning) rather than a tying 3. Watch defenders sag off drivers and glue to shooters.',
      expert: 'This is also where the “foul up 3” debate lives: the leading team may foul BEFORE a shot, sending the opponent to the line for a max of 2. Reading whether a defense is in “foul” or “defend the arc” mode is elite late-game literacy.',
    },
  },
  {
    id: 'nba-beg-2', level: 'beginner',
    board: { kind: 'basketball', away: { name: 'Comets', abbr: 'COM', score: 34 }, home: { name: 'Herons', abbr: 'HER', score: 30 },
      period: 'Q2', clock: '8:44', shotClock: 24 },
    prompt: 'The small “24” box just reset. What is the shot clock for?',
    options: ['The offense has 24 seconds to get a shot off', 'Each player can hold the ball 24 seconds', 'It counts free-throw time'],
    answer: 0,
    title: 'The 24-second shot clock',
    exp: {
      kid: 'The attacking team gets 24 seconds to try a shot. If they don’t, the other team gets the ball. No stalling allowed!',
      beginner: 'Every possession, the offense has 24 seconds to attempt a shot that at least hits the rim. Run out of time = shot-clock violation = turnover.',
      intermediate: 'The clock resets to 24 on a change of possession, and to 14 on an offensive rebound — the offense already advanced the ball, so it gets a shorter re-do.',
      expert: 'The 24-second clock (born 1954) is why basketball can’t be frozen: possessions are capped, so a lead can always be chased. Endgame tactics revolve around the 24-vs-game-clock interplay — mismatch those two clocks and you gift the opponent extra possessions.',
    },
  },
  {
    id: 'nba-beg-3', level: 'beginner',
    board: { kind: 'basketball', away: { name: 'Meteors', abbr: 'MET', score: 110 }, home: { name: 'Foxes', abbr: 'FOX', score: 110 },
      period: 'Q4', clock: '0:00' },
    prompt: 'Q4 ends tied 110–110. What happens now?',
    options: ['A 5-minute overtime period', 'The game ends in a draw', 'Sudden death — first basket wins'],
    answer: 0,
    title: 'Tied after regulation → 5:00 of overtime',
    exp: {
      kid: 'No ties in basketball! They play 5 more minutes. If it’s STILL tied, they play 5 more, until someone wins.',
      beginner: 'Overtime is a full 5-minute mini-quarter — not sudden death. Tied after OT? Another OT, as many as it takes.',
      intermediate: 'Teams carry their situation into OT: player fouls persist (a star with 5 fouls is one whistle from fouling out), and each team gets limited extra timeouts, not a full reset.',
      expert: 'OT punishes thin rotations: starters play through fatigue, foul-trouble compounds, and possessions get more valuable (only ~10 each). Teams that hunt free throws and protect the ball disproportionately win overtimes.',
    },
  },
  {
    id: 'nba-beg-4', level: 'beginner',
    board: { kind: 'basketball', away: { name: 'Comets', abbr: 'COM', score: 58 }, home: { name: 'Herons', abbr: 'HER', score: 63 },
      period: 'Q3', clock: '5:12', fouls: { away: 5, home: 2 }, bonus: 'home' },
    prompt: 'The board shows the Comets have 5 team fouls and “BONUS” is lit for the Herons. What does that mean?',
    options: ['Every new Comets foul sends the Herons to the free-throw line', 'The Herons get a bonus point', 'The Comets can’t foul anymore'],
    answer: 0,
    title: 'The bonus: team fouls have a price',
    exp: {
      kid: 'The Comets have fouled too many times this quarter. Now, ANY foul they commit gives the other team free throws — even far from the basket.',
      beginner: 'Fouls count per TEAM, per quarter. From the 5th team foul on, the fouled team shoots two free throws even on non-shooting fouls. That’s being “in the bonus” (or “the penalty”).',
      intermediate: 'The bonus changes defense: a team at 4 fouls early in a quarter must defend with hands off, while the opponent attacks the rim hunting contact. Team-foul counts reset each quarter.',
      expert: 'Watch coaches manage the foul budget like a resource: an early “take” foul is cheap at 1–2 team fouls but costs 2 FTs in the bonus. In the last 2:00 of a period the penalty tightens further — the 2nd team foul in that window already triggers free throws.',
    },
  },
  {
    id: 'nba-beg-5', level: 'beginner',
    board: { kind: 'basketball', away: { name: 'Meteors', abbr: 'MET', score: 71 }, home: { name: 'Foxes', abbr: 'FOX', score: 70 },
      period: 'Q3', clock: '2:01', shotClock: 11 },
    prompt: 'A Foxes player is fouled while MAKING a layup. What does he get?',
    options: ['The 2 points count PLUS one free throw', 'Two free throws, basket waved off', 'The points count, nothing more'],
    answer: 0,
    title: 'The and-one: basket + 1 free throw',
    exp: {
      kid: 'The shot still counts even though he was fouled — plus he gets ONE free throw as a bonus. Make it and that’s 3 points on one play!',
      beginner: 'Fouled while scoring = “and-one”: keep the basket, shoot 1 free throw. It turns a 2-point play into a possible 3 (or a 3-pointer into a possible 4).',
      intermediate: 'The and-one is why attackers go THROUGH contact rather than avoiding it — finishing despite the foul is strictly better than two free throws (points are banked, plus the extra shot).',
      expert: 'The four-point play (fouled on a made 3 + the free throw) is the game’s biggest single-possession swing shy of a flagrant. Defensively, the lesson is discipline: fouling a shooter who will score anyway is the worst foul in basketball.',
    },
  },
  {
    id: 'nba-beg-6', level: 'beginner',
    board: { kind: 'basketball', away: { name: 'Comets', abbr: 'COM', score: 0 }, home: { name: 'Herons', abbr: 'HER', score: 0 },
      period: 'Q1', clock: '12:00', shotClock: 24 },
    prompt: 'The Q1 clock starts at 12:00. How long is a full NBA game?',
    options: ['48 minutes — four 12-minute quarters', '60 minutes — four 15-minute quarters', '40 minutes — four 10-minute quarters'],
    answer: 0,
    title: 'NBA: 4 × 12 = 48 minutes',
    exp: {
      kid: 'Each quarter is 12 minutes and there are 4 of them — 48 minutes of playing time.',
      beginner: 'The NBA plays 12-minute quarters (48 total). Other leagues differ — college plays two 20-minute halves, FIBA and the WNBA play 10-minute quarters.',
      intermediate: 'Because the clock stops on whistles, 48 game-minutes stretch to ~2¼ real hours. “Minutes played” is the workload stat: a heavy night is 38–40 of the 48.',
      expert: 'The 12-minute choice (vs FIBA’s 40-minute total) is a big reason NBA scores run ~15–20 points higher than international games — more clock, more possessions. Adjust for pace before comparing scores across leagues.',
    },
  },

  // ── intermediate ──────────────────────────────────────────────────────────
  {
    id: 'nba-int-1', level: 'intermediate',
    board: { kind: 'basketball', away: { name: 'Meteors', abbr: 'MET', score: 99, possession: true }, home: { name: 'Foxes', abbr: 'FOX', score: 101 },
      period: 'Q4', clock: '0:08', shotClock: 8 },
    prompt: 'Down 101–99 with 8 seconds left, last possession. What’s the real decision?',
    options: ['Take a 2 to tie, or a 3 to win', 'Always shoot the 3', 'Hold for overtime'],
    answer: 0,
    title: 'Two for the tie or three for the win',
    exp: {
      kid: 'A regular basket makes it even (overtime). A long 3-pointer wins it right now. The team has to pick!',
      beginner: 'Down 2 on the last shot: a 2-pointer ties (then overtime), a 3 wins outright but is harder. There’s no “safe” option — that’s what makes it the classic endgame.',
      intermediate: 'The math is closer than instinct says: a ~40% chance at a game-winning 3 can beat “make a tougher-than-you-think 2 AND win a coin-flip OT” (~50% × make rate). Many coaches now play for the win on the road, the tie at home.',
      expert: 'Expected win probability: 3-for-the-win = P(make3). 2-for-the-tie = P(make2) × ~0.5(OT). With P(make2)≈0.5 contested, the tie path is ~25% — so any 3 you can generate above ~25–30% is the better shot. Defenses know this and switch everything to deny the arc.',
    },
  },
  {
    id: 'nba-int-2', level: 'intermediate',
    board: { kind: 'basketball', away: { name: 'Comets', abbr: 'COM', score: 77, possession: true }, home: { name: 'Herons', abbr: 'HER', score: 80 },
      period: 'Q4', clock: '4:30', shotClock: 3 },
    prompt: 'The shot clock shows 3. What must the Comets do RIGHT NOW?',
    options: ['Get a shot up that at least hits the rim', 'Call timeout to reset the shot clock', 'Pass to restart the 24'],
    answer: 0,
    title: 'Beat the buzzer or lose the ball',
    exp: {
      kid: 'Three seconds left to shoot! The ball has to leave the shooter’s hand and hit the rim, or the other team gets it.',
      beginner: 'A shot-clock violation (no rim contact before the 24 expires) is an automatic turnover. Passing doesn’t reset it — only a shot that hits the rim (or a defensive touch out of bounds… actually a new possession) does.',
      intermediate: 'Note what does NOT reset it: timeouts and passes. What does: rim contact (reset to 24 for the defense-rebound or 14 for an offensive rebound), a defensive foul, or a kicked-ball violation (to 14 if under 14).',
      expert: 'Late-clock offense is a known efficiency cliff — points per possession crater in the last 4 seconds of the clock. Good defenses “win the possession early” by forcing the ball sideways for 18 seconds; the bad shot at :02 was earned at :16.',
    },
  },
  {
    id: 'nba-int-3', level: 'intermediate',
    board: { kind: 'basketball', away: { name: 'Meteors', abbr: 'MET', score: 64 }, home: { name: 'Foxes', abbr: 'FOX', score: 66 },
      period: 'Q3', clock: '6:40', fouls: { away: 3, home: 3 } },
    prompt: 'A Meteor is fouled attempting a 3-pointer. The shot misses. How many free throws?',
    options: ['3 free throws', '2 free throws', '1 free throw'],
    answer: 0,
    title: 'Fouled on a 3 → three free throws',
    exp: {
      kid: 'He was trying a 3-point shot when he got fouled, so he gets 3 free throws — one for each point the shot was worth.',
      beginner: 'Free throws match the shot attempt: fouled on a 2, shoot 2; fouled on a 3, shoot 3. If the shot had gone IN, it would count plus one bonus throw instead.',
      intermediate: 'Three free throws ≈ 2.3 expected points — better than almost any possession. That’s why closeouts “fly by” with hands high but bodies swerving: contact with a 3-point shooter is a disaster foul.',
      expert: 'Shooters weaponize this: the rip-through, the sideways kick, the pump-fake-and-lean all hunt 3-shot fouls. Rule tweaks have pushed back (offensive “non-basketball moves” get no-calls or offensive fouls), so the cat-and-mouse at the arc is refereed frame by frame.',
    },
  },
  {
    id: 'nba-int-4', level: 'intermediate',
    board: { kind: 'basketball', away: { name: 'Comets', abbr: 'COM', score: 89 }, home: { name: 'Herons', abbr: 'HER', score: 89 },
      period: 'OT', clock: '5:00', shotClock: 24 },
    prompt: 'The board shows “OT 5:00.” How does overtime work if THIS also ends tied?',
    options: ['Another full 5-minute OT — repeat until someone leads', 'Shootout of free throws', 'The home team advances'],
    answer: 0,
    title: 'Overtimes repeat until there’s a winner',
    exp: {
      kid: 'They keep playing 5-minute periods until one team is ahead at the end of one. No basketball game ever ends in a tie.',
      beginner: 'Every OT is 5 minutes. Still tied? Play another. Double- and triple-overtimes are rare but perfectly normal — the rules just repeat.',
      intermediate: 'Each extra period compounds attrition: personal fouls carry over (six and you’re out), legs go, and benches shorten. Deep teams and foul-proof stars win long OT games.',
      expert: 'Multi-OT games are possession-scarce endgames stacked back to back — every trip is “clutch time.” Statistically, free-throw rate and turnover rate dominate shooting luck as predictors across OTs; execution beats talent when everyone is exhausted.',
    },
  },
  {
    id: 'nba-int-5', level: 'intermediate',
    board: { kind: 'basketball', away: { name: 'Meteors', abbr: 'MET', score: 92 }, home: { name: 'Foxes', abbr: 'FOX', score: 95 },
      period: 'Q4', clock: '7:15', fouls: { away: 2, home: 1 } },
    prompt: 'A star player just picked up his 5th personal foul. Why is the crowd nervous?',
    options: ['One more foul and he’s out of the game', 'He must sit for 5 minutes', 'His points get deducted'],
    answer: 0,
    title: 'Six personal fouls = fouled out (NBA)',
    exp: {
      kid: 'In the NBA, a player who commits 6 fouls is done for the whole game. This star has 5 — one more and he’s gone!',
      beginner: 'Personal fouls accumulate for the whole game (unlike team fouls, which reset each quarter). At 6, the player is disqualified — “fouled out” — and can’t return.',
      intermediate: '“Foul trouble” bends coaching all game: a star with 2 fouls in Q1 often sits, and a defender at 5 must defend without reaching. Attackers hunt the guy in foul trouble on switches.',
      expert: 'The 6-foul limit (international FIBA play uses 5) is a possession-value lever: smart offenses attack a 5-foul defender because his rational play is soft coverage — effectively removing him without the whistle. Foul-out risk is priced into every late-game defensive decision.',
    },
  },
  {
    id: 'nba-int-6', level: 'intermediate',
    board: { kind: 'basketball', away: { name: 'Comets', abbr: 'COM', score: 52 }, home: { name: 'Herons', abbr: 'HER', score: 49 },
      period: 'Q2', clock: '1:47', fouls: { away: 1, home: 2 }, bonus: 'away' },
    prompt: 'Only 2 team fouls on the Herons, but the BONUS lamp is lit for the Comets. Why?',
    options: ['In the last 2:00 of a period, the 2nd team foul already triggers free throws', 'The scoreboard is broken', 'Bonus is automatic in Q2'],
    answer: 0,
    title: 'The 2-minute penalty rule',
    exp: {
      kid: 'In the final two minutes of a quarter there’s a stricter rule: after just a couple of fouls, every foul means free throws.',
      beginner: 'Normally the bonus starts at the 5th team foul of a quarter — but inside the last 2:00 of a period, the 2nd team foul in that window already sends the opponent to the line.',
      intermediate: 'The rule exists to stop cheap end-of-quarter fouling (grabbing to shorten the clock). It means late-quarter defense must be clean even if the team barely fouled all period.',
      expert: 'It interacts with take-foul strategy: a team wanting to stop a fast break at 1:50 of Q4 may already be gifting FTs. Coaches count fouls-to-give precisely — “we have one to give until the two-minute mark” is real sideline arithmetic.',
    },
  },

  // ── expert ────────────────────────────────────────────────────────────────
  {
    id: 'nba-exp-1', level: 'expert',
    board: { kind: 'basketball', away: { name: 'Meteors', abbr: 'MET', score: 105, possession: true }, home: { name: 'Foxes', abbr: 'FOX', score: 108 },
      period: 'Q4', clock: '0:09', fouls: { away: 3, home: 2 } },
    prompt: 'Foxes lead by 3 with 9 seconds left; Meteors have the ball. Why might the Foxes foul BEFORE a shot goes up?',
    options: ['A non-shooting foul gives only 2 free throws — the 3-point tie is off the table', 'Fouling stops their own clock', 'It forces a jump ball'],
    answer: 0,
    title: 'Fouling up 3: kill the tying three',
    exp: {
      kid: 'If they foul gently before the other team shoots, the other team only gets 2 free throws — and 2 points can’t tie a 3-point lead!',
      beginner: 'A foul committed before the act of shooting = 2 free throws max. Even if both are made, the Foxes still lead by 1 with the ball coming back. The alternative — defending a 3 — risks overtime.',
      intermediate: 'The trailing team’s counter: make the first FT, MISS the second on purpose, and chase the offensive rebound for a tip — or catch the defense fouling a shooter in the act (3 shots). Timing the foul before the gather is everything.',
      expert: 'The debate is empirical: studies put “foul up 3” at a small but real win-probability edge IF executed before the shooting motion and with >~5 seconds left (too late and a lucky sequence can still beat you; too early and you extend the game). The failure mode is fouling a 3-point shooter mid-gather — the one catastrophic version.',
    },
  },
  {
    id: 'nba-exp-2', level: 'expert',
    board: { kind: 'basketball', away: { name: 'Comets', abbr: 'COM', score: 72, possession: true }, home: { name: 'Herons', abbr: 'HER', score: 75 },
      period: 'Q3', clock: '0:38', shotClock: 24 },
    prompt: '0:38 left in Q3, fresh 24 on the shot clock. Why do the Comets HURRY a shot in the first few seconds?',
    options: ['The 2-for-1: shoot early to guarantee the quarter’s last possession too', 'The shot clock is about to expire', 'They want to rest on defense'],
    answer: 0,
    title: 'The 2-for-1',
    exp: {
      kid: 'If they shoot fast NOW, there’s still time to get the ball back and shoot AGAIN before the quarter ends — two chances instead of one!',
      beginner: 'Quick math: shoot at 0:32, the opponent’s full 24 runs to ~0:08, and you get a final possession. Wait too long and the opponent’s possession swallows the rest of the quarter.',
      intermediate: 'The window is roughly 0:36–0:28: early enough that opponent-24 + your leftover ≥ one more real possession. A slightly worse shot now buys a whole extra possession — usually a great trade.',
      expert: 'Refinement: the goal is a decent-quality quick shot, not a heave — and teams pair it with intentional clock geometry on defense (no fouls, force a full 24). End-of-quarter possession counting like this is worth a point or two a game, which is enormous over a season.',
    },
  },
  {
    id: 'nba-exp-3', level: 'expert',
    board: { kind: 'basketball', away: { name: 'Meteors', abbr: 'MET', score: 110 }, home: { name: 'Foxes', abbr: 'FOX', score: 111, possession: true },
      period: 'Q4', clock: '0:18' },
    prompt: 'Q4, 18 seconds left — and the shot-clock display is BLANK. Why?',
    options: ['Game clock under 24: the shot clock is switched off', 'It broke at the worst moment', 'Shot clocks don’t run in Q4'],
    answer: 0,
    title: 'Shot clock off under 24 seconds',
    exp: {
      kid: 'There are only 18 seconds left — less than the 24 the shot clock gives. So it isn’t needed and gets turned off.',
      beginner: 'When the game clock drops below 24 seconds and a new possession starts, the shot clock is turned off — the period will end before a violation could occur.',
      intermediate: 'Consequence: the leading team with the ball never has to shoot again. Expect the trailing team to foul immediately — it’s the only way to get the ball back.',
      expert: 'This is the trigger for the endgame foul cascade: leading team inbounds (shot clock off) → trailing team must foul → FTs → trailing possession → repeat. The whole final 20 seconds of a 1-possession game is scripted by this one display going dark.',
    },
  },
  {
    id: 'nba-exp-4', level: 'expert',
    board: { kind: 'basketball', away: { name: 'Comets', abbr: 'COM', score: 100 }, home: { name: 'Herons', abbr: 'HER', score: 106, possession: true },
      period: 'Q4', clock: '0:32', fouls: { away: 4, home: 3 } },
    prompt: 'Comets just scored to cut it to 6, and they foul instantly on the inbound. Why give free throws on purpose?',
    options: ['A foul stops the clock and trades 2 FTs for a chance at the ball back', 'They’re frustrated', 'To injure the shooter — legally'],
    answer: 0,
    title: 'The foul game: buying possessions with the clock off',
    exp: {
      kid: 'Letting the clock run is certain defeat. A quick foul freezes the clock — the other team shoots free throws, but then the trailing team gets the ball back to try again.',
      beginner: 'Down 6 with 32 seconds, you can’t let 24 tick away. Fouling costs up to 2 points but returns possession with the clock stopped — the only currency that matters now is TIME.',
      intermediate: 'The math: need 2+ scores; each foul-cycle costs ~2 expected FT points but buys a ~7-second possession. It only works while “points needed per possession” stays achievable — down 6 needs two 3s and two stops/rebounds. Miss one link and it collapses.',
      expert: 'Sophistications: foul the worst free-throw shooter, foul BEFORE the inbound pass is caught (saves clock but beware the away-from-play rules late), and know the break-even — roughly, the strategy dies when (deficit) > 3 × (possessions buyable). Coaches carry that table in their heads.',
    },
  },
  {
    id: 'nba-exp-5', level: 'expert',
    board: { kind: 'basketball', away: { name: 'Meteors', abbr: 'MET', score: 118 }, home: { name: 'Foxes', abbr: 'FOX', score: 120 },
      period: 'Q4', clock: '0:00' },
    prompt: 'The buzzer sounded with a Meteors 3-pointer in the AIR… and it went in. Does it count?',
    options: ['Yes — it left the hand before 0:00, so it counts: Meteors win 121–120', 'No — the buzzer kills the play', 'It counts as 2, not 3'],
    answer: 0,
    title: 'The buzzer-beater rule',
    exp: {
      kid: 'If the ball leaves the shooter’s hand before the clock hits zero, the shot counts even if it lands after the horn. Meteors win!',
      beginner: 'Time-of-release is what matters, not time-of-landing. A shot released at 0:00.1 that drops after the horn is good — that’s what a “buzzer-beater” literally is.',
      intermediate: 'Officials verify by replay: the ball must be OUT of the hand before the backboard light (synced to 0:00) fires. Touch it again after release — or release late — and the basket is waved off.',
      expert: 'Precision matters to a tenth: 0.3 seconds is the canonical minimum to catch-and-shoot; at 0.2 or less only a tip counts. Endgame play design out of timeouts is built backwards from these thresholds — lob plays exist because of the 0.3 rule.',
    },
  },
  {
    id: 'nba-exp-6', level: 'expert',
    board: { kind: 'basketball', away: { name: 'Comets', abbr: 'COM', score: 84 }, home: { name: 'Herons', abbr: 'HER', score: 84 },
      period: 'Q4', clock: '2:00', fouls: { away: 4, home: 4 } },
    prompt: 'Tie game, 2:00 left, both teams at 4 team fouls. What does the NEXT defensive foul by either team cost?',
    options: ['Two free throws — both teams are now effectively in the penalty', 'Nothing — under 5 fouls is always safe', 'A technical foul'],
    answer: 0,
    title: 'Late and loaded: every foul is free throws now',
    exp: {
      kid: 'Both teams have used up their “free” fouls. From here to the end, any foul hands the other team free throws.',
      beginner: 'Two triggers stack here: 5th team foul of the quarter, OR 2nd team foul inside the final 2:00. At 4 fouls with 2:00 left, the very next foul crosses the 5-foul line — free throws either way.',
      intermediate: 'Endgames at 4+ team fouls are “no-touch” defense: no bumping cutters, no reach-ins, no take fouls on fast breaks. Offenses respond by driving relentlessly — contact now equals points.',
      expert: 'This is the hidden state that decides close finishes: identical defensive plays cost nothing at 3 team fouls and 2 points at 5. Elite closers check the team-foul count the way chess players check the clock — it dictates whether to attack the rim or settle for the switch-hunted jumper.',
    },
  },
];
