// Read the Score — NFL bank. Scoring-RULE scenarios only (evergreen); team names are
// fictional set dressing. 6 scenarios per tier × 4 tiers. Pure data, zero RN imports.
import type { ScoreScenario } from '../readTheScore';

export const NFL_SCENARIOS: ScoreScenario[] = [
  // ── kid ────────────────────────────────────────────────────────────────────
  {
    id: 'nfl-kid-1', level: 'kid',
    board: { kind: 'football', away: { name: 'Bulldogs', abbr: 'BUL', score: 21 }, home: { name: 'Stallions', abbr: 'STA', score: 14, possession: true },
      quarter: 'Q3', clock: '9:12', downDistance: '1st & 10', ballOn: 'STA 30' },
    prompt: 'Who is winning?',
    options: ['Bulldogs', 'Stallions', 'It’s a tie'],
    answer: 0,
    title: 'Bulldogs lead 21–14',
    exp: {
      kid: 'The Bulldogs have 21 points and the Stallions have 14. More points = winning!',
      beginner: 'Football scores come in chunks — touchdowns (6), extra kicks (1), field goals (3). 21–14 usually means the Bulldogs have scored one more touchdown-and-kick than the Stallions.',
      intermediate: 'Score patterns tell a story: 21 is three touchdowns with extra points; 14 is two. A 7-point gap is “one score” — the trailing team can tie with a single touchdown and extra point.',
      expert: 'Coaches think in “scores,” not points: 7 down is one score, 8 down is still one score (TD + 2-point try), 9 down is two. Reading the margin this way tells you how urgent the trailing team should play.',
    },
  },
  {
    id: 'nfl-kid-2', level: 'kid',
    board: { kind: 'football', away: { name: 'Miners', abbr: 'MIN', score: 7 }, home: { name: 'Wolves', abbr: 'WOL', score: 3, possession: true },
      quarter: 'Q2', clock: '5:40', downDistance: '2nd & 6', ballOn: 'MIN 18' },
    prompt: 'The Wolves reach the end zone with the ball. How many points is a touchdown?',
    options: ['6 points', '3 points', '1 point'],
    answer: 0,
    title: 'A touchdown is worth 6',
    exp: {
      kid: 'Getting the ball into the end zone is a touchdown — 6 points! Then the team gets a bonus kick for 1 more.',
      beginner: 'A touchdown scores 6, then the team attempts an extra point: a short kick worth 1 (or a riskier 2-point play). That’s why scores so often move by 7.',
      intermediate: 'The 6+1 structure explains most NFL scores: 7, 14, 21… When you see a score like 20, think two touchdowns with kicks (14) plus two field goals (6).',
      expert: 'Touchdown = ball breaking the plane of the goal line with possession — the ball, not the player, has to cross. That “plane” detail decides the replay reviews you’ll see at the goal line.',
    },
  },
  {
    id: 'nfl-kid-3', level: 'kid',
    board: { kind: 'football', away: { name: 'Bulldogs', abbr: 'BUL', score: 10 }, home: { name: 'Stallions', abbr: 'STA', score: 7 },
      quarter: 'Q4', clock: '2:15', downDistance: '4th & 5', ballOn: 'STA 12' },
    prompt: 'A team kicks the ball through the tall yellow posts. How many points is that?',
    options: ['3 points', '6 points', '2 points'],
    answer: 0,
    title: 'A field goal is worth 3',
    exp: {
      kid: 'Kicking the ball between the two tall posts is a field goal — 3 points.',
      beginner: 'A field goal (3 points) is what teams take when they can’t reach the end zone — usually on 4th down, close enough for the kicker.',
      intermediate: 'The field goal is football’s consolation prize: half a touchdown-and-kick. Good offenses turn drives into 7s; settling for 3s is how teams lose games they “moved the ball” in.',
      expert: 'FG distance = line of scrimmage + 10 (end zone) + ~7–8 (the hold). Ball at the 12 means a ~30-yard attempt — near automatic. That math drives every late-game decision about how close is “close enough.”',
    },
  },
  {
    id: 'nfl-kid-4', level: 'kid',
    board: { kind: 'football', away: { name: 'Miners', abbr: 'MIN', score: 0 }, home: { name: 'Wolves', abbr: 'WOL', score: 0, possession: true },
      quarter: 'Q1', clock: '12:47', downDistance: '1st & 10', ballOn: 'WOL 25' },
    prompt: 'The clock shows 12:47. Does the game clock count UP or DOWN?',
    options: ['Down — toward 0:00', 'Up — toward 15:00', 'It doesn’t move'],
    answer: 0,
    title: 'Football clocks count down',
    exp: {
      kid: 'The clock counts down to zero. When it hits 0:00, the quarter is over.',
      beginner: 'Each quarter starts at 15:00 and runs DOWN to 0:00. So 12:47 in Q1 means the game just started — about 2 minutes have been played.',
      intermediate: 'Counting down makes “time left” instant to read: 2:15 in Q4 means the game ends in at most 2 minutes 15 of play — though stoppages stretch that to much longer in real time.',
      expert: 'The countdown is also a weapon: leading teams drain it (runs, staying in bounds), trailing teams freeze it (incompletions, sideline routes, timeouts). Late-game football is as much clock management as yardage.',
    },
  },
  {
    id: 'nfl-kid-5', level: 'kid',
    board: { kind: 'football', away: { name: 'Bulldogs', abbr: 'BUL', score: 14 }, home: { name: 'Stallions', abbr: 'STA', score: 10 },
      quarter: 'Q2', clock: '0:58', downDistance: '3rd & 4', ballOn: 'BUL 44' },
    prompt: 'The board says Q2. How many quarters are in a football game?',
    options: ['4 quarters', '2 quarters', '3 quarters'],
    answer: 0,
    title: 'Four 15-minute quarters',
    exp: {
      kid: 'A game has 4 quarters. Q2 means it’s the second one — almost halftime!',
      beginner: 'Four quarters of 15 minutes each, with a long halftime break after Q2. The teams switch end zones every quarter.',
      intermediate: 'Q1–Q2 make the first half, Q3–Q4 the second. The team that kicked off to start the game receives to start the second half — possession to open each half alternates.',
      expert: 'Quarters matter for strategy: end-of-Q2 is a real deadline (points expire at halftime, driving two-minute urgency), while end-of-Q1 and Q3 are just direction changes — the drive continues with the same down and distance.',
    },
  },
  {
    id: 'nfl-kid-6', level: 'kid',
    board: { kind: 'football', away: { name: 'Miners', abbr: 'MIN', score: 13, possession: true }, home: { name: 'Wolves', abbr: 'WOL', score: 17 },
      quarter: 'Q3', clock: '6:21', downDistance: '2nd & 7', ballOn: 'WOL 41' },
    prompt: 'See the ▸ marker next to the Miners? What does it mean?',
    options: ['The Miners have the ball', 'The Miners are winning', 'The Miners are out of timeouts'],
    answer: 0,
    title: '▸ marks possession',
    exp: {
      kid: 'The little arrow points at the team that has the ball right now. The Miners are on offense.',
      beginner: 'The possession marker shows who’s on offense. Only the team WITH the ball can score on this drive (well, almost — a turnover can flip that fast).',
      intermediate: 'Possession + down & distance + ball spot is the full picture: the Miners have it, 2nd & 7, at the Wolves’ 41 — driving in scoring territory.',
      expert: 'Possession is the scarcest resource in football — each team only gets ~10–12 drives a game. That’s why turnovers swing win probability more than almost any other single play.',
    },
  },

  // ── beginner ──────────────────────────────────────────────────────────────
  {
    id: 'nfl-beg-1', level: 'beginner',
    board: { kind: 'football', away: { name: 'Bulldogs', abbr: 'BUL', score: 7, possession: true }, home: { name: 'Stallions', abbr: 'STA', score: 7 },
      quarter: 'Q2', clock: '8:03', downDistance: '2nd & 8', ballOn: 'BUL 37' },
    prompt: 'The board says “2nd & 8.” What does that mean?',
    options: ['2nd try, 8 more yards for a fresh set of downs', '2nd quarter, 8 minutes left', '8 players on the field'],
    answer: 0,
    title: 'Down & distance: attempt number + yards to go',
    exp: {
      kid: 'The team gets 4 tries to move the ball 10 big steps (yards). “2nd & 8” means it’s try number 2, and they still need 8 yards.',
      beginner: 'The offense gets 4 downs (tries) to gain 10 yards. Gain them and the count resets to “1st & 10.” Here they gained 2 yards on first down, so it’s 2nd & 8.',
      intermediate: 'Down & distance sets the play call: 2nd & 8 is a “passing lean” but still balanced. Compare 2nd & 2 (anything works) or 2nd & 15 (pass, almost surely). Defenses read the same numbers.',
      expert: 'The chains define the whole sport’s rhythm: staying “on schedule” (2nd & 6 or less) keeps every option open, while “off schedule” downs let the defense pin its ears back. Sustained offense is really a chain-management contest.',
    },
  },
  {
    id: 'nfl-beg-2', level: 'beginner',
    board: { kind: 'football', away: { name: 'Miners', abbr: 'MIN', score: 3 }, home: { name: 'Wolves', abbr: 'WOL', score: 10, possession: true },
      quarter: 'Q1', clock: '3:29', downDistance: '3rd & 2', ballOn: 'MIN 24' },
    prompt: 'On 3rd & 2 the Wolves run for 5 yards. What does the board show next?',
    options: ['1st & 10 — a fresh set of downs', '4th & 2', '3rd & 7'],
    answer: 0,
    title: 'Gain the distance → back to 1st & 10',
    exp: {
      kid: 'They needed 2 yards and got 5 — so they earned 4 brand-new tries. The board goes back to “1st & 10.”',
      beginner: 'Any time the offense gains the “& number,” it earns a first down: the count resets to 1st & 10 from the new spot. That’s how drives keep going.',
      intermediate: 'First downs are the currency of a drive — each one buys four more plays. “Moving the chains” literally means the sideline crew carries the 10-yard chain to the new spot.',
      expert: 'Note the reset is 1st & 10 unless inside the opponent’s 10 — then it’s “1st & goal,” where the end zone itself is the target and there are no more first downs to earn.',
    },
  },
  {
    id: 'nfl-beg-3', level: 'beginner',
    board: { kind: 'football', away: { name: 'Bulldogs', abbr: 'BUL', score: 13, possession: true }, home: { name: 'Stallions', abbr: 'STA', score: 14 },
      quarter: 'Q3', clock: '11:00', downDistance: '1st & 10', ballOn: 'STA 45' },
    prompt: 'The Bulldogs just scored a touchdown to reach 13. What’s the usual next play?',
    options: ['An extra-point kick worth 1', 'An immediate kickoff, no bonus play', 'A free field goal worth 3'],
    answer: 0,
    title: 'After a TD comes the try: kick for 1 (or go for 2)',
    exp: {
      kid: 'After a touchdown the team gets one bonus play: a short kick for 1 extra point. 6 + 1 = 7.',
      beginner: 'The “try” follows every touchdown: kick for 1 point (the safe, standard choice) or run one play for 2 points (riskier). Then the scoring team kicks off.',
      intermediate: 'A score of 13 usually means a missed kick or a 2-point attempt somewhere (7+3+3, or 6+7). Odd-looking totals are clues to how a team scored.',
      expert: 'The 1-vs-2 decision is pure math plus context: kicks succeed ~94%+, two-point tries under 50% — so 2 is reserved for score-margin logic (down 8, down 5, up 1…), the situations on every coach’s laminated chart.',
    },
  },
  {
    id: 'nfl-beg-4', level: 'beginner',
    board: { kind: 'football', away: { name: 'Miners', abbr: 'MIN', score: 9 }, home: { name: 'Wolves', abbr: 'WOL', score: 7, possession: true },
      quarter: 'Q2', clock: '6:55', downDistance: '1st & 10', ballOn: 'WOL 3' },
    prompt: 'The Wolves’ quarterback is tackled in his OWN end zone. What is that worth?',
    options: ['2 points for the Miners — a safety', '6 points for the Miners', 'Nothing — play continues'],
    answer: 0,
    title: 'A safety scores 2 for the defense',
    exp: {
      kid: 'Getting tackled in your own end zone gives the OTHER team 2 points. It’s called a safety.',
      beginner: 'A safety is 2 points for the defense — awarded when the ball carrier is downed in his own end zone (or the offense fouls there). The offense then has to kick the ball away, too.',
      intermediate: 'It’s a double punishment: 2 points AND possession, via a free kick to the scoring team. That’s why a 9 on the scoreboard sometimes means TD + safety, not three field goals.',
      expert: 'The safety explains backed-up-offense behavior: near your own goal line, teams call conservative plays because a sack or penalty in the end zone is points the other way plus the ball. It’s the worst square foot of real estate in football.',
    },
  },
  {
    id: 'nfl-beg-5', level: 'beginner',
    board: { kind: 'football', away: { name: 'Bulldogs', abbr: 'BUL', score: 17, possession: true }, home: { name: 'Stallions', abbr: 'STA', score: 20 },
      quarter: 'Q4', clock: '7:44', downDistance: '4th & 2', ballOn: 'STA 44' },
    prompt: '4th & 2. If the Bulldogs run a play and DON’T gain 2 yards, what happens?',
    options: ['The Stallions take over right there', 'The Bulldogs get one bonus down', 'Automatic field goal attempt'],
    answer: 0,
    title: 'Fail on 4th down = turnover on downs',
    exp: {
      kid: 'Fourth down is the LAST try. If they don’t make it, the other team gets the ball at that exact spot.',
      beginner: 'That’s why teams usually punt on 4th down — failing hands the opponent the ball where you stopped (“turnover on downs”). Going for it is a gamble with the field position.',
      intermediate: 'The 4th-down menu: punt (safe, flips field position), field goal (if in range), or go for it. At midfield like this — too far to kick, punt gains little — “go” is genuinely tempting.',
      expert: 'Modern analytics moved this decision dramatically: short-yardage 4th downs near midfield are now frequent “go” calls because possession is worth more than the ~40 yards a punt buys. The old “always punt” instinct is measurably wrong here.',
    },
  },
  {
    id: 'nfl-beg-6', level: 'beginner',
    board: { kind: 'football', away: { name: 'Miners', abbr: 'MIN', score: 14 }, home: { name: 'Wolves', abbr: 'WOL', score: 10 },
      quarter: 'Q2', clock: '0:00', downDistance: undefined, ballOn: undefined },
    prompt: 'The Q2 clock just hit 0:00. What happens now?',
    options: ['Halftime — the teams take a long break', 'The game is over', 'Q3 starts immediately'],
    answer: 0,
    title: '0:00 in Q2 = halftime',
    exp: {
      kid: 'Two quarters are done — that’s half the game, so it’s halftime. The teams rest and make plans, then come back.',
      beginner: 'Q1+Q2 form the first half. At halftime teams regroup for about 13 minutes, then Q3 begins with a kickoff — received by whichever team kicked off to open the game.',
      intermediate: 'Halftime is a hard reset: drives don’t carry over, and the down-and-distance disappears. That’s why teams hurry to score before the half — an unfinished drive is worth nothing.',
      expert: 'The second-half kickoff is decided at the opening coin toss — most winners defer, taking the ball after halftime. A team that scores just before the break AND receives the second-half kick can “double up” — two scores around an opponent’s zero possessions.',
    },
  },

  // ── intermediate ──────────────────────────────────────────────────────────
  {
    id: 'nfl-int-1', level: 'intermediate',
    board: { kind: 'football', away: { name: 'Bulldogs', abbr: 'BUL', score: 10, possession: true }, home: { name: 'Stallions', abbr: 'STA', score: 13 },
      quarter: 'Q3', clock: '4:18', downDistance: '1st & GOAL', ballOn: 'STA 7' },
    prompt: 'The board shows “1st & GOAL” at the 7. What does GOAL mean?',
    options: ['The end zone itself is the target — no more first downs to earn', 'They need a field goal', '7 yards for another first down'],
    answer: 0,
    title: '1st & Goal: the end zone is the line to gain',
    exp: {
      kid: 'They’re so close that the next prize isn’t 10 more yards — it’s the end zone itself! Four tries to score a touchdown.',
      beginner: 'Inside the opponent’s 10, “& 10” makes no sense — there aren’t 10 yards left. So it becomes “& GOAL”: four downs to cross the goal line.',
      intermediate: 'Goal-to-go changes both playbooks: the field shrinks, so deep routes vanish and defenses pack the box. Red-zone offense is its own skill — that’s why “red-zone TD%” is tracked separately.',
      expert: 'On 4th & goal the math sharpens: failing leaves the opponent pinned at their goal line (great field position for you next drive), which makes “going for it” cheaper than it looks — the hidden-value argument analytics folks love.',
    },
  },
  {
    id: 'nfl-int-2', level: 'intermediate',
    board: { kind: 'football', away: { name: 'Miners', abbr: 'MIN', score: 12, possession: true }, home: { name: 'Wolves', abbr: 'WOL', score: 20 },
      quarter: 'Q4', clock: '3:02', downDistance: '2nd & 4', ballOn: 'WOL 22' },
    prompt: 'The Miners trail 20–12 late. They score a touchdown (now 20–18). What should they try next?',
    options: ['A 2-point conversion to tie the game', 'The extra-point kick — it ties', 'An onside kick before the try'],
    answer: 0,
    title: 'Down 8 → touchdown + 2-point try = tie',
    exp: {
      kid: 'They’re 2 points behind after the touchdown. The bonus kick is only worth 1 — but the special 2-point play would make it even!',
      beginner: 'After a TD you choose: kick for 1 or run one play from the 2-yard line for 2. Down 20–18, only the 2-pointer ties. That’s why “down 8” is still called a one-score game.',
      intermediate: 'The 2-point try: one play from the 2-yard line, ball must cross the goal line. Succeed and it’s 20–20; fail and you’re chasing 2 with an onside kick or a stop. Kicking for 1 here would leave you needing another score anyway.',
      expert: 'Deeper cut: many analysts say go for 2 when down 14 AFTER the first TD (make it 8 → a later TD+kick wins rather than ties). The principle: take the information early, while there’s still time to react to a miss.',
    },
  },
  {
    id: 'nfl-int-3', level: 'intermediate',
    board: { kind: 'football', away: { name: 'Bulldogs', abbr: 'BUL', score: 7 }, home: { name: 'Stallions', abbr: 'STA', score: 7, possession: true },
      quarter: 'Q2', clock: '10:36', downDistance: '2nd & 15', ballOn: 'STA 28' },
    prompt: 'It was 2nd & 10, then the Stallions were flagged for holding (a 10-yard penalty… declined to 5 here: false start). Why does the board now say 2nd & 15?',
    options: ['Penalties move the ball back but the down repeats', 'Penalties cost a down', 'The board is wrong'],
    answer: 0,
    title: 'Most offensive penalties: lose yards, replay the down',
    exp: {
      kid: 'The team broke a rule, so they got pushed 5 yards backward. They keep the same try number, but now the goal is farther away.',
      beginner: 'A pre-snap foul like a false start moves the offense back 5 yards and the down is replayed: 2nd & 10 becomes 2nd & 15. Yardage penalties change the distance, not the down count.',
      intermediate: '“2nd & long” after a penalty is a drive-killer: now the offense needs a chunk play, and the defense knows a pass is coming. Penalty yards are the quietest way drives die.',
      expert: 'Exceptions worth knowing: some defensive penalties award an automatic first down regardless of yardage (defensive holding, DPI), and intentional grounding costs the offense a DOWN plus yards. The general rule — yards, replay the down — has carve-outs in both directions.',
    },
  },
  {
    id: 'nfl-int-4', level: 'intermediate',
    board: { kind: 'football', away: { name: 'Miners', abbr: 'MIN', score: 21, possession: true }, home: { name: 'Wolves', abbr: 'WOL', score: 24 },
      quarter: 'Q4', clock: '1:12', downDistance: '2nd & 10', ballOn: 'MIN 40' },
    prompt: 'Late, no timeouts. The Miners’ QB throws an INCOMPLETE pass. What does the clock do?',
    options: ['Stops until the next snap', 'Keeps running', 'Resets to 1:30'],
    answer: 0,
    title: 'Incompletions stop the clock',
    exp: {
      kid: 'When a pass hits the ground, the referee stops the clock until the next play starts. The team gets a free time-freeze!',
      beginner: 'The clock stops for incomplete passes, and for runners who go out of bounds (late in each half). That’s why trailing teams throw: passes preserve time, runs burn it.',
      intermediate: 'This is the core of the two-minute drill: sideline throws and incompletions function as free timeouts. A team with no timeouts can still march 70 yards in a minute if it stays “clock-clean.”',
      expert: 'The counting rule of thumb: each incompletion costs ~6 seconds of game time; each completed pass in-bounds costs ~35–40 unless you spike or reach the sideline. Elite 2-minute offenses are really managing a seconds-per-play budget.',
    },
  },
  {
    id: 'nfl-int-5', level: 'intermediate',
    board: { kind: 'football', away: { name: 'Bulldogs', abbr: 'BUL', score: 13, possession: true }, home: { name: 'Stallions', abbr: 'STA', score: 17 },
      quarter: 'Q4', clock: '1:58', downDistance: '3rd & 6', ballOn: 'STA 31' },
    prompt: 'Down 17–13 with under 2:00 left. Why is a field goal (3 points) the WRONG goal for this drive?',
    options: ['It leaves them losing 17–16 — they need a touchdown', 'Field goals are banned in the final 2 minutes', 'Kicks are too risky in the cold'],
    answer: 0,
    title: 'Down 4: only a touchdown helps',
    exp: {
      kid: 'They’re 4 points behind. A kick is only worth 3 — they’d STILL be losing. They need a touchdown (6) to jump ahead.',
      beginner: 'Margin math: down 4, a field goal makes it 17–16, still a loss. This drive must reach the end zone. Down 3 or less, the kick ties or wins — down 4+, it doesn’t.',
      intermediate: 'This changes 4th-down logic completely: on 4th down inside field-goal range, a team down 4 kicks NOTHING — they go for it, because 3 points have no value. The scoreboard dictates the risk.',
      expert: 'Sharp viewers track the “field-goal-relevant” margins: 0–3 down (kick ties/wins), exactly 4–5 (TD only), 6–8 (TD, then the try decides tie/win). Watch a coach’s 4th-down behavior flip precisely at these boundaries.',
    },
  },
  {
    id: 'nfl-int-6', level: 'intermediate',
    board: { kind: 'football', away: { name: 'Miners', abbr: 'MIN', score: 6, possession: true }, home: { name: 'Wolves', abbr: 'WOL', score: 14 },
      quarter: 'Q1', clock: '2:44', downDistance: '1st & 10', ballOn: 'MIN 25' },
    prompt: 'The board says the Miners have the ball at “MIN 25.” How far are they from the end zone they’re attacking?',
    options: ['75 yards', '25 yards', '50 yards'],
    answer: 0,
    title: 'Ball on your OWN 25 = 75 yards to score',
    exp: {
      kid: 'The field is 100 big steps long. “MIN 25” means they’re near their OWN end, so they have to go 75 more to score.',
      beginner: 'Yard lines are named by whose side they’re on: “MIN 25” is 25 yards from the Miners’ own goal line, so 100 − 25 = 75 yards to the scoring end zone. “WOL 25” would mean just 25 to go.',
      intermediate: 'This is why the abbreviation matters more than the number. Crossing midfield flips the label — from “MIN 45” to “WOL 45” — and entering the “WOL 35-ish” area puts you in field-goal range.',
      expert: 'Field position converts directly to expected points: drives from your own 25 average roughly 2 points; from the opponent’s 25, closer to 4–5. Punts and turnovers are really trades on this expected-points curve.',
    },
  },

  // ── expert ────────────────────────────────────────────────────────────────
  {
    id: 'nfl-exp-1', level: 'expert',
    board: { kind: 'football', away: { name: 'Bulldogs', abbr: 'BUL', score: 20, possession: true }, home: { name: 'Stallions', abbr: 'STA', score: 22 },
      quarter: 'Q4', clock: '0:38', downDistance: '4th & 2', ballOn: 'STA 20', timeouts: { away: 1, home: 2 } },
    prompt: 'Down 22–20, 4th & 2 at the Stallions’ 20, 0:38 left. What’s the right call?',
    options: ['Kick the ~38-yard field goal to take the lead', 'Go for it — keep the drive alive', 'Punt and trust the defense'],
    answer: 0,
    title: 'Take the points: 3 > 2 here',
    exp: {
      kid: 'They only need 2 points to pass the other team — and a kick is worth 3! Kick it and take the lead.',
      beginner: 'A field goal makes it 23–22 with about half a minute left. Going for it risks everything on one play when the kick already flips the game. FG distance ≈ 20 + 17 = a 37–38 yarder, very makeable.',
      intermediate: 'The decision matrix: down 0–3, a make wins/leads — kick. The counter-risk is leaving 0:38 and a timeout for the opponent’s kicker, so the offense should also have burned clock to near 0:25 before kicking.',
      expert: 'Elite detail: run the clock to ~0:03–0:05 of decision time before the kick if the opponent has timeouts — 0:38 with 2 TOs is a real answer window. The order of operations (bleed clock → force their timeouts → THEN kick) matters as much as the kick itself.',
    },
  },
  {
    id: 'nfl-exp-2', level: 'expert',
    board: { kind: 'football', away: { name: 'Miners', abbr: 'MIN', score: 10, possession: true }, home: { name: 'Wolves', abbr: 'WOL', score: 24 },
      quarter: 'Q4', clock: '5:05', downDistance: '1st & 10', ballOn: 'WOL 35' },
    prompt: 'Down 24–10 with 5:05 left. What’s the minimum the Miners need to force overtime?',
    options: ['Two touchdowns with both extra points', 'A touchdown and two field goals', 'Three field goals and a safety'],
    answer: 0,
    title: 'Down 14 = two TD + 2 XP to tie',
    exp: {
      kid: 'They’re 14 points behind. A touchdown plus its kick is 7 — and 7 + 7 = 14. Two of those makes it even!',
      beginner: 'Two full touchdowns (6+1 each) erase a 14-point gap: 24–24 → overtime. Three field goals is only 9; a TD plus two FGs is 13 — one short. The 7-point “score” is the unit that matters.',
      intermediate: 'They also need the ball twice — meaning a defensive stop (or onside kick) in between, all in 5 minutes. This is where timeouts and the two-minute warning become the offense’s extra possessions.',
      expert: 'The aggressive line: go for 2 after the FIRST touchdown. Make it and a later TD+kick WINS instead of ties; miss it and you know early that you need two more scores. Taking that information at 5:00 (not 0:30) is the whole argument.',
    },
  },
  {
    id: 'nfl-exp-3', level: 'expert',
    board: { kind: 'football', away: { name: 'Bulldogs', abbr: 'BUL', score: 20 }, home: { name: 'Stallions', abbr: 'STA', score: 23 },
      quarter: 'Q4', clock: '0:04', downDistance: '4th & 6', ballOn: 'STA 25', timeouts: { away: 0, home: 1 } },
    prompt: 'Bulldogs down 3, ball at the 25, 0:04 left — time for one play. What do they do?',
    options: ['Kick the ~43-yard field goal to force overtime', 'Throw to the end zone to win now', 'Kneel and regroup'],
    answer: 0,
    title: 'Down 3 at the gun: kick to tie, live for OT',
    exp: {
      kid: 'One play left and they’re 3 behind. A kick is worth exactly 3 — make it and the game keeps going in overtime!',
      beginner: 'A made field goal ties it 23–23 and forces overtime. A touchdown pass would win outright — but from the 25, one desperate throw into a packed end zone succeeds far less often than a 43-yard kick.',
      intermediate: 'This is expected-value math: NFL kickers make ~43-yarders at a high clip, while a contested end-zone heave is a low-percentage play. Tie + coin-flip OT beats a slim chance to win in regulation.',
      expert: 'Context can flip it: a badly outmatched team (or one whose defense can’t survive OT) might rationally take the win-now heave. But as a default, you take the high-probability path to extending the game — variance is the underdog’s friend, not the favorite’s.',
    },
  },
  {
    id: 'nfl-exp-4', level: 'expert',
    board: { kind: 'football', away: { name: 'Miners', abbr: 'MIN', score: 17 }, home: { name: 'Wolves', abbr: 'WOL', score: 20, possession: true },
      quarter: 'Q4', clock: '1:50', downDistance: '1st & 10', ballOn: 'WOL 40', timeouts: { away: 1, home: 3 } },
    prompt: 'Wolves lead by 3 with 1:50 left, 1st & 10; the Miners have ONE timeout. Can the Wolves end the game without another first down?',
    options: ['Yes — three kneel-downs run out the clock', 'No — they must gain at least one more first down', 'Only if they score again'],
    answer: 0,
    title: 'Victory formation: the kneel-down math',
    exp: {
      kid: 'The winning team can just kneel with the ball three times. Each kneel uses up lots of clock, and the other team can only stop it once with their timeout.',
      beginner: 'Between plays the offense can let up to 40 seconds tick off. Kneel #1 (Miners use their last timeout), kneel #2 burns ~40+, kneel #3 burns the rest — 1:50 is gone before 4th down ever comes.',
      intermediate: 'The arithmetic: 1:50 = 110 seconds. Opponent’s 1 timeout stops it once, then two full play-clock cycles (~40s each) plus play time (~2s each) ≈ 84+ seconds, and the third kneel’s runoff finishes it. Three kneels beat 110 seconds when the opponent has ≤1 timeout.',
      expert: 'The rule of thumb coaches carry: with a first down, you can kneel out ~40s per opponent-timeout-free down (about 2:00 max with none left after accounting for the snap). That’s why late defenses hoard timeouts — each one is ~40 seconds of life — and why a first down at 2:00 with zero opposing timeouts is checkmate.',
    },
  },
  {
    id: 'nfl-exp-5', level: 'expert',
    board: { kind: 'football', away: { name: 'Bulldogs', abbr: 'BUL', score: 14, possession: true }, home: { name: 'Stallions', abbr: 'STA', score: 21 },
      quarter: 'Q2', clock: '2:00', downDistance: '2nd & 5', ballOn: 'BUL 45' },
    prompt: 'The clock reads exactly 2:00 in Q2 and play stops automatically. What is this?',
    options: ['The two-minute warning — a free stoppage in each half', 'A TV timeout the referee felt like calling', 'A penalty for slow play'],
    answer: 0,
    title: 'The two-minute warning',
    exp: {
      kid: 'When the clock reaches 2 minutes left in a half, the game automatically pauses. It’s a built-in break before the exciting finish.',
      beginner: 'At 2:00 of the 2nd and 4th quarters, play stops automatically — it works like a free timeout for both teams and signals the start of “two-minute drill” time.',
      intermediate: 'Strategically it’s an extra timeout the trailing offense always gets: drives are planned around it (“we have two timeouts plus the warning”). Clock rules also tighten after it — e.g., runners going out of bounds stop the clock.',
      expert: 'Its origin is broadcast-era scheduling, but it’s now core clock strategy: leading teams want a first down BEFORE 2:00 (so kneels can span it), trailing defenses treat it as timeout #4. Counting “stops” (timeouts + warning + sidelines) is how coordinators script the final 120 seconds.',
    },
  },
  {
    id: 'nfl-exp-6', level: 'expert',
    board: { kind: 'football', away: { name: 'Miners', abbr: 'MIN', score: 23 }, home: { name: 'Wolves', abbr: 'WOL', score: 27, possession: false },
      quarter: 'Q4', clock: '0:00', downDistance: undefined, ballOn: 'WOL 8' },
    prompt: 'Time expired as the Wolves’ defense committed pass interference in the end zone. Is the game over?',
    options: ['No — the half can’t end on an accepted defensive penalty; untimed down', 'Yes — 0:00 always ends the game', 'Only if the referee wants overtime'],
    answer: 0,
    title: 'The untimed down',
    exp: {
      kid: 'Not yet! If the defense breaks a rule on the very last play, the other team gets one more play — even with no time left.',
      beginner: 'A half cannot end on an accepted defensive penalty. The offense gets one untimed down — here, from the 1-yard line (spot foul for DPI in the end zone) with a chance to win 29… well, 30–27 with the kick.',
      intermediate: 'The clock shows 0:00 but the game state says “one more snap.” The trailing team will take the TD chance; note they’d then choose whether to kick the meaningless XP. The same rule applies at the end of the 2nd quarter — a free play before halftime.',
      expert: 'Chain these and you get football’s wildest finishes: an untimed down can itself end in another defensive penalty → another untimed down, indefinitely. Defenses in this spot are coached to be almost passive — the only way to lose is to foul again.',
    },
  },
];
