// Read the Score — NHL bank. Scoring-RULE scenarios only (evergreen); team names are
// fictional set dressing. 6 scenarios per tier × 4 tiers. Pure data, zero RN imports.
import type { ScoreScenario } from '../readTheScore';

export const NHL_SCENARIOS: ScoreScenario[] = [
  // ── kid ────────────────────────────────────────────────────────────────────
  {
    id: 'nhl-kid-1', level: 'kid',
    board: { kind: 'hockey', away: { name: 'Glaciers', abbr: 'GLA', score: 3 }, home: { name: 'Frost', abbr: 'FRO', score: 1 },
      period: '2nd', clock: '12:44', sog: { away: 18, home: 11 } },
    prompt: 'Who is winning?',
    options: ['Glaciers', 'Frost', 'It’s a tie'],
    answer: 0,
    title: 'Glaciers lead 3–1',
    exp: {
      kid: 'The Glaciers have 3 goals and the Frost have 1. More goals wins!',
      beginner: 'Hockey counts GOALS — every goal is worth exactly 1, so scores stay small. 3–1 is a solid two-goal lead.',
      intermediate: 'Because goals are rare (about 6 total in a typical game), a 2-goal lead is significant — but hockey is famous for quick bursts; two goals can arrive in a minute.',
      expert: 'Hockey people call a 2-goal edge “the most dangerous lead” — big enough to relax, small enough to vanish in two shifts. Win-probability curves back the caution: a 2-goal lead midway through the 2nd is strong but far from safe.',
    },
  },
  {
    id: 'nhl-kid-2', level: 'kid',
    board: { kind: 'hockey', away: { name: 'Huskies', abbr: 'HUS', score: 0 }, home: { name: 'Icehawks', abbr: 'IHK', score: 2 },
      period: '1st', clock: '4:21' },
    prompt: 'The board says “1st” with the clock at 4:21. How is a hockey game divided?',
    options: ['3 periods', '4 quarters', '2 halves'],
    answer: 0,
    title: 'Hockey plays three periods',
    exp: {
      kid: 'Hockey is different — not quarters, not halves, but THREE periods. This is the first one.',
      beginner: 'Three periods of 20 minutes each, with two intermissions. The clock counts down from 20:00 in each period.',
      intermediate: 'The two intermissions matter: the ice is resurfaced, so early-period play is faster and cleaner. Teams also switch ends each period, which changes “long change” dynamics in the 2nd.',
      expert: 'The 2nd period’s “long change” (benches farther from the defensive zone) produces more tired-defender goals league-wide — a real scheduling quirk of the 3-period format that sharp viewers watch for.',
    },
  },
  {
    id: 'nhl-kid-3', level: 'kid',
    board: { kind: 'hockey', away: { name: 'Glaciers', abbr: 'GLA', score: 1 }, home: { name: 'Frost', abbr: 'FRO', score: 1 },
      period: '3rd', clock: '8:15', sog: { away: 22, home: 27 } },
    prompt: 'A puck crosses the goal line into the net. How much is a goal worth?',
    options: ['1 goal — every goal counts the same', '2 if it’s a slapshot', '3 from far away'],
    answer: 0,
    title: 'Every goal = 1',
    exp: {
      kid: 'All goals count as 1 — a tap-in from up close or a rocket from far away. The score just goes up by one.',
      beginner: 'Unlike basketball or football, hockey has no 2- or 3-point shots: the puck fully crossing the goal line = 1 goal, always.',
      intermediate: 'The puck must FULLY cross the line — a puck sitting half over the line is no goal. That inches-matter rule is why goal reviews stare at overhead camera frames.',
      expert: 'Flat scoring shapes strategy: there’s no “go long for more points” comeback lever, so trailing teams create volume instead — pulling the goalie for an extra attacker is the sport’s only way to raise the stakes of each possession.',
    },
  },
  {
    id: 'nhl-kid-4', level: 'kid',
    board: { kind: 'hockey', away: { name: 'Huskies', abbr: 'HUS', score: 2, }, home: { name: 'Icehawks', abbr: 'IHK', score: 3 },
      period: '2nd', clock: '15:02', situation: 'PP HUSKIES 1:36' },
    prompt: 'The board shows “PP HUSKIES 1:36.” What is happening?',
    options: ['The Huskies have a power play — an extra skater for 1:36', 'The Huskies lost a player for good', 'A penalty shot is coming'],
    answer: 0,
    title: 'PP = power play',
    exp: {
      kid: 'An Icehawks player broke a rule and has to sit in the penalty box. Until the time runs out, the Huskies get to play with one MORE skater — a power play!',
      beginner: 'A penalty sends the offender to the box (usually 2 minutes), and their team plays short-handed — 5 skaters vs 4. The clock on the board counts the remaining advantage.',
      intermediate: 'Power plays convert around 20% league-wide — the biggest scoring lever in a low-scoring sport. The short-handed team just tries to survive: clear pucks, block shots, kill the clock.',
      expert: 'Watch the PP clock like the score: a fresh 2:00 5-on-4 swings expected goals by ~0.2 — huge in a 3-goal sport. And a minor penalty ENDS the moment the power-play team scores, which is the next rule up the ladder.',
    },
  },
  {
    id: 'nhl-kid-5', level: 'kid',
    board: { kind: 'hockey', away: { name: 'Glaciers', abbr: 'GLA', score: 4 }, home: { name: 'Frost', abbr: 'FRO', score: 2 },
      period: '3rd', clock: '0:00' },
    prompt: 'The 3rd-period clock hits 0:00 with the Glaciers ahead 4–2. What happens?',
    options: ['Game over — Glaciers win', 'A 4th period starts', 'A shootout happens anyway'],
    answer: 0,
    title: 'Ahead after three periods = final',
    exp: {
      kid: 'Three periods are the whole game. The Glaciers are ahead, so they win — handshakes and home!',
      beginner: 'A game only continues past the 3rd period if the score is TIED. With a leader at 0:00 of the 3rd, that’s the final score.',
      intermediate: 'Tied games go to overtime (and possibly a shootout in the regular season) — but that’s exclusively for ties. A regulation win is worth more in the standings than an OT/shootout win… well, both are 2 points, but the LOSER of OT gets 1.',
      expert: 'The standings nuance: regulation wins are the first tiebreaker in NHL standings precisely because OT/shootout results carry a “loser point.” Teams late in a tied 3rd sometimes play safe to guarantee the 1 point before chasing the 2nd — a real, observable incentive quirk.',
    },
  },
  {
    id: 'nhl-kid-6', level: 'kid',
    board: { kind: 'hockey', away: { name: 'Huskies', abbr: 'HUS', score: 1 }, home: { name: 'Icehawks', abbr: 'IHK', score: 1 },
      period: '2nd', clock: '9:58', sog: { away: 19, home: 12 } },
    prompt: 'The board shows “SOG 19–12.” The score is 1–1. What is SOG?',
    options: ['Shots on goal — attempts the goalie had to stop', 'Second overtime goals', 'Skaters on the ice'],
    answer: 0,
    title: 'SOG counts shots, not goals',
    exp: {
      kid: 'SOG counts every shot aimed at the net — the goalies stopped almost all of them! It shows who is attacking more.',
      beginner: 'Shots on goal = shots that would go in if not saved. 19–12 says the Huskies are creating more chances even though the score is level — the goalie is keeping the Icehawks in it.',
      intermediate: 'SOG is the classic “who’s actually winning the play” stat: a 1–1 game at 19–12 shots suggests one goalie is outperforming. Score tells you the result; shots hint at what happens next.',
      expert: 'SOG has known limits — it ignores shot QUALITY — which is why analysts moved to expected goals (xG). But on a live scoreboard, a big shot gap with a level score is still your fastest read that the score is “unstable” and likely to break one way.',
    },
  },

  // ── beginner ──────────────────────────────────────────────────────────────
  {
    id: 'nhl-beg-1', level: 'beginner',
    board: { kind: 'hockey', away: { name: 'Glaciers', abbr: 'GLA', score: 2 }, home: { name: 'Frost', abbr: 'FRO', score: 2 },
      period: '3rd', clock: '0:00' },
    prompt: 'The 3rd period ends 2–2. What happens next in a regular-season game?',
    options: ['5 minutes of 3-on-3 overtime, sudden death', 'A replay tomorrow', 'It ends as a tie'],
    answer: 0,
    title: 'Regular-season OT: 5:00 of 3-on-3',
    exp: {
      kid: 'They play a short 5-minute extra period with only 3 skaters a side — lots of open ice! First goal wins instantly.',
      beginner: 'Regular-season overtime is 5 minutes of 3-on-3, sudden death — first goal ends it. Still tied after that? A shootout decides the winner.',
      intermediate: '3-on-3 is designed to force a result: with so much open ice, chances come constantly. Teams even pull moves like circling back to regroup — possession is everything when a single rush can end the game.',
      expert: 'Playoff OT is a different animal: full 5-on-5, 20-minute periods, sudden death, no shootout — games can run to double or triple OT. Knowing WHICH overtime you’re watching (regular vs playoffs) changes how you read every risk the teams take.',
    },
  },
  {
    id: 'nhl-beg-2', level: 'beginner',
    board: { kind: 'hockey', away: { name: 'Huskies', abbr: 'HUS', score: 3 }, home: { name: 'Icehawks', abbr: 'IHK', score: 3 },
      period: 'SO', clock: '--', situation: 'SHOOTOUT' },
    prompt: 'The board reads “SO.” How does a shootout work?',
    options: ['3 shooters each, one-on-one vs the goalie; more goals wins', 'Sudden-death shooting until a miss', 'Captains shoot until someone scores'],
    answer: 0,
    title: 'The shootout: best of 3, then sudden death',
    exp: {
      kid: 'Each team picks 3 players. One at a time, they skate in alone against the goalie. Whichever team scores more wins!',
      beginner: 'Three rounds of penalty shots, alternating. If it’s still level after 3 rounds, it goes shooter-by-shooter sudden death (new players until everyone has gone once).',
      intermediate: 'The shootout only exists in the regular season — playoffs play real overtime until a goal. The winning team gets a goal ADDED to its score, so the final reads like 4–3.',
      expert: 'That +1 is cosmetic bookkeeping: shootout goals don’t count in player scoring stats, and the game counts as an OT/SO result in standings (winner 2 points, loser 1). Some markets and tiebreakers treat SO wins as lesser — regulation wins are the premium currency.',
    },
  },
  {
    id: 'nhl-beg-3', level: 'beginner',
    board: { kind: 'hockey', away: { name: 'Glaciers', abbr: 'GLA', score: 1, }, home: { name: 'Frost', abbr: 'FRO', score: 2 },
      period: '2nd', clock: '7:40', situation: 'PP FROST 0:48' },
    prompt: 'The Frost are on a power play (0:48 left) — and they SCORE. What happens to the penalty?',
    options: ['It ends immediately — the penalized player returns', 'It keeps running the full 2:00', 'It doubles'],
    answer: 0,
    title: 'A power-play goal ends a minor penalty',
    exp: {
      kid: 'Once the team with extra players scores, the punished player gets out of the box right away. Back to even teams!',
      beginner: 'A MINOR (2-minute) penalty ends the instant the power-play team scores. The teams return to full strength — one power play, one goal, done.',
      intermediate: 'This is why penalty killers play desperate hockey: surviving the 2:00 costs nothing, but one goal both scores AND ends the punishment. Note the exception coming at higher tiers: major penalties don’t work this way.',
      expert: 'The rule creates the “kill the first minute” doctrine — PP conversion is front-loaded while the setup is fresh. Also note double-minors (4:00): a goal ends only the CURRENT 2:00 chunk, and the second minor still runs. The box clock on the board tells you which situation you’re in.',
    },
  },
  {
    id: 'nhl-beg-4', level: 'beginner',
    board: { kind: 'hockey', away: { name: 'Huskies', abbr: 'HUS', score: 2 }, home: { name: 'Icehawks', abbr: 'IHK', score: 4 },
      period: '3rd', clock: '1:44', situation: 'EMPTY NET HUS' },
    prompt: '“EMPTY NET HUS” — the Huskies’ goalie has skated to the bench. Why would a team remove its own goalie?',
    options: ['To add a 6th attacker while trailing late', 'The goalie is injured', 'It’s required in the final 2:00'],
    answer: 0,
    title: 'Pulling the goalie: 6 attackers, 0 margin for error',
    exp: {
      kid: 'They’re losing with almost no time left — so the goalie leaves and an extra attacker jumps on. More attackers, better chance to score… but their own net is wide open!',
      beginner: 'Trailing teams pull the goalie late for a 6-on-5 skater advantage. Score and you’re back in it; lose the puck and the opponent can shoot into the empty net from anywhere.',
      intermediate: 'The math says it’s right: you lose either way if you don’t score, so the empty-net goals against don’t really cost anything — the extra attacker meaningfully raises your chance to tie. Analytics pushed pull times earlier (down 2 goals, teams now pull with 3+ minutes left).',
      expert: 'The frontier keeps moving: models suggest pulling even earlier than coaches’ comfort (some say 4–5 minutes down 2). The asymmetry is the whole argument — a 6-on-5 boosts your tie probability by more than empty-netters reduce it, because a 1-goal loss and 2-goal loss are worth the same: zero points.',
    },
  },
  {
    id: 'nhl-beg-5', level: 'beginner',
    board: { kind: 'hockey', away: { name: 'Glaciers', abbr: 'GLA', score: 0 }, home: { name: 'Frost', abbr: 'FRO', score: 0 },
      period: '1st', clock: '20:00' },
    prompt: 'The period clock starts at 20:00. How much total regulation time is in the game?',
    options: ['60 minutes', '48 minutes', '90 minutes'],
    answer: 0,
    title: '3 × 20 = 60 minutes',
    exp: {
      kid: 'Three periods of 20 minutes each — that’s 60 minutes of hockey.',
      beginner: 'Regulation is 60 minutes. The clock stops at every whistle (offside, icing, goals, penalties), so real time runs much longer.',
      intermediate: 'The stop-clock means every second is real playing time — no kneel-downs, no dribbling out the clock without pressure. A trailing team always has a live chance while seconds remain.',
      expert: 'Hockey’s clock-stoppage plus unlimited “on the fly” substitutions creates the shift structure — 45-second bursts at full sprint. Reading line changes against the clock (catching a tired defense pair late in a shift) is a real in-game edge coaches chase.',
    },
  },
  {
    id: 'nhl-beg-6', level: 'beginner',
    board: { kind: 'hockey', away: { name: 'Huskies', abbr: 'HUS', score: 1 }, home: { name: 'Icehawks', abbr: 'IHK', score: 3 },
      period: '2nd', clock: '11:26', situation: 'PP ICEHAWKS 1:12' },
    prompt: 'While short-handed, a Huskies penalty-killer steals the puck and scores. Does it count?',
    options: ['Yes — a short-handed goal counts like any other', 'No — short-handed teams can’t score', 'It counts but the penalty restarts'],
    answer: 0,
    title: 'The short-handed goal',
    exp: {
      kid: 'Yes! Even the team with fewer players can score. It’s called a short-handed goal, and it counts just the same.',
      beginner: 'Being down a skater doesn’t disable scoring — a breakaway off a power-play turnover is classic. Note the penalty does NOT end when the short-handed team scores; the box time keeps running.',
      intermediate: 'That asymmetry is worth learning: PP goal → minor penalty ends; SH goal → penalty continues. Short-handed goals are also momentum bombs — they punish sloppy power plays that treat defense as optional.',
      expert: 'Aggressive penalty kills hunt exactly this: pressure the PP’s weakest handler at the blue line, spring a 2-on-1. A team’s SH-goals-for rate tracks its kill philosophy (passive box vs attacking kill) — visible live whenever the kill starts jumping passing lanes.',
    },
  },

  // ── intermediate ──────────────────────────────────────────────────────────
  {
    id: 'nhl-int-1', level: 'intermediate',
    board: { kind: 'hockey', away: { name: 'Glaciers', abbr: 'GLA', score: 2 }, home: { name: 'Frost', abbr: 'FRO', score: 2 },
      period: 'OT', clock: '3:12', situation: '3-ON-3' },
    prompt: 'Regular-season OT, 3-on-3, 3:12 left. A goal is scored. What happens?',
    options: ['Game ends instantly — sudden death', 'Play continues to 0:00', 'The other team gets a reply chance'],
    answer: 0,
    title: 'Sudden death: first goal wins',
    exp: {
      kid: 'In overtime, the first team to score wins right away — the game just stops. That’s why it’s called sudden death!',
      beginner: 'OT isn’t a full period that plays out — any goal ends it immediately. Score at 3:12 and the last 3:12 never happens.',
      intermediate: 'Sudden death changes risk math completely: a 2-on-1 rush against you IS the game. That’s why 3-on-3 teams sometimes retreat and regroup with full possession rather than force a contested entry — no goal against is priority one.',
      expert: 'Watch possession-hoarding in 3-on-3: teams circle back to their own zone to reset because a turnover in transition is near-fatal. Analytically, OT shifts are about controlling the FIRST chance — the first team to generate a high-danger look wins a disproportionate share.',
    },
  },
  {
    id: 'nhl-int-2', level: 'intermediate',
    board: { kind: 'hockey', away: { name: 'Huskies', abbr: 'HUS', score: 4 }, home: { name: 'Icehawks', abbr: 'IHK', score: 3 },
      period: 'FINAL/OT', clock: '0:00' },
    prompt: 'The final reads 4–3 in OT. In the standings, what does each team get?',
    options: ['Winner 2 points, loser 1 point', 'Winner 2, loser 0', 'Winner 3, loser 1'],
    answer: 0,
    title: 'The loser point',
    exp: {
      kid: 'The winner gets 2 points for the standings. The loser still gets 1 point as a prize for making it to overtime.',
      beginner: 'NHL standings: any win = 2 points. A REGULATION loss = 0, but lose in overtime or a shootout and you keep 1 — the “loser point.”',
      intermediate: 'This makes late tied games weird: both teams are guaranteed 1 point the moment regulation ends tied, so a cagey, low-risk final minute of a tied 3rd is often rational — protect the sure point, then gamble in OT.',
      expert: 'The loser point inflates standings (a team can be under .500 in real terms yet look healthy in points) — hence “regulation wins” as the first tiebreaker and the analytics convention of points percentage. Reading an NHL table without knowing this rule genuinely misleads you.',
    },
  },
  {
    id: 'nhl-int-3', level: 'intermediate',
    board: { kind: 'hockey', away: { name: 'Glaciers', abbr: 'GLA', score: 1 }, home: { name: 'Frost', abbr: 'FRO', score: 0 },
      period: '1st', clock: '6:19', situation: 'PP GLACIERS 4:32 (MAJOR)' },
    prompt: 'The Glaciers are on a 5-minute MAJOR power play and just scored. Does the penalty end?',
    options: ['No — major penalties run the full 5:00 regardless of goals', 'Yes — all penalties end on a goal', 'Only if the referee agrees'],
    answer: 0,
    title: 'Majors don’t end on a goal',
    exp: {
      kid: 'This is the bigger, 5-minute punishment — and it does NOT end when the other team scores. They can keep scoring for the whole 5 minutes!',
      beginner: 'Minor (2:00) penalties end on a power-play goal; MAJOR (5:00) penalties don’t. The short-handed team must survive all five minutes no matter how many goals it concedes.',
      intermediate: 'That’s why a major is a game-changing event: multiple PP goals on one penalty is realistic. Majors come with the fighting/boarding/high-danger class of fouls, and often a game misconduct on top.',
      expert: 'League practice: five-minute majors for contact fouls are typically reviewed on ice and can be reduced to minors — because the no-relief-on-goals rule makes the major SO punitive. When you see the refs at the monitor after a big hit, this rule is what they’re weighing.',
    },
  },
  {
    id: 'nhl-int-4', level: 'intermediate',
    board: { kind: 'hockey', away: { name: 'Huskies', abbr: 'HUS', score: 2 }, home: { name: 'Icehawks', abbr: 'IHK', score: 2 },
      period: '3rd', clock: '4:55', situation: '5-ON-3 HUS 0:54' },
    prompt: 'The board shows “5-ON-3” for 54 seconds. What is this situation?',
    options: ['Two Icehawks are in the box — a two-man advantage', 'A line brawl aftermath', 'Delayed penalty coming'],
    answer: 0,
    title: 'The two-man advantage',
    exp: {
      kid: 'TWO players from the same team are in the penalty box at once — so it’s 5 skaters against 3. Huge chance to score!',
      beginner: 'Overlapping penalties create a 5-on-3. The shorthanded team can’t even ice the puck safely — expect the attacking team to camp in the zone and pepper the net.',
      intermediate: '5-on-3s convert at roughly double a normal power play. The defense collapses into a tight triangle and blocks everything; the offense works for a cross-ice one-timer the triangle can’t reach in time.',
      expert: 'Detail: teams never play fewer than 3 skaters — a third penalty’s time doesn’t START until one of the first two expires (stacked penalties). So a “5-on-3 plus one waiting” is the worst legal situation in hockey, and killing it is a season-highlight feat for a PK unit.',
    },
  },
  {
    id: 'nhl-int-5', level: 'intermediate',
    board: { kind: 'hockey', away: { name: 'Glaciers', abbr: 'GLA', score: 3 }, home: { name: 'Frost', abbr: 'FRO', score: 3 },
      period: 'SO', clock: '--', situation: 'SO: GLA ●○● | FRO ●●' },
    prompt: 'Shootout: Glaciers have scored 2 of 3; Frost have scored 2 of 2 with one shooter left. What does the final Frost shooter mean?',
    options: ['Score and the Frost win without needing more rounds', 'It’s automatically sudden death', 'The Frost already won'],
    answer: 0,
    title: 'Reading a shootout line',
    exp: {
      kid: 'The dots show each try: filled = goal, empty = miss. The Frost have 2 goals and one more turn — if this shooter scores, they win 3–2!',
      beginner: 'Best-of-3 logic: Glaciers finished 2/3. The Frost are 2/2, so scoring on their last attempt wins it 3–2; missing means 2–2 and sudden-death rounds begin.',
      intermediate: 'Same clinch logic as any best-of series — a shootout can also end EARLY if a team becomes uncatchable (up 2 with 1 remaining), in which case the last shot isn’t even taken.',
      expert: 'Order strategy is real: coaches slot their most reliable scorer where clinch/must-score situations are likeliest (often 3rd). Goalies own the information edge in sudden death — shooters can’t repeat until everyone’s gone, so scouting depth matters more each round.',
    },
  },
  {
    id: 'nhl-int-6', level: 'intermediate',
    board: { kind: 'hockey', away: { name: 'Huskies', abbr: 'HUS', score: 0 }, home: { name: 'Icehawks', abbr: 'IHK', score: 1 },
      period: '2nd', clock: '13:37', situation: 'DELAYED PENALTY — IHK' },
    prompt: '“DELAYED PENALTY” against the Icehawks, but play continues and the Huskies’ goalie is sprinting off. Why?',
    options: ['Play only stops when the Icehawks touch the puck — so the Huskies add a free extra attacker', 'The goalie is being penalized', 'The refs forgot to whistle'],
    answer: 0,
    title: 'The delayed-penalty 6-on-5',
    exp: {
      kid: 'The referee’s arm is up — a penalty is coming, but the game won’t stop until the OTHER team touches the puck. So the good team’s goalie runs off for an extra attacker. They can’t be scored on while they have the puck!',
      beginner: 'On a delayed call, play stops only when the offending team gains possession. Since the non-offending team can’t concede (any Icehawks touch = whistle), pulling the goalie for a 6th attacker is free offense.',
      intermediate: 'Almost free: the infamous exception is scoring on your OWN net in the scramble — it counts, because the whistle needs an opponent’s touch, not a goal. It’s rare but it’s the risk teams accept.',
      expert: 'Modern teams treat delayed penalties as mini power plays and run set plays off them; some even delay their zone entry to complete the goalie swap first. Watch the ref’s raised arm → goalie sprint → 6-on-5 sequence; it’s one of the best “rules literacy” moments in a live game.',
    },
  },

  // ── expert ────────────────────────────────────────────────────────────────
  {
    id: 'nhl-exp-1', level: 'expert',
    board: { kind: 'hockey', away: { name: 'Glaciers', abbr: 'GLA', score: 2 }, home: { name: 'Frost', abbr: 'FRO', score: 3 },
      period: '3rd', clock: '1:21', situation: 'EMPTY NET GLA · PP FROST 0:40' },
    prompt: 'Frost lead by 1, on a power play — AND the trailing Glaciers pulled their goalie anyway. What’s the skater count?',
    options: ['5 attackers vs 5 — the pull cancels the shorthanded deficit', '6 vs 4', '4 vs 5 still'],
    answer: 0,
    title: 'Pulling the goalie while short-handed',
    exp: {
      kid: 'The losing team is a player short from a penalty — but sending the goalie off adds one back. So it’s 5 against 5, just with one net empty!',
      beginner: 'Penalized (−1) plus goalie pulled (+1 skater) = 5 skaters vs the power play’s 5. The Glaciers accept the empty net to erase the manpower deficit while they chase the tie.',
      intermediate: 'It’s the same asymmetric logic as a normal pull, sharpened: killing a penalty at 4-on-5 while trailing late is nearly hopeless, so convert it to 5-on-5 with an empty cage. An empty-net goal against changes nothing (a loss is a loss).',
      expert: 'You’ll see this from good coaches in the last ~2:00: down 1 ON the kill, pull immediately rather than burn the clock 4-on-5. The board reading skill is stacking situations — EN + PP tags together tell you the true on-ice count, which the score alone never shows.',
    },
  },
  {
    id: 'nhl-exp-2', level: 'expert',
    board: { kind: 'hockey', away: { name: 'Huskies', abbr: 'HUS', score: 3 }, home: { name: 'Icehawks', abbr: 'IHK', score: 3 },
      period: '3rd', clock: '0:58', sog: { away: 31, home: 30 } },
    prompt: 'Tied with a minute left in the 3rd (regular season). Why do BOTH teams suddenly play cautiously?',
    options: ['Reaching OT guarantees each team at least 1 standings point', 'Players are tired', 'The rules require it'],
    answer: 0,
    title: 'Protecting the guaranteed point',
    exp: {
      kid: 'If the game reaches overtime, BOTH teams get at least 1 point in the standings. Nobody wants to lose that gift in the last minute!',
      beginner: 'A regulation loss pays 0; an OT/shootout loss pays 1. Tied at 0:58, both teams effectively hold a point — risky pinches that concede a rush goal now cost a real standings point.',
      intermediate: 'This is the loser point’s incentive warp: the final minute of tied regulation is often the SAFEST hockey of the night, then OT explodes into chances. The rulebook accidentally choreographs the drama.',
      expert: 'Economists love this one: the 2-1-0/2-2-1 point structure makes ties-at-60-minutes collectively optimal, and observed play matches (shot rates drop in the last minute of tied 3rds, spike in OT). It’s a textbook case of standings design shaping in-game behavior — visible on any live scoreboard.',
    },
  },
  {
    id: 'nhl-exp-3', level: 'expert',
    board: { kind: 'hockey', away: { name: 'Glaciers', abbr: 'GLA', score: 1 }, home: { name: 'Frost', abbr: 'FRO', score: 2 },
      period: '2nd', clock: '8:03', situation: 'PP FROST — 4:00 DOUBLE MINOR 2:47' },
    prompt: 'A 4-minute DOUBLE MINOR power play, 2:47 left. The Frost score. What happens to the penalty clock?',
    options: ['Only the current 2:00 block ends — the rest still runs', 'The whole 4:00 wipes out', 'Nothing changes on any goal'],
    answer: 0,
    title: 'Double minors burn one block at a time',
    exp: {
      kid: 'A double penalty is really two 2-minute penalties stacked. A goal only erases the one that’s running — the second one still has to be served.',
      beginner: 'Double minor = 2:00 + 2:00. A power-play goal ends only the block in progress: at 2:47 remaining, the first block’s 0:47 dies and the fresh 2:00 begins. The Frost stay on the power play.',
      intermediate: 'So a double minor can yield TWO power-play goals with the penalty still doing its job in between — much closer to a major in real cost than “just two minors” sounds. High-sticking with blood drawn is the classic double-minor call.',
      expert: 'Clock bookkeeping is a real skill: goal at 2:47 remaining → penalty clock resets to 2:00, not zero. Broadcasters get this wrong live; scoreboards don’t. The general rule set — minor dies on a goal, major never, double minor by blocks — covers every PP clock situation you’ll ever see.',
    },
  },
  {
    id: 'nhl-exp-4', level: 'expert',
    board: { kind: 'hockey', away: { name: 'Huskies', abbr: 'HUS', score: 2 }, home: { name: 'Icehawks', abbr: 'IHK', score: 2 },
      period: 'OT', clock: '2:26', situation: 'PENALTY IHK — 3-ON-3?' },
    prompt: 'A penalty is called during 3-on-3 overtime. Teams can’t drop below 3 skaters — so what does the power play look like?',
    options: ['4-on-3 — the non-offending team ADDS a skater', '3-on-2', 'A penalty shot instead'],
    answer: 0,
    title: 'OT penalties: add, don’t subtract',
    exp: {
      kid: 'A team can never have fewer than 3 skaters. So instead of the bad team losing a player, the GOOD team gets an extra one — 4 against 3!',
      beginner: 'The 3-skater floor means OT penalties are served by addition: the fouled team goes to 4 skaters for the penalty duration. A 4-on-3 in open OT ice is close to a scoring guarantee.',
      intermediate: 'If the penalty expires without a goal, play continues 4-on-4 until the next whistle, THEN returns to 3-on-3. That little detail — the delayed return to 3s — trips up even seasoned viewers reading the ice.',
      expert: '4-on-3 PP geometry is unique: one fewer defender than a 5-on-4 but proportionally more ice per attacker — conversion rates run higher than any standard PP. Teams keep a dedicated 4-on-3 setup (usually a 1-3 umbrella hunting the one-timer through the seam). OT discipline is thus a hidden standings stat.',
    },
  },
  {
    id: 'nhl-exp-5', level: 'expert',
    board: { kind: 'hockey', away: { name: 'Glaciers', abbr: 'GLA', score: 0 }, home: { name: 'Frost', abbr: 'FRO', score: 1 },
      period: '3rd', clock: '11:50', situation: 'PENALTY SHOT — GLA' },
    prompt: 'The board announces a PENALTY SHOT for the Glaciers. What earns one, instead of a normal power play?',
    options: ['A foul from behind on a clean breakaway (denying the chance)', 'Any tripping penalty', 'Two minors at once'],
    answer: 0,
    title: 'The penalty shot: restoring a stolen breakaway',
    exp: {
      kid: 'A player was skating in all alone to score and got pulled down from behind. Since the foul stole a super chance, the rules give it back: one free skate-in, one-on-one with the goalie.',
      beginner: 'When a foul from behind denies a clear breakaway (no defender between attacker and goalie, puck under control), the referee can award a penalty shot instead of a minor — the rulebook literally replaces the stolen chance.',
      intermediate: 'Other triggers exist: a defender covering the puck in his own crease with a hand, or throwing a stick at the puck carrier. The logic is always the same — the foul erased a near-certain chance, so a time-served penalty would under-compensate.',
      expert: 'Penalty shots convert around ~30% — notably LOWER than many coaches’ instinct, and comparable to a strong power play’s expected value over 2:00. Referees weigh exactly that trade when choosing shot vs minor on borderline breakaway fouls; in the final minutes, teams often prefer the shot (a discrete chance beats clock-limited PP time).',
    },
  },
  {
    id: 'nhl-exp-6', level: 'expert',
    board: { kind: 'hockey', away: { name: 'Huskies', abbr: 'HUS', score: 4 }, home: { name: 'Icehawks', abbr: 'IHK', score: 5 },
      period: 'FINAL/SO', clock: '0:00' },
    prompt: 'The final reads 5–4 (SO). What does the “extra” goal in the score actually represent?',
    options: ['A bookkeeping goal added for winning the shootout', 'The best shootout goal', 'An empty-netter'],
    answer: 0,
    title: 'The phantom shootout goal',
    exp: {
      kid: 'The teams were really tied 4–4. Winning the shootout adds one pretend goal to the winner’s score, so the books show 5–4.',
      beginner: 'Shootout wins are recorded as a one-goal victory: the winner’s score gets +1 regardless of the shootout tally (win it 3–0 or 1–0 in rounds, the final still shows one extra goal).',
      intermediate: 'That phantom goal is credited to no player — it doesn’t appear in anyone’s stats, and the game officially ends 60-minutes-tied for analytics purposes. “(SO)” on a score line is your cue the real hockey ended 4–4.',
      expert: 'Consequences: goal differential in standings includes the phantom goal (a quirk purists dislike), player goal totals don’t, and models treat SO outcomes as near coin-flips — which is why points-percentage tables and “regulation + OT wins” exist. Reading “5–4 (SO)” as “a tied game plus a skills contest” is the expert’s parse.',
    },
  },
];
