// Read the Score — Rugby bank (rugby union; serves the pooled rugby/mlr category).
// Scoring-RULE scenarios only (evergreen); team names are fictional set dressing.
// Point values: try 5, conversion 2, penalty goal 3, drop goal 3, penalty try 7.
// 6 scenarios per tier × 4 tiers. Pure data, zero RN imports.
import type { ScoreScenario } from '../readTheScore';

export const RUGBY_SCENARIOS: ScoreScenario[] = [
  // ── kid ────────────────────────────────────────────────────────────────────
  {
    id: 'rug-kid-1', level: 'kid',
    board: { kind: 'rugby', home: { name: 'Stags', abbr: 'STG', score: 15 }, away: { name: 'Harriers', abbr: 'HRR', score: 10 },
      clock: "52'" },
    prompt: 'Who is winning?',
    options: ['Stags', 'Harriers', 'It’s level'],
    answer: 0,
    title: 'Stags lead 15–10',
    exp: {
      kid: 'The Stags have 15 points and the Harriers have 10. Most points wins!',
      beginner: 'Rugby points come in chunks — tries (5), conversion kicks (2), penalty kicks (3). A 5-point lead means one converted try flips the game.',
      intermediate: '15–10 is a “one-score game”: a converted try (5+2=7) puts the Harriers ahead. Reading margins in units of 7 (converted try) and 3 (kick) is core rugby literacy.',
      expert: 'Margin grammar: within 3 = a kick levels/wins; within 7 = one converted try; 8+ = two scores. Teams’ decisions (kick at goal vs kick to the corner) flow directly from which bracket the margin sits in.',
    },
  },
  {
    id: 'rug-kid-2', level: 'kid',
    board: { kind: 'rugby', home: { name: 'Bison', abbr: 'BIS', score: 5 }, away: { name: 'Kestrels', abbr: 'KES', score: 0 },
      clock: "14'" },
    prompt: 'A Bison player touches the ball down over the goal line. What is that called and what’s it worth?',
    options: ['A try — 5 points', 'A touchdown — 6 points', 'A goal — 1 point'],
    answer: 0,
    title: 'The try: 5 points',
    exp: {
      kid: 'Grounding the ball past the goal line is a TRY — worth 5 points. It’s rugby’s biggest prize!',
      beginner: 'A try = pressing the ball down in the opponent’s in-goal area. 5 points, plus the chance to “convert” it with a kick for 2 more.',
      intermediate: 'Unlike American football, the ball must be TOUCHED DOWN with downward pressure — crossing the line isn’t enough. Drop it or lose control over the line and it’s nothing.',
      expert: 'The grounding requirement drives the classic contests: defenders sliding under the ball-carrier to hold the ball up (no grounding = no try, goal-line drop-out instead), and the TMO replays scrutinizing whether downward pressure was applied. The name “try” is historical — originally it only earned an attempt (“a try”) at goal.',
    },
  },
  {
    id: 'rug-kid-3', level: 'kid',
    board: { kind: 'rugby', home: { name: 'Stags', abbr: 'STG', score: 7 }, away: { name: 'Bison', abbr: 'BIS', score: 3 },
      clock: "31'" },
    prompt: 'After a try, a player kicks the ball between the posts. What is this kick?',
    options: ['A conversion — 2 extra points', 'A field goal — 3 points', 'A bonus try'],
    answer: 0,
    title: 'The conversion: +2 after a try',
    exp: {
      kid: 'After a try, the scoring team gets a bonus kick at the posts. Make it and that’s 2 more points — 5 + 2 = 7!',
      beginner: 'The conversion is kicked from a spot in line with WHERE the try was scored — score near the corner and the kick is from a nasty angle; score under the posts and it’s simple.',
      intermediate: 'That placement rule is why try-scorers run toward the posts before dotting down when they can — a few extra strides turn a touchline conversion into a gimme, upgrading 5-point tries into 7s.',
      expert: 'Conversion placement is a real strategic layer: teams attack the corner when defense dictates but coaches track “conversion-adjusted” try value. At the elite level touchline conversions make ~60–70%, central ones ~99% — the diagonal run to centre is worth ~0.6 points a try.',
    },
  },
  {
    id: 'rug-kid-4', level: 'kid',
    board: { kind: 'rugby', home: { name: 'Kestrels', abbr: 'KES', score: 3 }, away: { name: 'Harriers', abbr: 'HRR', score: 0 },
      clock: "9'" },
    prompt: 'The referee awards a penalty and the Kestrels kick it through the posts. How many points?',
    options: ['3 points', '5 points', '2 points'],
    answer: 0,
    title: 'The penalty goal: 3 points',
    exp: {
      kid: 'When the other team breaks the rules, you can kick at the posts from where it happened. Through the middle = 3 points.',
      beginner: 'A penalty goal is worth 3. Teams choose it when they’re within their kicker’s range and a try looks unlikely — steady points for the opponent’s mistakes.',
      intermediate: 'The penalty menu: kick at goal (3), kick to touch for an attacking lineout (0 now, try chance next), scrum, or tap-and-go. The scoreboard and clock decide which — that choice is rugby’s most repeated strategic moment.',
      expert: 'Discipline is scoreboard currency: elite kickers land 75–85% from range, so every ruck infringement in your own half is ~2.4 expected points donated. Teams giving away 12+ penalties rarely win — the penalty count is the hidden score.',
    },
  },
  {
    id: 'rug-kid-5', level: 'kid',
    board: { kind: 'rugby', home: { name: 'Bison', abbr: 'BIS', score: 12 }, away: { name: 'Stags', abbr: 'STG', score: 12 },
      clock: "40' HT" },
    prompt: 'The clock shows 40’ and HT. How long is a rugby match?',
    options: ['Two 40-minute halves — 80 minutes', 'Four 20-minute quarters', 'Two 45-minute halves'],
    answer: 0,
    title: 'Rugby: 40 + 40',
    exp: {
      kid: 'Rugby is played in two halves of 40 minutes each — 80 minutes in all. It’s halftime now!',
      beginner: 'Two 40-minute halves with the clock counting UP, like soccer — but rugby’s clock STOPS for long breaks (TMO reviews, injuries), so the board time is closer to real playing time.',
      intermediate: 'Because the match clock stops for major stoppages, rugby has no soccer-style added time — when the clock passes 80:00, the half ends at the next dead ball. The board is the truth.',
      expert: 'That “next dead ball” rule creates rugby’s signature finishes: a team trailing at 80:00 can keep the ball alive through dozens of phases — the game literally cannot end while they maintain possession. Multi-minute after-the-siren epics are a structural feature, not luck.',
    },
  },
  {
    id: 'rug-kid-6', level: 'kid',
    board: { kind: 'rugby', home: { name: 'Harriers', abbr: 'HRR', score: 17 }, away: { name: 'Kestrels', abbr: 'KES', score: 8 },
      clock: "66'", tally: { home: { t: 2, c: 2, p: 1, d: 0 }, away: { t: 1, c: 0, p: 1, d: 0 } } },
    prompt: 'The board shows a “T” column with 2 for the Harriers. What does T count?',
    options: ['Tries scored', 'Tackles made', 'Timeouts left'],
    answer: 0,
    title: 'T is for tries',
    exp: {
      kid: 'T counts tries! The Harriers have scored 2 tries. The other letters count the kicks: C for conversions, P for penalties.',
      beginner: 'The tally row is the score’s recipe: T (tries ×5), C (conversions ×2), P (penalty goals ×3), D (drop goals ×3). Harriers: 2×5 + 2×2 + 1×3 = 17. It checks out!',
      intermediate: 'Reading the tally beats reading the total: 17 built on 2 tries reads “attacking team,” while 17 from penalties says “disciplined kicker, struggling attack.” Same number, opposite stories.',
      expert: 'The tally also flags competition bonus points at a glance: in many leagues a 4th try earns the attacking bonus regardless of result. Commentators tracking “they need two more tries for the bonus” are reading this exact row, not the score.',
    },
  },

  // ── beginner ──────────────────────────────────────────────────────────────
  {
    id: 'rug-beg-1', level: 'beginner',
    board: { kind: 'rugby', home: { name: 'Stags', abbr: 'STG', score: 7 }, away: { name: 'Kestrels', abbr: 'KES', score: 6 },
      clock: "44'", tally: { home: { t: 1, c: 1, p: 0, d: 0 }, away: { t: 0, c: 0, p: 2, d: 0 } } },
    prompt: 'Stags: 1 try, 1 conversion. Kestrels: 2 penalty goals. Check the math — why is it 7–6?',
    options: ['5+2 = 7 beats 3+3 = 6', 'Tries are 6 points', 'Conversions are 3 points'],
    answer: 0,
    title: 'One converted try edges two penalties',
    exp: {
      kid: 'A try (5) plus its bonus kick (2) makes 7. Two penalty kicks make 3 + 3 = 6. So it’s 7–6!',
      beginner: 'The converted try (7) is rugby’s premium score — worth more than two penalties (6). This scoreline is the sport’s value system in miniature.',
      intermediate: 'It’s also the classic style contrast: one team crossing the line once beats a team kicking twice. Over a match, though, three penalties (9) beat a converted try — the accounting war between “take the 3” and “go for the corner” never ends.',
      expert: 'The 7>6 asymmetry is deliberate rule design: tries were once worth less than kicks (in the 1800s a try was 0–1 point!), and the value has been ratcheted up repeatedly (3→4 in 1971, 4→5 in 1992) precisely to reward attacking rugby over penalty accumulation.',
    },
  },
  {
    id: 'rug-beg-2', level: 'beginner',
    board: { kind: 'rugby', home: { name: 'Bison', abbr: 'BIS', score: 9 }, away: { name: 'Harriers', abbr: 'HRR', score: 9 },
      clock: "71'" },
    prompt: 'From open play, a Harriers fly-half bounces the ball off the ground and kicks it through the posts. What is that?',
    options: ['A drop goal — 3 points', 'Illegal — you can’t kick in open play', 'A conversion — 2 points'],
    answer: 0,
    title: 'The drop goal: 3 from anywhere, anytime',
    exp: {
      kid: 'That’s a drop goal! The ball must touch the ground just before the kick. It’s worth 3 points and you can try one whenever you have the ball.',
      beginner: 'A drop goal requires the ball to be dropped and struck on the half-volley, in open play. No penalty needed — just position, a brave kicker, and 3 points.',
      intermediate: 'The drop goal is the tied-game weapon: no need to wait for the referee’s whistle. Teams engineer them — pick-and-go phases to set the pocket, forwards shielding, then the kick. 9–9 at 71’ is exactly drop-goal territory.',
      expert: 'Drop goals decide finals because they’re defense-proof: you can’t tackle a ball in flight. The counter is line-speed pressure on the pocket and charging the kick. Watch for the tell — a team suddenly playing one-out rugby in front of the posts at 38 phases is not trying to score a try.',
    },
  },
  {
    id: 'rug-beg-3', level: 'beginner',
    board: { kind: 'rugby', home: { name: 'Kestrels', abbr: 'KES', score: 10 }, away: { name: 'Stags', abbr: 'STG', score: 3 },
      clock: "26'", tally: { home: { t: 1, c: 1, p: 1, d: 0 }, away: { t: 0, c: 0, p: 1, d: 0 } } },
    prompt: 'The Kestrels have 10 points. Using the tally (1 try, 1 conversion, 1 penalty), verify the total.',
    options: ['5 + 2 + 3 = 10 ✓', '4 + 3 + 3 = 10 ✓', '6 + 1 + 3 = 10 ✓'],
    answer: 0,
    title: 'Score arithmetic: 5 + 2 + 3',
    exp: {
      kid: 'A try is 5, its bonus kick is 2, and a penalty kick is 3. Add them up: 5 + 2 + 3 = 10!',
      beginner: 'Every rugby score decomposes into 5s (tries), 2s (conversions), 3s (penalties/drop goals). 10 here = 5+2+3. With practice you’ll reverse-engineer any total instantly.',
      intermediate: 'Some totals have multiple recipes (13 = 5+5+3 or 5+2+3+3), and a few are flat-out impossible — a team can never finish on 1, 2, or 4, because conversions (2) only exist attached to tries (5). Decomposing scores is a genuine fan skill.',
      expert: 'The number theory: building from penalties/drops (3), tries (5), converted tries (7), and penalty tries (7), the impossible team totals are exactly 1, 2, and 4 — everything else is reachable (3, 5, 6, 7, 8=5+3, 9, 10, 11=5+3+3…). Spot a “4” on a rugby union scoreboard and you’ve spotted a malfunction.',
    },
  },
  {
    id: 'rug-beg-4', level: 'beginner',
    board: { kind: 'rugby', home: { name: 'Harriers', abbr: 'HRR', score: 14 }, away: { name: 'Bison', abbr: 'BIS', score: 12 },
      clock: "55'", note: 'YELLOW CARD — BIS · 10:00' },
    prompt: 'A Bison player is shown a YELLOW card. What happens?',
    options: ['10 minutes in the sin-bin — Bison play with 14', 'He’s out for the whole match', 'Just a warning, nothing more'],
    answer: 0,
    title: 'Yellow card = 10 minutes in the sin-bin',
    exp: {
      kid: 'A yellow card sends the player to sit out for 10 minutes. His team plays a man short until he’s allowed back.',
      beginner: 'The sin-bin: 10 minutes off the field for cynical or dangerous play. 14 v 15 for ten minutes is a big deal — then the player returns. A RED card, by contrast, is permanent.',
      intermediate: 'Ten minutes of 14 v 15 costs roughly 7 points on average at elite level — teams target the shorthanded side’s scrum and stretch the fringes. Killing the ball near your line to “take the yellow” can still be a rational trade against a certain try.',
      expert: 'That trade is exactly why the penalty try (7 points, no conversion needed) and card often arrive together — the laws price in cynicism. Modern wrinkle to know: some competitions use a 20-minute red card with replacement allowed; check the competition’s rules before assuming the classic permanent red.',
    },
  },
  {
    id: 'rug-beg-5', level: 'beginner',
    board: { kind: 'rugby', home: { name: 'Stags', abbr: 'STG', score: 6 }, away: { name: 'Harriers', abbr: 'HRR', score: 13 },
      clock: "37'", note: 'PENALTY STG — KICK TO TOUCH' },
    prompt: 'Stags get a penalty in range of the posts — but kick it OUT of play instead. Why give up the 3 points?',
    options: ['They get the lineout throw near the try line — chasing 7 instead of 3', 'The kicker slipped', 'Penalties can’t be kicked at goal in the first half'],
    answer: 0,
    title: 'Corner over posts: hunting the try',
    exp: {
      kid: 'When you kick a penalty out of the field, YOUR team gets to throw the ball back in, close to the other team’s goal line. They’re saying “no thanks” to 3 points because they want a 7-point try!',
      beginner: 'On a penalty, kicking to touch keeps possession (unlike a normal kick out of play) — the attacking lineout 5 metres out is one of rugby’s best try platforms. Down 7, they need tries anyway.',
      intermediate: 'The math: a 5m attacking lineout converts to a try roughly 25–35% of the time (≈2+ expected points, plus conversion upside), competitive with a long-range kick’s 3×75%. Score, clock and momentum tip the choice.',
      expert: 'Elite teams have explicit “points policies”: take 3 when the margin brackets say kicks matter (within 3, or building past 7), go to the corner when chasing tries or bonus points, or when the opponent’s maul defense is weak. Watching the captain point to posts vs corner is watching the win-probability model speak.',
    },
  },
  {
    id: 'rug-beg-6', level: 'beginner',
    board: { kind: 'rugby', home: { name: 'Bison', abbr: 'BIS', score: 22 }, away: { name: 'Kestrels', abbr: 'KES', score: 22 },
      clock: "80'", note: 'BALL IN PLAY' },
    prompt: 'The clock has passed 80:00 but the teams keep playing. Why hasn’t the match ended?',
    options: ['Play continues until the ball next goes dead', 'The referee forgot the time', 'Ties require extra time in every match'],
    answer: 0,
    title: 'No siren-stop: play to the dead ball',
    exp: {
      kid: 'Rugby doesn’t stop the instant time runs out — the game ends the NEXT time the ball goes out of play. As long as they keep the ball moving, the game keeps going!',
      beginner: 'After 80:00, the half ends at the next dead ball: a knock-on, the ball into touch, a score. A team keeping the ball through phase after phase can play on for minutes.',
      intermediate: 'This is why leading teams at 80:00 want ONE ruck to kill: win a penalty or turnover, boot it into touch, game over. Trailing teams do the opposite — endless phases, never kick, never make an error.',
      expert: 'Key subtlety: a PENALTY does not end the game even after 80:00 — the fouled team may kick to touch and (under current law) still take the lineout, or tap and play on. Defending your line after the siren means defending WITHOUT infringing; one ruck penalty resets the whole siege.',
    },
  },

  // ── intermediate ──────────────────────────────────────────────────────────
  {
    id: 'rug-int-1', level: 'intermediate',
    board: { kind: 'rugby', home: { name: 'Stags', abbr: 'STG', score: 23 }, away: { name: 'Bison', abbr: 'BIS', score: 14 },
      clock: "68'", tally: { home: { t: 2, c: 2, p: 3, d: 0 }, away: { t: 2, c: 2, p: 0, d: 0 } } },
    prompt: 'Both teams have 2 converted tries — yet it’s 23–14. Where did the Stags’ extra 9 come from?',
    options: ['Three penalty goals (3 × 3)', 'A bonus try', 'Three drop conversions'],
    answer: 0,
    title: 'Same tries, different discipline',
    exp: {
      kid: 'Both teams scored the same tries and kicks — but the Stags also kicked THREE penalty goals when the Bison broke the rules. 3+3+3 = the whole difference!',
      beginner: 'Tally check: each side has 2×5 + 2×2 = 14 from tries. Stags add P3 → +9 → 23. The Bison lost this game at the ruck, not in attack — every infringement in range fed the kicker.',
      intermediate: 'This is the most common “hidden defeat” in rugby: even attacking parity, lost on penalty count. A disciplined team with a reliable kicker banks 9–12 points a match from opponents’ errors alone.',
      expert: 'Coaches call it the “3-point tax”: infringe in your half within kicking range and elite kickers collect ~2.4 expected points. The Bison conceded three taxable penalties and paid full price — the scoreboard’s P column is a discipline audit, and 9 unanswered penalty points is a losing audit.',
    },
  },
  {
    id: 'rug-int-2', level: 'intermediate',
    board: { kind: 'rugby', home: { name: 'Harriers', abbr: 'HRR', score: 7 }, away: { name: 'Kestrels', abbr: 'KES', score: 3 },
      clock: "33'", note: 'PENALTY TRY — HRR' },
    prompt: 'The referee awards a “PENALTY TRY” after a Kestrel deliberately collapses a maul heading for the line. What does it score?',
    options: ['7 points automatically — no conversion is taken', '5 points plus a normal conversion', '3 points'],
    answer: 0,
    title: 'The penalty try: an automatic 7',
    exp: {
      kid: 'The other team cheated to stop a certain try — so the referee just GIVES the try, and it’s worth the full 7 points (no kick needed).',
      beginner: 'When foul play prevents a PROBABLE try, the ref awards a penalty try: 7 points, no conversion attempted, awarded under the posts. The offender usually also gets a yellow (or red) card.',
      intermediate: 'The test is probability: “would the try PROBABLY have been scored but for the foul?” Collapsed mauls and deliberate knock-ons near the line are classic triggers. The automatic 7 (introduced 2017) removed the old ritual of kicking an easy conversion after.',
      expert: 'The design closes a cynical loophole: without it, deliberately collapsing a try-bound maul cost only 3 (penalty) or a card — cheap against a 7-point certainty. Automatic 7 + card makes the foul strictly worse than conceding. Watch refs verbalize the exact legal test to the TMO: “probable try? foul play? penalty try, yellow card.”',
    },
  },
  {
    id: 'rug-int-3', level: 'intermediate',
    board: { kind: 'rugby', home: { name: 'Bison', abbr: 'BIS', score: 24 }, away: { name: 'Stags', abbr: 'STG', score: 17 },
      clock: "80'+2", note: 'STAGS BALL — PHASE 14' },
    prompt: 'Two minutes past the 80, the trailing Stags have kept the ball for 14 phases. What ends this game?',
    options: ['Only a dead ball — a Stags error, a turnover kicked into touch, or a score', 'The referee’s stopwatch at 82:00', 'The next tackle'],
    answer: 0,
    title: 'After the siren, possession is life',
    exp: {
      kid: 'The game can’t end while the Stags keep the ball alive! It only ends when the ball goes dead — if they drop it, or if they score.',
      beginner: 'Post-80 play runs until the ball is dead. The Stags (down 7) must reach the line without a single knock-on or held-up ball; the Bison must defend without conceding a penalty — a penalty would let the Stags kick to touch, take the lineout, and keep the siege going.',
      intermediate: 'Note both pressure points: the ATTACK dies to any error or turnover-kick; the DEFENSE can’t infringe (penalty = play on) and shouldn’t even compete recklessly at rucks. Down 7, the Stags want the converted try to draw — expect them to dot down as close to the posts as possible.',
      expert: 'Endgame tree, down 7 after the siren: try (5) makes it 24–22, then the conversion draws it at 24–24. In league play that draw stands (2 league points each — and note the Stags were already banking a losing bonus at within-7, so even the failed siege pays something). Every branch of the final phases is priced in league points, and good captains chase the branch, not the glory.',
    },
  },
  {
    id: 'rug-int-4', level: 'intermediate',
    board: { kind: 'rugby', home: { name: 'Kestrels', abbr: 'KES', score: 31 }, away: { name: 'Harriers', abbr: 'HRR', score: 28 },
      clock: 'FT', tally: { home: { t: 4, c: 4, p: 1, d: 0 }, away: { t: 4, c: 4, p: 0, d: 0 } } },
    prompt: 'Final: 31–28, both teams scored 4 tries. In many league competitions, what EXTRA standings reward did both teams earn?',
    options: ['Bonus points — 4 tries earns one; losing by ≤7 earns one too', 'Double match points', 'A replay'],
    answer: 0,
    title: 'Bonus points: the table rewards style',
    exp: {
      kid: 'In lots of rugby leagues, scoring 4 tries in a game earns an extra table point — and losing by 7 or less earns one too. Both teams here get a little prize!',
      beginner: 'Standard league scoring: win 4, draw 2, loss 0 — PLUS a try bonus (4+ tries) and a losing bonus (defeat by 7 or fewer). Here: Kestrels 4+1 = 5; Harriers 0+1 (close loss) +1 (4 tries) = 2.',
      intermediate: 'Bonus points reshape endgames: a team down 10 late plays for the 7-point margin (losing bonus), and a team with 3 tries may spurn kickable penalties chasing the 4th. The table, not just the match, is always in play.',
      expert: 'Caveat for reading real tables: bonus systems vary — the classic 4/2/0+bonuses is common (Premiership, Super Rugby, World Cup pools), but France’s Top 14 famously requires winning by a margin for the offensive bonus. Never compute standings from scores without checking the competition’s bonus rules.',
    },
  },
  {
    id: 'rug-int-5', level: 'intermediate',
    board: { kind: 'rugby', home: { name: 'Stags', abbr: 'STG', score: 12 }, away: { name: 'Kestrels', abbr: 'KES', score: 12 },
      clock: "76'", note: 'ADVANTAGE — STG (PENALTY)' },
    prompt: 'The board shows “ADVANTAGE — STG.” The referee saw a Kestrels penalty but hasn’t whistled. Why?',
    options: ['Stags get a chance to gain more than the penalty would give — the whistle waits', 'The referee is unsure', 'Advantage means a warning only'],
    answer: 0,
    title: 'Playing advantage: the penalty in your pocket',
    exp: {
      kid: 'The referee saw the foul but lets the good team keep playing — maybe they’ll score! If it goes wrong for them, he brings play back for the penalty. They can’t lose!',
      beginner: 'Advantage = play on with a safety net. If the Stags gain something better (territory, a try), play continues; if not, the ref returns to the original penalty spot. Tied at 76’, that pocket penalty is 3 points in the bank.',
      intermediate: 'Smart teams weaponize advantage: with a penalty guaranteed behind them, they attempt the low-percentage plays — the crossfield kick, the offload, even a drop goal attempt — because failure just means taking the penalty anyway.',
      expert: 'The free-play economics are identical to a football free play after an offside flag: risk asymmetry invites maximum-variance choices. Watch fly-halves audible to a drop goal or long raking kick the instant the arm goes out — “advantage rugby” is often the most creative rugby in the match, by design.',
    },
  },
  {
    id: 'rug-int-6', level: 'intermediate',
    board: { kind: 'rugby', home: { name: 'Harriers', abbr: 'HRR', score: 9 }, away: { name: 'Bison', abbr: 'BIS', score: 7 },
      clock: "51'", tally: { home: { t: 0, c: 0, p: 2, d: 1 }, away: { t: 1, c: 1, p: 0, d: 0 } } },
    prompt: 'Harriers lead 9–7 without scoring a single try (2 penalties + 1 drop goal). What does this scoreline tell you?',
    options: ['Kicking accuracy is beating try-scoring — for now', 'The scoreboard is malfunctioning', 'Harriers must have scored a try somewhere'],
    answer: 0,
    title: 'Winning without tries',
    exp: {
      kid: 'The Harriers haven’t crossed the line at all — but three good kicks (3+3+3) beat one try and its bonus kick (7). Kicks add up!',
      beginner: '9 = 3+3+3 (two penalty goals + a drop goal). It’s a completely legitimate way to lead, and a classic wet-weather or knockout scoreline — kicks are low-risk points.',
      intermediate: 'But it’s fragile: one converted try flips it, and no try bonus accrues in bonus-point competitions. “Kick-built” leads pressure the opponent’s discipline; “try-built” leads pressure their whole defense.',
      expert: 'Score construction predicts the endgame: a 9–7 team defends its lead via territory kicks and forced penalties; the 7-point team knows a single 3 puts THEM ahead too. Statistically, the team scoring more tries wins most matches — but finals, uniquely, skew toward boot-built scores because risk appetite collapses under stakes.',
    },
  },

  // ── expert ────────────────────────────────────────────────────────────────
  {
    id: 'rug-exp-1', level: 'expert',
    board: { kind: 'rugby', home: { name: 'Bison', abbr: 'BIS', score: 20 }, away: { name: 'Stags', abbr: 'STG', score: 14 },
      clock: "79'", note: 'PENALTY STG, 40M OUT' },
    prompt: 'Stags trail by 6 with a kickable penalty at 79’. Why is kicking at goal (3) probably WRONG here?',
    options: ['3 leaves them losing 20–17 with no time — they need a converted try (7) anyway', 'The kick is too easy', 'Penalties expire at 79 minutes'],
    answer: 0,
    title: 'Margin math at the death: 6 down needs 7',
    exp: {
      kid: 'They’re 6 behind. A kick makes it 3 behind — still losing, with almost no time left! Better to kick the ball into the corner and try to score a 7-point try to WIN.',
      beginner: 'Down 6, only a try helps: an unconverted try (5) still loses by 1, but a converted try (7) wins by 1. The penalty’s real value is the attacking LINEOUT — kick to the corner, maul for the try.',
      intermediate: 'The bracket rule: down 1–3 → take the kick (it levels or leads); down 4–7 → corner (need the try regardless); down 8+ → corner AND you need more after. At 79’ the clock kills any two-score plan, so 3 points is strictly worse than a try attempt.',
      expert: 'One refinement: down 6 with 5+ minutes left, kick-then-chase (3 now, drop goal or penalty later to win) is defensible; at 79’ it isn’t — there’s no second possession coming. Elite captains verbalize exactly this: “no value in three.” The corner kick also runs almost no clock, while a shot at goal burns 60–90 seconds they don’t have.',
    },
  },
  {
    id: 'rug-exp-2', level: 'expert',
    board: { kind: 'rugby', home: { name: 'Kestrels', abbr: 'KES', score: 15 }, away: { name: 'Harriers', abbr: 'HRR', score: 13 },
      clock: "80'+1", note: 'PENALTY HRR — KICKED TO TOUCH' },
    prompt: 'After the siren, the trailing Harriers win a penalty and kick it into touch. Under current law, what happens?',
    options: ['They throw into the lineout and play continues — the game isn’t over', 'The game ends the moment the ball crosses the touchline', 'A scrum is set instead'],
    answer: 0,
    title: 'The after-the-siren penalty-to-touch',
    exp: {
      kid: 'Normally, ball out of play after the siren = game over. But this ball went out from a PENALTY kick — so the Harriers still get to throw it back in and keep attacking!',
      beginner: 'A penalty kicked to touch keeps the throw-in for the kicking team, and the law lets that lineout be played even after time has expired. Down 2, the Harriers buy one more attacking platform 10 metres out.',
      intermediate: 'This closed an old sore point: the ball going “dead” off a post-siren penalty used to end matches awkwardly (law tweaked in the 2010s so the lineout is taken). Combined with “penalties never end the half,” a defending team can be trapped in an endless post-siren cycle of its own making.',
      expert: 'The full post-80 decision tree for a team down 2: penalty in range → kick at goal (game ends on the result — made, win; missed and dead, loss); penalty out of range → touch, lineout, maul, repeat. Every additional defensive infringement re-arms the attack. Referees manage this theater carefully: the only exits are a score, a clean turnover kicked dead, or an attacking error.',
    },
  },
  {
    id: 'rug-exp-3', level: 'expert',
    board: { kind: 'rugby', home: { name: 'Stags', abbr: 'STG', score: 18 }, away: { name: 'Bison', abbr: 'BIS', score: 18 },
      clock: "80'+3", note: 'STG IN THE POCKET — DROP GOAL ATTEMPT?' },
    prompt: 'Tied after the siren, the Stags set a ruck 25m out, fly-half deep “in the pocket.” If his drop goal attempt MISSES and rolls dead, what’s the result?',
    options: ['Full time — the match ends in a draw (or as the competition’s tie rules dictate)', 'The Stags get to retry', 'Sudden-death overtime always follows'],
    answer: 0,
    title: 'The all-or-nothing post-siren drop',
    exp: {
      kid: 'If the kick misses and the ball goes dead, the game is instantly over with the score still tied. The kick is the last roll of the dice — make it and win, miss it and settle for the tie.',
      beginner: 'A missed drop that crosses the dead-ball line = dead ball after 80 = full time. In league play the draw stands (2 points each); only knockout matches move to extra time. The drop goal is a “win-or-draw” gamble — you can’t LOSE on the kick itself.',
      intermediate: 'That asymmetry (win if made, draw if missed-dead) makes the post-siren drop hugely favorable when tied. The defense must NOT concede a ruck penalty — that would gift an easier placekick instead. Its only real options: charge the kick, or pressure the pocket without infringing.',
      expert: 'Full decision calculus: tied, post-siren, 25m pocket — a ~60–70% drop attempt dominates continuing phases (turnover risk) UNLESS a penalty advantage is already playing (then attempt it for free). Defensively, charging is right precisely because the miss-and-dead outcome only draws; any infringement upgrades the attack to a ~95% placekick. Both teams are solving the same little game tree, live, exhausted.',
    },
  },
  {
    id: 'rug-exp-4', level: 'expert',
    board: { kind: 'rugby', home: { name: 'Harriers', abbr: 'HRR', score: 22 }, away: { name: 'Kestrels', abbr: 'KES', score: 19 },
      clock: "74'", note: '2ND YELLOW — KES №7' },
    prompt: 'The Kestrels’ openside flanker receives his SECOND yellow card of the match. What does the board show next?',
    options: ['A red card — he’s off for good, Kestrels finish with 14', 'A 20-minute sin-bin', 'Both yellows cancel out'],
    answer: 0,
    title: 'Two yellows make a red',
    exp: {
      kid: 'Two yellow cards for the same player add up to a red card — he’s out of the game for good, and his team plays the rest a man short.',
      beginner: 'Second yellow = automatic red: permanent dismissal, no replacement, and the earlier 10-minute rule no longer applies — the team is 14 for the remaining 6+ minutes of a 3-point game.',
      intermediate: 'Repeat-offender management is a captain’s job: a flanker on a yellow must stop living offside at the ruck, and his skipper may literally instruct him to stop competing at breakdowns. Referees also warn captains about TEAM repeat offences — persistent infringement is itself yellow-card grounds.',
      expert: 'The “team yellow” escalation is underappreciated: refs count repeated infringements in the red zone and card the NEXT offender regardless of who it is — so a team on a final warning defends its line with dramatically reduced ruck aggression. Down 3 with 6 to play against 14: attack the shorthanded side of the scrum and the openside’s vacated breakdowns.',
    },
  },
  {
    id: 'rug-exp-5', level: 'expert',
    board: { kind: 'rugby', home: { name: 'Bison', abbr: 'BIS', score: 27 }, away: { name: 'Harriers', abbr: 'HRR', score: 27 },
      clock: 'FT', note: 'KNOCKOUT — EXTRA TIME NEXT' },
    prompt: 'A knockout match ends 27–27. What does rugby union’s classic extra-time format look like?',
    options: ['Two 10-minute halves; if still tied, competitions vary (sudden death / kicks)', 'One 30-minute golden-try period', 'Straight to a scrum contest'],
    answer: 0,
    title: 'Knockout ties: 10 + 10, then the fine print',
    exp: {
      kid: 'They play two extra halves of 10 minutes each. If it’s STILL tied after that, different tournaments have different tiebreakers — even a kicking contest!',
      beginner: 'The common format: 10 minutes each way of normal rugby (not sudden death). Still level? Depending on the competition: a sudden-death period, then a place-kicking competition — rugby’s version of a shootout.',
      intermediate: 'World Cup knockout rules: 2×10 extra time → 10 minutes sudden death (first score of ANY kind wins) → kicking competition (5 kickers each from set positions). Domestic cups vary — some go straight to kicks, some count tries scored as a tiebreaker first.',
      expert: 'Deep cut: “most tries scored in the match” sits ABOVE the kicking contest in several competitions’ tiebreak ladders, which retroactively changes how a 27–27 team should have valued a late corner-kick vs posts decision. Knockout rugby demands reading the tournament handbook BEFORE the 80th minute — the tiebreak ladder is part of the game state.',
    },
  },
  {
    id: 'rug-exp-6', level: 'expert',
    board: { kind: 'rugby', home: { name: 'Kestrels', abbr: 'KES', score: 3 }, away: { name: 'Stags', abbr: 'STG', score: 0 },
      clock: "12'", note: 'STG MAUL HELD UP OVER THE LINE' },
    prompt: 'The Stags drive over the line but the ball is HELD UP — never grounded. What restarts play under current law?',
    options: ['A goal-line drop-out to the defending Kestrels', 'A 5m attacking scrum to the Stags', 'A penalty try'],
    answer: 0,
    title: 'Held up = goal-line drop-out',
    exp: {
      kid: 'No touch-down, no try! And the defenders get a special reward for stopping it: they restart with a kick from their own goal line.',
      beginner: 'A try needs downward pressure on the ball. Held up over the line = no score, and (under the current law) the DEFENSE restarts with a goal-line drop-out — possession flips as a reward for the goal-line stand.',
      intermediate: 'This is a recent, significant change: for decades a held-up ball gave the ATTACK a 5m scrum (another siege). The goal-line drop-out (introduced globally in the 2020s) rewards defense and injects kick-return rugby — attacking teams now think twice about one-out pick-and-drives.',
      expert: 'Law-evolution literacy matters at expert level: pre-2021 analyses, old highlights, and older coaching material assume the 5m scrum. The switch measurably reduced goal-line phase-count sieges and added a contestable restart — one of several recent “speed the game up” amendments (50:22, goal-line drop-outs, ruck use-it) that changed endgame geometry near the line.',
    },
  },
];
