// Read the Score — Soccer bank (serves the pooled soccer/epl/laliga/worldcup category).
// Scoring-RULE scenarios only (evergreen); club names are fictional set dressing.
// 6 scenarios per tier × 4 tiers. Pure data, zero RN imports.
import type { ScoreScenario } from '../readTheScore';

export const SOCCER_SCENARIOS: ScoreScenario[] = [
  // ── kid ────────────────────────────────────────────────────────────────────
  {
    id: 'soc-kid-1', level: 'kid',
    board: { kind: 'soccer', home: { name: 'Harbor FC', abbr: 'HAR', score: 2 }, away: { name: 'Riverton', abbr: 'RIV', score: 1 },
      minute: "67'" },
    prompt: 'Who is winning?',
    options: ['Harbor FC', 'Riverton', 'It’s level'],
    answer: 0,
    title: 'Harbor FC lead 2–1',
    exp: {
      kid: 'Harbor FC have 2 goals, Riverton have 1. More goals wins!',
      beginner: 'Soccer scores are small because goals are hard to come by — a 2–1 lead in the 67th minute is a real advantage, but one goal ties it.',
      intermediate: 'Low scoring is the sport’s defining feature: a single goal changes everything, which is why a 2–1 game at 67’ still feels completely open.',
      expert: 'Average match produces ~2.7 goals total, so each goal swings win probability enormously — far more than a basket or a single run. That scarcity underwrites everything: defensive tactics, time-wasting, and the drama of late goals.',
    },
  },
  {
    id: 'soc-kid-2', level: 'kid',
    board: { kind: 'soccer', home: { name: 'Olympic', abbr: 'OLY', score: 1 }, away: { name: 'Vale', abbr: 'VAL', score: 0 },
      minute: "23'" },
    prompt: 'A striker scores from very far out — a spectacular shot. How much is it worth?',
    options: ['1 goal — all goals count the same', '2 goals for distance', '3 goals if it’s a volley'],
    answer: 0,
    title: 'Every goal counts exactly one',
    exp: {
      kid: 'No matter how amazing the shot is, a goal is a goal — the score goes up by 1.',
      beginner: 'Soccer has no bonus points: tap-in or 30-yard screamer, each goal adds exactly 1. The whole ball must cross the whole line.',
      intermediate: 'The “whole ball over the whole line” rule is precise — a ball half over the line is nothing. Goal-line technology signals the referee’s watch the instant it fully crosses.',
      expert: 'Flat goal value means there is no comeback shortcut (no 3-pointer equivalent) — a two-goal deficit requires two separate successful attacks. That’s why two-goal leads change team behavior so dramatically, and why holding one is its own art.',
    },
  },
  {
    id: 'soc-kid-3', level: 'kid',
    board: { kind: 'soccer', home: { name: 'Harbor FC', abbr: 'HAR', score: 0 }, away: { name: 'Vale', abbr: 'VAL', score: 0 },
      minute: "34'" },
    prompt: 'The clock shows 34’. Does a soccer clock count UP or DOWN?',
    options: ['Up — from 0’ toward 90’', 'Down — toward 0:00', 'It restarts every 15 minutes'],
    answer: 0,
    title: 'Soccer time counts up',
    exp: {
      kid: 'The clock climbs from 0 up to 90 minutes. 34’ means 34 minutes have been played.',
      beginner: 'Unlike American sports, the soccer clock runs UP and almost never stops — not for throw-ins, not for goals. Lost time is added at the end of each half instead.',
      intermediate: 'The referee keeps the official time on the pitch; the stadium clock is a courtesy. That’s why halves end when the ref whistles, not when the display says so.',
      expert: 'The running clock is a philosophical choice: the game breathes continuously, and time-wasting is punished by added time rather than stoppages. It also means “minutes” are comparable across eras — a 90-minute match in 1930 and today are the same clock.',
    },
  },
  {
    id: 'soc-kid-4', level: 'kid',
    board: { kind: 'soccer', home: { name: 'Olympic', abbr: 'OLY', score: 1 }, away: { name: 'Riverton', abbr: 'RIV', score: 2 },
      minute: 'HT' },
    prompt: 'The board says “HT.” What does that mean?',
    options: ['Halftime — the first half is over', 'Home team wins', 'High tempo'],
    answer: 0,
    title: 'HT = halftime',
    exp: {
      kid: 'HT means halftime — the players get a 15-minute rest, then play the second half.',
      beginner: 'A match is two 45-minute halves with a 15-minute break. “HT 1–2” tells you Riverton lead at the break; the teams switch ends for the second half.',
      intermediate: 'Half-time scores are worth reading: leads at HT hold up more often than not, but switching ends (and tactical changes in the dressing room) makes second halves statistically higher scoring.',
      expert: 'Second halves produce ~55% of goals — fatigue, chasing scorelines, and substitutions all push openness. “HT/FT” (halftime result vs full-time result) is even a classic betting market because the flip patterns are so studied.',
    },
  },
  {
    id: 'soc-kid-5', level: 'kid',
    board: { kind: 'soccer', home: { name: 'Harbor FC', abbr: 'HAR', score: 0 }, away: { name: 'Olympic', abbr: 'OLY', score: 0 },
      minute: "88'" },
    prompt: 'It’s 0–0 in the 88th minute. What do fans call a 0–0 score?',
    options: ['Nil-nil', 'Zero-zip', 'Love-all'],
    answer: 0,
    title: '0–0 is “nil-nil”',
    exp: {
      kid: 'In soccer, zero is called “nil.” A 0–0 game is nil-nil!',
      beginner: '“Nil” is the traditional word for zero in soccer scores: 2–0 is “two-nil.” A nil-nil draw means neither team scored.',
      intermediate: 'If it ends 0–0 in a league match, that’s a completed result — a draw, one point each. No overtime in regular league play.',
      expert: 'Scoreline language is part of the sport’s literacy: “two-nil” (comfortable), “nil-nil” (stalemate), “one-all” (level). And a goalless draw isn’t necessarily dull to the trained eye — it’s often a tactical siege that one team survived.',
    },
  },
  {
    id: 'soc-kid-6', level: 'kid',
    board: { kind: 'soccer', home: { name: 'Vale', abbr: 'VAL', score: 3 }, away: { name: 'Riverton', abbr: 'RIV', score: 1 },
      minute: 'FT' },
    prompt: 'The board shows “FT 3–1.” What happened?',
    options: ['Full time — Vale won 3–1', 'The game was abandoned', 'Vale lead at halftime'],
    answer: 0,
    title: 'FT = full time: the final score',
    exp: {
      kid: 'FT means full time — the match is over. Vale scored 3, Riverton scored 1, so Vale won!',
      beginner: 'Full time comes after both 45-minute halves (plus added time). FT 3–1 is the final result — in a league, Vale collect 3 points, Riverton none.',
      intermediate: 'The result trio: win (3 points), draw (1 each), loss (0). League seasons are just these FT results accumulated into a table.',
      expert: 'The 3-points-for-a-win rule (universal since the 1990s; it used to be 2) deliberately rewards attacking: a win plus a loss (3 pts) now beats two draws (2 pts). One scoreboard convention quietly reshaped how the whole sport approaches risk.',
    },
  },

  // ── beginner ──────────────────────────────────────────────────────────────
  {
    id: 'soc-beg-1', level: 'beginner',
    board: { kind: 'soccer', home: { name: 'Harbor FC', abbr: 'HAR', score: 1 }, away: { name: 'Vale', abbr: 'VAL', score: 1 },
      minute: "45'" },
    prompt: 'How long is each half of a soccer match?',
    options: ['45 minutes', '30 minutes', '60 minutes'],
    answer: 0,
    title: 'Two halves of 45',
    exp: {
      kid: 'Each half is 45 minutes, and there are two — so 90 minutes of soccer in all.',
      beginner: '45 + 45 = 90 minutes, plus the added (stoppage) time the referee tacks onto each half for injuries and delays.',
      intermediate: 'The ball is actually in play for roughly 55–60 of those 90 minutes — the rest leaks away in throw-ins, goal kicks, and treatment. Added time compensates only partially.',
      expert: '“Effective playing time” is a live debate in the laws — trials of a stopped clock exist precisely because in-play time varies so much between matches. Until then, the referee’s added-time discretion is the only rebate for lost minutes.',
    },
  },
  {
    id: 'soc-beg-2', level: 'beginner',
    board: { kind: 'soccer', home: { name: 'Olympic', abbr: 'OLY', score: 2 }, away: { name: 'Riverton', abbr: 'RIV', score: 1 },
      minute: "90'+3" },
    prompt: 'The clock shows 90’+3. What does the “+3” mean?',
    options: ['Added (stoppage) time — at least 3 extra minutes', 'Overtime period 3', 'Riverton need 3 goals'],
    answer: 0,
    title: 'Stoppage time: paying back lost minutes',
    exp: {
      kid: 'The referee added 3 extra minutes to make up for time lost during the game — injuries, substitutions, celebrations.',
      beginner: 'The clock never stops in soccer, so time lost to stoppages is repaid at the end of each half. The fourth official’s board shows the minimum added: “+3” = at least 3 more minutes.',
      intermediate: 'It’s a minimum, not a countdown — the ref can extend it (for new stoppages within stoppage time) but shouldn’t shorten it. Goals scored at 90’+2 count exactly like any other.',
      expert: 'Referees now add substantial time for goal celebrations and VAR checks, so +8 or more is common in modern matches. Managing stoppage time — when to make that last substitution, when to keep the ball in the corner — is a real coaching skill measured in points per season.',
    },
  },
  {
    id: 'soc-beg-3', level: 'beginner',
    board: { kind: 'soccer', home: { name: 'Harbor FC', abbr: 'HAR', score: 1 }, away: { name: 'Olympic', abbr: 'OLY', score: 1 },
      minute: 'FT' },
    prompt: 'A league match ends 1–1. What does each team get?',
    options: ['1 point each — a draw', 'A replay next week', 'Penalty shootout'],
    answer: 0,
    title: 'League draws stand: one point each',
    exp: {
      kid: 'In a league season, a tie is a real result! Both teams get 1 point and go home.',
      beginner: 'League play: win = 3 points, draw = 1 each, loss = 0. There’s no overtime — 1–1 at full time simply ends 1–1. Shootouts belong to knockout tournaments only.',
      intermediate: 'This is the big structural split in soccer: LEAGUES accept draws (points accumulate over 38-ish games), KNOCKOUTS can’t (someone must advance → extra time and penalties). Same sport, two endgames.',
      expert: 'Draw-acceptance changes late-game strategy by context: a league away side at 1–1 in the 85th may happily kill the game for its point, while the identical scoreline in a cup tie guarantees 30 more minutes. Always know which competition you’re watching before judging the tactics.',
    },
  },
  {
    id: 'soc-beg-4', level: 'beginner',
    board: { kind: 'soccer', home: { name: 'Vale', abbr: 'VAL', score: 0 }, away: { name: 'Riverton', abbr: 'RIV', score: 1 },
      minute: "58'", note: 'RED CARD — VAL' },
    prompt: 'A Vale defender is shown a RED card. What happens to the team?',
    options: ['They play the rest with 10 players — no replacement', 'A substitute replaces him', 'They lose 1 goal'],
    answer: 0,
    title: 'Red card: down to 10, permanently',
    exp: {
      kid: 'A red card means that player is out of the game — and nobody can take his place. His team plays the rest with only 10!',
      beginner: 'A sending-off cannot be substituted: the team is short-handed for the remainder. (Two yellow cards in one match equal a red.) The player is also banned for future matches.',
      intermediate: 'Playing 10 v 11 for half an hour usually forces a reshuffle: a striker sacrificed for a defender, the block sitting deeper. Statistically, going down a man early costs about a goal of expectation.',
      expert: 'Unlike hockey’s timed penalties, soccer’s red is permanent — the punishment scales with time remaining, which referees implicitly weigh in borderline calls. Note the roster nuance: the shorthanded team may still use its remaining substitutions, just to swap the 10 who remain.',
    },
  },
  {
    id: 'soc-beg-5', level: 'beginner',
    board: { kind: 'soccer', home: { name: 'Olympic', abbr: 'OLY', score: 1 }, away: { name: 'Vale', abbr: 'VAL', score: 1 },
      minute: "72'", note: 'PENALTY — OLY' },
    prompt: 'Olympic are awarded a penalty kick. If they score it, what’s it worth?',
    options: ['1 goal, like any other', '2 goals — it’s a bonus', 'It only counts if the keeper touches it'],
    answer: 0,
    title: 'A penalty is just a very good chance at 1',
    exp: {
      kid: 'A penalty is a free shot from the spot, only the goalie to beat — but it still counts as 1 normal goal.',
      beginner: 'Penalties (for fouls inside the box) convert about 3 times in 4 — a huge chance, but the goal itself is an ordinary goal: 1 on the scoreboard.',
      intermediate: 'In-match penalties are live: a save or rebound can be followed up (unlike shootout kicks, which end when saved). The award of a penalty swings expected goals by ~0.75 in one whistle — the biggest single refereeing decision in the sport.',
      expert: 'This is why the penalty box is soccer’s legal minefield and VAR’s main workload: an identical foul is worth ~0.05 xG at midfield and ~0.75 xG as a penalty. The binary in/out line, not the foul’s severity, sets the price — a structural quirk the laws accept for clarity.',
    },
  },
  {
    id: 'soc-beg-6', level: 'beginner',
    board: { kind: 'soccer', home: { name: 'Harbor FC', abbr: 'HAR', score: 2 }, away: { name: 'Riverton', abbr: 'RIV', score: 2 },
      minute: "81'", note: 'LEAGUE MATCH' },
    prompt: 'League game, 2–2 in the 81st. Why might BOTH teams still push hard for a winner?',
    options: ['A win is worth 3 points but a draw only 1', 'Draws are humiliating', 'The rules require attacking'],
    answer: 0,
    title: '3 for the win: the attacking incentive',
    exp: {
      kid: 'Winning gets you 3 points, but a tie only gets 1. Two more points are still out there to grab!',
      beginner: 'The jump from 1 point (draw) to 3 (win) is the largest incentive in the league system — chasing a late winner risks losing your 1 point but can triple it.',
      intermediate: 'Game state economics: at 2–2, each team weighs +2 points (win) against −1 (defeat). Home teams and teams chasing league position usually gamble; a relegation-threatened side may bank the point.',
      expert: 'The 3-1-0 system was adopted specifically to break the old 2-1-0 equilibrium where late draws were mutually acceptable. It measurably increased late-game attacking — a rare case of incentive design provably changing on-field behavior across an entire sport.',
    },
  },

  // ── intermediate ──────────────────────────────────────────────────────────
  {
    id: 'soc-int-1', level: 'intermediate',
    board: { kind: 'soccer', home: { name: 'Olympic', abbr: 'OLY', score: 1 }, away: { name: 'Harbor FC', abbr: 'HAR', score: 0 },
      minute: "90'+4", note: 'MIN. ADDED: 4' },
    prompt: 'The board announced 4 minutes of added time, and play is now at 90’+4. Can the half continue past +4?',
    options: ['Yes — the +4 is a minimum; the ref can extend it', 'No — it ends at exactly 94:00', 'Only for a penalty'],
    answer: 0,
    title: 'Added time is a floor, not a ceiling',
    exp: {
      kid: 'The 4 means AT LEAST 4 extra minutes. If something else slows the game down during those minutes, the referee adds even more.',
      beginner: 'The fourth official’s board shows the MINIMUM added time. New stoppages within stoppage time (an injury, a substitution, a goal) extend it further at the referee’s discretion.',
      intermediate: 'What the ref shouldn’t do is cut it short — the half must run at least the indicated time, and convention says finish the current attack around the whistle… actually the whistle can come mid-attack; only a penalty already awarded must be completed after time expires.',
      expert: 'That last rule is worth knowing: a half CAN end with the ball in the air, but a penalty kick awarded before time expires is always taken, even at 90’+9 with everyone else dismissed to the halfway line. “Minimum, extendable, penalty-must-complete” is the full grammar of added time.',
    },
  },
  {
    id: 'soc-int-2', level: 'intermediate',
    board: { kind: 'soccer', home: { name: 'Riverton', abbr: 'RIV', score: 2 }, away: { name: 'Vale', abbr: 'VAL', score: 1 },
      minute: "76'", note: 'LEG 2 · AGGREGATE: RIV 2–3 VAL' },
    prompt: 'Two-legged tie: the board shows Riverton winning TONIGHT 2–1, but the aggregate reads 2–3. Who advances if it ends now?',
    options: ['Vale — the aggregate across both legs decides it', 'Riverton — they won the second leg', 'It goes to a third match'],
    answer: 0,
    title: 'Aggregate scoring: two legs, one total',
    exp: {
      kid: 'The teams played twice, and BOTH games’ goals get added together. Vale have 3 total and Riverton 2 — so Vale go through, even though they’re losing tonight!',
      beginner: 'In two-legged knockout ties, the winner is decided by the sum of both matches. Riverton must score another goal tonight just to level the aggregate at 3–3.',
      intermediate: 'This is why a team can celebrate a 1–0 “defeat” — game state is the aggregate, not the night’s score. Vale can lose 1–2 and still advance; Riverton chase the TIE, not just the win.',
      expert: 'Historical note for old match reports: away goals used to break aggregate ties (a 3–3 with more away goals advanced), but major competitions abolished that rule in the 2020s — level aggregates now go to extra time and penalties in the second leg. Modern boards therefore show pure totals.',
    },
  },
  {
    id: 'soc-int-3', level: 'intermediate',
    board: { kind: 'soccer', home: { name: 'Harbor FC', abbr: 'HAR', score: 1 }, away: { name: 'Olympic', abbr: 'OLY', score: 1 },
      minute: 'FT', note: 'CUP FINAL — KNOCKOUT' },
    prompt: 'A cup final ends 1–1 at full time. What happens next?',
    options: ['Extra time: two 15-minute halves', 'Straight to penalties', 'A replay next month'],
    answer: 0,
    title: 'Knockout ties go to extra time',
    exp: {
      kid: 'Someone HAS to win a final! First they play 30 more minutes (two 15-minute halves). Still tied after that? Then a penalty shootout.',
      beginner: 'Knockout order of operations: 90 minutes → extra time (2 × 15, played in full) → penalty shootout. Extra time is real soccer, not sudden death — an early goal doesn’t end it.',
      intermediate: 'Don’t confuse extra time with stoppage time: stoppage is repaid minutes inside a half; extra time is an additional 30-minute period for tied knockouts only. Both halves of ET are always completed.',
      expert: 'Golden-goal sudden death was trialed around 1996–2004 and abandoned — it made ET more cautious, not less. Full-length ET plus the shootout threat produces the classic dynamic: tired legs, defensive errors, and managers saving one substitution purely for penalty specialists.',
    },
  },
  {
    id: 'soc-int-4', level: 'intermediate',
    board: { kind: 'soccer', home: { name: 'Vale', abbr: 'VAL', score: 0 }, away: { name: 'Riverton', abbr: 'RIV', score: 0 },
      minute: 'PENS', note: 'SHOOTOUT: VAL 4–3 RIV (KICK 5 OF 5)' },
    prompt: 'Penalty shootout, 4–3 after four kicks each. Riverton’s fifth kicker steps up. What’s at stake?',
    options: ['Miss and Vale win; score and it’s 4–4 → sudden death', 'Nothing — five kicks always finish', 'A miss replays the kick'],
    answer: 0,
    title: 'Best of five, then sudden death',
    exp: {
      kid: 'Each team gets 5 kicks. Vale are ahead 4–3 with one Riverton kick left — if he misses, Vale win. If he scores, they keep going one kick at a time!',
      beginner: 'Shootouts are best-of-5, alternating. Level after 5 each → sudden-death rounds: one kick apiece until one scores and the other misses. Shootout “goals” don’t count in the match score — the game is recorded as a draw decided on penalties.',
      intermediate: 'Shootouts also end EARLY when mathematically decided (up 3 with 2 remaining, the rest aren’t taken). Kick 5 here is decisive only because the ledger says so — reading the ledger is the skill.',
      expert: 'Rules details experts enjoy: only players on the pitch at the final whistle may kick, the keeper can be replaced only by one of those players (e.g., if injured), and every eligible player must kick before anyone repeats. Order strategy (best kickers at 1 and 5, or front-loaded under newer thinking) is a genuine studied edge.',
    },
  },
  {
    id: 'soc-int-5', level: 'intermediate',
    board: { kind: 'soccer', home: { name: 'Olympic', abbr: 'OLY', score: 2 }, away: { name: 'Harbor FC', abbr: 'HAR', score: 2 },
      minute: "63'", note: 'GOAL DISALLOWED — OFFSIDE (VAR)' },
    prompt: 'Harbor FC put the ball in the net, but the board still shows 2–2 with “GOAL DISALLOWED — OFFSIDE.” Why?',
    options: ['The scorer was offside when the pass was played — no goal', 'The referee didn’t see it', 'The net was faulty'],
    answer: 0,
    title: 'Offside erases the goal',
    exp: {
      kid: 'The attacker was standing too far forward — past the last defender — when his teammate passed. That’s offside, so the goal doesn’t count and the score stays the same.',
      beginner: 'Offside: at the moment a teammate plays the ball, an attacker involved in play must not be nearer the goal than both the ball and the second-last defender (the keeper usually being the last). Offside at the pass = the goal is disallowed.',
      intermediate: 'The judgment freezes at the PASS, not the finish — a player can look miles onside when he scores yet have been off by a toe when the ball was released. VAR draws the lines at that frozen frame.',
      expert: 'Offside is positional, not just about touching the ball — “interfering with play or an opponent” from an offside position also counts. The law exists to prevent goal-hanging and forces the entire attacking shape to play against the defensive line, which is why the high-line/offside-trap chess match defines modern tactics.',
    },
  },
  {
    id: 'soc-int-6', level: 'intermediate',
    board: { kind: 'soccer', home: { name: 'Riverton', abbr: 'RIV', score: 1 }, away: { name: 'Olympic', abbr: 'OLY', score: 3 },
      minute: 'FT', note: 'TABLE: BOTH TEAMS NOW ON 54 PTS' },
    prompt: 'After this result both clubs sit on 54 points. What usually separates them in the league table?',
    options: ['Goal difference (goals scored minus conceded)', 'A coin toss', 'Alphabetical order'],
    answer: 0,
    title: 'Goal difference: the standard tiebreaker',
    exp: {
      kid: 'When teams have the same points, the table looks at goals: the team that has scored a lot more than it let in goes higher.',
      beginner: 'Goal difference = goals for − goals against, across the season. Tied on points, the better GD ranks higher; still tied, most leagues then use goals scored.',
      intermediate: 'This makes big wins matter beyond the 3 points — a 4–0 banks goal difference that can decide titles and relegation months later. Teams chase extra goals at 3–0 for exactly this reason.',
      expert: 'Tiebreaker hierarchies vary by competition: many leagues use GD → goals scored → head-to-head, while some (e.g., Spain’s) put head-to-head FIRST — the same two results can order teams differently in different countries. Reading a table means knowing its tiebreaker rules, not just its points column.',
    },
  },

  // ── expert ────────────────────────────────────────────────────────────────
  {
    id: 'soc-exp-1', level: 'expert',
    board: { kind: 'soccer', home: { name: 'Vale', abbr: 'VAL', score: 2 }, away: { name: 'Harbor FC', abbr: 'HAR', score: 1 },
      minute: 'FT', note: 'LEG 2 · AGGREGATE LEVEL 3–3' },
    prompt: 'Second leg ends with the aggregate level at 3–3. What happens next in a modern major competition?',
    options: ['Extra time (2×15), then penalties if still level', 'The away-goals rule decides it', 'A replay at a neutral venue'],
    answer: 0,
    title: 'Level aggregate → extra time → penalties',
    exp: {
      kid: 'The two games together ended even, so they play 30 more minutes right now. Still even? Penalty shootout decides who goes through!',
      beginner: 'When the two-leg total is tied at the end of the second leg, that match continues into extra time (two full 15-minute halves) and then a shootout if needed — all at the second-leg venue.',
      intermediate: 'Goals in extra time count toward the aggregate like any others. The second-leg host effectively gets 30 bonus home minutes — a scheduling asymmetry people debated even more when away goals also applied.',
      expert: 'The away-goals rule (aggregate ties broken by more goals scored away) governed European ties for over 50 years until UEFA abolished it in 2021 — old match reports and older fans still reference it, so date-check any “away goals” claim. Post-abolition, level aggregates go straight to ET/pens, full stop.',
    },
  },
  {
    id: 'soc-exp-2', level: 'expert',
    board: { kind: 'soccer', home: { name: 'Olympic', abbr: 'OLY', score: 1 }, away: { name: 'Riverton', abbr: 'RIV', score: 0 },
      minute: "ET 97'", note: 'EXTRA TIME — FIRST HALF' },
    prompt: 'Olympic score in the 97th minute — early in extra time. Does the game end (sudden death)?',
    options: ['No — both 15-minute halves of extra time are always played in full', 'Yes — golden goal wins it', 'Only the first ET half is completed'],
    answer: 0,
    title: 'No golden goal: ET plays out in full',
    exp: {
      kid: 'No sudden death here — they play ALL 30 extra minutes no matter who scores. Riverton still have time to answer!',
      beginner: 'Extra time is two complete 15-minute halves. A goal changes the score, not the schedule — the trailing team gets the full remaining time to respond.',
      intermediate: 'This is a deliberate rules choice: sudden-death “golden goal” existed (and “silver goal” briefly), but full ET keeps the contest alive and rewards fitness and squad depth over one lucky break.',
      expert: 'The golden-goal era (c. 1996–2004) is a famous natural experiment: designed to encourage attacking, it measurably did the opposite — teams terrified of conceding played safe. Its abolition is the canonical example (alongside 3-points-for-a-win) of soccer iterating on incentive design.',
    },
  },
  {
    id: 'soc-exp-3', level: 'expert',
    board: { kind: 'soccer', home: { name: 'Harbor FC', abbr: 'HAR', score: 0 }, away: { name: 'Vale', abbr: 'VAL', score: 0 },
      minute: 'PENS', note: 'SHOOTOUT: HAR 4–2 VAL (AFTER 4 ROUNDS EACH)' },
    prompt: 'Shootout: Harbor lead 4–2 with each team having taken 4 of their 5 kicks. Is Vale’s fifth kick taken?',
    options: ['No — Harbor are uncatchable; the shootout is over', 'Yes — all five kicks are mandatory', 'Only if Vale request it'],
    answer: 0,
    title: 'Shootouts stop when the math does',
    exp: {
      kid: 'Vale can only reach 3 even if they score their last kick — Harbor already have 4. So there’s no point kicking: Harbor win right now!',
      beginner: 'A shootout ends the moment one side can’t catch the other: 4–2 with one Vale kick remaining means a maximum of 3. The remaining kicks are never taken.',
      intermediate: 'The same “uncatchable” logic can strike even earlier — 3–0 with only two kicks left for the trailing team ends it after just three rounds. The referee tracks reachability after every single kick.',
      expert: 'Formally: after each kick, if (leader’s score) > (trailer’s score + trailer’s remaining kicks), the shootout ends. This is also why kick ORDER interacts with pressure — going second means more of your kicks are “must score” situations, one argument in the long-running debate about coin-toss advantage in shootouts.',
    },
  },
  {
    id: 'soc-exp-4', level: 'expert',
    board: { kind: 'soccer', home: { name: 'Riverton', abbr: 'RIV', score: 2 }, away: { name: 'Olympic', abbr: 'OLY', score: 2 },
      minute: "90'+5", note: 'MIN. ADDED: 5' },
    prompt: 'Riverton score at 90’+5, right at the end of the announced added time. Is the goal valid?',
    options: ['Yes — play continues until the referee whistles; goals in added time count fully', 'No — anything after 90’ is void', 'Only if the opponent agrees'],
    answer: 0,
    title: 'Added-time goals are full goals',
    exp: {
      kid: 'Totally counts! The game isn’t over until the referee blows the final whistle — and this goal came before it. 3–2!',
      beginner: 'Stoppage-time goals are ordinary goals — some of the most famous in history came deep in added time. The half ends on the whistle, not on the board’s number.',
      intermediate: 'And since the +5 was a minimum, the ref may add a bit more for the celebration itself. The trailing team will get a kickoff and likely one final attack — the whistle usually comes once the ball reaches a neutral zone.',
      expert: 'The interplay is delicious: a 90’+5 goal extends the half (celebrations cost ~1 minute, added on), so scoring “at the death” rarely ends the game instantly. Referees are trained to complete the restart; abandoning without it invites controversy. Late-goal management — by both benches — is elite game-craft.',
    },
  },
  {
    id: 'soc-exp-5', level: 'expert',
    board: { kind: 'soccer', home: { name: 'Vale', abbr: 'VAL', score: 1 }, away: { name: 'Riverton', abbr: 'RIV', score: 1 },
      minute: "84'", note: 'RED CARD — VAL GOALKEEPER · NO SUBS LEFT' },
    prompt: 'Vale’s goalkeeper is sent off, and Vale have used ALL their substitutions. Who goes in goal?',
    options: ['An outfield player already on the pitch puts on the gloves', 'A substituted keeper returns', 'They play with an empty net'],
    answer: 0,
    title: 'The emergency outfield goalkeeper',
    exp: {
      kid: 'Someone already playing has to become the goalie! A defender or striker puts on the keeper shirt and gloves — and Vale play with 10, including their new keeper.',
      beginner: 'A team must always have a goalkeeper. With no substitutions left, an on-pitch outfield player takes the keeper’s jersey; Vale continue with 10 players total (the red card can’t be replaced).',
      intermediate: 'If subs REMAINED, Vale would sacrifice an outfielder to bring on the backup keeper — still 10 players, but a real goalie. The double cost (down a man AND likely down to a makeshift keeper) is why keeper reds are so devastating.',
      expert: 'The rulebook requirement is absolute: a designated, distinctly-dressed goalkeeper at all times — even during penalty shootouts (where an injured keeper may only be replaced if the team has a substitution left). Watching a striker in oversized gloves face a free kick is the law’s most theatrical edge case.',
    },
  },
  {
    id: 'soc-exp-6', level: 'expert',
    board: { kind: 'soccer', home: { name: 'Olympic', abbr: 'OLY', score: 0 }, away: { name: 'Harbor FC', abbr: 'HAR', score: 1 },
      minute: "89'", note: 'HAR: BALL TO THE CORNER FLAG' },
    prompt: 'Leading 1–0 at 89’, Harbor’s winger dribbles to the CORNER FLAG and shields the ball. What is he doing?',
    options: ['Killing the clock legally — trapping the ball 100 yards from his own goal', 'Showing off', 'Waiting for a substitution'],
    answer: 0,
    title: 'The corner-flag clinic: legal time-wasting',
    exp: {
      kid: 'He’s protecting the lead by keeping the ball in the safest corner of the field, far from his own goal. Every second it stays there is a second Olympic can’t attack!',
      beginner: 'Shielding the ball at the corner flag burns clock with zero risk: a defender’s tackle usually concedes a corner or throw-in (Harbor keep possession), and a foul gives Harbor a free kick deep in their attacking half.',
      intermediate: 'It exploits the running clock: soccer has no possession clock, so a team that holds the ball at the flag gives the opponent no path back except fouling — which costs a free kick 100 yards from Harbor’s goal.',
      expert: 'This is “game state” play: leading teams accept zero attacking value in exchange for time and territory. Modern refs counter with generous added time, and analysts measure it (leading teams’ effective playing time drops sharply after 80’). It’s the rational endpoint of a sport with a running clock, flat goal values, and 3-1-0 payoffs.',
    },
  },
];
