// Read the Score — Tennis bank. Scoring-RULE scenarios only (evergreen); player names
// are fictional set dressing. 6 scenarios per tier × 4 tiers. Pure data, zero RN imports.
import type { ScoreScenario } from '../readTheScore';

export const TENNIS_SCENARIOS: ScoreScenario[] = [
  // ── kid ────────────────────────────────────────────────────────────────────
  {
    id: 'ten-kid-1', level: 'kid',
    board: { kind: 'tennis', p1: { name: 'Marek', sets: [4], points: '15' }, p2: { name: 'Ito', sets: [2], points: '0' }, server: 1 },
    prompt: 'Look at the games column (4–2). Who is winning this set?',
    options: ['Marek', 'Ito', 'It’s even'],
    answer: 0,
    title: 'Marek leads the set 4 games to 2',
    exp: {
      kid: 'The big numbers count GAMES. Marek has won 4 games and Ito only 2 — Marek is ahead in this set.',
      beginner: 'Tennis scores stack in layers: points make a game, games make a set (first to 6), sets make the match. The 4–2 is the games layer — the one that decides the set.',
      intermediate: 'Reading order on any tennis board: completed sets (left), current-set games (middle-right), current-game points (far right). 4–2 with Marek serving means Ito must soon “break back” or the set slips away.',
      expert: 'The layered system means leads are structural, not just numeric: 4–2 with serve is really “on serve plus one break” — the deficit isn’t 2 games, it’s ONE break of serve. Thinking in breaks, not games, is how players and commentators actually read a set.',
    },
  },
  {
    id: 'ten-kid-2', level: 'kid',
    board: { kind: 'tennis', p1: { name: 'Silva', sets: [3], points: '30' }, p2: { name: 'Renard', sets: [3], points: '15' }, server: 1 },
    prompt: 'Silva has 30 and wins the next point. What does the board show for Silva?',
    options: ['40', '31', '45'],
    answer: 0,
    title: 'The ladder goes 0 → 15 → 30 → 40',
    exp: {
      kid: 'Tennis points climb a funny ladder: 0, then 15, then 30, then 40. After 30 comes 40 — one more point after that usually wins the game!',
      beginner: 'Game scoring: love (0) → 15 → 30 → 40 → game. So a player at 40 wins the game with the next point (unless both reach 40 — that’s deuce, a story of its own).',
      intermediate: 'The numbers are medieval quirk (possibly clock quarters: 15, 30, 45-shortened-to-40) — they’re labels, not arithmetic. What matters: each is one point, and 40 means “one from the game.”',
      expert: 'Because the labels compress information, pros read pressure instead: 30–15 is “two points from game vs three” — a swing point. Statistically, winning the 30–15 point vs losing it (30–30) moves game-win probability by ~20 points. The ladder’s steps are not equal-sized.',
    },
  },
  {
    id: 'ten-kid-3', level: 'kid',
    board: { kind: 'tennis', p1: { name: 'Ito', sets: [1], points: '0' }, p2: { name: 'Marek', sets: [2], points: '30' }, server: 2 },
    prompt: 'The umpire says Ito has “love.” What does love mean in tennis?',
    options: ['Zero — no points yet', 'One point', 'The final point'],
    answer: 0,
    title: 'Love = zero',
    exp: {
      kid: '“Love” is tennis-talk for zero! “30–love” means 30 to nothing.',
      beginner: 'Love = 0, everywhere in tennis: “love–15” (0–1 in points), a “love game” (won without conceding a point), even a “6–love set” (a shutout set, also called a bagel).',
      intermediate: 'The word likely comes from the French “l’œuf” (the egg — shaped like a 0), though etymologists argue. Either way, “hold to love” = a service game won 4 points to none — a statement of dominance.',
      expert: 'Love games are a real tell when scanning a scoreboard’s history: a set full of love holds signals serve dominance (expect tiebreaks); scattered deuce games signal a returner getting traction. The vocabulary encodes match texture, not just numbers.',
    },
  },
  {
    id: 'ten-kid-4', level: 'kid',
    board: { kind: 'tennis', p1: { name: 'Renard', sets: [2], points: '15' }, p2: { name: 'Silva', sets: [2], points: '15' }, server: 2 },
    prompt: 'See the little dot next to Silva’s name? What does it mean?',
    options: ['Silva is serving', 'Silva is winning', 'Silva called a timeout'],
    answer: 0,
    title: 'The dot marks the server',
    exp: {
      kid: 'The dot shows who’s serving — hitting the first shot of every point. Right now it’s Silva’s turn to serve a whole game.',
      beginner: 'Players alternate serving GAMES (not points): Silva serves every point of this game, then Renard serves the next game, and so on through the set.',
      intermediate: 'Serving is a big advantage — pros win the clear majority of their service games (“holds”). That’s why the serve marker matters: 2–2 with Silva serving is normal; 2–2 with Silva about to LOSE serve is drama.',
      expert: 'The alternating-serve structure defines tennis strategy: sets are decided by the rare “break” games. A scoreboard reader tracks serve like a chess clock — “on serve” (no breaks either way) is the baseline state, and every deviation from it is the actual story of the set.',
    },
  },
  {
    id: 'ten-kid-5', level: 'kid',
    board: { kind: 'tennis', p1: { name: 'Marek', sets: [6, 2], points: '30' }, p2: { name: 'Ito', sets: [3, 1], points: '15' }, server: 1 },
    prompt: 'Marek won the first set 6–3. In a best-of-3 match, how many sets does he need in total?',
    options: ['2 sets — one more wins the match', '3 sets', 'Just the one he has'],
    answer: 0,
    title: 'Best of 3: first to 2 sets',
    exp: {
      kid: 'Most matches are “best of 3”: whoever wins 2 sets first wins the whole match. Marek has 1 set — one more and it’s over!',
      beginner: 'Sets are the match currency. Best-of-3 = first to 2 sets; the big men’s Grand Slam matches are best-of-5 = first to 3. The 6–3 in the left column is a finished set banked forever.',
      intermediate: 'Completed sets can’t be un-won — that’s why a player can drop the first set 0–6 and still win the match 2 sets to 1. Each set is a fresh contest; only the COUNT of sets matters.',
      expert: 'Set-count scoring creates tennis’s famous non-linearity: match win probability is a function of sets, and within sets of breaks, and within games of clutch points. It’s why “momentum” talk is so loud in tennis — the scoreboard literally resets sub-scores while preserving the meta-score.',
    },
  },
  {
    id: 'ten-kid-6', level: 'kid',
    board: { kind: 'tennis', p1: { name: 'Silva', sets: [5], points: '40' }, p2: { name: 'Renard', sets: [3], points: '15' }, server: 1 },
    prompt: 'Silva has 40 and Renard has 15. If Silva wins the next point, what happens?',
    options: ['Silva wins the game — the games column becomes 6–3', 'The points reset to 30–30', 'Silva needs one more point after this'],
    answer: 0,
    title: 'Winning a point at 40: game over',
    exp: {
      kid: 'At 40, one more point wins the game! Silva would take the game, and his games number goes from 5 to 6.',
      beginner: 'From 40 (with the opponent below 40), the next point wins the game. Here it also brings up 6–3: six games with a two-game lead = Silva wins the SET too.',
      intermediate: 'This is “set point”: a point that, if won, delivers the whole set. Boards don’t always label it — you compute it: 40–15 at 5–3 means Silva has two set points (40–15 = two chances before deuce).',
      expert: 'Counting chances is the skill: 40–15 = two set points; 40–30 = one; 40–40 = none (deuce). Elite viewers track “set points saved/converted” live because those single points carry more win-probability weight than entire routine games.',
    },
  },

  // ── beginner ──────────────────────────────────────────────────────────────
  {
    id: 'ten-beg-1', level: 'beginner',
    board: { kind: 'tennis', p1: { name: 'Marek', sets: [4], points: '40' }, p2: { name: 'Ito', sets: [4], points: '40' }, server: 1 },
    prompt: 'Both players are at 40. What is this score called?',
    options: ['Deuce', 'Double game point', 'Even-forty'],
    answer: 0,
    title: '40–40 is deuce',
    exp: {
      kid: 'When BOTH players reach 40, it’s called “deuce.” Now someone has to win two points in a row to take the game!',
      beginner: 'At deuce, winning one point gives you “advantage”; win the next too and the game is yours. Lose it and it’s back to deuce — repeat as long as it takes.',
      intermediate: 'Deuce is tennis’s win-by-two rule at the point level: games can’t be won 5–4 in points. Long deuce battles (5, 8, 12 deuces) are where service games get broken and legs get heavy.',
      expert: 'The win-by-2 requirement makes deuce games disproportionately decisive: each deuce is a fresh best-of-2-in-a-row, so the better clutch player compounds. Analytics confirm deuce-game win rate correlates with match wins more strongly than ace count — the scoreboard’s most innocuous symbol hides its highest-leverage state.',
    },
  },
  {
    id: 'ten-beg-2', level: 'beginner',
    board: { kind: 'tennis', p1: { name: 'Silva', sets: [3], points: 'Ad' }, p2: { name: 'Renard', sets: [5], points: '40' }, server: 1 },
    prompt: 'The board shows “Ad” for Silva. What does it mean?',
    options: ['Advantage — one more point wins the game', 'Administrative timeout', 'Silva is a set up'],
    answer: 0,
    title: 'Ad = advantage',
    exp: {
      kid: '“Ad” means advantage — Silva won the deuce point. If he wins the NEXT point too, the game is his. If he loses it, back to deuce!',
      beginner: 'From deuce: win a point → advantage (Ad). Win the next → game. Lose it → deuce again. The board shows “Ad” next to whoever holds it.',
      intermediate: 'You’ll hear “ad-in” (server has it) and “ad-out” (receiver has it) — the in/out refers to the server. Ad-out is a break point: the receiver is one point from stealing the game.',
      expert: 'Note the format wrinkle: much of doubles (and some team competitions) uses NO-AD scoring — at deuce, one sudden-death point decides the game, receiver picks the side. Knowing whether the event plays ad or no-ad changes how you read every 40–40 on the board.',
    },
  },
  {
    id: 'ten-beg-3', level: 'beginner',
    board: { kind: 'tennis', p1: { name: 'Ito', sets: [5], points: '0' }, p2: { name: 'Marek', sets: [4], points: '0' }, server: 2 },
    prompt: 'Ito leads 5–4 in games. What does he need to win the set?',
    options: ['Reach 6 games with a 2-game lead — 6–4 now, or 7–5 later', 'Reach 6 games any way', 'Win 5 more points'],
    answer: 0,
    title: 'Sets need 6 games AND a 2-game cushion',
    exp: {
      kid: 'To win a set you need 6 games, but you also must be 2 ahead. If Ito gets to 6–4, the set is his!',
      beginner: 'First to 6 by a margin of 2: 6–4 works, 6–5 does not (play continues to 7–5 or 6–6). Marek is serving here — if he holds, it’s 5–5.',
      intermediate: 'A 5–4 lead with the OPPONENT serving isn’t really a set lead — it’s “on serve.” Ito needs a break (or to reach a tiebreak at 6–6). The games number alone overstates his edge.',
      expert: 'The margin-of-2 rule at the games layer mirrors deuce at the points layer — tennis fractalizes win-by-two at every level except the modern tiebreak set (7–6). That structural rhyme (points, games, tiebreaks all win-by-2) is the scoring system’s single organizing principle.',
    },
  },
  {
    id: 'ten-beg-4', level: 'beginner',
    board: { kind: 'tennis', p1: { name: 'Renard', sets: [2], points: '30' }, p2: { name: 'Silva', sets: [3], points: '40' }, server: 1 },
    prompt: 'The umpire announces “30–40.” Whose score is said FIRST in tennis?',
    options: ['The server’s — Renard has 30, Silva has 40', 'The leader’s', 'The home player’s'],
    answer: 0,
    title: 'Server’s score first, always',
    exp: {
      kid: 'The serving player’s points are always said first. Renard is serving, so “30–40” means Renard 30, Silva 40.',
      beginner: 'Announcing convention: server first. “15–40” means the SERVER trails. Learn this and umpire calls suddenly make sense without seeing the board.',
      intermediate: 'And 30–40 has a name: break point. The receiver (Silva) is one point from breaking serve — the highest-drama single point in a set.',
      expert: 'Server-first convention encodes leverage instantly: “15–40” = double break point (two chances); “Ad–out” = break point after deuce. Skilled listeners track break-point conversion across a match from the calls alone — the audio IS the scoreboard.',
    },
  },
  {
    id: 'ten-beg-5', level: 'beginner',
    board: { kind: 'tennis', p1: { name: 'Marek', sets: [6, 6], points: '—' }, p2: { name: 'Ito', sets: [4, 6], points: '—' }, server: 1, note: 'SET 2: TIEBREAK AT 6–6' },
    prompt: 'The second set reached 6–6. What happens now?',
    options: ['A tiebreak game decides the set', 'They keep playing until someone leads by 2 games', 'The set is a draw'],
    answer: 0,
    title: '6–6 → tiebreak',
    exp: {
      kid: 'At 6 games each, they play one special deciding game called a tiebreak — first to 7 points (2 ahead) wins the whole set!',
      beginner: 'The tiebreak replaces endless 8–6, 10–8 sets: first to 7 POINTS, win by 2, and the set goes in the books as 7–6. Numbers in a tiebreak are plain (1, 2, 3…), not 15/30/40.',
      intermediate: 'Serve rotates differently: one player serves point 1, then two serves each, switching ends every 6 points. The set winner’s line shows 7–6 with the tiebreak score often in superscript, e.g. 7–6(4).',
      expert: 'That “(4)” notation means the loser scored 4 tiebreak points (7–4). Tiebreaks are statistically near coin-flips between similar players — which is why big servers structure whole sets around reaching them, and why deciding-set rules (10-point breakers etc.) became such a debated design space.',
    },
  },
  {
    id: 'ten-beg-6', level: 'beginner',
    board: { kind: 'tennis', p1: { name: 'Silva', sets: [2], points: '40' }, p2: { name: 'Renard', sets: [1], points: '30' }, server: 2, note: 'RENARD SERVING' },
    prompt: 'Renard is SERVING at 30–40 (his score first). If Silva wins this point, what is it called?',
    options: ['A break of serve', 'A hold', 'An ace'],
    answer: 0,
    title: 'Winning the opponent’s service game = a break',
    exp: {
      kid: 'Winning a game when the OTHER player was serving is called “breaking serve” — like stealing a game that was supposed to be theirs!',
      beginner: 'Servers usually win their games (“holds”). When the receiver wins one instead, that’s a “break” — and 30–40 is “break point,” the chance to do it.',
      intermediate: 'Breaks are the currency of sets: since holds are the norm, a single break often decides a set 6–4. “Break back” = immediately returning the favor to restore balance.',
      expert: 'Match-reading pro tip: track breaks, not games. “Two breaks up” is nearly unassailable; “a break up” means protect every hold; “on serve” means nothing has happened yet no matter what the game count says. Every tennis scoreline decompresses into hold/break language.',
    },
  },

  // ── intermediate ──────────────────────────────────────────────────────────
  {
    id: 'ten-int-1', level: 'intermediate',
    board: { kind: 'tennis', p1: { name: 'Marek', sets: [6, 3, 5], points: '40' }, p2: { name: 'Ito', sets: [4, 6, 4], points: '30' }, server: 1 },
    prompt: 'Best of 3. Marek: sets 6–4, 3–6, now 5–4 and serving at 40–30. What is this point?',
    options: ['Match point — winning it wins set and match', 'Set point only', 'Break point'],
    answer: 0,
    title: 'Serving for the match, match point',
    exp: {
      kid: 'If Marek wins this point he wins the game, which makes 6 games — winning the set. And that’s his second set, which wins the WHOLE match. One point for everything!',
      beginner: 'Chain it: point → game (40–30 is game point) → set (5–4 becomes 6–4) → match (sets 2–1). When one point completes the whole chain, it’s match point.',
      intermediate: 'The board never says “match point” — you derive it: server at 40–30, 5–4 in games, one set apiece… every layer is one step from done. This chained reading is THE core tennis-board skill.',
      expert: 'Serving for the match at 5–4 is also tennis’s most famous pressure spot — “serving it out.” Statistically, break rates spike in these games (the receiver swings free, the server tightens). A reader who sees 5–4/40–30 knows both the arithmetic (match point) and the psychology (the hardest hold in tennis).',
    },
  },
  {
    id: 'ten-int-2', level: 'intermediate',
    board: { kind: 'tennis', p1: { name: 'Silva', sets: [4, 6], points: '6' }, p2: { name: 'Renard', sets: [6, 6], points: '5' }, server: 2, note: 'TIEBREAK' },
    prompt: 'Tiebreak: Silva leads 6–5. Is this set point — and what if it gets to 6–6?',
    options: ['Yes, set point; at 6–6 the tiebreak continues until someone leads by 2', 'No — tiebreaks go to 10', 'At 6–6 the set is replayed'],
    answer: 0,
    title: 'Tiebreaks: first to 7, win by 2, no ceiling',
    exp: {
      kid: 'Silva needs 7 points and has 6 — one more wins the set! But if Renard makes it 6–6, they keep going until someone is 2 points ahead. Tiebreaks can get LONG.',
      beginner: 'First to 7 by 2: 7–5 wins, 6–6 continues (8–6, 9–7, even 15–13…). There’s no cap — the win-by-2 rule alone ends it.',
      intermediate: 'At 6–5 the server matters enormously: Renard serves this point (note the marker), so Silva has set point ON RETURN — statistically harder to convert. Mini-breaks (winning a point on the opponent’s tiebreak serve) are the tiebreak’s unit of progress.',
      expert: 'Tiebreak literacy: track serve sequence (1, then 2-2-2…) and mini-breaks (points won on the opponent’s serve). Careful here: 6–5 to the returner at this exact spot is “on serve” — if every server had held, the player who served FIRST trails 5–6 before serving points 12–13. So Silva’s set point is the chance to grab the decisive mini-break, not the product of one. Marathon breakers (18–16 and beyond) exist because win-by-2 has no ceiling.',
    },
  },
  {
    id: 'ten-int-3', level: 'intermediate',
    board: { kind: 'tennis', p1: { name: 'Ito', sets: [6], points: '0' }, p2: { name: 'Marek', sets: [5], points: '0' }, server: 2, note: 'MAREK SERVING AT 5–6' },
    prompt: 'Ito leads 6–5 and Marek serves. Does Ito win the set if he breaks — and what if Marek holds?',
    options: ['Break = set 7–5 to Ito; hold = 6–6 tiebreak', 'The set already ended at 6', 'Either way a tiebreak happens'],
    answer: 0,
    title: '6–5 is not 6–6: the set is live',
    exp: {
      kid: 'Six games isn’t enough on its own — you need to be 2 ahead. If Ito wins this game it’s 7–5, set over. If Marek wins, it’s 6–6 and a tiebreak!',
      beginner: 'Common misreading: “first to 6” — actually first to 6 BY TWO. At 6–5 there’s exactly one game that decides the fork: 7–5 (set) or 6–6 (tiebreak).',
      intermediate: 'This game at 5–6 is “serving to stay in the set” — the mirror of serving for it. The server carries all the pressure: lose one service game at the wrong moment and the set is simply gone.',
      expert: 'Sequencing nuance: a receiver leading 6–5 gets TWO bites — win the 5–6 game (return) or, failing that, the tiebreak. That option value is why breaking to LEAD 6–5 (instead of trailing into a breaker) measurably improves set-win probability beyond the single game gained.',
    },
  },
  {
    id: 'ten-int-4', level: 'intermediate',
    board: { kind: 'tennis', p1: { name: 'Renard', sets: [3], points: '40' }, p2: { name: 'Silva', sets: [3], points: 'Ad' }, server: 1, note: 'DEUCE COUNT: 5' },
    prompt: 'Silva had advantage, but the board flips back to showing deuce. What happened?',
    options: ['Silva lost the advantage point — deuce again, indefinitely repeatable', 'The umpire overruled the game', 'Advantage expires after 20 seconds'],
    answer: 0,
    title: 'Advantage lost → deuce again',
    exp: {
      kid: 'If you have advantage but lose the next point, the score goes right back to deuce. It can bounce back and forth many, many times!',
      beginner: 'Deuce → advantage → (win: game / lose: deuce). There is no limit — games have gone 20+ deuces. The note “deuce count: 5” means they’ve been here five times already.',
      intermediate: 'Marathon deuce games are physical and psychological wars — each advantage is a game point or break point, so the pressure alternates sides point by point. Neither the set nor the clock caps it (no-ad formats exist precisely to cap this).',
      expert: 'Probability view: from deuce, if the server wins each point with probability p, the game resolves as p²/(p²+(1−p)²) — at p=0.5 it’s a true coin flip that just… takes a while. The longest recorded deuce games ran past 30 deuces. The rule is beautiful and merciless: win two in a row or stay forever.',
    },
  },
  {
    id: 'ten-int-5', level: 'intermediate',
    board: { kind: 'tennis', p1: { name: 'Marek', sets: [6, 1], points: '15' }, p2: { name: 'Ito', sets: [7, 2], points: '30' }, server: 1, note: 'SET 1: 6–7(4)' },
    prompt: 'The first set reads 6–7(4). What does the “(4)” tell you?',
    options: ['Ito won the tiebreak 7–4', 'The set had 4 deuces', 'Marek led 4–0 at one point'],
    answer: 0,
    title: 'Reading tiebreak notation',
    exp: {
      kid: 'The little number shows the tiebreak score! 7–6(4) means the tiebreak finished 7 points to 4.',
      beginner: 'Convention: the bracketed number is the LOSER’s tiebreak points. “6–7(4)” from Marek’s side = he lost the breaker 4–7. You’ll see it written 7–6(4) from the winner’s side.',
      intermediate: 'If the breaker went past 7 (say 11–9), the notation shows (9) — you can reconstruct: loser 9 means winner needed 11 (win by 2). One bracketed digit encodes the whole overtime story.',
      expert: 'Deep habit: scan the brackets across a finished match. A line like 7–6(8), 7–6(6) certifies overtime inside both breakers — (8) means 10–8, a tiebreak that ran through 6–6 and 8–8 with the loser repeatedly a point from stealing the set. Bracket-reading recovers the drama the raw set scores hide.',
    },
  },
  {
    id: 'ten-int-6', level: 'intermediate',
    board: { kind: 'tennis', p1: { name: 'Silva', sets: [2], points: '15' }, p2: { name: 'Renard', sets: [4], points: '40' }, server: 1, note: 'BREAK POINT ×2' },
    prompt: 'Silva serves at 15–40. The note says “break point ×2.” Why two?',
    options: ['Renard has two chances in a row to break (at 15–40, losing one still leaves 30–40)', 'It’s his second break of the match', 'Double points are scored here'],
    answer: 0,
    title: 'Counting break points at 15–40',
    exp: {
      kid: 'Renard needs one more point to steal the game — and even if he misses the first chance, he gets another (the score would be 30–40). Two chances!',
      beginner: '15–40 = double break point: from here the receiver can win the game at 40 (first chance), and if the server saves it, 30–40 offers a second. 0–40 would be triple break point.',
      intermediate: 'Chance-counting works for any 40-state: 15–40 → two break points; 30–40 → one; deuce → zero until someone earns advantage. Servers “saving” multiple break points in a game is a momentum signature worth watching for.',
      expert: 'Break-point conversion (chances taken ÷ chances earned) is among the most predictive in-match stats — and the asymmetry matters: SAVED break points swing games back to holds, and multi-break-point games that end in holds are demoralization events. From 15–40, servers still hold roughly a third of the time at pro level; the board understates their escape odds.',
    },
  },

  // ── expert ────────────────────────────────────────────────────────────────
  {
    id: 'ten-exp-1', level: 'expert',
    board: { kind: 'tennis', p1: { name: 'Marek', sets: [7, 4, 6], points: '—' }, p2: { name: 'Ito', sets: [6, 6, 6], points: '—' }, server: 1, note: 'DECIDING SET: 6–6 — 10-POINT TIEBREAK' },
    prompt: 'Deciding set reaches 6–6 and the board announces a 10-POINT tiebreak. How does it differ from a normal one?',
    options: ['First to 10 points (win by 2) instead of 7', 'It has no win-by-2 rule', 'Each point counts double'],
    answer: 0,
    title: 'The deciding-set super-tiebreak',
    exp: {
      kid: 'It’s a bigger tiebreak for the final set: first to 10 points instead of 7, still needing to be 2 ahead. A longer race for the biggest moment!',
      beginner: 'The “super-breaker”: same serving pattern as a normal tiebreak, but the target is 10, win by 2. Modern Grand Slams adopted a 10-point breaker at 6–6 in deciding sets, ending the era of endless final sets.',
      intermediate: 'History helps reading old scores: deciding sets once had NO tiebreak at some majors (scores like 70–68 in games happened at Wimbledon 2010’s famous marathon). Different events standardized differently until the slams aligned on the 10-pointer in the 2020s.',
      expert: 'Format literacy is genuinely level-relevant: best-of-3 vs 5, ad vs no-ad, 7-point vs 10-point deciders, and match-tiebreaks replacing third sets entirely in doubles. Before judging any scoreline (“how is the set 12–12?”), identify the event’s format sheet — the same sport runs half a dozen scoring dialects simultaneously.',
    },
  },
  {
    id: 'ten-exp-2', level: 'expert',
    board: { kind: 'tennis', p1: { name: 'Silva', sets: [1, 7, 7], points: '—' }, p2: { name: 'Renard', sets: [6, 6, 6], points: '—' }, server: 1, note: 'MATCH COMPLETE — SILVA WINS' },
    prompt: 'Final: Silva wins 1–6, 7–6(4), 7–6(6). Renard actually won MORE total points. How is that possible?',
    options: ['Only set count matters — margins inside lost sets don’t carry over', 'It’s impossible — the board is wrong', 'Points carry over to the next set'],
    answer: 0,
    title: 'The scoring paradox: win less, win anyway',
    exp: {
      kid: 'Tennis only counts SETS at the end. You can lose one set REALLY badly and win two sets by a whisker — the blowout set doesn’t spill into the others!',
      beginner: 'Each set is sealed when it ends: losing a set 0–6 costs exactly as much as losing it 6–7 — one set. So a player winning tight sets and losing lopsided ones can win the match with fewer points, fewer games, even fewer… everything except sets.',
      intermediate: 'This is called a “Simpson’s paradox” structure: aggregation by sets discards within-set margins. Estimates suggest a meaningful share of professional matches are won by the player with fewer total points — clutch-point distribution beats volume.',
      expert: 'Strategic implication: not all points are worth fighting for equally. Theory (and some observed behavior) says conserve energy in lost causes (down 0–4 in a set) and spend everything on high-leverage points — the scoring system explicitly rewards leverage allocation over uniform effort. Tennis’s scoreboard is a leverage market, and the best players trade it well.',
    },
  },
  {
    id: 'ten-exp-3', level: 'expert',
    board: { kind: 'tennis', p1: { name: 'Ito', sets: [6, 6], points: '9' }, p2: { name: 'Marek', sets: [6, 6], points: '9' }, server: 2, note: '10-POINT TIEBREAK: 9–9' },
    prompt: 'Super-tiebreak tied 9–9. A player wins the next point. Is that match point converted?',
    options: ['No — at 9–9 you still need TWO clear points; 10–9 is match point, not match', 'Yes — first to 10 wins immediately', 'The breaker restarts at 9–9'],
    answer: 0,
    title: 'Win-by-2 survives even at 9–9',
    exp: {
      kid: 'Even in the race to 10, you must finish 2 points ahead! At 9–9, the next point only makes it 10–9 — match point, but not the match yet.',
      beginner: '10–9 is a chance, not a conclusion: win the next too (11–9) and it’s over; lose it and 10–10 continues the ladder (12–10, 13–11…). The win-by-2 rule never sleeps.',
      intermediate: 'Reading super-breaker boards: any score ≥9 for both means sudden-death-by-pairs — each pair of points either ends it (won by same player) or advances the stalemate. Serve alternates in the usual 2-2 pattern with ends changing every 6, so no one serves consecutive “match point pairs” from the same end.',
      expert: 'The deuce-structure isomorphism completes here: 9–9 in a 10-pointer ≡ deuce ≡ 6–6 in games. Tennis is one recursive win-by-2 automaton at every scale — the only exception ever carved out is the set won 7–6. Once you see the recursion, you can read any tennis score state, in any format, from first principles.',
    },
  },
  {
    id: 'ten-exp-4', level: 'expert',
    board: { kind: 'tennis', p1: { name: 'Renard', sets: [6, 2], points: '30' }, p2: { name: 'Silva', sets: [4, 3], points: '15' }, server: 2, note: 'SET 2 · SILVA SERVED FIRST IN SET 1' },
    prompt: 'A set ended 6–4 with Renard winning. What does the games total guarantee about breaks of serve in that set?',
    options: ['At least one — Renard won 6 of 10 games but served only 5', 'None — sets can end 6–4 on serve', 'Exactly two'],
    answer: 0,
    title: 'A 6–4 set always contains a break',
    exp: {
      kid: 'In 10 games, each player serves 5. Renard won 6 — more than his 5 serving turns — so he MUST have won at least one game on Silva’s serve. That’s a break!',
      beginner: 'Serve alternates every game, so in a 6–4 set the winner (6 wins in 10 games, 5 serves each) necessarily broke at least once. “Every set win requires at least one break or a tiebreak” — pure arithmetic.',
      intermediate: 'Extend the logic: 6–3 (9 games — winner served 5, or 4… either way 6 > 5) guarantees a break; 7–5 guarantees one; 7–6 is the ONLY set score achievable with zero breaks (all holds into a tiebreak). Set scores are break-count constraints in disguise.',
      expert: 'Full decode table (winner’s games minus games they could have served): 6–0 guarantees ≥3 breaks; 6–1 and 6–2 guarantee ≥2; 6–3, 6–4 and 7–5 guarantee ≥1; only 7–6 can be break-free (all holds into the breaker). Glancing at completed set scores tells you serve-dominance texture without a single stat — 7–6, 7–6 was a serving contest; 6–3, 6–2 was a return clinic.',
    },
  },
  {
    id: 'ten-exp-5', level: 'expert',
    board: { kind: 'tennis', p1: { name: 'Marek', sets: [5], points: '30' }, p2: { name: 'Ito', sets: [5], points: '40' }, server: 1, note: 'SET POINT — RETURN' },
    prompt: 'Games 5–5, Marek serving at 30–40. A TV graphic flashes “SET POINT.” Is the graphic right?',
    options: ['No — a break only makes it 6–5, short of the 2-game margin. It’s break point, nothing more', 'Yes — winning this point wins Ito the set 6–5', 'Yes, but only because Marek is serving'],
    answer: 0,
    title: 'Careful: at 5–5, a break is NOT yet the set',
    exp: {
      kid: 'Trick question! If Ito wins this point he leads 6–5 — but that’s not 2 ahead, so the set isn’t over. The graphic is wrong: it’s a break point, not a set point.',
      beginner: 'At 5–5, breaking makes it 6–5 — Ito would still need one more game (serving the set out at 6–5, or the tiebreak at 6–6). A true set point needs THIS game to finish the set: 6 games AND a 2-game lead.',
      intermediate: 'The precise test: “if the receiving player wins this game, do they satisfy 6+ games AND +2 margin?” At 5–5: 6–5 fails the margin. At 5–4: 6–4 passes — so 30–40 at 5–4 IS set point. Scoreboard notes get this wrong surprisingly often; now you can audit them.',
      expert: 'This is the expert habit the whole game teaches: never trust a leverage label without recomputing it from the layered rules. Real broadcast graphics do occasionally mislabel set/match points in 5–5 and tiebreak-adjacent states. The layered win-by-2 automaton is the ground truth; the graphics are a rendering of it — sometimes a buggy one.',
    },
  },
  {
    id: 'ten-exp-6', level: 'expert',
    board: { kind: 'tennis', p1: { name: 'Silva', sets: [6, 6], points: '—' }, p2: { name: 'Renard', sets: [7, 7], points: '—' }, server: 1, note: 'FINAL: 6–7(5), 6–7(8)' },
    prompt: 'Final: 6–7(5), 6–7(8). Reconstruct the second-set tiebreak from the “(8)”.',
    options: ['Renard won it 10–8 — win-by-2 pushed it through 6–6, 7–7 and 8–8', 'It ended 8–6', 'Silva won it 8 points to 7'],
    answer: 0,
    title: 'Bracket forensics: (8) means 10–8',
    exp: {
      kid: 'The bracket shows the loser’s tiebreak points. Silva lost it with 8 — and since you must win by 2, the winner needed 10. The tiebreak went 10–8!',
      beginner: 'Reconstruction: loser scored 8; winner’s total = max(7, 8+2) = 10. So the breaker passed the normal 7 (through 6–6, 7–7, 8–8) before Renard took two straight. A “(5)” by contrast just means a straightforward 7–5.',
      intermediate: 'Any bracket ≥6 certifies overtime inside the tiebreak: (6) = 8–6, (8) = 10–8, (16) = 18–16. Each implies the loser was within a point or two of the set repeatedly — margin data hiding in one digit.',
      expert: 'Full-match forensics from “6–7(5), 6–7(8)”: both sets reaching breakers signals serve dominance (7–6 is the only break-free set score), and the escalating brackets (5 → 8) show the loser getting CLOSER while still losing — the classic heartbreak signature. A single line of notation, properly read, contains the emotional arc of a two-hour match. That’s scoreboard literacy at its highest setting.',
    },
  },
];
