// Read the Score — WNBA bank. Scoring-RULE scenarios only (evergreen); team names are
// fictional set dressing. WNBA specifics are real: 10-minute quarters (40-minute game),
// 24-second shot clock, 6 personal fouls, 5-minute OT. 6 per tier × 4 tiers. Pure data.
import type { ScoreScenario } from '../readTheScore';

export const WNBA_SCENARIOS: ScoreScenario[] = [
  // ── kid ────────────────────────────────────────────────────────────────────
  {
    id: 'wnba-kid-1', level: 'kid',
    board: { kind: 'basketball', away: { name: 'Aurora', abbr: 'AUR', score: 67 }, home: { name: 'Tempest', abbr: 'TEM', score: 74 },
      period: 'Q4', clock: '5:02', shotClock: 17 },
    prompt: 'Who is winning?',
    options: ['Tempest', 'Aurora', 'It’s a tie'],
    answer: 0,
    title: 'Tempest lead 74–67',
    exp: {
      kid: 'The Tempest have 74 points and the Aurora have 67 — the bigger number is winning.',
      beginner: 'Points pile up in 1s (free throws), 2s (regular baskets) and 3s (long shots). 74–67 is a 7-point Tempest lead in the last quarter.',
      intermediate: 'Seven points is “three possessions at most” — two 3s and a free throw could level it. With 5:02 left, this is very much a live game.',
      expert: 'WNBA pace runs a bit under 2 possessions per team per minute, so ~9–10 possessions each remain. Down 7, Aurora need to win those possessions by ~0.7 points apiece — pressure defense and 3-hunting territory, but no panic yet.',
    },
  },
  {
    id: 'wnba-kid-2', level: 'kid',
    board: { kind: 'basketball', away: { name: 'Vipers', abbr: 'VIP', score: 22 }, home: { name: 'Sirens', abbr: 'SIR', score: 19 },
      period: 'Q1', clock: '1:15', shotClock: 20 },
    prompt: 'A Sirens guard makes a shot from BEHIND the big arc. How many points?',
    options: ['3 points', '2 points', '1 point'],
    answer: 0,
    title: 'Behind the arc = 3',
    exp: {
      kid: 'Shots from behind the big curved line are worth 3 points instead of 2. Extra distance, extra point!',
      beginner: 'Inside the arc a made basket is 2; from behind it, 3. The shooter’s feet must be fully behind the line when she jumps.',
      intermediate: 'A toe ON the line turns the 3 into a 2 — the line belongs to the 2-point area. That’s why shooters set their feet a beat before the catch.',
      expert: 'Same points-per-shot revolution as everywhere in basketball: 35% from deep (1.05 PPS) outproduces 50% from mid-range (1.00). Spacing the floor around reliable 3-point shooting is the modern offense, WNBA included.',
    },
  },
  {
    id: 'wnba-kid-3', level: 'kid',
    board: { kind: 'basketball', away: { name: 'Aurora', abbr: 'AUR', score: 31 }, home: { name: 'Tempest', abbr: 'TEM', score: 28 },
      period: 'Q2', clock: '6:47', shotClock: 24 },
    prompt: 'A player is fouled and goes to the free-throw line for two shots. What is each made shot worth?',
    options: ['1 point', '2 points', '3 points'],
    answer: 0,
    title: 'Free throws: 1 point each',
    exp: {
      kid: 'Free throws are free shots with nobody guarding you. Each one is worth 1 point.',
      beginner: 'After a foul on a shooter, she gets free throws — usually two, worth 1 point each, taken from the free-throw line with play stopped.',
      intermediate: 'The count follows the attempt: 2 shots for a foul on a 2-pointer, 3 for a foul on a 3-pointer, 1 extra if the basket went in anyway (“and-one”).',
      expert: 'Free-throw trips are elite offense — two shots at ~80% is ~1.6 points per trip, better than any set play. Drawing fouls is a repeatable skill, and late-game strategy revolves around who is (and isn’t) safe to foul.',
    },
  },
  {
    id: 'wnba-kid-4', level: 'kid',
    board: { kind: 'basketball', away: { name: 'Vipers', abbr: 'VIP', score: 0 }, home: { name: 'Sirens', abbr: 'SIR', score: 0 },
      period: 'Q1', clock: '10:00', shotClock: 24 },
    prompt: 'The first-quarter clock starts at 10:00. How many quarters will they play?',
    options: ['4 quarters', '2 quarters', '5 quarters'],
    answer: 0,
    title: 'Four 10-minute quarters',
    exp: {
      kid: 'A WNBA game has 4 quarters, and each one is 10 minutes long.',
      beginner: 'Four quarters of 10 minutes = 40 minutes of game time, with halftime after Q2. (The NBA plays 12-minute quarters — 48.)',
      intermediate: 'The 40-minute format means fewer total possessions than an NBA game, so WNBA scores naturally sit lower — compare scoring by pace and efficiency, not raw totals.',
      expert: 'Format literacy prevents a classic mistake: an 85-point WNBA team over 40 minutes is scoring at the same per-minute rate as a 102-point NBA team over 48. Normalize per possession and league scoring gaps mostly reflect minutes, not quality.',
    },
  },
  {
    id: 'wnba-kid-5', level: 'kid',
    board: { kind: 'basketball', away: { name: 'Aurora', abbr: 'AUR', score: 45 }, home: { name: 'Tempest', abbr: 'TEM', score: 45 },
      period: 'Q4', clock: '0:00' },
    prompt: 'The final buzzer sounds at 45–45. Is the game over?',
    options: ['No — they play overtime', 'Yes — it’s a tie', 'They flip a coin'],
    answer: 0,
    title: 'No ties: overtime decides it',
    exp: {
      kid: 'Basketball never ends in a tie! The teams play 5 more minutes of overtime to find a winner.',
      beginner: 'A tie at the end of Q4 forces a 5-minute overtime period. If it’s still tied after that, they play another one — as many as needed.',
      intermediate: 'OT is a full period, not sudden death: 5:00 on the clock, jump ball to start, normal scoring. Player fouls carry over, which makes foul trouble loom large.',
      expert: 'Note OT is 5:00 even though quarters are 10:00 — overtime length is standardized across leagues (NBA too). Half-length OTs make every possession roughly twice as valuable as a regulation possession; turnovers are lethal.',
    },
  },
  {
    id: 'wnba-kid-6', level: 'kid',
    board: { kind: 'basketball', away: { name: 'Vipers', abbr: 'VIP', score: 58, possession: true }, home: { name: 'Sirens', abbr: 'SIR', score: 60 },
      period: 'Q3', clock: '2:30', shotClock: 24 },
    prompt: 'The little “24” next to the clock just reset. What does it count?',
    options: ['Seconds the offense has left to shoot', 'Points needed to win', 'Seconds until a TV break'],
    answer: 0,
    title: 'The 24-second shot clock',
    exp: {
      kid: 'The attacking team has 24 seconds to take a shot. It keeps the game fast — no holding the ball forever!',
      beginner: 'Each possession, the offense must attempt a shot that hits the rim within 24 seconds, or it’s a turnover (shot-clock violation).',
      intermediate: 'The 24 resets on a change of possession; an offensive rebound resets it to only 14 — the offense is already set up, so it gets a shorter clock.',
      expert: 'The shot clock caps how slow a game can go, which is what makes leads chaseable — the leader must keep producing possessions. Every endgame script (fouling, 2-for-1s) is really arithmetic between the 24 and the game clock.',
    },
  },

  // ── beginner ──────────────────────────────────────────────────────────────
  {
    id: 'wnba-beg-1', level: 'beginner',
    board: { kind: 'basketball', away: { name: 'Aurora', abbr: 'AUR', score: 79, possession: true }, home: { name: 'Tempest', abbr: 'TEM', score: 82 },
      period: 'Q4', clock: '0:15', shotClock: 15 },
    prompt: 'Aurora trail 82–79 with 15 seconds left and the ball. What do they need to tie?',
    options: ['A 3-pointer', 'Any two baskets', 'One free throw'],
    answer: 0,
    title: 'Down 3 → hunt the three',
    exp: {
      kid: 'They’re 3 behind, so only a 3-point shot makes it even. Watch them pass around the arc looking for an open shooter!',
      beginner: 'A 2-pointer leaves them down 1 with almost no time — so the possession is designed for a 3. The defense will chase shooters and happily give up a layup.',
      intermediate: 'Both sides know the target, which warps the floor: defenders “top-lock” shooters to force drives, and the offense screens FOR the arc, not the rim. A quick 2 is only useful if it comes fast enough to foul afterward.',
      expert: 'Watch the leading side’s choice: defend straight up, switch everything to deny airspace, or foul before the shot (2 FTs can’t tie). Each option has a known win-probability profile — late-game defense is a solved-ish decision tree, executed under chaos.',
    },
  },
  {
    id: 'wnba-beg-2', level: 'beginner',
    board: { kind: 'basketball', away: { name: 'Vipers', abbr: 'VIP', score: 40 }, home: { name: 'Sirens', abbr: 'SIR', score: 44 },
      period: 'Q2', clock: '0:00' },
    prompt: 'The Q2 clock hits 0:00. What happens now?',
    options: ['Halftime', 'The game is over', 'A 5-minute overtime'],
    answer: 0,
    title: 'Two quarters down = halftime',
    exp: {
      kid: 'Two quarters are done — that’s half of the four. Time for the halftime break!',
      beginner: 'Q1+Q2 form the first half (20 of the 40 minutes). Teams rest, adjust, and return for Q3; the game can only end after Q4 (or overtime).',
      intermediate: 'Halftime resets nothing on the scoreboard but resets team fouls are per quarter anyway; what carries over is player fouls and the flow of matchups the coaches just spent 15 minutes dissecting.',
      expert: 'Half-by-half reading: a 4-point halftime lead is worth surprisingly little (home teams overcome more overnight); what matters more is HOW — free-throw disparity and turnover margin persist across halves far better than hot 3-point shooting does.',
    },
  },
  {
    id: 'wnba-beg-3', level: 'beginner',
    board: { kind: 'basketball', away: { name: 'Aurora', abbr: 'AUR', score: 50 }, home: { name: 'Tempest', abbr: 'TEM', score: 53 },
      period: 'Q3', clock: '4:29', fouls: { away: 5, home: 2 }, bonus: 'home' },
    prompt: 'The Aurora have 5 team fouls this quarter and the BONUS lamp is lit for the Tempest. What does that mean?',
    options: ['Any further Aurora foul = Tempest free throws', 'Tempest get 5 bonus points', 'Aurora players are ejected'],
    answer: 0,
    title: 'In the bonus at 5 team fouls',
    exp: {
      kid: 'The Aurora used up their quarter’s fouls. From now until the quarter ends, every foul they commit gives the Tempest free throws.',
      beginner: 'Team fouls count per quarter. From the 5th one on, the fouled team shoots two free throws even when the foul wasn’t on a shooter — that’s “the bonus.”',
      intermediate: 'Being in the bonus early in a quarter is a real handicap: 5+ minutes of no-touch defense while the opponent attacks the paint hunting contact. The count resets at the next quarter.',
      expert: 'Coaches budget fouls like timeouts: an aggressive take foul at 2 team fouls is free; the identical foul at 5 costs ~1.6 expected points. Watch substitution patterns follow the team-foul count, not just player matchups.',
    },
  },
  {
    id: 'wnba-beg-4', level: 'beginner',
    board: { kind: 'basketball', away: { name: 'Vipers', abbr: 'VIP', score: 66 }, home: { name: 'Sirens', abbr: 'SIR', score: 61 },
      period: 'Q4', clock: '8:10', shotClock: 24 },
    prompt: 'A Sirens forward is fouled while her layup goes IN. What happens?',
    options: ['Basket counts + 1 free throw', 'Basket waved off, 2 free throws', 'Jump ball'],
    answer: 0,
    title: 'And-one: keep the bucket, add a shot',
    exp: {
      kid: 'The basket still counts — and she gets one bonus free throw. Make it and that’s a 3-point play!',
      beginner: 'Fouled while scoring = the points stand plus ONE free throw. It beats getting fouled on a miss (two shots, nothing banked).',
      intermediate: 'The and-one rewards finishing through contact — absorbing the bump and completing the shot converts defense’s desperation into extra points. Fouled on a made 3, it becomes a possible 4-point play.',
      expert: 'Defensive discipline flows from this rule: if the shot is going in anyway, the foul is pure gift. “Verticality” technique — arms straight up, no lateral movement — exists specifically to contest without donating and-ones.',
    },
  },
  {
    id: 'wnba-beg-5', level: 'beginner',
    board: { kind: 'basketball', away: { name: 'Aurora', abbr: 'AUR', score: 12 }, home: { name: 'Tempest', abbr: 'TEM', score: 14, possession: true },
      period: 'Q1', clock: '2:05', shotClock: 2 },
    prompt: 'The shot clock reads 2 and the Tempest are still passing. What’s about to happen if nobody shoots?',
    options: ['Shot-clock violation — Aurora ball', 'The clock resets automatically', 'A jump ball'],
    answer: 0,
    title: 'Shoot or lose it',
    exp: {
      kid: 'If the 24 seconds run out before a shot hits the rim, the ball goes to the other team. Two seconds left — shoot!',
      beginner: 'A shot-clock violation is an automatic turnover: the attempt must leave the hand AND reach the rim before the buzzer. Passing doesn’t help — only shooting does.',
      intermediate: 'Defenses force this on purpose: deny the first option, keep the ball moving sideways, and the possession dies at the buzzer. “Forcing a late clock” is a defensive win even if a desperate shot falls.',
      expert: 'Possession efficiency collapses under 4 seconds on the clock — the defense has already won most of these. Offenses build “late-clock bailout” actions (a designated iso or high pick-and-roll at :06) precisely because unstructured late-clock basketball is the worst offense in the sport.',
    },
  },
  {
    id: 'wnba-beg-6', level: 'beginner',
    board: { kind: 'basketball', away: { name: 'Vipers', abbr: 'VIP', score: 88 }, home: { name: 'Sirens', abbr: 'SIR', score: 88 },
      period: 'OT', clock: '5:00', shotClock: 24 },
    prompt: 'The board shows “OT” with 5:00 on the clock — but quarters here are 10:00. Why is overtime shorter?',
    options: ['Overtime is always a 5-minute period', 'The scoreboard is set up wrong', 'OT length equals the final margin'],
    answer: 0,
    title: 'OT is 5:00 — half a quarter',
    exp: {
      kid: 'Overtime is its own special period: always 5 minutes, no matter how long the quarters are.',
      beginner: 'Even with 10-minute quarters, OT is a standard 5:00. If that ends tied too, another 5:00 is played, and so on until someone leads at a buzzer.',
      intermediate: 'Five minutes ≈ 8–10 possessions each — a sprint where one turnover or one and-one swings everything. Fouls carry over from regulation, so key players may be defending on eggshells.',
      expert: 'Short OTs raise variance, which favors the underdog — fewer possessions for talent to assert itself. This is a general principle: the shorter the decisive window, the more upsets. (It’s the same reason cup formats produce shocks that long series don’t.)',
    },
  },

  // ── intermediate ──────────────────────────────────────────────────────────
  {
    id: 'wnba-int-1', level: 'intermediate',
    board: { kind: 'basketball', away: { name: 'Aurora', abbr: 'AUR', score: 70, possession: true }, home: { name: 'Tempest', abbr: 'TEM', score: 72 },
      period: 'Q4', clock: '0:07', shotClock: 7 },
    prompt: 'Down 2, ball in hand, 7 seconds left. What’s the strategic choice?',
    options: ['A 2 ties (then OT); a 3 wins it outright', 'Only a 3 helps', 'Hold for the buzzer then decide'],
    answer: 0,
    title: 'Two-for-the-tie or three-for-the-win',
    exp: {
      kid: 'A regular basket makes it even and they’d play overtime. A long 3 wins right now! The coach picks one during the timeout.',
      beginner: 'Down 2 isn’t down 3: the rim is in play. A drive for the tie is higher-percentage; the 3 is winner-take-all. Watch where the inbounder looks — it tells you the call.',
      intermediate: 'Rule of thumb: at home, play for the tie (crowd + OT edge); on the road, lean win-now. The defense’s shape gives it away too — packed paint says they fear the drive, spread says they fear the arc.',
      expert: 'The EV comparison: P(win) via 2 = P(make2)×~0.5. Via 3 = P(make3). A contested rim attempt at ~55% yields ~27.5%; any 3 above that wins the argument. Since defenses concede the worse option, great closers read WHICH shot the defense is giving and take the other one’s equity.',
    },
  },
  {
    id: 'wnba-int-2', level: 'intermediate',
    board: { kind: 'basketball', away: { name: 'Vipers', abbr: 'VIP', score: 47 }, home: { name: 'Sirens', abbr: 'SIR', score: 45, possession: true },
      period: 'Q3', clock: '7:03', shotClock: 14 },
    prompt: 'The Sirens missed, grabbed their own rebound — and the shot clock reset to 14, not 24. Why?',
    options: ['Offensive rebounds reset to 14 by rule', 'The operator made an error', 'Rebounds don’t reset the clock'],
    answer: 0,
    title: 'The 14-second reset',
    exp: {
      kid: 'When the shooting team grabs its own miss, it gets a shorter clock — 14 seconds — because it’s already set up near the basket.',
      beginner: 'A full 24 is for building a possession from scratch. After an offensive rebound the ball is already in attack position, so the rule gives 14 — enough to reorganize, not to stall.',
      intermediate: 'The 14-second reset (adopted across leagues in the late 2010s) sped up endgames and punished stalling. It also applies after certain defensive fouls/kicked balls when the clock was under 14.',
      expert: 'Strategic ripple: offensive rebounds now produce immediate second-chance attacks (putbacks, kick-out 3s) rather than reset offense — second-chance points per rebound rose league-wide. Late in games, a team protecting a lead LOVES a 14 reset less than the old 24; count those seconds in endgame math.',
    },
  },
  {
    id: 'wnba-int-3', level: 'intermediate',
    board: { kind: 'basketball', away: { name: 'Aurora', abbr: 'AUR', score: 60 }, home: { name: 'Tempest', abbr: 'TEM', score: 59 },
      period: 'Q4', clock: '6:22', fouls: { away: 1, home: 2 } },
    prompt: 'A Tempest guard is fouled shooting a 3 that misses. How many free throws does she shoot?',
    options: ['3', '2', '1'],
    answer: 0,
    title: 'Three shots for a foul on a three',
    exp: {
      kid: 'She was shooting a 3-pointer, so she gets 3 free throws — a chance at all 3 points she was denied.',
      beginner: 'Free throws mirror the attempt’s value: 2 for a 2, 3 for a 3. (If the 3 had gone in, it would count plus one bonus throw — a 4-point play.)',
      intermediate: 'Three free throws is ~2.4 expected points for a good shooter — a catastrophic foul to commit. Closeouts are coached “high hands, fly PAST the shooter” to avoid landing-space contact.',
      expert: 'The shooter’s landing space is protected: a defender who slides under a jump shooter commits the foul even without arm contact. Savvy shooters draw these; savvy defenders contest-and-swerve. The arc is where fouls are most expensive per incident in the entire sport.',
    },
  },
  {
    id: 'wnba-int-4', level: 'intermediate',
    board: { kind: 'basketball', away: { name: 'Vipers', abbr: 'VIP', score: 75 }, home: { name: 'Sirens', abbr: 'SIR', score: 77 },
      period: 'Q4', clock: '3:40', fouls: { away: 3, home: 2 } },
    prompt: 'A Vipers star just committed her 5th PERSONAL foul. What’s her situation?',
    options: ['One more and she’s disqualified for the game', 'She must leave for 2 minutes', 'Nothing until the 8th'],
    answer: 0,
    title: 'Six personals and you’re out',
    exp: {
      kid: 'Players are allowed 6 fouls for the whole game. She has 5 — one more and she’s out for good.',
      beginner: 'Personal fouls never reset (team fouls do, each quarter). At 6 a player “fouls out” and must leave the game permanently. At 5, every defensive play is a risk.',
      intermediate: 'Smart offenses attack the 5-foul player relentlessly — screen her defender into switches, drive at her. Her rational response (soft defense) concedes points; her aggressive response risks losing her entirely.',
      expert: 'Foul trouble is a bankroll problem: minutes remaining vs fouls available. Coaches model it — a star at 5 fouls with 3:40 left usually stays (expected minutes lost < benching cost), but at 5 fouls with 8:00 left she often sits until the 5-minute mark. The scoreboard’s foul column drives rotations as much as the score does.',
    },
  },
  {
    id: 'wnba-int-5', level: 'intermediate',
    board: { kind: 'basketball', away: { name: 'Aurora', abbr: 'AUR', score: 39 }, home: { name: 'Tempest', abbr: 'TEM', score: 41 },
      period: 'Q2', clock: '1:12', fouls: { away: 1, home: 1 }, bonus: 'away' },
    prompt: 'Only 1 team foul each — yet the next Tempest foul gives Aurora free throws. What rule is this?',
    options: ['2nd team foul in the final 2:00 of a period triggers the penalty', 'Home teams reach the bonus first', 'Q2 is always penalty time'],
    answer: 0,
    title: 'The last-two-minutes penalty',
    exp: {
      kid: 'In the last two minutes of a quarter the rules get stricter — after just a couple of fouls, everything becomes free throws.',
      beginner: 'Besides the 5-fouls-per-quarter bonus, there’s a second trigger: inside the final 2:00 of any period, a team’s 2nd foul in that window sends the opponent to the line.',
      intermediate: 'It stops teams from “borrowing” fouls they never used — grabbing and bumping to shorten the last two minutes cheaply. Clean quarters don’t buy you a rough finish.',
      expert: 'It stacks with endgame tactics: a defense planning a take-foul or a clock-stopping foul must count its window fouls first. In practice, coaches call “we have one to give” — meaning one foul before the 2:00 penalty (or the 5-foul line) starts paying the opponent.',
    },
  },
  {
    id: 'wnba-int-6', level: 'intermediate',
    board: { kind: 'basketball', away: { name: 'Vipers', abbr: 'VIP', score: 83, possession: true }, home: { name: 'Sirens', abbr: 'SIR', score: 85 },
      period: 'Q4', clock: '0:04', shotClock: 4 },
    prompt: 'Down 2 with 4 seconds left, sideline inbound. Why is a timeout here so valuable?',
    options: ['It lets the coach draw a set play and advances nothing — but organizes the final shot', 'It adds seconds to the clock', 'It resets the shot clock'],
    answer: 0,
    title: 'The drawn-up final play',
    exp: {
      kid: 'With 4 seconds left there’s time for exactly one play — so the coach uses a timeout to draw it up perfectly on the whiteboard.',
      beginner: 'Four seconds is one catch-and-shoot or one quick drive. A timeout lets the coach set screens, decoys and a first/second option, instead of improvising the season’s biggest possession.',
      intermediate: 'Inbound plays are choreography: a screen for the screener, a decoy flare, the real target curling late. The defense counters by switching everything and face-guarding the star — or denying the INBOUND pass itself, the play’s weakest link.',
      expert: 'Time thresholds rule the design: ~0.3s = tip only; ~0.8s = catch-and-shoot without a dribble; 4s = catch, one dribble, pull-up. Coaches keep a card of sets indexed by seconds remaining. Watching WHO takes the ball out tells you the play — the best passer inbounds, the best shooter comes off the last screen.',
    },
  },

  // ── expert ────────────────────────────────────────────────────────────────
  {
    id: 'wnba-exp-1', level: 'expert',
    board: { kind: 'basketball', away: { name: 'Aurora', abbr: 'AUR', score: 90, possession: true }, home: { name: 'Tempest', abbr: 'TEM', score: 93 },
      period: 'Q4', clock: '0:11', fouls: { away: 2, home: 3 } },
    prompt: 'Tempest lead by 3 with 11 seconds left; Aurora inbound. What’s the Tempest’s “foul up 3” option?',
    options: ['Foul before any shot — 2 FTs can’t tie a 3-point lead', 'Foul the 3-point shooter mid-shot', 'Call timeout to ice the shooter'],
    answer: 0,
    title: 'Fouling up 3, done right',
    exp: {
      kid: 'If they foul softly BEFORE a shot starts, the other team only gets 2 free throws — not enough to tie a 3-point lead.',
      beginner: 'A non-shooting foul caps the trip at 2 points, so the lead survives. The catch: it must come clearly before the shooting motion — fouling a 3-point SHOOTER hands over 3 free throws and disaster.',
      intermediate: 'The trailing team’s best response: make FT #1, intentionally miss #2, chase the board for a tying tip — or inbound-and-shoot faster than the foul can arrive. Execution beats theory on both sides; that’s why some coaches still just defend.',
      expert: 'Consensus from win-probability studies: fouling up 3 helps modestly when done with >5 seconds left and before the gather. The tail risks — a 4-point play from a late foul, or an offensive rebound off the missed FT — are exactly the scenarios that keep the “never foul” camp alive. Judge execution, not just the decision.',
    },
  },
  {
    id: 'wnba-exp-2', level: 'expert',
    board: { kind: 'basketball', away: { name: 'Vipers', abbr: 'VIP', score: 55, possession: true }, home: { name: 'Sirens', abbr: 'SIR', score: 58 },
      period: 'Q3', clock: '0:34', shotClock: 24 },
    prompt: 'Fresh possession, 0:34 left in Q3. Where should the Vipers aim their shot timing?',
    options: ['Shoot by ~0:28 — the 2-for-1 window', 'Hold for the final shot at 0:02', 'Shoot instantly at 0:33'],
    answer: 0,
    title: 'Manufacturing the extra possession',
    exp: {
      kid: 'If they shoot quickly, the other team’s turn will end with a few seconds left — enough for one MORE shot before the quarter ends. Two chances beats one!',
      beginner: 'The 2-for-1: shoot around 0:28, the opponent’s 24-second clock runs down to ~0:04, and you get the quarter’s last shot too. Waiting even 6–7 seconds forfeits the extra possession.',
      intermediate: 'The trade is shot quality now vs. a whole extra possession: a “pretty good” look at 0:29 beats a “great” look at 0:20. The opposite trap: shooting TOO early (0:33) gives the opponent their own 2-for-1.',
      expert: 'Optimal window ≈ 0:36–0:26 depending on rebound risk and opponent pace. Elite teams script it out of a timeout: quick side action into a rhythm 3, then defend a full 24 without fouling. Quarter-boundary possession counting compounds — win the last possession of all four quarters and you’ve stolen ~4 points a game.',
    },
  },
  {
    id: 'wnba-exp-3', level: 'expert',
    board: { kind: 'basketball', away: { name: 'Aurora', abbr: 'AUR', score: 78 }, home: { name: 'Tempest', abbr: 'TEM', score: 79, possession: true },
      period: 'Q4', clock: '0:19' },
    prompt: 'Tempest lead by 1 with 0:19 left and the ball — and the shot clock is dark. What does that force Aurora to do?',
    options: ['Foul immediately — the Tempest never have to shoot again', 'Wait for a shot-clock violation', 'Set up a zone defense'],
    answer: 0,
    title: 'Dark shot clock = foul or lose',
    exp: {
      kid: 'With less time left than a shot clock (under 24 seconds), the shot clock turns off — the leading team could just hold the ball until the buzzer. The only way to stop that is to foul.',
      beginner: 'Once the game clock is under 24 on a new possession, the shot clock is switched off. The leading team can run out the entire game — so the trailing team must foul to stop the clock and trade free throws for possession.',
      intermediate: 'This is why you see instant, almost polite fouls on the inbound: every second before the foul is pure loss. The leading team counters by inbounding to its best free-throw shooter — endgames become FT contests by design.',
      expert: 'Roster wrinkle: leading coaches sub OUT poor FT shooters for the “closing five,” and trailing coaches foul the worst shooter left (within the rules on away-from-play fouls). The dark shot clock converts basketball into a sequenced exchange — FT efficiency × foul speed — that good teams rehearse weekly.',
    },
  },
  {
    id: 'wnba-exp-4', level: 'expert',
    board: { kind: 'basketball', away: { name: 'Vipers', abbr: 'VIP', score: 71 }, home: { name: 'Sirens', abbr: 'SIR', score: 71 },
      period: 'Q4', clock: '0:00' },
    prompt: 'At the Q4 buzzer, a Sirens shot was in the AIR and dropped through after the horn. Tied game otherwise — what’s the ruling?',
    options: ['Counts if released before 0:00 — Sirens win at the buzzer', 'No basket — anything after the horn is dead', 'Counts, but only for 1 point'],
    answer: 0,
    title: 'Release beats the buzzer',
    exp: {
      kid: 'If the ball left her hands before the clock hit zero, the basket counts even though it went in after the horn — a buzzer-beater win!',
      beginner: 'The rule is time-of-RELEASE: out of the hand before 0:00 = live shot. Officials review the replay against the backboard light that fires exactly at zero.',
      intermediate: 'The horn is just sound; the synced LED strip is the legal signal. If any part of the hand still touches the ball as the light fires, the basket is waved off and we go to OT.',
      expert: 'Officiating detail: reviews check release vs light frame-by-frame AND whether the clock started on time on the catch (timing errors can add/remove tenths). The 0.3-second catch-and-shoot threshold comes from this same body of timing rules — below it, only a tap counts.',
    },
  },
  {
    id: 'wnba-exp-5', level: 'expert',
    board: { kind: 'basketball', away: { name: 'Aurora', abbr: 'AUR', score: 80 }, home: { name: 'Tempest', abbr: 'TEM', score: 86, possession: true },
      period: 'Q4', clock: '0:41', fouls: { away: 4, home: 3 } },
    prompt: 'Aurora trail by 6 with 41 seconds left, Tempest ball. Walk the only realistic path: what must Aurora do?',
    options: ['Foul now, make FTs count, score fast, foul again — trade points for possessions', 'Play defense and hope for two misses', 'Save fouls for overtime'],
    answer: 0,
    title: 'The foul-and-score ladder',
    exp: {
      kid: 'They can’t just wait — the clock is their enemy. They foul to stop it, hope for missed free throws, score quickly, then do it all again. It’s a race!',
      beginner: 'Down 6 with 41 seconds = they need at least two scores plus stops. Fouling stops the clock and returns the ball after (at most) 2 free throws. Passive defense lets the Tempest kill the whole 41 with one dark-ish shot clock… so fouls are mandatory.',
      intermediate: 'The ladder: foul (~2s), FTs, fast score (~6s), foul again (~2s)… Each rung costs up to 2 points and buys ~8 seconds of usable game. Down 6 needs the opponent to miss at least a couple of FTs or you to hit 3s — which is why the first score should be a 3, not a layup.',
      expert: 'Break-even math: possessions buyable ≈ clock ÷ ~9s per cycle → 41s ≈ 4 possessions. Points needed per possession = 6 ÷ (your 2 possessions) = 3.0 → all 3s, plus opponent FT misses. If the deficit-per-buyable-possession exceeds 3, the game is mathematically dead absent turnovers — that’s the number closers compute before deciding to keep fouling or concede.',
    },
  },
  {
    id: 'wnba-exp-6', level: 'expert',
    board: { kind: 'basketball', away: { name: 'Vipers', abbr: 'VIP', score: 64 }, home: { name: 'Sirens', abbr: 'SIR', score: 66 },
      period: 'Q4', clock: '5:20', fouls: { away: 4, home: 4 } },
    prompt: 'Both teams sit at 4 team fouls with 5:20 left in Q4. What state is the endgame in?',
    options: ['Knife’s edge: the next foul by either side starts the free-throw parade', 'Fouls are irrelevant until 2:00', 'Both teams get a foul amnesty'],
    answer: 0,
    title: 'One foul from the penalty, both ways',
    exp: {
      kid: 'Both teams are one foul away from giving free throws on EVERY foul. The rest of the game will be very careful — or very generous!',
      beginner: 'At the 5th team foul of the quarter, every subsequent foul = 2 free throws. Both teams at 4 means the next whistle against either side opens the penalty for the rest of Q4.',
      intermediate: 'Expect both offenses to attack downhill — rim pressure converts marginal contact into points once the penalty opens. Defenses counter with verticality and early “no-foul” switches. The team-foul column is now the game’s most important number.',
      expert: 'Game theory: neither side wants to commit foul #5 first, but soft defense concedes layups — a classic chicken situation resolved by personnel (who can defend without fouling) and by hunting the opponent’s foul-prone defender. Sharp bettors and coaches both re-price the “points environment” the moment both teams hit 4: expect FT volume, slower clock, higher variance.',
    },
  },
];
